### ISSUE TITLE
Some users are unable to load the new URL 

### ISSUE THREAD

**Issue by CindyLo0** [5afe/safe-support#100]
### Issue Category

Safe loading issue, doesnt load on any interface

### What happened?

Some users are unable to access the Safe site using the new URL (app.safe.global) but works fine using the old one (gnosis-safe.io)

Steps taken: 

1. Hard reload
2. Disabled adblockers
3. tried behind a VPN > works fine site is accessible using the new URL. User is in Spain, used Japan location for VPN. 
4. User is connected to their home wifi. 
5. Error in dev console, 
![image](https://user-images.githubusercontent.com/79137197/208090969-8a145f1c-70fc-4edb-ad02-501c32017a81.png)

### Date and time this happened or you first noticed this issue

16-12-2022 13:00

### Network

Ethereum Mainnet

### Token Type

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ennisjo** [comment]
Does this issue still persist @CindyLo0 ?

**Comment by shebeengs** [comment]
Hi @ennisjo, checked the ticket and looks like the user has been unresponsive. We can close this for now as I'm not seeing other users getting this issue as well. Thank you!

**Comment by shebeengs** [comment]
Hi @ennisjo sorry to reopen this. A new user came in having loading issues with the safe. Not working on old and new URLs and also in mobile app. 

Location: UK
OS: Mac OSX running Ventura latest.
Browser: Latest Chrome and Firefox
Mobile: v3.18.1(1435)
![image](https://user-images.githubusercontent.com/54754746/208486642-ac85b370-b61f-4e85-a255-ce7c3e6441f2.png)

**Comment by phoebe-serveth** [comment]
Another user reporting safe loading issues as well.
Safe address: 0x1f28eD9D4792a567DaD779235c2b766Ab84D8E33
![image](https://user-images.githubusercontent.com/114040259/208495785-2fa7a5d1-d092-409a-a108-03b1e257d128.png)

**Comment by med3000** [comment]
hi @phoebe-serveth I am able to load this safe with no issues, are you able to replicate the issue on your end?

**Comment by med3000** [comment]
Hi @shebeengs / @CindyLo0  - as with the related issues raised, the closing comment here https://github.com/5afe/safe-support/issues/107#issuecomment-1366428809 could you please ask the users to try with VPN and see if they are still having connection issues. Thanks

**Comment by med3000** [comment]
if no further update, will close this off. please feel free to reopen if more info is provided. thanks
