### ISSUE TITLE
[Arbitrum] Safe could not be loaded

### ISSUE THREAD

**Issue by joanpan** [5afe/safe-support#101]
### Issue Category

Safe loading issue, doesnt load on any interface

### What happened?

Multiple users reported being unable to load their safes on Arbitrum
![image](https://user-images.githubusercontent.com/114049668/208218272-63967139-db2d-4c3e-b053-29929cf84a37.png)

> Tried on multiple browsers - same issue
> Tried both old and new UI - same issue

arb1:0x11BE7EA0F6e10D0222f31aF459B05669E32A5b88
arb1:0xfD3B8b2Ece329d3429Ba2c466906D20570E3d7F9

### Date and time this happened or you first noticed this issue

16-12-2022

### Network

Arbitrum

### Safe Address

0x11BE7EA0F6e10D0222f31aF459B05669E32A5b88

### Token Type

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joanpan** [comment]
New users not able to load their safes:
0x9Cf11F95FfB3F122be512f73918e63187a18A71d
0x6f8B7fF6AA8921D9ca93B8852BC29FcE2DF0006d

**Comment by inahlikenoother** [comment]
Another user experiencing the problem:

https://app.safe.global/arb1:0xA72fDfAFa7dbb7663e71B3006953c55eD165936b/home
![image](https://user-images.githubusercontent.com/114049495/208224584-72fe7b87-fe41-42ec-ad74-6b25b42c93b4.png)

https://gnosis-safe.io/app/arb1:0xA72fDfAFa7dbb7663e71B3006953c55eD165936b
![image](https://user-images.githubusercontent.com/114049495/208224631-83ff8ea2-cc24-434b-be40-25c3f1e32881.png)

![image](https://user-images.githubusercontent.com/114049495/208224639-7df4015b-2434-4bf8-b96c-2bd36a2dbf79.png)

**Comment by DefiDebauchery** [comment]
Having the same issue with ours, as well. 

The error received by the safe-client (which is passed through from the safe-transaction service) is
```json
{
    "code": 50,
    "message": "Cannot get Safe info from blockchain",
    "arguments": [
        "0x3f5eddad52C665A4AA011cd11A21E1d5107d7862"
    ]
}
```

As far as I can tell from Safe configuration, it's just using the public Arbitrum RPC at `https://arb1.arbitrum.io/rpc`
I don't see any issues with hitting the RPC from my location, so I'm curious if maybe the Safe infrastructure is getting throttled.

**Comment by westonnelson** [comment]
I am currently also unable to access Safes on Arbitrum - both on Mobile and Web.

**Comment by lensonwang** [comment]
I had the same problem, too bad

**Comment by SeamanHL07** [comment]
I have the same problem with the safe on the arbitrum
![Screenshot (1)](https://user-images.githubusercontent.com/119759471/208231456-497dc2ca-da85-4e15-a7ad-3107a5184a3d.png)

**Comment by cty328807718** [comment]
how to slove

**Comment by cty328807718** [comment]
How to deal with it

**Comment by DefiDebauchery** [comment]
I think the Safe team has enough evidence that there's an issue. Additional "me too" replies will just drown out official communication, so simply subscribe to Notifications to this issue (on the right side of the page) and you'll be able to follow when progress is made.

**Comment by Johnnyyy24** [comment]
The issue seems to have been fixed? It works for me now

**Comment by lensonwang** [comment]
yes，thx so mach！



---Original---
From: "Johnny ***@***.***&gt;
Date: Sat, Dec 17, 2022 17:54 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [5afe/safe-support] [Arbitrum] Safe could not be loaded (Issue#101)




 
The issue seems to have been fixed? It works for me now

**Comment by med3000** [comment]
thanks for your patience on this, it appears to have been related to some network issues at the time.
