### ISSUE TITLE
Proposed transaction doesn't appear in queue and can't be confirmed

### ISSUE THREAD

**Issue by joanpan** [5afe/safe-support#106]
### Issue Category

Transaction execution issue

### What happened?

Safe address: eth:0x6952bb94F2B6bA725868B44E2c654DA67C43Fcc6
Safe contract version: 0.1.0

User is using the old safe UI to propose a transaction since new UI does not support safe version 0.1.0
![image](https://user-images.githubusercontent.com/114049668/209598398-23aabfef-2264-43ac-87da-8f26703611bd.png)

Similar issue on stackexchange:
https://ethereum.stackexchange.com/questions/122778/proposed-transaction-doesnt-appear-in-queue-and-cant-be-confirmed

-tried different browsers
-different owner wallets
-seems to be happening to types all transactions, tried a send txn and upgrade safe txn
send
![image](https://user-images.githubusercontent.com/114049668/209598462-3d36ce98-8061-442d-94c4-8779efdae7d9.png)
upgrade
![image](https://user-images.githubusercontent.com/114049668/209598850-609037b6-2ccb-4885-b464-7caad765d32a.png)

Dev console error:
![image](https://user-images.githubusercontent.com/114049668/209598449-a9bf36f5-c43b-4f1d-a05f-9755f446b814.png)

### Date and time this happened or you first noticed this issue

27-12-2022

### Network

Ethereum Mainnet

### Safe Address

0x6952bb94F2B6bA725868B44E2c654DA67C43Fcc6

### Token Type

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JagoFigueroa** [comment]
Hey team, 0.1.0 safes are expected to not work on UI and are out of scope for support at this moment. 

To interact with a safe on this version these tools should work for the user: [safe-cli](https://github.com/5afe/safe-cli) and [safe-tasks](https://github.com/5afe/safe-tasks)

Cheers!
