### ISSUE TITLE
Proposed Transaction not showing up in Queue tab

### ISSUE THREAD

**Issue by phoebe-serveth** [5afe/safe-support#108]
### Issue Category

Transaction missing / not visible in app or service

### What happened?

Getting an error when trying to initiate any transactions and it doesn't appear in queued tab. Happening on brave and firefox browser.
Error message: "The Safe SDK could not be initialized"
Types of transactions tried: changing threshold, adding or removing owners, sending money to another wallet
Safes affected:
     Eth:0x3bC8Ff1711c4CBC9da447E01De7B99Ed08428546
     Matic:0xd93562789679D439Ab279422f8550676bDDcD05E
     Bnb:0x1a4399f9B14286f243Ab757c6bA94caADD735379

Tried both new and old UI

![image](https://user-images.githubusercontent.com/114040259/210111764-0c394f9c-777e-42a3-ad36-9a6253c49743.png)

![image](https://user-images.githubusercontent.com/114040259/210111617-41034f4c-1ef3-46e4-be5a-0f92cf70bc16.png)
![image](https://user-images.githubusercontent.com/114040259/210111628-6c80e145-0e51-4fe0-bb3e-f1bbdc9e74bd.png)

### Date and time this happened or you first noticed this issue

31-12-2022 4:30

### Network

Ethereum Mainnet, Polygon, Binance Smart Chain

### Safe Address

Eth:0x3bC8Ff1711c4CBC9da447E01De7B99Ed08428546, Matic:0xd93562789679D439Ab279422f8550676bDDcD05E, Bnb:0x1a4399f9B14286f243Ab757c6bA94caADD735379

### Token Type

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JagoFigueroa** [comment]
Good morning! Could we reach out to the user to see if the issue still persists? might have been a temporary issue.

I have just tried on these 2 browsers and queued transactions are popping up for me as usual.

Thanks 😄

**Comment by phoebe-serveth** [comment]
Hi @JagoFigueroa Already checked with the user but still waiting for a response.

**Comment by phoebe-serveth** [comment]
@JagoFigueroa Hello again :) The user is still getting the same error when trying to submit a new transaction today.

**Comment by Sherie15** [comment]
@JagoFigueroa The user was able to make multiple transactions last 1/5 and also the user has had no response in the ticket since 1/3. 
![image](https://user-images.githubusercontent.com/113986185/211246060-8618d4ec-ea17-44be-b974-d5e6064a447b.png)
