### ISSUE TITLE
[Missing Token] Usdc tokens not showing in the UI

### ISSUE THREAD

**Issue by jakekvm01** [5afe/safe-support#11]
### What happened?

User's USDC tokens are not shown in the UI. They are experiencing delays in eth network. Intercom ticket https://gnosis-safe.io/app/eth:0xcDcCF94f10d8A7165C1A336DD3795430a6CDE530/balances and https://etherscan.io/address/0xcDcCF94f10d8A7165C1A336DD3795430a6CDE530.

### Network

Ethereum Mainnet

### Safe Address

eth:0xcDcCF94f10d8A7165C1A336DD3795430a6CDE530

### Token Address

usdc

### What issue are you experiencing?

Missing completely / Not visible in the interface or service

### Transfers

```shell
0x894096439ba0d1ec6d265cdce16f10d0798c253f7e8489621be67aae3c9d703b
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by liliya-soroka** [comment]
@jakekvm01 , seems that the balance is up to date and USD coin is displayed in the UI.
<img width="623" alt="image" src="https://user-images.githubusercontent.com/338622/192448125-e5d95f15-2b3d-466f-8cdd-601b01037a43.png">
