### ISSUE TITLE
USDC and GALA balance not visible in Assets both in old and new UI 

### ISSUE THREAD

**Issue by joanpan** [5afe/safe-support#113]
### Issue Category

Token balance not up-to-date, in the interface or service

### What happened?

USDC balance on etherscan:
![image](https://user-images.githubusercontent.com/114049668/211131517-8f900cab-f475-4caa-9d02-ea729e11581c.png)

OLD UI
![image](https://user-images.githubusercontent.com/114049668/211131527-83d65107-c7f9-443c-bf4b-b7be11bb18a3.png)

NEW UI
![image](https://user-images.githubusercontent.com/114049668/211131537-4a87e43e-82d6-4b28-ac50-50fe960ab4f9.png)

Address: eth:0x2759A9709119D2DfC240Af52C45A83F47580a0Fb

### Date and time this happened or you first noticed this issue

07-01-2023

### Network

Ethereum Mainnet

### Safe Address

0x2759A9709119D2DfC240Af52C45A83F47580a0Fb

### Token Type

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ennisjo** [comment]
@joanpan - this could be related to the recent changes in the Erigon client. We've now re-indexed the Safe, and the balance should appear in the UI soon.

**Comment by joanpan** [comment]
@ennisjo it looks like it's updated now. thank you
