### ISSUE TITLE
Error when trying to submit transaction using Trezor

### ISSUE THREAD

**Issue by joanpan** [5afe/safe-support#114]
### Issue Category

Transaction execution issue

### What happened?

When user signs in the new interface (app.safe.global) with Trezor( w/ Metamask), it says: "Code 804: Error processing a transaction (MetaMask Message Signature: Error: Invalid length, bigger than 1024)"
Screenshot:
![image](https://user-images.githubusercontent.com/114049668/211982242-825fc679-ffc9-4ef7-8107-9379038a3efc.png)

User is able to submit other transactions, issue only occurs when transaction data is long. As per user, the old interface (gnosis-safe.io) requires signing twice. The 1st times (EIP712) also fails and the 2nd times (eth_sign) success. So when the transaction is long, user can only use the old version. 

- Safe address: arb1:0x029A4A97e892e7270d9B3B90bFEF95599BC6BfD6
- Trezor firmware 2.5.3 (latest)
- Tested on both Chrome and Firefox
- Tested signing with Metamask (without Trezor) and it was successful.

It seems the issue is related to Trezor, but user can not replace the owners to hot-wallets because unsafe. Is there a way to bypass this problem in the new interface? Or a way to run an older version of Safe?

User also requested to extend the life cycle old version until this issue is fixed?

### Date and time this happened or you first noticed this issue

12-01-2023

### Network

Arbitrum

### Safe Address

arb1:0x029A4A97e892e7270d9B3B90bFEF95599BC6BfD6

### Token Type

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by med3000** [comment]
Duplicate, closing this one and  keeping original https://github.com/5afe/safe-support/issues/73
