### ISSUE TITLE
Contract interaction transaction cannot be queued if the transaction is going to fail 

### ISSUE THREAD

**Issue by shanefontaine** [5afe/safe-support#115]
### Issue Category

Transaction execution issue

### What happened?

On the https://app.safe.global/ site, when preparing a "Contract interaction" transaction that will fail, the UI blocks you from completing the process. See attached photo. In the image, those blank fields never populate.

I would expect the blank fields to populate and I would expect to be able to submit the transaction for others to sign.

A practical example where this may be useful is queueing a timelocked transaction. If a multisig needs to queue a transaction and then execute it 24 hours later because of a timelock contract, it is convenient to be able to queue both transactions on the Safe at the same time (even though the latter will not be executed for at least 24 more hours).

<img width="597" alt="fail" src="https://user-images.githubusercontent.com/9441295/212220186-9a276e9a-dff1-4991-93fd-901874756dc4.png">

### Date and time this happened or you first noticed this issue

12-01-2023

### Network

Ethereum Mainnet

### Safe Address

0x1ec078551A5ac8F0f51fAc57Ffc48Ea7d9A86E9d

### Token Type

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JagoFigueroa** [comment]
Good point! Will share this with the team so that they can take a look 😄

**Comment by usame-algan** [comment]
Could we get more details on the type of error that is thrown either by checking the browser console or pressing on Details under the Error message.

**Comment by shanefontaine** [comment]
@usame-algan It looks like this occurs any time the transaction will fail. In the image below, the `Timelock::executeTransaction:Transaction hasn't been queued` in the console is expected. However, I would expect to still be able to submit this tx, since I know the execution will work when the final multisig signer gets around to sign it (just like in the old UI).

Of note, this Safe is v1.1.1, which might be causing this?


<img width="1715" alt="safeErr" src="https://user-images.githubusercontent.com/9441295/214489734-6bee4f3e-3d14-4170-9968-dadb36affd5b.png">

**Comment by usame-algan** [comment]
@shanefontaine thanks for the follow up. I was able to reproduce the issue in a 1.1.1 safe but not a 1.3.0 safe so I think it is related indeed!

**Comment by usame-algan** [comment]
This has been fixed with [web-core v1.4.5](https://github.com/safe-global/web-core/releases/tag/v1.4.5)
