### ISSUE TITLE
Ethereum - USDC not showing in Safe interface, but shows in Etherscan

### ISSUE THREAD

**Issue by inahlikenoother** [5afe/safe-support#116]
### Issue Category

Token missing completely / not visible in the interface or service

### What happened?

USDC is not showing in safe user interface

![image](https://user-images.githubusercontent.com/114049495/212291538-a7c5bf1f-c7e2-433f-bc74-5c001b4f898e.png)

But shows in Etherscan 

![image](https://user-images.githubusercontent.com/114049495/212291687-cdfaccc9-d7d5-48b1-a495-4dca59888d72.png)

### Date and time this happened or you first noticed this issue

01-13-2023

### Network

Ethereum Mainnet

### Token Address

0x79B320ABac3C3c3e0DA938fc55e457af588d4D57

### Token Type

ERC20

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by moisses89** [comment]
@inahlikenoother I just checked that the assets appear in that safe.

**Comment by inahlikenoother** [comment]
Issue resolved 
![image](https://user-images.githubusercontent.com/114049495/212460156-b31364c0-8c99-49d9-9212-d1d9835924ea.png)
