### ISSUE TITLE
ERC20 token not showing a fiat value on polygon network

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#118]
### Issue Category

Other

### What happened?

Fiat value for Telcoin (TEL) token is not showing up on the UI. User said the price was showing until yesterday. 
![image](https://user-images.githubusercontent.com/114005210/212979863-84ff8db6-4d37-453e-ab11-75d5695c2d55.png)

### Date and time this happened or you first noticed this issue

17-01-2023

### Network

Polygon

### Safe Address

0xfE82fEAD341F3c8293C9e64a5D0682Ce34ca51f7

### Token Address

0xdF7837DE1F2Fa4631D716CF2502f8b230F1dcc32

### Token Type

ERC20

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Claire-serveth** [comment]
Fiat value is already showing up on the UI.

**Comment by joanpan** [comment]
Issue reoccurred, fiat value does not reflect in the Safe UI:

![image](https://user-images.githubusercontent.com/114049668/221715586-2deb548e-6749-41ca-be35-7f32b2773f6d.png)
![image](https://user-images.githubusercontent.com/114049668/221715622-c997239c-360b-4c82-a9e0-59e746358cd3.png)

**Comment by joanpan** [comment]
Fiat value now showing up

**Comment by joanpan** [comment]
Issue recurred. Telcoin not showing up again
![image](https://user-images.githubusercontent.com/114049668/225806863-b511f8c8-ef5f-47fc-92b5-e075e8e4fb0f.png)

**Comment by katspaugh** [comment]
@5afe/safe-services any idea why it’s in this limbo state?

**Comment by Uxio0** [comment]
We only offer prices for tokens we can find in some oracles we have configured, it's just an approximation and we cannot guarantee a price for every token
