### ISSUE TITLE
Unable to select certain NFTs when trying to send assets

### ISSUE THREAD

**Issue by joanpan** [5afe/safe-support#119]
### Issue Category

Safe loading issue, doesnt load on any interface

### What happened?

User trying to transfer NFTs but is unable to select the BoredApeYachtClub (without space), whichever user chooses it automatically selects the bored ape yacht club (with space) which is a malicious NFT, same behavior for the otherdeed NFT. Other NFTs are working fine.

Issue only occurs in the new interface (tested different browsers). Old interface works fine. 

https://user-images.githubusercontent.com/114049668/213335195-3e9870b8-efd2-43e3-bc82-9cb307d12166.mov

safe address: eth:0xd99e9aeC0a12a710420f27Cf13fcD248F8470b00

### Date and time this happened or you first noticed this issue

19-01-2023

### Network

Ethereum Mainnet

### Safe Address

0xd99e9aeC0a12a710420f27Cf13fcD248F8470b00

### Token Type

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iamacook** [comment]
Thanks for reporting the issue @joanpan, we are actively looking into it. You can following our progress [here](https://github.com/safe-global/web-core/issues/1560).

**Comment by joanpan** [comment]
@iamacook we have another similar issue. Safe address: eth: 0x2aE6B0630EBb4D155C6e04fCB16840FFA77760AA

When user tries to transfer [Bean NFT](https://etherscan.io/token/0x306b1ea3ecdf94ab739f1910bbda052ed4a9f949?a=0x2aE6B0630EBb4D155C6e04fCB16840FFA77760AA) from the assets page > **Transfer** button, it selects the Physical Backed Token. It seems to only happen when selecting Beans NFT.
https://user-images.githubusercontent.com/114049668/215623000-030d006c-bee3-4ff9-9574-a93e8da3bc03.mov

**Comment by iamacook** [comment]
@joanpan, our [forthcoming release](https://github.com/safe-global/web-core/pull/1616) includes a reworked NFT page which should solve these issues.

**Comment by iamacook** [comment]
@joanpan, we released an updated NFT page yesterday that should've solved this. Can you confirm whether you are still experiencing issues?

**Comment by joanpan** [comment]
@iamacook will check with the user, thanks!

**Comment by joanpan** [comment]
@iamacook issue resolved thank you!
