### ISSUE TITLE
NFT not showing up on UI (Assets page)

### ISSUE THREAD

**Issue by joanpan** [5afe/safe-support#12]
### Issue Category

Token missing completely / not visible in the interface or service

### What happened?

NFT not showing up on assets page, only showing placeholder:
![image](https://user-images.githubusercontent.com/114049668/191567398-219194de-b607-4551-860d-8453371a7dee.png)
Tested on my end - also not seeing NFT

### Date and time this happened or you first noticed this issue

22-09-22

### Network

Arbitrum

### Safe Address

0xdE28200f6A56ABd7C92B310C5bC4206B6E2b8Fdc

### Token Address

0x2aa5d15eb36e5960d056e8fea6e7bb3e2a06a351

### Token Type

ERC721

### Transactions

```shell
https://arbiscan.io/tx/0x970c966a263d8b7c1522280f43d002957549a675be756871fc4224e25a9b4c6e
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iamacook** [comment]
Thanks for submitting the issue @joanpan.

The image is not showing because it doesn't exist. We only add logos for ERC-20 tokens.
