### ISSUE TITLE
Take back ownership issue

### ISSUE THREAD

**Issue by reyserveth** [5afe/safe-support#120]
### Issue Category

Other

### What happened?

User's issue with Take back ownership. He is getting an error "Cannot estimate gas"
<img width="538" alt="Capture" src="https://user-images.githubusercontent.com/114401730/213406659-2dded5a2-5c04-4e09-97fd-396a09f963a8.PNG">

### Date and time this happened or you first noticed this issue

01-19-23 4:22 PM

### Network

Ethereum Mainnet

### Token Type

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by inahlikenoother** [comment]
I have a user experiencing the same issue, user is trying to mint the manifesto here https://safe.mirror.xyz/tO26nZ4CruKCS8d49pyModJhzHw1TTm2QcMqx2lYaXQ  but keep getting this error
![image](https://user-images.githubusercontent.com/114049495/213408542-06b103d1-7357-401f-a2a2-b46dd8255ed2.png)

Wallet address used: 0x4b7f5762f5aB05fdEB8De0522154BeeA46873649 (Op)

**Comment by ennisjo** [comment]
Hey Rey, can you let the user know that they need to raise this issue with either Mirror or the wallet provider they're using? Unless they're using a Safe to claim the NFT, this does not relate to our support scope. Btw - can you let the user know that the 10k mint limit has been reached?

**Comment by ennisjo** [comment]
And can you close this issue if you're happy with the above :)

**Comment by reyserveth** [comment]
Thank you
