### ISSUE TITLE
Error GS010 when transacting with Walletconnect safe app

### ISSUE THREAD

**Issue by reyserveth** [5afe/safe-support#124]
Issue: When user uses walletconnect safe app in the Safe. He keeps getting the error GS010. The user tried other dapps like sushiswap and cowswap and it works fine. Done basic t/s already and it seems that it is isolated only when the user uses walletconnect that he is getting the error.
![image](https://user-images.githubusercontent.com/114401730/213919944-1b7c5d95-0756-4f12-8872-c55d62ca680c.png)

Network: Gnosis Chain
Safe address: 0x491A47E1c9585CC7416a19Bd7D347F21a2d664Df

**Comment by dasanra** [comment]
@reyserveth there are some smart contract interactions that are getting wrong gas limit estimations. User should just manually increase the gas limit, expanding the estimated fee field, until they don't get the error any more. We are aware of that and we are preparing a fix that should mitigate this scenarios

**Comment by mikhailxyz** [comment]
as outlined by @dasanra above the current solution is to manually increase the gas limit in transaction settings.

We will release a fix that would increase it automatically. The issue should only affect Gnosis Chain
