### ISSUE TITLE
[Polygon] USDC balance not visible in Assets page both in old and new UI 

### ISSUE THREAD

**Issue by joanpan** [5afe/safe-support#126]
### Issue Category

Token missing completely / not visible in the interface or service

### What happened?

USDC balance on etherscan:
![image](https://user-images.githubusercontent.com/114049668/215240626-cdb73542-4ae3-43a1-80df-5ad41b125885.png)

OLD UI
![image](https://user-images.githubusercontent.com/114049668/215240681-0c559988-30f1-44a7-bd37-8d36d7db64e2.png)

NEW UI
![image](https://user-images.githubusercontent.com/114049668/215240706-bf030a3b-40c8-4d58-a096-a9ee1f8c3678.png)

Address: 0x061D5579989BBe273321Bf993c09b2E8dF888ACf

User mentioned USDC balance showed previously but randomly disappeared from UI (funds were sent 7 hrs ago)

### Date and time this happened or you first noticed this issue

28-01-2023

### Network

Polygon

### Safe Address

0x061D5579989BBe273321Bf993c09b2E8dF888ACf

### Token Type

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mikhailxyz** [comment]
I've asked the backend team to take a look

**Comment by moisses89** [comment]
Could you check again? Seems that currently the token appear correctly.
https://app.safe.global/matic:0x061D5579989BBe273321Bf993c09b2E8dF888ACf/balances

**Comment by joanpan** [comment]
All good now, thanks
