### ISSUE TITLE
Incoming transaction missing on the transactions history on the UI on polygon network

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#127]
### Issue Category

Transaction missing / not visible in app or service

### What happened?

One received transaction happened 2 days ago is missing on the web app's Transactions History:

![image](https://user-images.githubusercontent.com/114005210/215472186-cccb03b7-f04b-48e0-909b-b03f51fd8a08.png)
 
![image](https://user-images.githubusercontent.com/114005210/215472213-6d28b6a7-4267-4bd4-8718-2b0f5a069004.png)

### Date and time this happened or you first noticed this issue

30-01-2023

### Network

Polygon

### Safe Address

matic:0xBcA3d442B16B173978105f7a4C61ef41eA779f3D

### Token Address

n/a

### Token Type

None

### Transactions

```shell
https://polygonscan.com/tx/0xc9b23238b31321b35260bc12dee9bfeaafdeb86e1237ed8ac29bf0c0699f538a
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mikhailxyz** [comment]
I've asked the backend team to take a look

**Comment by moisses89** [comment]
The transaction is currently appearing.

**Comment by Claire-serveth** [comment]
> I've asked the backend team to take a look

Thank you so much @mikhailxyz. Seems the transaction history is updated now. Closing this issue 🙏
