### ISSUE TITLE
Cannot swap using the Uniswap Safe dapp

### ISSUE THREAD

**Issue by reyserveth** [5afe/safe-support#128]
User tried to make a swap using the Uniswap Safe dapp. When the user clicks on the "Approve" button in Uniswap it is not responding. 

Safe address: 0xb0f8415fD93358d0FA9f57143595a248032E3Ebb
Network: Optimism

![image](https://user-images.githubusercontent.com/114401730/215530392-e0d0e098-d7b7-4935-aeb3-e3fa943ea5ab.png)

We already cleared cache and hard reset on the browser and used walletconnect and still nothing.

**Comment by JagoFigueroa** [comment]
Hi there! This is a known [issue](https://github.com/safe-global/safe-react-apps/issues/554) that will more than likely need to be tackled by the Uniswap team side. As a workaround could you let the user know to try connecting to the uniswap dapp via the wallet connect safe app? That should do the trick.

Cheers!
