### ISSUE TITLE
Cannot swap using the Uniswap Safe dapp

### ISSUE THREAD

**Issue by slon36** [5afe/safe-support#129]
### Issue Category

Other

### What happened?

I'm tried to make a **swap** using the **Uniswap Safe dapp.** When I click on the _**"Approve USDC"**_ button in Uniswap it's make a transaction.
But when I'm tried to make a **swap** it shows a button _"Approve USDC"_ again and **it doesn't respond.**
So I can't swap **USDC** on **ETH**.

Safe address: 0xb0f8415fD93358d0FA9f57143595a248032E3Ebb
Network: Optimism

scr_1
![image](https://user-images.githubusercontent.com/41619854/215531666-b7c690e0-afa0-4c0c-8a64-af2cad39bdea.png)
scr_2
![image](https://user-images.githubusercontent.com/41619854/215533493-9826562b-5654-4f0f-8fd1-2d56bcd7c662.png)
scr_3
![image](https://user-images.githubusercontent.com/41619854/215531878-96c0e2e1-7699-41d2-8e0f-4bc7f8be11aa.png)
(here I **click** on the "_Authorized Spender_ --> [Permit2]

https://optimistic.etherscan.io/address/0x000000000022D473030F116dDEE9F6B43aC78BA3

### Date and time this happened or you first noticed this issue

30-1-2023 (17:00)

### Network

Optimism

### Safe Address

0xb0f8415fD93358d0FA9f57143595a248032E3Ebb

### Token Address

USDC

### Token Type

ERC20

### Transactions

```shell
approve USDC on Uniswap
https://optimistic.etherscan.io/tx/0x3c863f37053c5ee73727309c794028d41833f11130caa6cbe3c517fb7ffd2892
revoke contract
https://optimistic.etherscan.io/tx/0xaec037c7197ceac9363b1fecd33aacf24e3f45838e1891b0674614cbbf0f6414
approve USDC on Uniswap (again)
https://optimistic.etherscan.io/tx/0x606bffb50b027676aa3f5ad444a40ad38f067050d2efa3cbfb880c4b5043eb91
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mikhailxyz** [comment]
We've reported the issue to the Uniswap team

**Comment by katspaugh** [comment]
Closing, please feel free to reopen if there's any update.
