### ISSUE TITLE
Getting Error -33004: Invalid Response in Safe mobile app when executing tx (Polygon)

### ISSUE THREAD

**Issue by inahlikenoother** [5afe/safe-support#13]
### Issue Category

Transaction execution issue

### What happened?

Getting **Error -33004: Invalid Response
Data: "response not found for request id 'int(4)'"** when executing tx from Safe mobile app in Polygon network. 

![47FA4E1F-61A3-4950-AB8B-BBDEAD3E3EF1](https://user-images.githubusercontent.com/114049495/191654656-3def01e1-c6cb-408a-8741-90ddcbe6aa17.jpeg)

### Date and time this happened or you first noticed this issue

22-09-2022 11:30

### Network

Polygon

### Safe Address

0x41710708EDD1e6ab1C8E13C5639b84Ed3DaDDfA9

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by liliya-soroka** [comment]
Thank you foe reporting. It's a known issue in the mobile app - https://github.com/safe-global/safe-ios/issues/2154
The fix will be available in the next release 3.17.0
