### ISSUE TITLE
[Gnosis Chain] Safe query in Dune shows negative value for xDAI

### ISSUE THREAD

**Issue by shebeengs** [5afe/safe-support#130]
### Issue Category

Other

### What happened?

Hi team, a user reported this query about Safes in Gnosis chain, showing a negative value for xDAI:
https://dune.com/safe/gnosis-chain

![image](https://user-images.githubusercontent.com/54754746/215596021-ebe20828-8fb3-45f0-a190-b0a0afefc08c.png)

Reported in Discord: https://discord.com/channels/907968493134155807/915922168846618674/1069711831914008656

### Date and time this happened or you first noticed this issue

31/01/2023 23:11:54

### Network

Gnosis Chain

### Safe Address

NA

### Token Address

NA

### Token Type

None

### Transactions

```shell
NA
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by med3000** [comment]
hi, thanks for raising - it is a known issue due to changes in how Gnosis chain bridge works. This is something we will look at updating in Dune but is currently low priority for us.
