### ISSUE TITLE
Failed Transaction with MATIC being sent to executing wallet to Safe

### ISSUE THREAD

**Issue by la1234512345** [5afe/safe-support#131]
### Issue Category

Transaction execution issue

### What happened?

User creates a 1inch swap transaction (Chainlink>USDT) via API which returns a failed transaction
Sample: 0xa06cdd52f22d4cc99e0a764252a30cbb0ee432c8ff7e3f6cd7a193bb8eecec2d

Together with the transaction above. A separate transaction is created that sends MATIC tokens from safe to executing wallet
Sample: 0x4bb504beb328576ff9e86660c37763f9c5d8b21433e5a320f5f3d3f48e1033bd
This send transaction does not reflect on the History tab either

### Date and time this happened or you first noticed this issue

Feb-01-2023

### Network

Polygon

### Safe Address

0x612C207a38769361216085b9096eFA628D9e4Bbd

### Token Type

None

### Transactions

```shell
https://polygonscan.com/tx/0x70e52a11717bb5cd303d4b8031e3f274ac4d9cc5918fa6faa8c232bd5d4827bd
https://polygonscan.com/tx/0xa06cdd52f22d4cc99e0a764252a30cbb0ee432c8ff7e3f6cd7a193bb8eecec2d
https://polygonscan.com/tx/0x35fb85a5c5e1ff29ce1e210a8febb86d70185e6b6081bda0a6c78961a4ff08a5
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mikhailxyz** [comment]
How did they create this transaction?

**Comment by piyushhanchate** [comment]
I used the safe-core-sdk to create it. Basically, fetched the transaction data from API, added custom gas price, and created a safeTransaction safe-core-sdk, then executed.

**Comment by mikhailxyz** [comment]
Please use the dev-support channel in discord, this issue is for support with our client-facing applications.
