### ISSUE TITLE
Ledger Nano X not showing in the Safe App (Android)

### ISSUE THREAD

**Issue by reyserveth** [5afe/safe-support#134]
The user installed the Safe app from Google Play on his Android device (12 version OS, no root), but the Safe app don't see the Ledger Nano X (user followed all instruction in the app). 

Safe network: BSC

Note: User can access the Safe just fine using his PC and iOS mobile device.

**Comment by liliya-soroka** [comment]
do you have information about the user device ?
We have known issues for the pixel devices

**Comment by Novobranec** [comment]
It's my ticket. :) My device: Xiaomi Note10 (Information from Android device: Model: m2101k7ag, OS Android 12 SKQ1.210908.001, MIUI Global 13.0.5)

**Comment by liliya-soroka** [comment]
Thank you @Novobranec, for the details.

**Comment by reyserveth** [comment]
Deleting this ticket as advised. Issue is related to this https://github.com/safe-global/safe-android/issues/1795
