### ISSUE TITLE
Frontend/UX problem - does not allow user to select the asset - using Brave browser

### ISSUE THREAD

**Issue by jakekvm01** [5afe/safe-support#137]
### Issue Category

Other

### What happened?

Problem regarding the "select an asset" dropbox when sending tokens using Brave Browser?
![image](https://user-images.githubusercontent.com/105864754/217310539-d52f176f-6020-4f25-821a-bb007604ac45.png)
![image](https://user-images.githubusercontent.com/105864754/217311581-3163cde9-ae7b-4d13-88ab-03557afb6f9a.png)

https://app.intercom.com/a/inbox/km54f6ih/inbox/shared/all/conversation/36000022594?view=List

- Done basic troubleshooting-

### Date and time this happened or you first noticed this issue

N/A

### Network

Polygon

### Safe Address

matic:0xF1A926cFF2d6358F58720775908686a800Ea2D04

### Token Address

N/A

### Token Type

None

### Transactions

```shell
https://app.intercom.com/a/inbox/km54f6ih/inbox/shared/all/conversation/36000022594?view=List
https://app.safe.global/matic:0xF1A926cFF2d6358F58720775908686a800Ea2D04
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by schmanu** [comment]
Did the user by any chance hide the native token in the interface?
That is the only way I was able to reproduce this.

**Comment by jakekvm01** [comment]
Let me check this first with the user. Thank you

**Comment by jakekvm01** [comment]
Resolved. Thank you @schmanu
