### ISSUE TITLE
[Missing Token] The following token is not up to date: BNB_USDT 

### ISSUE THREAD

**Issue by joanpan** [5afe/safe-support#14]
### What happened?

Network: BSC
BNB_USDT token not showing on Assets page. 

Safe Assets page:
![image](https://user-images.githubusercontent.com/114049668/192336483-0405dfea-64b7-47b4-af00-62740f4096d8.png)

On-chain:
![image](https://user-images.githubusercontent.com/114049668/192336576-41954a66-73c6-4383-adf2-4169fc4d49f1.png)

### Network

Ethereum Mainnet

### Safe Address

0x505d1180061727c59Ce04E7acfc117283CF797F0

### Token Address

0x55d398326f99059ff775485246999027b3197955

### What issue are you experiencing?

Missing completely / Not visible in the interface or service, Balance not up-to-date in the interface or service

### Transfers

```shell
1st - https://bscscan.com/tx/0x4d2a71de8b262fa37d14a6d97dfe1bfb2a3bd31e769f639fe34f69668247c8bd

2nd - https://bscscan.com/tx/0x14217ff1c675ac8b415298f825926f5fa15a74db81dc6d5be9c1070405badba0
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Uxio0** [comment]
This is fixed now, thanks for reporting
