### ISSUE TITLE
link for the Safe mobile app misconfigured

### ISSUE THREAD

**Issue by reyserveth** [5afe/safe-support#140]
<img width="253" alt="Capture" src="https://user-images.githubusercontent.com/114401730/217816921-62059c6a-fc88-469d-9240-07d2db311447.PNG">
As per user the link for the Safe mobile app (android) is misconfigured, on the "What's new" sidebar. It now points to the appstore.

**Comment by med3000** [comment]
hi @reyserveth thanks for flagging, the link has been updated :)
