### ISSUE TITLE
[iOS] Cannot execute transactions in Optimism

### ISSUE THREAD

**Issue by CindyLo0** [5afe/safe-support#141]
### Issue Category

Transaction execution issue

### What happened?

User cannot execute transactions using iOS mobile app. Works fine in web app. 

Please see screenshot and video recording for errors: 
![image](https://user-images.githubusercontent.com/79137197/218095843-d4b54669-9463-43e9-8bcc-80dec3b57348.png)

***User has requested to have the video deleted. 

### Date and time this happened or you first noticed this issue

10-02-2023 11:00

### Network

Optimism

### Safe Address

0x90BC4cf4C8bd23cBE78D45B0Ef9898C4C555768C

### Token Type

None

**Comment by Claire-serveth** [comment]
Safe address for this user: https://app.safe.global/oeth:0x659d2c7EC3D0a3d9Ac972EF36b132cbECe118462/home

**Comment by Claire-serveth** [comment]
> We have another user experiencing the same issue with an iPad.
 
> Safe address - https://app.safe.global/oeth:0xff0f16d86741bf6993ff0a055fc6098e0d1849e9/home

For this user ☝️ 

Safe mobile app version: 3.18.1
iOS version: 16.3.1

**Comment by katspaugh** [comment]
@5afe/safe-mobile have you looked into this? On the web, it works fine.

**Comment by liliya-soroka** [comment]
@katspaugh , I have an issue during execution on web too 
<img width="634" alt="image" src="https://user-images.githubusercontent.com/338622/224985975-85e2fa62-1870-4161-b8e9-73dffe14d2f1.png">

**Comment by liliya-soroka** [comment]
Reported to the mobile team. Please, follow the progress in the https://github.com/safe-global/safe-ios/issues/2961
