### ISSUE TITLE
(Op) iOS Safe mobile app constantly receiving notifications for incoming tokens

### ISSUE THREAD

**Issue by inahlikenoother** [5afe/safe-support#144]
### Issue Category

Other

### What happened?

User receives constant notifications in the safe mobile app about incoming tokens but when checking the safe and Optimism block explorer, there was only 1 receive transaction 

![image](https://user-images.githubusercontent.com/114049495/218250407-23f7468c-644a-4b88-a6d6-50625c4e1adb.png)
![image](https://user-images.githubusercontent.com/114049495/218250436-4f7b7587-3f6b-41ac-87d3-6ae0e55bfa3b.png)
![image](https://user-images.githubusercontent.com/114049495/218250511-8de10296-d323-4e43-b5bd-09a98beab13a.png)

### Date and time this happened or you first noticed this issue

11-02-2023 11:15

### Network

Optimism

### Safe Address

0x9D07041e0a29F3E017006e4850f614f28A541Bf8

### Token Type

None

**Comment by med3000** [comment]
hi @inahlikenoother thanks for raising this - would you find out if it was just for this transaction or is happening with others too.

**Comment by Claire-serveth** [comment]
> hi @inahlikenoother thanks for raising this - would you find out if it was just for this transaction or is happening with others too.

Hi @med3000, we'll surely update here as soon as we get the response from the user.

**Comment by Claire-serveth** [comment]
Issue seems resolved, closing this issue now.
