### ISSUE TITLE
Cannot remove liquidity on Uniswap (Polygon network)

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#145]
### Issue Category

Transaction execution issue

### What happened?

User was not able to remove liquidity on Uniswap. Tried interacting through walletconnect safe app, done basic troubleshooting steps including clear data; also tried using Uniswap's older version using IPFS links but transaction is not going through--even though user was able to confirm and execute the transaction.

![image](https://user-images.githubusercontent.com/114005210/218322364-b7f62e27-2877-44e5-9700-443f09e57ae4.png)
![image](https://user-images.githubusercontent.com/114005210/218322382-82642f74-5938-413d-88e1-3f535bcb34c3.png)

### Date and time this happened or you first noticed this issue

12-02-2023

### Network

Polygon

### Safe Address

matic:0xA4d03d17275159798ECaee3E5551B6da0AA981C5

### Token Type

None

**Comment by mikhailxyz** [comment]
We reported the bug to the uniswap team and awaiting action from them

**Comment by Claire-serveth** [comment]
> We reported the bug to the uniswap team and awaiting action from them

Thank you so much @mikhailxyz :)

**Comment by inkom-io** [comment]
Any updates?

**Comment by mikhailxyz** [comment]
@inkom-io this solely depends on Uniswap's team. They're looking at it, for updates please reach out to their support

**Comment by inkom-io** [comment]
Now is working, you can close the issue
