### ISSUE TITLE
Transferring a token via Multisig gets capped due to spending limit

### ISSUE THREAD

**Issue by shebeengs** [5afe/safe-support#148]
### Issue Category

Transaction execution issue

### What happened?

User is unable to transfer USDC out of the safe via a multisig (Send button). The amount gets capped due to the spending limit for that address. 
![image](https://user-images.githubusercontent.com/54754746/219883110-d9bd702b-5aca-421c-9a4e-ba212a5107e2.png)
![image](https://user-images.githubusercontent.com/54754746/219883234-2997fd16-5c0a-439e-b21d-8408e99e4b3e.png)

The safe only had 2 owners and both have spending limits. Impersonated user's owner wallet and I'm getting the same thing on my end on both wallets. 

Same behavior in Goerli as well. 
![image](https://user-images.githubusercontent.com/54754746/219883275-801c4561-0f2c-431f-a9de-ce7218cf4049.png)

### Date and time this happened or you first noticed this issue

18/02/2023 18:55:22

### Network

Ethereum Mainnet

### Safe Address

https://app.safe.global/eth:0xf1801A495775e56b3Ef043Fb3777a7a0b6C3bF09/home

### Token Address

https://etherscan.io/address/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48

### Token Type

ERC20

### Transactions

```shell
N/A
```

**Comment by iamacook** [comment]
We merged a [fix](https://github.com/safe-global/web-core/pull/1657) for this last week. It will be included in a forthcoming [hotfix](https://github.com/safe-global/web-core/pull/1683).

**Comment by shebeengs** [comment]
Thank you! 🙏
