### ISSUE TITLE
Wrong contract addresses displayed in UI transaction details

### ISSUE THREAD

**Issue by CindyLo0** [5afe/safe-support#151]
### Issue Category

Other

### What happened?

A user reported Safe UI is displaying the wrong contract addresses in Transaction details. Polygonscan displays the correct details but _receiver(address) displays the token address and _token(address) displays the receiver address instead of the other way around. Please see screenshots: 

![image](https://user-images.githubusercontent.com/79137197/221837203-a5f2d90e-2bc7-4a37-b300-b1a02a018ee4.png)
![image](https://user-images.githubusercontent.com/79137197/221837223-66d70b69-8566-4347-8dd7-59dbfe5c341d.png)
![image](https://user-images.githubusercontent.com/79137197/221837250-37a82be5-639c-4860-a472-1d199cd0b20b.png)

Sample transaction details: https://app.safe.global/transactions/tx?safe=matic:0x2f52AaC7cD0F8a83C15eE933F0b9c00F6A5A2f95&id=multisig_0x2f52AaC7cD0F8a83C15eE933F0b9c00F6A5A2f95_0x142480fb068c57c027d75184fb7ef49034142b644e7654e18d9f849dcb49e96f

Same issue with other transactions in this safe, please see History tab. 

### Date and time this happened or you first noticed this issue

28-02-2023 11:00

### Network

Polygon

### Safe Address

matic:0x2f52AaC7cD0F8a83C15eE933F0b9c00F6A5A2f95

### Token Address

0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174

### Token Type

ERC20

### Transactions

```shell
https://polygonscan.com/tx/0x93be75e862e8049251c6e5d86a063b1e7e2535d8c17b02cb68bb070c091e3970

Same issue with this transaction, 
https://polygonscan.com/tx/0x3494abed3ac4ba10af74e0912f388ac494044610cb44f43227cb925a6308189f
```

**Comment by katspaugh** [comment]
@5afe/safe-services can you create an issue on your side?
Looks like the tx is decoded incorrectly.

The fields are indeed swapped: https://safe-client.safe.global/v1/chains/137/transactions/multisig_0x2f52AaC7cD0F8a83C15eE933F0b9c00F6A5A2f95_0x142480fb068c57c027d75184fb7ef49034142b644e7654e18d9f849dcb49e96f)

**Comment by Uxio0** [comment]
Hi @katspaugh @CindyLo0 provided contract is a Diamon Proxy. Proxies are not supported for decoding, so service is trying its best using signature from other supported contract
