### ISSUE TITLE
Missing token (Blur Pool)

### ISSUE THREAD

**Issue by CindyLo0** [5afe/safe-support#152]
### Issue Category

Token missing completely / not visible in the interface or service

### What happened?

Token Blur Pool 0x0000000000A39bb272e79075ade125fd351887Ac is not displayed in the Safe UI > Assets
![image](https://user-images.githubusercontent.com/79137197/221881400-9d2099fb-f607-4f7d-a7b7-2bf4953b6dde.png)

Etherscan - https://etherscan.io/address/0x3cB87118B42c056616780A4105Fb01d89F838a21
![image](https://user-images.githubusercontent.com/79137197/221881556-6e943a27-4589-4496-af0e-f397b6207441.png)

### Date and time this happened or you first noticed this issue

28-02-2023 16:00

### Network

Ethereum Mainnet

### Safe Address

eth:0x3cB87118B42c056616780A4105Fb01d89F838a21

### Token Address

0x0000000000A39bb272e79075ade125fd351887Ac

### Token Type

ERC20

### Transactions

```shell
https://etherscan.io/address/0x3cB87118B42c056616780A4105Fb01d89F838a21#tokentxns
```

**Comment by katspaugh** [comment]
No token in the CGW response either: https://safe-client.safe.global/v1/chains/1/safes/0x3cB87118B42c056616780A4105Fb01d89F838a21/balances/usd?trusted=false

@Uxio0 any clue?

**Comment by Uxio0** [comment]
Contract is not valid for us, it has `name` but no `symbol`, so it's not indexed. I fixed it manually and should be showing as soon as cache expires
