### ISSUE TITLE
Can't execute transaction using Ledger (Polygon)

### ISSUE THREAD

**Issue by jakekvm01** [5afe/safe-support#154]
### Issue Category

Transaction execution issue

### What happened?

User can't execute transaction using his Ledger.
Already done basic troubleshooting, using other device and browser.

User is getting these errors when trying to execute the transaction.
![image](https://user-images.githubusercontent.com/105864754/222464955-5aa39f36-f141-44aa-91b9-166f905ea5f8.png)
![image](https://user-images.githubusercontent.com/105864754/222466641-3e38564b-0181-4fe3-ad67-f635755c2b8d.png)

### Date and time this happened or you first noticed this issue

N/A

### Network

Polygon

### Safe Address

https://app.safe.global/transactions/queue?safe=matic:0xAF8A1548Fd69a59Ce6A2a5f308bCC4698E1Db2E5

### Token Address

N/A

### Token Type

None

### Transactions

```shell
https://app.safe.global/transactions/queue?safe=matic:0xAF8A1548Fd69a59Ce6A2a5f308bCC4698E1Db2E5
```

**Comment by liliya-soroka** [comment]
Thank you for the report.
The issue is reported to the team. Please, follow the https://github.com/safe-global/web-core/issues/1748 to see the progress. 
It happens not only for the Ledger nano x owners

**Comment by jakekvm01** [comment]
Thank you @liliya-soroka
