### ISSUE TITLE
Not seeing some of NFT collectibles in Safe UI (Using Desktop app)

### ISSUE THREAD

**Issue by jakekvm01** [5afe/safe-support#157]
### Issue Category

Token missing completely / not visible in the interface or service

### What happened?

![image](https://user-images.githubusercontent.com/105864754/225707263-ef6eee2e-bdf6-4cc1-8c84-7f2ea8585b06.png)

Basic troubleshooting (Done)
Visible using webapp but user prefer using Desktop app.
Same issue on my end as well using Desktop app. 
![image](https://user-images.githubusercontent.com/105864754/225707746-1e1bec40-5b3b-4f0a-b096-61b517fa32d7.png)

### Date and time this happened or you first noticed this issue

N/A

### Network

Ethereum Mainnet

### Safe Address

0x3f657B1182008520A5e9cCC75884ef01422B2559

### Token Address

N/A

### Token Type

ERC721

### Transactions

```shell
https://app.safe.global/apps?safe=eth:0x3f657B1182008520A5e9cCC75884ef01422B2559
```

**Comment by katspaugh** [comment]
We will not support the desktop app going forward. NFTs will soon stop working there altogether due to backend changes.

Please advise desktop app users to use the new web app. It’s installable and offline-friendly.

**Comment by katspaugh** [comment]
Here's how you install it as a standalone app:
<img width="1078" alt="Screenshot 2023-03-17 at 13 08 40" src="https://user-images.githubusercontent.com/381895/225900234-a702c6bd-7bfd-4b9b-97bc-4f9b41e43694.png">
