### ISSUE TITLE
Normal token transfer/send transactions displays contract interaction in Queue/History tab

### ISSUE THREAD

**Issue by CindyLo0** [5afe/safe-support#161]
### Issue Category

Other

### What happened?

Queue/History tab shows a contract interaction instead of a normal send transaction with token amount displayed. 
User is just sending tokens via Assets > Send button 
![image](https://user-images.githubusercontent.com/79137197/226908417-9135b154-f509-42c0-812e-764fa9169425.png)

![image](https://user-images.githubusercontent.com/79137197/226907443-4ced9939-146d-4c6f-8ae3-ee35ef1bbece.png)

### Date and time this happened or you first noticed this issue

22-03-2023 14:30

### Network

Binance Smart Chain

### Safe Address

bnb:0xD2cc1Dc3423bc317E585115f42E998D888957649

### Token Address

0x510Ca7D22A84599e7d0f15F09E674056a6255389

### Token Type

ERC20

### Transactions

```shell
https://bscscan.com/tx/0x6286cd1594fec06a5099161f556f69e9e3c0597085281cedf38dd1bba0cb6a25
https://bscscan.com/tx/0x6ceec29dd067b621a88970fde356a35c6b6d8abce4674576b3b5ec982b690f1c
https://bscscan.com/tx/0x087ea4a8c93d2e8b5f1b334d4810ede7f47ba58e3443b70644c312932fc771fd
```

**Comment by iamacook** [comment]
I've passed this onto the team and they'll look into it. cc @hectorgomezv

**Comment by hectorgomezv** [comment]
@CindyLo0 the issue seems fixed now, could you confirm? Thanks! cc. @iamacook

**Comment by DiogoSoaress** [comment]
Hi @reyserveth can you share new details on why this ticket was reopened? Is it still about the same Safe / same token? AFAIK no regression should have been introduced thus asking.
