### ISSUE TITLE
[Polygon] Transaction execution reverted: GS020 error 

### ISSUE THREAD

**Issue by Sherie15** [5afe/safe-support#166]
### Issue Category

Transaction execution issue

### What happened?

The user tried to initiate a transaction but it shows 1 out 1 status waiting for execution from the pending queue. The current Safe policies require 2 out of 2 confirmations. Nonce 25 doesn't appear in the transaction history, as per user _nonce 25 (that was actually a tx to add a new owner and increase the threshold)_

Safe version: 1.3.0+L2

![image](https://user-images.githubusercontent.com/113986185/229421548-c654e5ef-91bd-4286-bf09-18f01fb961d2.png)
![image](https://user-images.githubusercontent.com/113986185/229421638-f78ccc8c-c547-4405-ba42-f1787e251af3.png)
![image](https://user-images.githubusercontent.com/113986185/229421676-fa4ff43f-7e13-4567-91dd-348249c59fff.png)

### Date and time this happened or you first noticed this issue

03-04-2023 14:49 

### Network

Polygon

### Safe Address

matic:0xB817599dae5fC26D4959f5be8ad58eD42c80C9f4

### Token Type

None

**Comment by Sherie15** [comment]
Hi team, nonce 25 is now visible in the transaction history, waiting for the user to complete the signature for none 26 and then execute. I will be closing this ticket once user nonce 26 will be executed. Thank you!

![image](https://user-images.githubusercontent.com/113986185/229666759-9b778fe2-a9fb-4a19-bfa1-4f47bde3dfb8.png)

**Comment by med3000** [comment]
thank you @Sherie15 - this was an indexing issue resolved yesterday evening which needed a re-sync that updated the users Safe interface with the missing tx.

**Comment by ubinatus** [comment]
Hi @Sherie15 and @med3000. I'm the user of that Safe. I've just executed tx with nonce 26. Thanks for the support.

**Comment by Sherie15** [comment]
Hi team, reopening this ticket as nonce 26 has been executed but is not visible in the transaction history. 
![image](https://user-images.githubusercontent.com/113986185/229955317-b4f323e0-6625-4b96-8df0-ae8f24e66d91.png)
![image](https://user-images.githubusercontent.com/113986185/229955401-080e2aab-4c6c-498c-9309-f520e655f066.png)

**Comment by ubinatus** [comment]
Nice catch. In case it helps debugging, the proccess for Tx with nonce 26 was the following (doesn't mean replicating it would necessarily trigger the bug): 

1. Tx with nonce 26 created on web
2. 1/2 approval submitted on web
3. 2/2 approval submitted on mobile (iOS SafeApp)
4. Tx with nonce 26 executed on mobile (iOS SafeApp)

**Comment by francovenica** [comment]
The tx 26 is showing now in the history tab. I'll close again, but feel free to reopen it if the issue happens again.
