### ISSUE TITLE
Can user recover tokens mistakenly sent to the $SAFE token contract?

### ISSUE THREAD

**Issue by CindyLo0** [5afe/safe-support#168]
### Issue Category

Other

### What happened?

User mistakenly sent their tokens to the $SAFE token contract address. Can they still recover the tokens?

Transaction hash - https://etherscan.io/tx/0x36d6365e0d52abdbd175bf51c6ecdb3125ab3abe551c0487c8c33e6d5acd7b58
Token amount - 231,000 TPY

### Date and time this happened or you first noticed this issue

08-04-2023

### Network

Ethereum Mainnet

### Safe Address

0xE00E52489Aa7208260d7d924bEbe7b64ea64efC9

### Token Address

0x968Cbe62c830A0Ccf4381614662398505657A2A9

### Token Type

ERC20

### Transactions

```shell
https://etherscan.io/tx/0x36d6365e0d52abdbd175bf51c6ecdb3125ab3abe551c0487c8c33e6d5acd7b58
```

**Comment by rmeissner** [comment]
Yes (see https://github.com/safe-global/safe-token/blob/main/contracts/TokenRescuer.sol), but it requires a dao vote. So best would be to request this in the [forum](https://forum.safe.global)

**Comment by Claire-serveth** [comment]
> Yes (see https://github.com/safe-global/safe-token/blob/main/contracts/TokenRescuer.sol), but it requires a dao vote. So best would be to request this in the [forum](https://forum.safe.global)

Alright, will let the user know. Thank you so much @rmeissner 🙏 I'll go ahead and close this issue as well.
