### ISSUE TITLE
Threshold is still showing 2/2 for newly created transactions when the current threshold is 3/4 (Polygon)

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#169]
### Issue Category

Transaction execution issue

### What happened?

User is getting GS020 error when executing a transaction since the threshold seemed to be not updated on the UI. User's current threshold is 3/4 but when he tries creating a new transaction, it's still showing 2/2:

![image](https://user-images.githubusercontent.com/114005210/230789384-38f9b3f0-7ee4-4ac6-99e5-dfe891eb79f8.png)
![image](https://user-images.githubusercontent.com/114005210/230789392-e794fe79-da0c-4305-8009-c5ccf232aa97.png)

### Date and time this happened or you first noticed this issue

08-04-2023

### Network

Polygon

### Safe Address

matic:0xa84F4Ab7cC67e9421B05bAB84E1167CD497C75Ee

### Token Address

n/a

### Token Type

None

**Comment by francovenica** [comment]
Hi there. The team worked on it and should be fixed now. The transaction 38 where you changed the tx is now visible and your tx in queue are actually waiting for the new threshold.
I'll close this issue
