### ISSUE TITLE
Multiple Arbitrum users are experiencing an issue in loading their Safe wallets.

### ISSUE THREAD

**Issue by jakekvm01** [5afe/safe-support#175]
### Issue Category

Safe loading issue, doesnt load on any interface

### What happened?

Users can't load their Safe wallets.
![image](https://user-images.githubusercontent.com/105864754/232135611-2e80b89f-7709-4732-b4e6-e91e31a3340a.png)

### Date and time this happened or you first noticed this issue

N/A

### Network

Arbitrum

### Safe Address

N/A

### Token Address

N/A

### Token Type

None

**Comment by mahreenisba** [comment]
![safe](https://user-images.githubusercontent.com/127922764/232182424-93e995aa-a556-4887-aadf-ea18540b70cd.jpg)
I can't load Safe Wallet, after trying to submit vote on Arbitrum proposal

**Comment by kingmayor2022** [comment]
Is gnosis safe still safe?

**Comment by Rider2023** [comment]
![image](https://user-images.githubusercontent.com/130848694/232230609-21ec1bb5-13be-470f-826d-580244dc2d26.png)

Hello, I still can't do anything with this wallet,

**Comment by Rider2023** [comment]
![IMG_1104](https://user-images.githubusercontent.com/130848694/232232911-383b68b9-a765-4083-873f-7fe6db2efe5d.jpeg)

**Comment by Rider2023** [comment]
We continue with the problem. The wallet is restored, but it has a stuck transaction that corrupts it every time. Then I can't get out of the problem because the problem will fail again

**Comment by Rider2023** [comment]
![image](https://user-images.githubusercontent.com/130848694/232237175-9ddafc38-b020-46c0-8b79-e13eea891e1a.png)

**Comment by Rider2023** [comment]
Transactions do not load correctly and fail to load

**Comment by Rider2023** [comment]
![image](https://user-images.githubusercontent.com/130848694/232238424-f208e363-3aba-447c-8fe7-c3eca4bd1329.png)

Full of errors!!!!!

**Comment by Rider2023** [comment]
**And in the wallets to confirm the operations, it says that the information loads with errors. Messages already sent!!
**

**Comment by Rider2023** [comment]
![image](https://user-images.githubusercontent.com/130848694/232238592-1bb52c40-62fe-437a-a3ee-02a791c430bc.png)

**Comment by Rider2023** [comment]
OK Now the successful historical operations are well loaded, but not the pending ones. Eye that has all these we are spending GAS in all the retries!!!

**Comment by Rider2023** [comment]
Everything that is happening jeopardizes the Wallets in some way?

**Comment by Rider2023** [comment]
When I am going to do the execution of the transaction, in the last step, I click on execute, and Submit should leave, and at that stage the transaction falls


![image](https://user-images.githubusercontent.com/130848694/232245311-2f555700-0b8b-47c0-a4b8-3aefb26e70e7.png)

**Comment by Rider2023** [comment]
Does anyone read these messages to keep posting them or am I wasting my time on this?

**Comment by Sherie15** [comment]
Reported cases of being unable to launch their Safe UIs are now u and running. Closing this ticket!
