### ISSUE TITLE
Trezor scanned addresses only displaying 10 addresses

### ISSUE THREAD

**Issue by joanpan** [5afe/safe-support#178]
### Issue Category

Other

### What happened?

User has 3 signers, the first signer is on their Trezor (address number 15) - but when connecting to the Safe UI, it is only showing 10 addresses so user can't view their 15th address. User is using at least 20 trezor addresses, they tried connecting to other dapps and it's showing

The user has three signers, the first signer is on their Trezor (address #15), but when they connect to the Safe UI, it only displays 10 addresses, therefore the user is unable to access their 15th address (first signer).

See screenshot:
![image](https://user-images.githubusercontent.com/114049668/233509990-132439c6-ff59-4299-9363-e88ae8144b9c.png)

The user has at least 20 trezor addresses, and when they tried to connect to other dapps, all of them appeared.
Is this a limitation in the Safe UI? Is there a way to increase the number of scanned addresses displayed?

### Date and time this happened or you first noticed this issue

21-04-23

### Network

Ethereum Mainnet

### Token Type

None

**Comment by liliya-soroka** [comment]
Known issue, please follow - https://github.com/safe-global/web-core/issues/1424

**Comment by joanpan** [comment]
Will do, thank you~

**Comment by liliya-soroka** [comment]
I suggest to close the support ticket on follow the original one on the team board

**Comment by joanpan** [comment]
Got it, thanks again
