### ISSUE TITLE
[Goerli] Safe couldn't be loaded

### ISSUE THREAD

**Issue by joanpan** [5afe/safe-support#18]
### Issue Category

Safe loading issue, doesnt load on any interface

### What happened?

User reported safes not loading. Tested on my end, same issue.
![image](https://user-images.githubusercontent.com/114049668/192655522-56e2a88e-5864-495b-87d4-e77edcf792a5.png)

Safes affected:
https://gnosis-safe.io/app/gor:0x2FE1aE582F5Fd58f06a7DE630FEEC2b61E16Bc62/home
https://gnosis-safe.io/app/gor:0xdb7bae1f6656429B51F06E3Ed8db864e2774B426/home

### Date and time this happened or you first noticed this issue

28-09-2022

### Network

Etherum Testnet

### Safe Address

0x2FE1aE582F5Fd58f06a7DE630FEEC2b61E16Bc62, 0xdb7bae1f6656429B51F06E3Ed8db864e2774B426

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by med3000** [comment]
hi, thanks for raising this, the affect Safes appear to be loading for me now - can you confirm if this is true for you also?

**Comment by joanpan** [comment]
Working now, thanks
