### ISSUE TITLE
[Eth Mainnet] Asset page/all token balance not visible with error "There was an error loading your assets"

### ISSUE THREAD

**Issue by la1234512345** [5afe/safe-support#180]
### Issue Category

Token missing completely / not visible in the interface or service

### What happened?

User gets an error when navigating to https://app.safe.global/balances?safe=eth:0xb1720612D0131839DC489fCf20398Ea925282fCa instead of assets/balance showing

Gets the same error for other browsers (Chrome, Brave, Firefox)
![image](https://user-images.githubusercontent.com/114544040/233815357-485cfdbe-69e9-424e-b745-e0a6ce2534e6.png)

### Date and time this happened or you first noticed this issue

23/04/2023

### Network

Ethereum Mainnet

### Safe Address

0xb1720612D0131839DC489fCf20398Ea925282fCa

### Token Address

All tokens including ETH

### Token Type

None

### Transactions

```shell
NA
```

**Comment by liliya-soroka** [comment]
The issue was reported to the infrastraction team.

**Comment by liliya-soroka** [comment]
The issue was fixed and released to prod. Could you check and close the support ticket?
?

**Comment by la1234512345** [comment]
Hi there, yes. Thank you. The issue is already fixed. Closing this ticket now
