### ISSUE TITLE
Can't confirm/initiate transactions on iOS safe mobile app and web app mobile (Safari) using Trustwallet in Polygon network

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#184]
### Issue Category

Transaction execution issue

### What happened?

No confirmation popping up on trustwallet when user initiates/submits any transaction using the Safe mobile app (but was able to execute after transactions had been initiated and confirmed by other owner--current threshold 2/3). Details:

Safe mobile app: v3.19.1 (1700)
Device: iPhone 13 Pro
iOS version: 16.3.1
Trustwallet mobile app: v8.6

Steps to reproduce (Safe mobile app):

1: User initiates transaction
2. Selected connected owner key (Trust wallet)
![image](https://user-images.githubusercontent.com/114005210/234867940-d15adcc2-1b28-44a0-b2c4-1ba944b751e2.png)
3. Clicked submit; message prompts "Confirm transaction with your owner wallet" 
4. No confirmation popped up on Trustwallet app

Other issue facing using Safari Mobile + Trust Wallet mobile;

1. Open Safe in Safari Mobile
2. Initiate transaction for replacing the owner
3. Click Submit - the web page of Trust Wallet will open with the button on the top - OPEN, to open in Trust Walet
4. Trust Wallet opens, face id unlock, and nothing happens - no transaction
5. Return to Safari and click Back in browser
6. The page reloads with transaction and Trust Open wallet page will open again (Same with #3)
7. Click Open again, iOS will switch you to Trust Wallet app again, BUT now the Transaction will FINALLY APPEAR!
![image](https://user-images.githubusercontent.com/114005210/234870178-5188168d-ae25-4545-8fc7-53367043f0d4.png)

Note: User is not comfortable sharing his Safe address

### Date and time this happened or you first noticed this issue

27-042023

### Network

Polygon

### Token Type

None

**Comment by liliya-soroka** [comment]
Could you add in the title that It's not only for the Safe mobile app but also for Web app on mobile

**Comment by Claire-serveth** [comment]
> Could you add in the title that It's not only for the Safe mobile app but also for Web app on mobile

Oh, sure @liliya-soroka thank you 🙏

**Comment by Davcontrol** [comment]
Do you still have the same issue

**Comment by oceanemil** [comment]
> Do you still have the same issue

Yep

**Comment by Davcontrol** [comment]
Talk to Onsite Control on the [Live help website] (https://onsitecontrol.online/) so that your problem can be investigated. To get a quicker response, kindly use the live chat icon on the lower right side to start a chat with a member of our service.

**Comment by oceanemil** [comment]
Btw, it is still not working... (
