### ISSUE TITLE
Unrecognized addresses showing up in the Confirmations list

### ISSUE THREAD

**Issue by joanpan** [5afe/safe-support#186]
### Issue Category

Other

### What happened?

Unrecognized addresses showing up in the Confirmations list for multiple executed transactions. 
![image](https://user-images.githubusercontent.com/114049668/234997480-b53bc46f-40fd-482d-a18d-9acd0ca6121b.png)

List of owners:
![image](https://user-images.githubusercontent.com/114049668/234997133-b54cab09-dd0e-4cda-938a-9781c3128ed3.png)

Checked their transaction history and there were no changes in the owners.

_User requested not to post their safe address_

### Date and time this happened or you first noticed this issue

28-04-2023

### Network

Ethereum Mainnet

### Token Type

None

**Comment by katspaugh** [comment]
https://etherscan.io/address/0xD92E9F039E4189c342b4067CC61f5d063960D248 – this is the contract the account was supposed to have interacted with, but there's no transaction with that tx hash. So it's most likely a fake/scam event that got indexed as a Safe tx.
The user should ignore it and use the Address Book to better differentiate owners.

**Comment by la1234512345** [comment]
History and confirmation now shows the correct addresses. Closing this ticket. Thanks!
