### ISSUE TITLE
Fiat value not showing up on the UI (both web app and mobile app) for polygon network

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#187]
### Issue Category

Other

### What happened?

Fiat value is still not showing up on the UI for about 24 hours now--this is both on the web app and the mobile app: 

![image](https://user-images.githubusercontent.com/114005210/235454712-d74bdd83-2856-4d2b-b97a-d2850e4dc303.png)

Device OS: iOS 16.3.1
Safe app version: 3.19.1 (1700)
Device version: iPhone 13 Pro
Safe Web version: v1.8.1

### Date and time this happened or you first noticed this issue

01-05-2023

### Network

Polygon

### Token Address

0xc2132D05D31c914a87C6611C10748AEb04B58e8F, 0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174

### Token Type

ERC20

**Comment by liliiaorlenko** [comment]
hey, can we get a safe address to reproduce issue?

**Comment by Sherie15** [comment]
Hi team, the user already reported that it now working properly.
![image](https://user-images.githubusercontent.com/113986185/235633324-4bd85e38-b2a2-43b0-9845-56d54c54e62c.png)

**Comment by oceanemil** [comment]
Doesn't work again... (

**Comment by liliiaorlenko** [comment]
> Doesn't work again... (

please provide your address so we can reproduce this issue

**Comment by Sherie15** [comment]
Hi @liliiaorlenko, this is the Safe address matic:0xaad8DAFcF6F5fd15d2c7097Ea38dcA1995D88d90

![image](https://user-images.githubusercontent.com/113986185/236784472-a4e016ea-4865-4cc1-9084-46bb0decf7ec.png)
![image](https://user-images.githubusercontent.com/113986185/236784589-c605341d-dcbc-4882-9e92-e83406ec9ea7.png)

**Comment by Sherie15** [comment]
Hi team, it seems that UI is now updated for the USDT fiat value.

![image](https://user-images.githubusercontent.com/113986185/236970395-0dc3f046-51d3-4d54-98fb-a7f9911c9fad.png)
