### ISSUE TITLE
Ethereum - Cannot sign transaction with WalletConnect

### ISSUE THREAD

**Issue by inahlikenoother** [5afe/safe-support#191]
### Issue Category

Transaction execution issue

### What happened?

User gets the following error when signing a transaction using WalletConnect
![image](https://user-images.githubusercontent.com/114049495/236608599-24d47241-8317-4b0d-8a15-f18a959ef5b6.png)

### Date and time this happened or you first noticed this issue

06-05-2023

### Network

Ethereum Mainnet

### Safe Address

0xecB0CCB33a2239e420057da30b2dDaF42bb2b6D8

### Token Type

None

**Comment by schmanu** [comment]
What is the owner wallet the user is using here?

**Comment by Sherie15** [comment]
Hi @schmanu the user mentioned. 

_I was able to get a step further by use metamask as a signer, but now I run into the issue of:_

![image](https://user-images.githubusercontent.com/113986185/236785419-6ea7cab7-937b-4520-87b5-411c19fc13f6.png)

**Comment by schmanu** [comment]
Hmm the User is using a feature which is not live on prod yet.
Do you know which deployment is being used here?

**Comment by Sherie15** [comment]
This was the error he originally encountered. "The method eth_signTypedData_v4 does not exist/is not available".

**Comment by schmanu** [comment]
Hey @Claire-serveth and @Sherie15 we found the issue. It will be fixed in this issue: https://github.com/safe-global/safe-wallet-web/pull/1958

**Comment by Claire-serveth** [comment]
> Hey @Claire-serveth and @Sherie15 we found the issue. It will be fixed in this issue: [safe-global/safe-wallet-web#1958](https://github.com/safe-global/safe-wallet-web/pull/1958)

Thank you so much @schmanu 🙏

**Comment by Claire-serveth** [comment]
Closing this issue now 🙏
