### ISSUE TITLE
Request Finance: Safe UI keeps asking for token approval for every transaction and does not allow to enter max amount

### ISSUE THREAD

**Issue by joanpan** [5afe/safe-support#194]
### Issue Category

Other

### What happened?

For reference: 
![image](https://github.com/5afe/safe-support/assets/114049668/d5f4e32b-816c-44c4-aef7-68da63f3d96e)

Tried basic troubleshooting, same issue. The interface keeps asking for token approval (every request finance transaction) and they can't fill the max amount of approval but if left blank, the transaction can go through anyway.

User (CEO of Request finance) is unsure if this is an issue from Safe or Request Finance side.

### Date and time this happened or you first noticed this issue

12-05-2023

### Network

Ethereum Mainnet

### Safe Address
eth:0xBAE3d36E5fb173F8fAEdFcc7314F5204596FFCD2

_No response_

### Token Type

None

**Comment by schmanu** [comment]
Hey @joanpan,

The amount can not be changed when the transaction is in the queue and therefore already signed.

The user that initially creates the transaction is able to change the approval amount. 
See here for instance a multiSend of 2 approvals.
![Screenshot 2023-05-12 at 09 31 05](https://github.com/5afe/safe-support/assets/2670790/8d6c9817-f542-4584-9c47-dc1b75bef4bb)

If that doesnt help it would help us to see the transaction data of an example as I am not familiar with the RequestFinance transactions.

**Comment by joanpan** [comment]
@schmanu thank you, will let them know!

**Comment by Sherie15** [comment]
@schmanu Closing this ticket, the user is good to go. Thank you so much for the help.
