### ISSUE TITLE
Typo in Safe mobile iOS

### ISSUE THREAD

**Issue by shebeengs** [5afe/safe-support#196]
### Issue Category

Other

### What happened?

User was confused why creating a BSC safe in iOS app asks for an Ethereum address as an owner. 
![image](https://github.com/5afe/safe-support/assets/54754746/dec4012a-3998-496a-8006-8e3286dc38fc)

### Date and time this happened or you first noticed this issue

15/05/2023 02:58:45

### Network

Binance Smart Chain

### Safe Address

NA

### Token Address

NA

### Token Type

None

### Transactions

```shell
None
```

**Comment by schmanu** [comment]
The issue was forwarded to the mobile team.

**Comment by shebeengs** [comment]
Thanks. I'll go ahead and close this then. 🙏
