### ISSUE TITLE
Safe is READ-ONLY when connected to Owner wallet

### ISSUE THREAD

**Issue by joanpan** [5afe/safe-support#20]
### Issue Category

Other

### What happened?

Owner wallet: eth:0xFA2930a9d96e91B0A7e78d9fEBB7A8c744afD0da

Steps taken:
- disconnected wallet
- deleted cookies on gnosis site
- closed gnosis site
- opened metamask extension and removed connections to gnosis from all wallets
- cleared cookies, history other browser data
- closed chrome and reopened
- update chrome
- for some reason, user does not want to try firefox and walletconnect
- 
![image](https://user-images.githubusercontent.com/114049668/193149412-a0937400-1995-4e8f-9552-20763a80b234.png)
![image](https://user-images.githubusercontent.com/114049668/193149432-2484d35f-49ab-430e-9203-edff2381d765.png)

### Date and time this happened or you first noticed this issue

30-09-2022

### Network

Ethereum Mainnet

### Safe Address

0x2160e03972baD7BBCD9d547D01C8851004780134

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by med3000** [comment]
hi @joanpan taking a look into this, could you find out if the same is happening on the second owner also? I see an outgoing transaction sent after this ticket was created.

**Comment by med3000** [comment]
hi @joanpan will close this ticket off since no further news from the user. thanks
