### ISSUE TITLE
Duplicate notifications for transactions using Safe mobile app on iOS

### ISSUE THREAD

**Issue by Sherie15** [5afe/safe-support#201]
### Issue Category

Other

### What happened?

The user has been experiencing a recurring issue of duplicate incoming transaction notifications shown in the screenshot below.

Safe app version: 3.19.2
iOS version: iOS 16.4.1

![image](https://github.com/5afe/safe-support/assets/113986185/656a7638-fbaf-45b3-8063-b536fb2b4067)

### Date and time this happened or you first noticed this issue

20-05-2023   04:01 PM

### Network

Ethereum Mainnet

### Safe Address

eth:0xc5e9Febecd9fD19597566aaE97A61EbCe73b2C8B

### Token Type

None

**Comment by rudyfraser** [comment]
Happened again for a third time on the same transaction 1 hour after the original transaction was received.![image](https://github.com/5afe/safe-support/assets/26655424/4f022d72-706d-4a29-849e-e3e0cb11ca6c)

**Comment by liliya-soroka** [comment]
thank you for reporting. This is a known issue on the back-end side.

**Comment by Sherie15** [comment]
Already fixed here: https://github.com/safe-global/safe-transaction-service/pull/1483
