### ISSUE TITLE
Opensea buttons not working (error 404) 

### ISSUE THREAD

**Issue by jakekvm01** [5afe/safe-support#203]
### Issue Category

Other

### What happened?

Opensea buttons in ASSETS>NFTs not working. It gives error 404 on the page when you click the icon.
![image](https://github.com/5afe/safe-support/assets/105864754/d2ea55b8-695d-46a3-9a26-f64cbe3cc6fe)
![image](https://github.com/5afe/safe-support/assets/105864754/cb3afadc-2e8b-4e0f-b877-7fb72ac503f0)

### Date and time this happened or you first noticed this issue

N/A

### Network

Ethereum Mainnet

### Safe Address

eth:0x55ecA4D1c9eA7021509a7cd88C68c279dABDd37d

### Token Address

N/A

### Token Type

ERC721

### Transactions

```shell
https://app.safe.global/balances/nfts?safe=eth:0x55ecA4D1c9eA7021509a7cd88C68c279dABDd37d
```

**Comment by liliya-soroka** [comment]
reported to the team. Please, follow the issue - https://github.com/safe-global/safe-wallet-web/issues/2078

**Comment by Claire-serveth** [comment]
> reported to the team. Please, follow the issue - [safe-global/safe-wallet-web#2078](https://github.com/safe-global/safe-wallet-web/issues/2078)

Thank you so much @liliya-soroka 🙏 I'll forward the said issue to the user as well. Closing this issue now.
