### ISSUE TITLE
Cannot execute transactions, getting "4 signatures missing" error

### ISSUE THREAD

**Issue by phoebe-serveth** [5afe/safe-support#204]
### Issue Category

Transaction execution issue

### What happened?

Safe has 8 of 17 threshold but the UI only asks for 4 of 4 signatures. No option for other 4 owners (5th - 8th signers) to confirm/sign the transactions, only see option to execute. Getting "4 missing signatures" when trying to execute a transaction. 
![image](https://github.com/5afe/safe-support/assets/114040259/f9e8432f-0eab-4896-9c14-db04cea17fea)
![image](https://github.com/5afe/safe-support/assets/114040259/bb9ee69d-29c3-4c94-ad6a-648f4a51e827)

### Date and time this happened or you first noticed this issue

25-05-2023 07:30

### Network

Ethereum Mainnet

### Safe Address

0x33927F7D725426FcC3deAb8d837482C6E0326816

### Token Type

None

**Comment by mrtoronto** [comment]
Additional context,

The threshold was changed to 8 signatures on 5/14/2022

https://app.safe.global/transactions/tx?safe=eth:0x33927F7D725426FcC3deAb8d837482C6E0326816&id=multisig_0x33927F7D725426FcC3deAb8d837482C6E0326816_0x7faf16df1302b0e4c7e7d1989ae7678c7412f9c014c5877fabaac21bd14e1df8

Transactions after 5/14/2022 required 8 signatures but the UI is now saying 8 of 4 confirmations.

![image](https://github.com/5afe/safe-support/assets/34576341/48e1c305-0676-439d-8856-dd58d945b0a0)

The stuck transactions were queued on September 28 and September 29 2022 so they should require 8 signers but the UI only wants 4. When the transactions are submitted, we get an error saying "execution reverted: GS020" (GS020: Signatures data too short). 

![image](https://github.com/5afe/safe-support/assets/34576341/bf8f70d4-8d32-4415-b16c-c0b75ad59e85)

**Comment by fmrsabino** [comment]
Thank you for reporting the issue. It should be fixed now: https://app.safe.global/transactions/queue?safe=eth:0x33927F7D725426FcC3deAb8d837482C6E0326816

**Comment by phoebe-serveth** [comment]
Thanks for your help @fmrsabino Yes, I can now see that the 5th signer was able to confirm a transaction. Just waiting for the user to execute a transaction.

**Comment by phoebe-serveth** [comment]
The UI is now showing 8 confirmations are required. User is unresponsive already. Closing the ticket now.
