### ISSUE TITLE
Error: This Safe Account couldn't be loaded

### ISSUE THREAD

**Issue by shebeengs** [5afe/safe-support#205]
### Issue Category

Safe loading issue, doesnt load on any interface

### What happened?

User created the safe 1d 5h ago, but never loaded in the interface. Checked recently created safes, and they load just fine. 
![image](https://github.com/5afe/safe-support/assets/54754746/73bc2b6a-545e-4752-8196-a91e1e66d4b8)
![image](https://github.com/5afe/safe-support/assets/54754746/e0f6369f-ec22-4ccf-9014-7b54c53b2eae)

https://polygonscan.com/address/0xe04Bd6AD36d152Dc27c650e61708A9E7F76487b7#code

### Date and time this happened or you first noticed this issue

2023-05-31 19:21:14

### Network

Polygon

### Safe Address

https://app.safe.global/transactions/history?safe=matic:0xe04Bd6AD36d152Dc27c650e61708A9E7F76487b7

### Token Address

None

### Token Type

None

### Transactions

```shell
Safe creation: https://polygonscan.com/tx/0xd99e681dc97c4b819c2deae5938569512ee37b900e6463ef3bdef0650f5db8d0#eventlog
```

**Comment by shebeengs** [comment]
Doesn't load on mobile as well:
![image](https://github.com/5afe/safe-support/assets/54754746/4e5232bb-e757-4d41-88dd-d0312c77364e)

**Comment by yagopv** [comment]
The attached transaction indicates the created Safe is `0x9C15470b92BbBf7Ea4b7d8DdFadF2Fb50a1f46B2` 

Internal transactions: https://polygonscan.com/tx/0xc3142bee13f2cba08bc4395d88cebd975456b65629a96d49e928d0dc0e0d8e00#internal

Safe: https://app.safe.global/home?safe=matic:0x9c15470b92bbbf7ea4b7d8ddfadf2fb50a1f46b2

**Comment by shebeengs** [comment]
Right, sorry. I think that's one of the safes I checked to see if it's only isolated to this safe. 😅 
Here's the correct one 
Safe creation: https://polygonscan.com/tx/0xd99e681dc97c4b819c2deae5938569512ee37b900e6463ef3bdef0650f5db8d0#eventlog

Edited the original post as well.

**Comment by yagopv** [comment]
Hey @shebeengs, it's fixed 😊

[https://app.safe.global/home?safe=matic:0xe04bd6ad36d152dc27c650e61708a9e7f76487b7](https://app.safe.global/home?safe=matic:0xe04bd6ad36d152dc27c650e61708a9e7f76487b7)

**Comment by phoebe-serveth** [comment]
Hi @yagopv :), another user reporting the same issues with these 2 Safes created 16 days ago. 
Cannot load in the Safe interface. 

https://app.safe.global/home?safe=matic:0x8f44c1A950fA7b1b1E05A152E5352Cb7B451c5C7
![image](https://github.com/5afe/safe-support/assets/114040259/d97cb5c1-336f-441a-babf-dc22251ac476)
https://polygonscan.com/tx/0x92a97eea009799d0ee4772464724e9d1adda19cbbe9a7fea297689e01b4fece2#eventlog

https://app.safe.global/home?safe=matic:0xB85DED4EcB3c578A0B6A0dE42b476f82eAdBAF29
![image](https://github.com/5afe/safe-support/assets/114040259/ed356a41-3ace-40be-9d65-fcadc35618e5)
https://polygonscan.com/tx/0x37b02749e9c70029415c9337865704b0b569609be319e54a5be5d83828b39432#eventlog

**Comment by Sherie15** [comment]
Hi @yagopv, It seems that this is the ONLY Safe account https://app.safe.global/home?safe=matic:0xe04Bd6AD36d152Dc27c650e61708A9E7F76487b7 can be accessible and the other 2 Safes below both has the same problem. 

https://app.safe.global/home?safe=matic:0x8f44c1A950fA7b1b1E05A152E5352Cb7B451c5C7
![image](https://github.com/5afe/safe-support/assets/113986185/a601a1ca-857c-4513-affd-1465a5ff0aaf)

https://app.safe.global/home?safe=matic:0xB85DED4EcB3c578A0B6A0dE42b476f82eAdBAF29
![image](https://github.com/5afe/safe-support/assets/113986185/45edc1ab-fc58-4a5f-9877-6e293e428edb)

**Comment by yagopv** [comment]
yes, we are looking into reindexing last month. I'll let you know 😊

**Comment by yagopv** [comment]
Hey! Could you take a look now. I think they are all solved and being showed

**Comment by Sherie15** [comment]
Both Safe address can now access the UI. Thank you for the quick fixed. @yagopv
