### ISSUE TITLE
OUSD fiat value not fetched

### ISSUE THREAD

**Issue by joanpan** [5afe/safe-support#209]
### Issue Category

Token balance

### What happened?

Fiat value for the OUSD (https://etherscan.io/address/0x2A8e1E676Ec238d8A992307B495b45B3fEAa5e86) not displayed in the UI
![image](https://github.com/5afe/safe-support/assets/114049668/2e5a80d8-9ef5-4866-aa96-a838fad122f1)

### Date and time this happened or you first noticed this issue

10-06-2023

### Network

Ethereum Mainnet

### Safe Address

User requested not to share safe address

### Token Type

None

**Comment by Claire-serveth** [comment]
> Could you please confirm that this problem has been solved?

Hi @MouazAlzahabi yes, the fiat value for this specific token is now updated: 
![image](https://github.com/5afe/safe-support/assets/114005210/4541f4b9-ea56-4b65-91fe-d4e5b7bb1cdf)

Thank you so much! Closing this issue now 🙏

**Comment by Claire-serveth** [comment]
Hello team, reopening this case since the issue has occurred again (OUSD fiat value not fetched) for the last 12 hours:

![image](https://github.com/5afe/safe-support/assets/114005210/54ac9b1a-d311-457f-bf83-25d0d3f3b88d)

**Comment by liliya-soroka** [comment]
reported to the team

**Comment by liliya-soroka** [comment]
@Claire-serveth , could you check with the user, please?  It should be fixed now

**Comment by phoebe-serveth** [comment]
Hi @liliya-soroka . OETH value is now showing up. Closing this now.
![image](https://github.com/5afe/safe-support/assets/114040259/3cc5e4ce-66c0-4784-b5bd-0431d8fd3234)
