### ISSUE TITLE
Cannot verify proxy contract in Etherscan

### ISSUE THREAD

**Issue by CindyLo0** [5afe/safe-support#21]
### Issue Category

Other

### What happened?

User cannot verify proxy contract in Etherscan. Getting this error when they try to verify, 

![image](https://user-images.githubusercontent.com/79137197/193398401-ae4d6b64-1e02-4553-92f6-2dd4cefd1ebb.png)

### Date and time this happened or you first noticed this issue

30-09-2022 09:35 GMT+8

### Network

Ethereum Mainnet

### Safe Address

0x5FAB1284e1650249d32F14835f755953ce2D231f

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by med3000** [comment]
hi @CindyLo0 thanks for raising. I believe on Mainnet it requires at least one transaction after which the proxy contract can be verified. The read/write as a proxy functionality is added automatically after at leas one transaction.
