### ISSUE TITLE
Offchain signing not working

### ISSUE THREAD

**Issue by jakekvm01** [5afe/safe-support#210]
### Issue Category

Other

### What happened?

Done basic TS and also using other browser.

![image](https://github.com/5afe/safe-support/assets/105864754/83043459-b179-45c8-a14a-4a030e7691b0)

![image](https://github.com/5afe/safe-support/assets/105864754/3644123f-34e4-4cb0-90b9-edfba7e72878)

### Date and time this happened or you first noticed this issue

N/A

### Network

Ethereum Mainnet

### Safe Address

eth:0x6E9cb366000470626Ee0b4103Dc9F77CcA19243B

### Token Address

N/A

### Token Type

None

### Transactions

```shell
https://app.safe.global/transactions/messages?safe=eth:0x6E9cb366000470626Ee0b4103Dc9F77CcA19243B
```

**Comment by schmanu** [comment]
Hey @jakekvm01,

I was able to reproduce the error. This is definitely an error on the dapp's side.
I didnt find any info on the dapp but I suspect that it does not support EIP-1271 smart contract signatures.

When I reproduced the issue the signature was correctly picked up by the dapp and the `/authenticate` endpoint was queried with the payload (Safe address and signature).
This request stays pending indefinitely. So I guess their backend for Sign in with Ethereum is not handling smat contract sigs.

**Comment by Claire-serveth** [comment]
> Hey @jakekvm01,
> 
> I was able to reproduce the error. This is definitely an error on the dapp's side. I didnt find any info on the dapp but I suspect that it does not support EIP-1271 smart contract signatures.
> 
> When I reproduced the issue the signature was correctly picked up by the dapp and the `/authenticate` endpoint was queried with the payload (Safe address and signature). 
> 
> This request stays pending indefinitely. So I guess their backend for Sign in with Ethereum is not handling smat contract sigs.

Thank you so much @schmanu! Will forward this to the user; closing this issue now 🙏
