### ISSUE TITLE
Getting Errors 32010 and 1322 when setting push notification with MetaMask on iOS safe mobile app

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#212]
### Issue Category

Other

### What happened?

User cannot enable push notification while importing owner key via Metamask on iOS.

Details:

iOS version: 16.5
Safe app version: 3.20.0
Metamask version: 6.3.0

Steps to reproduce:

1. Add owner key -> Walletconnect -> MetaMask
2. After connecting, then press push button
3. Then the following errors prompt:

![image](https://github.com/5afe/safe-support/assets/114005210/b4eeff86-aa0c-4077-8a28-cac114e65210)
![image](https://github.com/5afe/safe-support/assets/114005210/466ed207-5b9b-4c41-854e-c7a3eb4ddbdc)

User was able to enable push notification through generated owner key and ledger with no problem--only with Metamask throws an error.

### Date and time this happened or you first noticed this issue

12-06-2023

### Network

Ethereum Mainnet

### Token Type

None

**Comment by MouazAlzahabi** [comment]
It's known issue, will try to solve it soon
https://github.com/safe-global/safe-ios/issues/2996

**Comment by Claire-serveth** [comment]
> 

Oh, so sorry, I haven't seen this, but thank you so much for the update @MouazAlzahabi 🙏 will close this issue now.
