### ISSUE TITLE
Can't connect Trezor directly in Safe webapp

### ISSUE THREAD

**Issue by shebeengs** [5afe/safe-support#214]
### Issue Category

Other

### What happened?

Trezor wallet just loads indefinitely when trying to connect to the webapp. User has already reached out to Trezor support but mentioned Safe app is using an outdated Trezor Connect - version 8 (latest is version 9 according to the support). Please see the email from Trezor below:
![image](https://github.com/5afe/safe-support/assets/54754746/6c7df3eb-c02e-428f-8d4e-d798237e4b8b)

Works fine when connecting it to Metamask first, but doesn't work when connected directly. 
User already tried different browsers, clearing cache and cookies, using different computers, disabling antiviruses and using VPN but still having the same behavior. 
![image](https://github.com/5afe/safe-support/assets/54754746/c08c8c91-4da6-4e30-b844-29b7092a1e28)

### Date and time this happened or you first noticed this issue

14/06/2023 19:52:04

### Network

Ethereum Mainnet

### Safe Address

NA

### Token Address

NA

### Token Type

None

### Transactions

```shell
NA
```

**Comment by ennisjo** [comment]
Our forthcoming release will include an updated version (https://github.com/safe-global/safe-wallet-web/pull/2018) of onboard which uses v9 (https://github.com/blocknative/web3-onboard/blob/develop/packages/trezor/package.json#L69).

**Comment by ennisjo** [comment]
The release is planned for Thursday

**Comment by shebeengs** [comment]
Thank you!
