### ISSUE TITLE
Error 404 when loading balances on iOS and safe not loading on the web app (desktop) on Polygon network

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#215]
### Issue Category

Other

### What happened?

Using the latest version of the Safe mobile app on iOS, user is getting this error when trying to check his balance: Failed to load balances: Safe Account not found... but he's able to view his transaction history.

I cannot load his safe on the web app as well: https://app.safe.global/transactions/history?safe=matic:0x7e222F314B6bea57cC40759476f762574e931469

![image](https://github.com/5afe/safe-support/assets/114005210/53b89f36-f8f0-45a5-8edc-495f2d47fdc7)
![image](https://github.com/5afe/safe-support/assets/114005210/47d1241f-4a89-4f69-9aa5-f31cfaf2fb35)

### Date and time this happened or you first noticed this issue

15-06-2023

### Network

Polygon

### Safe Address

0x7e222F314B6bea57cC40759476f762574e931469

### Token Address

n/a

### Token Type

None

**Comment by johannesmoormann** [comment]
Reindex triggered, Safe is good now

**Comment by ennisjo** [comment]
Thanks for reporting. We needed to reindex this specific Safe on our Polygon services. The issue should now be fixed. 

We'll investigate why this specific one caused a 404.

**Comment by Claire-serveth** [comment]
Thank you so much @johannesmoormann @ennisjo 🙏 Closing this issue now.
