### ISSUE TITLE
Cannot execute transaction, gives GS010 error

### ISSUE THREAD

**Issue by inahlikenoother** [5afe/safe-support#216]
### Issue Category

Transaction execution issue

### What happened?

User cannot execute transaction, tenderly gives GS010 error even when owner wallets have enough balance for Gas fees. User tried all 3 owner wallets to execute transaction but still gives error. Also tried on Firefox browser for isolation - behavior is the same.

![image](https://github.com/5afe/safe-support/assets/114049495/89ef3cd7-514a-4f49-a604-e39a4ae9f771)
![image](https://github.com/5afe/safe-support/assets/114049495/79c859ce-5b8e-47c7-9333-d3f037a97358)

### Date and time this happened or you first noticed this issue

15-06-2023

### Network

Ethereum Mainnet

### Safe Address

0xb5b3f108E065F6e099AE3db0C20Ae020fEBF2b58

### Token Type

None

### Transactions

```shell
https://dashboard.tenderly.co/public/safe/safe-apps/simulator/fc6a82b1-3b2f-4d6a-9c51-1bc4f45b7681
```

**Comment by schmanu** [comment]
Did the user try increasing the `gasLimit`? 
It looks like the gasLimit is too low.

I increased it to for example 70_000 and the tenderly simulation succeeds.
I'd advice to increase the gasLimit slightly while re-simulating to find out how much gas is enough.

Also can you ask  the user if they set the gasLimit manually or if they used the estimation from our interface.
