### ISSUE TITLE
Token balance not showing

### ISSUE THREAD

**Issue by shebeengs** [5afe/safe-support#218]
### Issue Category

Token missing completely / not visible in the interface or service

### What happened?

User transferred USDT tokens into his safe ~3h 45m ago, but still not showing up in the interface. Same behavior in mobile app. 

![image](https://github.com/5afe/safe-support/assets/54754746/10031d5c-9463-4878-8ddc-b768f3a73e8c)
![image](https://github.com/5afe/safe-support/assets/54754746/e86a2cd8-863b-4105-9965-c722148ae8f3)
![image](https://github.com/5afe/safe-support/assets/54754746/f194fc5b-bc43-4e12-867b-b686a33d533a)

### Date and time this happened or you first noticed this issue

18/06/2023 22:59:01

### Network

Polygon

### Safe Address

https://app.safe.global/balances?safe=matic:0x6858657f14AcD076Bdd1eF6Bb26CeE4d14D940FF

### Token Address

0xc2132D05D31c914a87C6611C10748AEb04B58e8F

### Token Type

ERC20

### Transactions

```shell
https://polygonscan.com/tx/0x14be98c00c34b20e4db6453801366118e9effa24c12bc2516c14dca80eb11343
```

**Comment by JagoFigueroa** [comment]
Hi there! Issue should be resolved now 😄

**Comment by shebeengs** [comment]
Thank you!
