### ISSUE TITLE
Transaction initiation stuck and getting net::ERR_NAME_NOT_RESOLVED / Code 611 Failed to fetch on Polygon network

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#219]
### Issue Category

Other

### What happened?

User is trying to create/initiate a simple transfer/send transaction using Metamask + Ledger but stuck on loading UI or having the following error:

![image](https://github.com/5afe/safe-support/assets/114005210/e7140088-0ea8-46a2-9c77-044e3b5b7ddd)
![image](https://github.com/5afe/safe-support/assets/114005210/1076e0e2-425b-4071-8d9f-e60ee163f8f5)

Is this issue related to the signing wallet or safe related error?

### Date and time this happened or you first noticed this issue

21-06-2023

### Network

Polygon

### Token Type

None

**Comment by liliya-soroka** [comment]
Could you check with the user if the re-submit a few times can help?

**Comment by Claire-serveth** [comment]
> Could you check with the user if the re-submit a few times can help?

Hi @liliya-soroka yes, after some tries, transaction was confirmed. But still happening using another safe address. I also advised user to try using different RPC, and according to user, _"there's just the issue of the slow loading when it's erroring due to the invalid gas station URL"_, but the transaction was confirmed eventually.

**Comment by liliya-soroka** [comment]
Thank you for the update. The team is informed and we are checking what can be done on our side. I will provide more information tomorrow

**Comment by liliya-soroka** [comment]
@Claire-serveth . we have updated Gas Station for the Polygon on prod.

**Comment by Claire-serveth** [comment]
> @Claire-serveth . we have updated Gas Station for the Polygon on prod.

Thank you very much @liliya-soroka 🙏 Closing this issue now.
