### ISSUE TITLE
Safe not loading on Gnosis chain

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#220]
### Issue Category

Safe loading issue, doesnt load on any interface

### What happened?

The safe wallet was created more than 2 hours ago via relayer as execution method but the safe can't still be loaded on the UI (_Address given is not a valid Safe Account address_): https://app.safe.global/home?safe=gno:0x80953A3499be102BDde1E50B06bF7F1F17Cbaa61

![image](https://github.com/5afe/safe-support/assets/114005210/f833b18e-7bcb-4b5a-8939-65384e52b3cd)
![image](https://github.com/5afe/safe-support/assets/114005210/7c3f08b3-7549-464c-aee8-f34a64462ada)

### Date and time this happened or you first noticed this issue

25-06-2023

### Network

Gnosis Chain

### Safe Address

0x80953A3499be102BDde1E50B06bF7F1F17Cbaa61

### Token Type

None

**Comment by Claire-serveth** [comment]
I just checked now and the safe can be loaded already. But I just wanted to know if this is expected for those using the relayer as execution method?

**Comment by liliya-soroka** [comment]
yes, relay is a default type for the tx execution on web for the Gnosis chain

**Comment by liliya-soroka** [comment]
I will close the issue , as it was fixed yesterday
