### ISSUE TITLE
No option to edit gas limit

### ISSUE THREAD

**Issue by CindyLo0** [5afe/safe-support#221]
### Issue Category

Transaction execution issue

### What happened?

User is trying to send Hypetoon DAO token (0xe0b43A6e49028b8C0781739084DeD74C4c251dDd)  but always get an error GS013. 
Simulation result - https://dashboard.tenderly.co/public/safe/safe-apps/simulator/1b556c49-e60b-46ca-a399-1f7abd51d4c8/debugger?trace=0.0.6

No option to edit the gas limit in the UI only to edit the Safe Nonce. 
![image](https://github.com/5afe/safe-support/assets/79137197/2b14a725-0df7-4abc-8910-16ce250c7aa4)

Users should have an option to edit the gas limit in the UI. 
Is this an issue with the token?

### Date and time this happened or you first noticed this issue

28-06-2023 11:00

### Network

Ethereum Mainnet

### Safe Address

0x11FFc5bA95377eA1aFb7a8f62Ee394d91371Bd63

### Token Address

0xe0b43A6e49028b8C0781739084DeD74C4c251dDd

### Token Type

ERC20

**Comment by mmv08** [comment]
These are safe transaction parameters. Gas limit belongs to the ethereum transaction parameters and is only available when executing the safe transaction (after all owners confirm and someone tries to execute the tx)

`GS013` means the internal transaction reverted, in this case, it's the transfer transaction. They should contact token contract maintainers to figure out why it reverts.

**Comment by mmv08** [comment]
Also, looking at the safe transaction history, it seems like they were able to send the token after all.

**Comment by Claire-serveth** [comment]
Thank you @mmv08 🙏 Closing this issue now.
