### ISSUE TITLE
Cannot propose a new transaction, unable to load other Safes on Mainnet

### ISSUE THREAD

**Issue by phoebe-serveth** [5afe/safe-support#222]
### Issue Category

Safe loading issue, doesnt load on any interface

### What happened?

User reported an issue when proposing a new transaction. Getting a timedout error:
![image](https://github.com/5afe/safe-support/assets/114040259/a15199eb-2f2c-4061-aa31-fce955d3cdaf)

Upon pulling up the safe on my end, getting issues pulling up transaction records
![image](https://github.com/5afe/safe-support/assets/114040259/652cd08a-5634-4fd8-b7ac-c728f7670d78)

Tried checking other safes in mainnet and unable to load them as well.
![image](https://github.com/5afe/safe-support/assets/114040259/ba868bf0-e075-4446-be35-af4626949ce1)

### Date and time this happened or you first noticed this issue

29-06-2023 04:25

### Network

Ethereum Mainnet

### Safe Address

0xdb2a2BbA2346E79352f5eb612613437bCAe8D80F

### Token Type

None

**Comment by bordumb** [comment]
I'm also seeing issues.

## Failed Transactions 

When trying to make a transaction, I get this error on 100% of transaction attempts:
```
1337: reqwest::Error
{ kind: Request,
  url: Url { scheme: "http", host: Some(Domain("mainnet-safe-transaction-web.safe.svc.cluster.local")),
             port: None,
             path: "/api/v1/safes/0x394B920c5d39E0Ca40fCa2871569B6B90D750c7c/multisig-transactions/",
             query: None,
             fragment: None },
source: TimedOut }
```
Or this error:
```
Failed proposing the transaction. Please try again.
Details
1337: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.21.6</center>
</body>
</html>
```

**Comment by phoebe-serveth** [comment]
@bordumb This has already been fixed. Feel free to reach out to us again in chat if you are still experiencing an issue. Closing this ticket now.
