### ISSUE TITLE
Cannot sign tx with Avocado wallet

### ISSUE THREAD

**Issue by inahlikenoother** [5afe/safe-support#223]
### Issue Category

Transaction execution issue

### What happened?

User is sending OP from his Safe to another address, but gets the error below when signing the transaction using the 2nd owner wallet (Avocado wallet)
![image](https://github.com/5afe/safe-support/assets/114049495/2e2ade0a-a466-4f51-bb3d-29e89861c8f8)
![image](https://github.com/5afe/safe-support/assets/114049495/6d16a4fb-65f8-4769-827f-9bb7fa573f08)

### Date and time this happened or you first noticed this issue

29-06-2023

### Network

Optimism

### Safe Address

0xf4F0543baCc318827E733c44BbBe1487E03ddFC7

### Token Type

None

**Comment by mmv08** [comment]
We will investigate this. In the meantime, they can use an eoa to execute a transaction.

**Comment by 0xbaer** [comment]
i cannt ; the safe is, unfortunately 2/2

**Comment by inahlikenoother** [comment]
@mmv08 Yes the Safe is 2/2, so adding a new owner wallet would still require confirmation from the current owner wallet using Avocado wallet.

**Comment by 0xbaer** [comment]
Avocado isn't recognising this the input either

**Comment by mmv08** [comment]
Not sure I understand what you mean. What input?

**Comment by 0xbaer** [comment]
<img width="666" alt="image" src="https://github.com/5afe/safe-support/assets/67889231/d707f636-521c-42fd-9b1f-332636c0bc92">

**Comment by 0xbaer** [comment]
<img width="666" alt="image" src="https://github.com/5afe/safe-support/assets/67889231/363c91ea-f303-40fa-a370-65e0d9f3ee10">

**Comment by Seb-EthMonk** [comment]
Hey @0xbaer there was an error here that has since been fixed, it should work correctly for you now:

![image](https://github.com/5afe/safe-support/assets/76888251/1760d891-4425-4942-9ac7-e158efca5e0b)

**Comment by inahlikenoother** [comment]
Resolved - user was already able to execute transactions on his safe.
