### ISSUE TITLE
Can't receive Celo tokens through contract interaction (Sending a TransferFrom contract call)

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#226]
### Issue Category

Transaction execution issue

### What happened?

User is getting GS013 error when trying to receive Celo tokens from a governance contract address. There was a previous successful transaction using another safe address, but not sure why it keeps on reverting for this safe address.

This is the safe address that successfully received the tokens: https://app.safe.global/transactions/history?safe=celo:0x38dbab5c651f352c8f5f765fda292e9b92d850ff

![image](https://github.com/5afe/safe-support/assets/114005210/2f0516ec-8ce5-4518-9e09-3bca331d715e)

But this is the safe address that executed the same contract interaction, but failed: https://celoscan.io/tx/0x0e9ad21483870949d56a346edca47500aa4f5112d8bd7d8042b3796dc7aad6c1

What could be causing the issue? User is following the same guide as this: https://hackmd.io/@bacbEY7zQzOvotKS1npyfA/BkmRUiD8h

### Date and time this happened or you first noticed this issue

04-07-2023

### Network

Goerli

### Safe Address

0x4763a32d5256eda615fd5c07b0e333c7baa4d628

### Token Address

0x471EcE3750Da237f93B8E339c536989b8978a438

### Token Type

ERC20

### Transactions

```shell
Successful transaction: https://celoscan.io/tx/0xa9da03ab4326f2bfd774ca0dc542c97ee54268c80f636f74386ec3c965e367a5


Failed transaction: https://celoscan.io/tx/0x0e9ad21483870949d56a346edca47500aa4f5112d8bd7d8042b3796dc7aad6c1
```

**Comment by mmv08** [comment]
Since `GS013` indicates an internal error (an error thrown by the token contract), we cannot provide any help here. They should contact CELO token contract maintainers.
