### ISSUE TITLE
[CELO] Token not showing up Fiat value

### ISSUE THREAD

**Issue by joanpan** [5afe/safe-support#228]
### Issue Category

Token missing completely / not visible in the interface or service

### What happened?

Fiat value for multiple tokens is not being displayed in the Safe Assets page. This problem seems to be affecting several safes.
![image](https://github.com/5afe/safe-support/assets/114049668/112267d9-a479-4d77-aeaf-180afd8cfbea)
![image](https://github.com/5afe/safe-support/assets/114049668/2f4855cd-30a9-4640-81fa-7cb584dd43f5)

### Date and time this happened or you first noticed this issue

7-7-2023

### Network

CELO

### Safe Address

0x87647780180B8f55980C7D3fFeFe08a9B29e9aE1

### Token Type

ERC20

**Comment by joanpan** [comment]
Tagging @0lektronisch

**Comment by johannesmoormann** [comment]
Unfortunately, we cannot provide support for individual token values at this time but the team is exploring alternative oracles that cover a bigger selection of assets.

**Comment by joanpan** [comment]
Thank you, will let the user know
