### ISSUE TITLE
Broken link in Safe UI under Settings

### ISSUE THREAD

**Issue by CindyLo0** [5afe/safe-support#229]
### Issue Category

Other

### What happened?

Reporting a broken link in the UI under Settings > Safe Apps > Signing Method. Please see screenshot, 
![image](https://github.com/5afe/safe-support/assets/79137197/7cb3302c-1eaf-4272-bdc8-5af0072343fe)

The link opens to, 
![image](https://github.com/5afe/safe-support/assets/79137197/bd74f2c5-aa8a-427c-9e2d-c8d3363ed778)

Correct link should be - https://help.safe.global/en/articles/40783-what-are-signed-messages

### Date and time this happened or you first noticed this issue

11-07-2023

### Network

Ethereum Mainnet

### Token Type

None

**Comment by usame-algan** [comment]
Thanks for reporting this! We will update the link shortly.
