### ISSUE TITLE
[Polygon] Executed safe transaction still shows as queued in the UI

### ISSUE THREAD

**Issue by shebeengs** [5afe/safe-support#23]
### Issue Category

Transaction execution issue

### What happened?

User already executed nonce `98` but still shows as a queued transaction in the interface. Checking on Polygonscan, `nonce` for the safe is already `99`.

Nonce in safe interface:
![image](https://user-images.githubusercontent.com/54754746/193642323-9bacd391-2f4f-4316-be9d-13cdd9ab6aa6.png)

Nonce in Polygonscan:
![image](https://user-images.githubusercontent.com/54754746/193642395-05a90ebf-bab9-4f0c-8c0f-70c89a77805d.png)

https://polygonscan.com/address/0x580D0d0c52fEE405c0fA7447eDEB9625D4A3fA3B#readProxyContract
https://gnosis-safe.io/app/matic:0x580D0d0c52fEE405c0fA7447eDEB9625D4A3fA3B/transactions/queue

### Date and time this happened or you first noticed this issue

04-10-2022 01:31:17

### Network

Polygon

### Safe Address

0x580D0d0c52fEE405c0fA7447eDEB9625D4A3fA3B

### Token Address

N/A

### Transactions

```shell
https://polygonscan.com/tx/0xcf199a7bbf059266ca8514f981211dfe5f70a4a482590d2536a05ae42297b205
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shebeengs** [comment]
The queue seems to be updated now, so it might have been just a delay.

**Comment by liliya-soroka** [comment]
closing the issue, as it works now. 
It's also some maintenance work on the polygon side in the progress
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/338622/193777690-e868d96e-05c8-4318-b9c7-fa9359144b8a.png">
