### ISSUE TITLE
Assets page is not loading on BSC, Arbitrum, Avalanche Networks

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#233]
### Issue Category

Other

### What happened?

Balances are not showing up for the following safes on various networks:

https://app.safe.global/balances?safe=bnb:0xb5563C0dA3ae618975c65bd4b207A98F0b14C36B
https://app.safe.global/balances?safe=arb1:0xbA60b89c01bB62061231eF580831304a641DEADf
https://app.safe.global/balances?safe=avax:0x95E4f54A900C1D802298F3A5D437522a5aF9f9c2

![image](https://github.com/5afe/safe-support/assets/114005210/f64f685d-a42e-44ae-8087-f9934a89bbd5)

### Date and time this happened or you first noticed this issue

14-07-2023

### Network

Binance Smart Chain

### Safe Address

0xb5563C0dA3ae618975c65bd4b207A98F0b14C36B

### Token Type

None

**Comment by jakekvm01** [comment]
Additional safe addresses: 

https://app.safe.global/balances?safe=bnb:0xbea6Eaa4D05A9324fE19f7bDD48ec5BaD3895fFC
https://app.safe.global/balances?safe=bnb:0x00B208907181952d43E1D844B62e4f597040a1cd

**Comment by liliya-soroka** [comment]
Thank you for the reporting. The team is notified and checking the issue.

**Comment by phoebe-serveth** [comment]
Hi team. We also have users impacted with the same issue in Gnosis Chain. 
![image](https://github.com/5afe/safe-support/assets/114040259/6f9dd140-acda-47a2-af1a-2f855dbb9a19)

**Comment by liliya-soroka** [comment]
yes, all networks with our new CGW have the same issue. The team is on it right now. The issue from the team is linked above to the support ticket
