### ISSUE TITLE
Safe SDK inquiry

### ISSUE THREAD

**Issue by joanpan** [5afe/safe-support#234]
### Issue Category

Other

### What happened?

User wants to use Safe in their dapp and is wondering if the Safe SDK and contract proxy kit allow them to use multisignature functionalities outside safe iframe?

They're asking if they can use safe functionalities outside the iframe or do they always have to open their app in iframe to use Safe?

### Date and time this happened or you first noticed this issue

n/a

### Network

Ethereum Mainnet

### Token Type

None

**Comment by mmv08** [comment]
Yes, that's the primary function of the Safe{Core} SDKs - https://github.com/safe-global/safe-core-sdk

The iframe SDK is safe-apps-sdk, and it's a separate SDK for iframe app communication.
