### ISSUE TITLE
[GOERLI] Cannot execute any Safe transactions

### ISSUE THREAD

**Issue by Sherie15** [5afe/safe-support#235]
### Issue Category

Transaction execution issue

### What happened?

When trying to execute a transaction it will show **indexing** tried to replace the transaction and it automatically greyed out from the pending queue.

I tried to test by sending a token to attempt to replicate the issue but the sent tokens are not reflected in the Safe UI but already showing on Etherscan that the Safe already received the tokens after almost immediately it was sent to my test Safe account.

![image](https://github.com/5afe/safe-support/assets/113986185/27322a53-d529-4549-acd2-998415d6157c)

### Date and time this happened or you first noticed this issue

17-07-2023 09:18 

### Network

Goerli

### Safe Address

0x28c84612D37de9209018aD96167f12169b653e9a

### Token Type

None

**Comment by Sherie15** [comment]
The user was able to execute nonce 25. Closing this ticket now.

**Comment by liliya-soroka** [comment]
The team checked and fixed it this morning

**Comment by AnnaBarotova** [comment]
Thank you a lot!
