### ISSUE TITLE
Indexing Issue

### ISSUE THREAD

**Issue by reyserveth** [5afe/safe-support#236]
### Issue Category

Safe loading issue, doesnt load on any interface

### What happened?

When trying to load the Safe it keeps getting the message "This Safe Account couldn't be loaded"

I tried to replicate the issue and I am also unable to load the Safe

![image](https://github.com/5afe/safe-support/assets/114401730/f828920d-12b3-42e8-b8f3-8213bd2044da)

### Date and time this happened or you first noticed this issue

16-07-2023 

### Network

Binance Smart Chain

### Safe Address

0xcEba60280fb0ecd9A5A26A1552B90944770a4a0e

### Token Address

N/A

### Token Type

None

**Comment by liliya-soroka** [comment]
The issue reported to the team

**Comment by fmrsabino** [comment]
@reyserveth we've fixed the issue. Safe should load now. Thank you for reporting.

**Comment by reyserveth** [comment]
Issue fixed. Safe is now loading.
![image](https://github.com/5afe/safe-support/assets/114401730/c57cf294-c79a-4160-bac1-61779a7dffff)
