### ISSUE TITLE
Executed transaction still stuck in Queue after 6hrs

### ISSUE THREAD

**Issue by shebeengs** [5afe/safe-support#237]
### Issue Category

Transaction execution issue

### What happened?

User already executed nonce 15 but still showing up in Queue tab even after 6hrs, blocking other transactions to get executed in the interface. Nonce 15 is also already showing up in History but still stuck in queue. 
![image](https://github.com/5afe/safe-support/assets/54754746/833d9e4a-4a5b-494e-ba3f-819858142965)
![image](https://github.com/5afe/safe-support/assets/54754746/cbf26597-240f-4389-b755-a1394c80ec80)

On Gnosisscan the nonce appears to be at nonce 16 already:
![image](https://github.com/5afe/safe-support/assets/54754746/a6a9fa14-882f-4003-ba21-bc675e8fb044)

Token balances seems to be fine and updated though. 

### Date and time this happened or you first noticed this issue

17/07/2023 18:52:39

### Network

Gnosis Chain

### Safe Address

https://app.safe.global/transactions/history?safe=gno:0xbD54408D41b22FA513Ac5921d7F8CbCc26aC0BCc

### Token Address

NA

### Token Type

None

### Transactions

```shell
https://gnosisscan.io/tx/0x6d4cfb46acd92bf0c1d44152c47437a5a2f2ba60e3dba089962b970a273a36e5/
```

**Comment by JagoFigueroa** [comment]
Good morning! The issue is related to this other [one](https://github.com/NethermindEth/nethermind/issues/5936) that we opened on nethermind side yesterday.

Cheers!

**Comment by shebeengs** [comment]
Thank you!

**Comment by shebeengs** [comment]
User no longer responds, will close this now.
