### ISSUE TITLE
Polygon Safe cannot be loaded

### ISSUE THREAD

**Issue by inahlikenoother** [5afe/safe-support#24]
### Issue Category

Safe loading issue, doesnt load on any interface

### What happened?

User cannot load their Polygon safe, getting error "This Safe couldn't be loaded"

Safe address https://gnosis-safe.io/app/matic:0x1b4441020351E38A1501cB3859cEAbE95B666bD4

![image](https://user-images.githubusercontent.com/114049495/193729469-0b065722-a15a-4e53-a9aa-c6e4897d01f9.png)

### Date and time this happened or you first noticed this issue

04-10-2022 11:42

### Network

Polygon

### Safe Address

0x1b4441020351E38A1501cB3859cEAbE95B666bD4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by la1234512345** [comment]
Same experience on this safe address
https://gnosis-safe.io/app/matic:0xe12723fD734a7B5B1682e2542D3A769C033741aF
![image](https://user-images.githubusercontent.com/114544040/193729767-6c4b5f87-4239-4bd5-a80f-222982ba29e1.png)

**Comment by Sherie15** [comment]
![image](https://user-images.githubusercontent.com/113986185/193734904-f850941b-d6fb-499d-abcb-c840b456d87c.png)

https://gnosis-safe.io/app/matic:0xb5408c2977daa3E371279b72bD598000db84d12a

Following errors when adding and accessing Safe on mobile and Web app:

 1. 'Server error' when accessing existing safes on mobile iOS
 2. When adding the Safe on the web app, it gives 'Address given is not a valid Safe address'
 3. This Safe couldn't be loaded

**Comment by inahlikenoother** [comment]
Another user experiencing the same issue

https://gnosis-safe.io/app/matic:0xd196FF4d7147E24837C9991fCBe6501E42852177

![image](https://user-images.githubusercontent.com/114049495/193745239-546f6961-45bc-4ef0-bf5d-737a176c723f.png)

**Comment by Sherie15** [comment]
![image](https://user-images.githubusercontent.com/113986185/193746644-5f83a830-4ea0-4901-9700-307d6c7c3fc5.png)
![image](https://user-images.githubusercontent.com/113986185/193746704-9ef9cec4-6723-46b9-87ef-6c10f3cd7ef3.png)

https://gnosis-safe.io/app/matic:0xC9ae380E267FDD0983d52608C01c15AE640B42e3

**Comment by liliya-soroka** [comment]
Could you recheck your safes, please? 
I will close the issue as all of them are loaded for me now and, please, take into account maintenance work on the polygon side 
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/338622/193776997-d0b3e6fe-40db-49bd-ae60-4567cdb2c192.png">
