### ISSUE TITLE
Executed transaction stuck in Queue

### ISSUE THREAD

**Issue by phoebe-serveth** [5afe/safe-support#241]
### Issue Category

Transaction execution issue

### What happened?

Nonce 224 was successfully executed but still stuck in queue tab, hindering users to proceed with the next transaction. 
Current nonce in polygonscan is 225. 
![image](https://github.com/5afe/safe-support/assets/114040259/15532555-5747-49d7-8ea6-a41f1ad30987)
![image](https://github.com/5afe/safe-support/assets/114040259/8a07cdd2-3952-4fe2-a729-74f7894c491d)

### Date and time this happened or you first noticed this issue

20-07-2023 - 3:12 AM

### Network

Polygon

### Safe Address

matic:0xF4CA99Db277934Ec406c33dc153A7389F6e060FA

### Token Type

None

**Comment by cuchorapido** [comment]
hi, if you have any quesitons, please let me know, we need to solve this ASAP, thank you!!

**Comment by cuchorapido** [comment]
it has been resolved!

**Comment by shebeengs** [comment]
Seeing the same issue with another safe (nonce **4**): https://app.safe.global/transactions/queue?safe=matic:0xf00bf8f80e6d9ce02fc21ce8a398a87319fdf3d8

![image](https://github.com/5afe/safe-support/assets/54754746/b6f40603-be76-4530-bb96-a8264a6d786a)
![image](https://github.com/5afe/safe-support/assets/54754746/061f8bc4-1fe8-4502-88cd-6858cdd29818)

**Comment by bingclo** [comment]
Nonce 4 is cleared from the transaction queue now.
