### ISSUE TITLE
User can't execute tx automatically.

### ISSUE THREAD

**Issue by jakekvm01** [5afe/safe-support#243]
### Issue Category

Other

### What happened?

User can't execute tx automatically. The UI doesn't have this option. 
![image](https://github.com/5afe/safe-support/assets/105864754/de1fd934-14ff-4245-9385-df450c38492b)

User is using Brave browser and tried Firefox browser as well (same behavior) .
![image](https://github.com/5afe/safe-support/assets/105864754/c44d533d-8c37-42ce-80bb-36ad819416f9)
![image](https://github.com/5afe/safe-support/assets/105864754/8a31f3ee-08b9-406d-b2a4-f9e8c4a24847)

### Date and time this happened or you first noticed this issue

N/A

### Network

Polygon

### Safe Address

https://app.safe.global/transactions/queue?safe=matic:0x29787AD4C1909Aa40A683D772B3206Bc66f0EdF8

### Token Address

N/A

### Token Type

None

**Comment by Claire-serveth** [comment]
User just need to execute all transactions in queue or replace the oldest nonce in queue to see the "Execute" and "Only sign" options. User did execute all transactions in queue, then clear cache, cookies and did the hard refresh to see both options again. Case is resolved so closing this issue now.
