### ISSUE TITLE
Initiated transaction stuck at signing on Polygon network

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#248]
### Issue Category

Transaction execution issue

### What happened?

After the transaction is initiated and the first signer signs, the UI keeps loading/stuck at signing:

![image](https://github.com/5afe/safe-support/assets/114005210/c41d47ad-f1a5-499c-812b-fc775f05ef73)
 

### Date and time this happened or you first noticed this issue

26-07-2023

### Network

Polygon

### Safe Address

0x3E007586e1b81cBe5f0463AD2fe84E1d84A6934c

### Token Type

None

**Comment by liliya-soroka** [comment]
Could you check the issue with the user , please?
It was fixed yesterday and should work now

**Comment by Claire-serveth** [comment]
> Could you check the issue with the user , please? It was fixed yesterday and should work now

Hi @liliya-soroka as I checked, user was able to execute transactions already. Thank you so much for the update 🙏 Closing this issue now.
