### ISSUE TITLE
Unable to claim Safe tokens

### ISSUE THREAD

**Issue by Sherie15** [5afe/safe-support#25]
### Issue Category

Other

### What happened?

The user attempted to claim his Safe tokens five-eight times using Safe address 0x2B2a44d107eC260147bfB6A854d10e46B5133b8d but there's no transactions from the Safe pending queue

https://gnosis-safe.io/app/eth:0x1158A37B17B7ac2343764113537f68B57151ac17/transactions/queue

The current Safe nonce shows 11 and the Safe claim transaction proposes nonce 11
User already tried using Chrome, Edge and Firefox
User already use 2 different computers

![image](https://user-images.githubusercontent.com/113986185/194022622-8eb4656f-71d5-4a4f-b8dc-5c32a6782761.png)
![image](https://user-images.githubusercontent.com/113986185/194022744-b8ad0cd8-2cb4-4b75-a56b-2d957b0aba47.png)
![image](https://user-images.githubusercontent.com/113986185/194022896-3355984b-6a60-4abc-912f-709af135d92b.png)

### Date and time this happened or you first noticed this issue

5-10-2022

### Network

Ethereum Mainnet

### Token Address

0x1158A37B17B7ac2343764113537f68B57151ac17

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by liliya-soroka** [comment]
@Sherie15 , could we get information about the amount the user is trying to claim. I am surprised that there is only set delegate action on review screen

**Comment by Sherie15** [comment]
We went through the step by step to claim the Safe tokens and this is the information from the user when we try to check the number of tokens he will claim.

![image](https://user-images.githubusercontent.com/113986185/194247052-86cb2f55-2612-4f8f-b6e0-5c3cdd1f37e0.png)

https://raw.githubusercontent.com/safe-global/safe-token/main/user-allocations/safes_tokens.csv

![image](https://user-images.githubusercontent.com/113986185/194247695-3ab8bb86-b7f3-41dd-b5f8-116078a49681.png)

**Comment by liliya-soroka** [comment]
![image](https://user-images.githubusercontent.com/338622/194517410-74a8565c-69eb-489c-b7db-0121c122b6f5.png)

**Comment by DiogoSoaress** [comment]
The shared [URL](https://gnosis-safe.io/app/eth:0x1158A37B17B7ac2343764113537f68B57151ac17/transactions/queue) also shows me the correct data.

The two ways we have to display 0 are either:
1. Safe is not eligible (which **is** as we see on the top bar)
2. There is a network issue and we fallback to show 0.

Given the second case, I would ask the user to reload the app and try again the claiming process.

**Comment by phoebe-serveth** [comment]
User tried claiming again but still having the same issue. Showing 0 allocated tokens but when I checked it on my end it shows an amount. Tried clearing cache and claim again but still the same. Also, user keeps getting this error message from time to time. "Unexpected error while loading the app"
![image](https://user-images.githubusercontent.com/114040259/194684502-6580ff3c-d914-4281-aa0b-088ea6f1244c.png)
![image](https://user-images.githubusercontent.com/114040259/194684516-e9242e47-2283-4e3e-976d-e06d7bcabe13.png)

**Comment by schmanu** [comment]
This issue arises when some requests fail which try to: 
- fetch the claiming data OR
- fetch the vesting status on-chain (via RPC)

In either case the error should get logged to the browser console. Could the user check the browser console for errors?

**Comment by schmanu** [comment]
Okay I just saw that the user was able to claim. I think we can close this issue.

https://gnosis-safe.io/app/eth:0x1158A37B17B7ac2343764113537f68B57151ac17/transactions/multisig_0x1158A37B17B7ac2343764113537f68B57151ac17_0xadb9139bbfdc8680b80d30de28f4482246dd7a88c3840ba855f93324f22cc68c

**Comment by DiogoSoaress** [comment]
User was already able to claim
