### ISSUE TITLE
Not able to connect safe mobile app to the safe wallet web app

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#251]
### Issue Category

Other

### What happened?

User tried to connect his safe wallet (mobile app) on the web app but not able to.

When user tried to click "connect wallet" on the web app > > Choose "Safe wallet" button then scan the code, it says connecting but then it goes back to connect wallet on the top right of the safe web:

![image](https://github.com/5afe/safe-support/assets/114005210/2ead5e67-a633-4cd0-b5b3-ffe6a1b601b3)

Mobile info:
iOS version: 16.6
Safe mobile app version: 3.21.0

Owner wallet address: eth:0xC3cd84d7E0cac63929EF674F571EcD5AE8F584dF

### Date and time this happened or you first noticed this issue

27-07-2023

### Network

Ethereum Mainnet

### Safe Address

0xA362a3C19e1840bdAcE99956be6C2ff9d5081598

### Token Type

None

**Comment by liliya-soroka** [comment]
Thank you for reporting. Reported to the team - https://github.com/safe-global/safe-wallet-web/issues/2316

**Comment by Claire-serveth** [comment]
> Thank you for reporting. Reported to the team - [safe-global/safe-wallet-web#2316](https://github.com/safe-global/safe-wallet-web/issues/2316)

Thank you so much @liliya-soroka 🙏
