### ISSUE TITLE
Error connecting Ledger wallet on Mac

### ISSUE THREAD

**Issue by phoebe-serveth** [5afe/safe-support#252]
### Issue Category

Other

### What happened?

Cannot connect Ledger wallet directly to Safe. Getting an error when selecting Ledger from the wallet options using chrome and firefox.

![image](https://github.com/5afe/safe-support/assets/114040259/fd8e7e6a-fb3c-4508-b61a-7513cb94ace4)

Console logs:
![image](https://github.com/5afe/safe-support/assets/114040259/f69a8e56-f4a6-464c-944d-a5eb3b2cb67b)

User already updated fireware, tried other USB ports, cleared cache and hard refresh.
Getting "Ledger device is locked" error.

![image](https://github.com/5afe/safe-support/assets/114040259/cd3f07e6-c3da-451e-8a93-31cc40003efd)

Device: 
Macbook pro, MacOS Ventura 13.0.1
Ledger nano x, firmware 2.2.2

### Date and time this happened or you first noticed this issue

27-07-2023 05:00 pm

### Network

Polygon

### Safe Address

0xf00bF8F80E6d9CE02fc21ce8a398a87319fDF3d8

### Token Type

None

**Comment by katspaugh** [comment]
@liliya-soroka looks like the error you also saw with Ledger last week.

**Comment by liliya-soroka** [comment]
Could you ensure the Ledger device is unlocked, and Eth app runs on the user's Ledger device during connection ?
And advice to restart the connection with ledger Nano X after the device is unlocked and Eth app is opened

**Comment by reyserveth** [comment]
Hi team, the user already the following steps: 
1. Could you ensure the Ledger device is unlocked, and Eth app runs on your Ledger device during connection?
2. Please restart the connection with ledger Nano X after the device is unlocked and Eth app is opened.

Did not resolve the issue.

**Comment by liliya-soroka** [comment]
Could we please check if the issue is still actual for the user?

**Comment by phoebe-serveth** [comment]
@liliya-soroka We're waiting for the user's reply. We'll update you if we hear from them.

**Comment by phoebe-serveth** [comment]
Hi @liliya-soroka, the user has already disposed of the Ledger, so I'll go ahead and close this ticket.
