### ISSUE TITLE
BSC] This transaction will likely to fail...

### ISSUE THREAD

**Issue by Sherie15** [5afe/safe-support#255]
### Issue Category

Transaction execution issue

### What happened?

The user try to execute a send function for BUSD and encountered and error `This transaction will likely to fail..

1. Used Chrome/Brave with Metamask
2. User changed the RPC on Metamask (https://rpc.ankr.com/bsc) but the result error message
3. Also encountered _could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.2)_ when connecting his Metamask wallet using Chrome/Brave
4. Used https://rpc.ankr.com/bsc RPC on Safe and it worked

![image](https://github.com/5afe/safe-support/assets/113986185/2af5daf6-9711-4ad4-968e-27e231df0b7a)

### Date and time this happened or you first noticed this issue

31-07-2023 11:00:00 am

### Network

Binance Smart Chain

### Safe Address

bnb:0x28bfEE29EfC1fe0Ed7abb21313446Cb69AeB9402

### Token Type

None

**Comment by GnosisFans** [comment]
this is some issue that's going on on BSC Network just now

**Comment by JagoFigueroa** [comment]
I think this issue should be resolved. Could you close the ticket if that is the case? 😄

**Comment by Claire-serveth** [comment]
> I think this issue should be resolved. Could you close the ticket if that is the case? 😄

Hi @JagoFigueroa closing this issue now. Thank you 🙏
