### ISSUE TITLE
Polygon - Something Went Wrong error when accessing Safe

### ISSUE THREAD

**Issue by inahlikenoother** [5afe/safe-support#259]
### Issue Category

Safe loading issue, doesnt load on any interface

### What happened?

User is getting "Something Went Wrong, please try again" error when loading/accessing the Safe. It's the same behavior on different browsers. I also get the same behavior when loading user's Safe on Firefox. 

It's happening to two Safes on Polygon:
https://app.safe.global/home?safe=matic:0x828d55AaF0fE916879C7dCf0E3278D1E8dbEDDd3
https://app.safe.global/home?safe=matic:0xf796ef3Fa1328ebeff10D5b196a8f15B757748ec

Error message:
![image](https://github.com/5afe/safe-support/assets/114049495/1b14679e-bcd1-49aa-9f9e-c27ea125d52a)

Browser console logs:
![image](https://github.com/5afe/safe-support/assets/114049495/1265f9eb-803f-4296-b0eb-00aadf7b1a27)
![image](https://github.com/5afe/safe-support/assets/114049495/7139565c-4765-49b2-80b2-6e55178b61ab)
![image](https://github.com/5afe/safe-support/assets/114049495/91b1d8b4-7443-49fc-98e8-3f66d141d156)

### Date and time this happened or you first noticed this issue

02-08-2023

### Network

Polygon

### Safe Address

0x828d55AaF0fE916879C7dCf0E3278D1E8dbEDDd3

### Token Type

None

**Comment by liliya-soroka** [comment]
reported to the team

**Comment by liliya-soroka** [comment]
https://github.com/safe-global/safe-client-gateway-nest/issues/613 - the issue to follow the progress

**Comment by Sherie15** [comment]
Hi team, is this user's issue related to fiat value incorrect for this token https://polygonscan.com/address/0xfa68FB4628DFF1028CFEc22b4162FCcd0d45efb6? This is the Safe https://app.safe.global/balances?safe=matic:0x342f9116e62232a8ac189bb60923020a919ffe78.

**Comment by stonysam** [comment]
> Hi team, is this user's issue related to fiat value incorrect for this token https://polygonscan.com/address/0xfa68FB4628DFF1028CFEc22b4162FCcd0d45efb6? This is the Safe https://app.safe.global/balances?safe=matic:0x342f9116e62232a8ac189bb60923020a919ffe78.

I am the user who reported this issue. As far as I am concerned this is unrelated. I'm not aware of this token or the Safe mentioned.

**Comment by katspaugh** [comment]
The fiat thing is now fixed, and the original two Safes are as good as new.

**Comment by stonysam** [comment]
Thank you! Confirming the issue with the Safes is fixed.
