### ISSUE TITLE
Connection Rejected when using MetaMask mobile app via WC (multiple users affected) 

### ISSUE THREAD

**Issue by CindyLo0** [5afe/safe-support#267]
### Issue Category

Other

### What happened?

A user reported getting Connection Rejected! error when connecting their MetaMask mobile app via WalletConnect to the Safe web app. User also mentioned they have multiple staff experiencing the same error. 

![image](https://github.com/5afe/safe-support/assets/79137197/08fa47a7-d400-48ae-94e7-b254ef80f8bd)

Same issue on my end. 

### Date and time this happened or you first noticed this issue

10-08-2023 17:40

### Network

Ethereum Mainnet

### Token Type

None

**Comment by katspaugh** [comment]
It's being tracked here: https://github.com/safe-global/safe-wallet-web/issues/2435

**Comment by katspaugh** [comment]
This is fixed now and will go live this Wednesday.

**Comment by la1234512345** [comment]
Hi @katspaugh, we are still currently experiencing the issue

**Comment by katspaugh** [comment]
It’s not live yet, release will happen today.

**Comment by la1234512345** [comment]
Thank you, it's working now. We'll go ahead and close this issue
