### ISSUE TITLE
Cannot execute transaction (Execute button greyed out) when sending ETH on Optimism network

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#270]
### Issue Category

Transaction execution issue

### What happened?

Trying to send 0.0005 ETH but the 3rd owner was not able to execute the transaction--Execute button is greyed out (but tenderly simulation shows success):

Executing owner wallet address: oeth:0xb2C14afDEc6B26Bf1842641cC4f2c6D7aAbc73cD

Safe address: https://app.safe.global/transactions/queue?safe=oeth:0x910DB9aC51Ad901acc68E95dE42173c6B9aBb877

![image](https://github.com/5afe/safe-support/assets/114005210/53aa39cd-0a06-4e0b-a441-6ae335ecf90e)

![image](https://github.com/5afe/safe-support/assets/114005210/adbbec03-bb06-47a5-8cba-39d374fba779)

### Date and time this happened or you first noticed this issue

14-08-2023

### Network

Optimism

### Safe Address

0x910DB9aC51Ad901acc68E95dE42173c6B9aBb877

### Token Type

None

**Comment by usame-algan** [comment]
Are there any errors in the console? Can the user try again? The button is not disabled for me when using impersonator:
<img width="1107" alt="Screenshot 2023-08-15 at 08 56 21" src="https://github.com/5afe/safe-support/assets/5880855/e9e8f5b5-7a09-43eb-8311-6cf8bca60b23">

**Comment by Claire-serveth** [comment]
> Are there any errors in the console? Can the user try again? The button is not disabled for me when using impersonator: <img alt="Screenshot 2023-08-15 at 08 56 21" width="1107" src="https://user-images.githubusercontent.com/5880855/260646529-e9e8f5b5-7a09-43eb-8311-6cf8bca60b23.png">

Hi @usame-algan hmm, let me ask the user for now if the issue still persists. Will get back as soon as I have the response. Thank you for looking into this 🙏

**Comment by Claire-serveth** [comment]
Hi @usame-algan the issue seemed to be with the user's proxy server. After further troubleshooting, the issue was resolved when the user changed his proxy server. I'll go ahead and close this issue now. Thank you so much again 🙏
