### ISSUE TITLE
Page not responding error; UI is stuck when navigating on various tabs [Goerli network]

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#271]
### Issue Category

Other

### What happened?

User was trying to send NFTs and was stuck at signing for 10-15 minutes before a successful transaction execution. But checking on transactions tab, page seemed to be stuck and getting "Page not responding" pop up. Tried clicking on assets tab and the UI is stuck again. User has 6000+ NFTs, does this affect how the page loads? I tried loading his safe on my end from different browsers (even on private browser) and I'm getting the same issue on my end as well. 

User is using Chrome on Ubuntu 20.04, while I tried Edge and Firefox on my end.

Safe address: https://app.safe.global/balances/nfts?safe=gor:0x41cec4Cd8b75308586C151839c314BCf4d98069D

### Date and time this happened or you first noticed this issue

15-08-2023

### Network

Goerli

### Safe Address

0x41cec4Cd8b75308586C151839c314BCf4d98069D

### Token Type

None

**Comment by usame-algan** [comment]
Thanks for reporting, I am also able to reproduce this issue and will investigate further.

**Comment by Claire-serveth** [comment]
> Thanks for reporting, I am also able to reproduce this issue and will investigate further.

Thank you @usame-algan 🙏

**Comment by katspaugh** [comment]
I'll move it to the frontend issue tracker.

**Comment by Claire-serveth** [comment]
> I've created a frontend issue for it: [safe-global/safe-wallet-web#2482](https://github.com/safe-global/safe-wallet-web/issues/2482)

Thank you @katspaugh 🙏 closing this issue now.
