### ISSUE TITLE
Error: Missing revert data in call exception; Transaction reverted without a reason string [ETH network]

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#272]
### Issue Category

Transaction execution issue

### What happened?

User is trying to transfer USDT but getting this error when trying to execute the transaction (already tried basic troubleshooting steps and tried different browsers):

[ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="execTransaction(address,uint256,bytes,uint8,uint256,uint256,uint256,address,address,bytes)", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)

And this is the error when executing later:
![image](https://github.com/5afe/safe-support/assets/114005210/c2979054-1883-4c1f-b590-4bcd41d928ce)

Owner wallet address is connected via walletconnect using Trust wallet mobile app. 
Safe wallet: https://app.safe.global/balances?safe=eth:0xe39646E5153Cc2173ecC51F0ee6CFe133d47B0f3

More details:

Trust wallet mobile app version: 9.2 (785)
Device: Iphone 14
Device OS: IOS 16.6

Dev console logs:
![image](https://github.com/5afe/safe-support/assets/114005210/127898a6-5533-4252-868b-9832df4cfe87)

I tried to impersonate the owner but was not able to replicate the issue on my end, might be isolated to trust wallet?
![image](https://github.com/5afe/safe-support/assets/114005210/742febe3-2e02-4fe1-af80-d20279ca80d7)

### Date and time this happened or you first noticed this issue

16-08-2023

### Network

Ethereum Mainnet

### Safe Address

0xe39646E5153Cc2173ecC51F0ee6CFe133d47B0f3

### Token Type

None

**Comment by Claire-serveth** [comment]
Another user reported the same issue using trust wallet. Safe address: https://app.safe.global/transactions/queue?safe=eth:0xd366F566D560C18aEa6AB89268dAC40f428308f5

![image](https://github.com/5afe/safe-support/assets/114005210/bd292622-4d7a-4913-ab29-3304d6789c9b)


I gave users another work around due to urgent transfers--(import seedphrase/private key to metamask or safe mobile app) while executing via trust wallet issue is not fixed yet.

**Comment by Sherie15** [comment]
Hi team, reporting the same issue and error for Tangem wallet for the Safe address: **0xbf5d64Ac041cf9a28713Db75FfB1a9cf0e177422**. User is using Chrome.

_This transaction will most likely fail. To save gas costs, reject this transaction.
call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="execTransaction(address,uint256,bytes,uint8,uint256,uint256,uint256,address,address,bytes)", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)_

**Comment by gittyup-ship-it** [comment]
i am having the same problem (above).  I need to transfer out tokens within 30 days to migrate otherwise they will all be useless and i will lose thousands.  please help, thank you!

**Comment by gittyup-ship-it** [comment]
now it says this 
![image](https://github.com/5afe/safe-support/assets/143585022/b5bef458-3819-4fc0-8bcc-8d95efabac3e)

**Comment by gittyup-ship-it** [comment]
if choose to execute later, it gives me this
![image](https://github.com/5afe/safe-support/assets/143585022/b0760533-affd-44c7-9e7f-0c7a141ac8fc)

**Comment by gittyup-ship-it** [comment]
i suspect it's an issue with wallet connect but i also see that there was a migration back in june.  did safe not migrate?  https://docs.walletconnect.com/2.0/advanced/migration-from-v1.x/overview

**Comment by gittyup-ship-it** [comment]
i use wallet connect with tangem all the time ex aave, uniswap, sushi, quickswap etc and i have no issues so it must be a safe issue.  someone please fix this and upgrade to walletconnect v2!

**Comment by gittyup-ship-it** [comment]
it is not tangem issue  
![image](https://github.com/5afe/safe-support/assets/143585022/88760419-25ce-4d5e-9459-7a865087c8f6)

**Comment by iamacook** [comment]
@gittyup-ship-it, can you confirm that your wallet is/was on the _same_ chain as the Safe interface before connecting to it? (Please note that we have supported WalletConnect v2 from its release.)

@Claire-serveth @Sherie15, can you also confirm the above with the other reports?

**Comment by Claire-serveth** [comment]
> @gittyup-ship-it, can you confirm that your wallet is/was on the _same_ chain as the Safe interface before connecting to it? (Please note that we have supported WalletConnect v2 from its release.)
> 
> @Claire-serveth @Sherie15, can you also confirm the above with the other reports?

Hi @iamacook still checking with the user; will definitely update here as soon as the user responds. Thank you 🙏

**Comment by gittyup-ship-it** [comment]
Hi

> > @gittyup-ship-it, can you confirm that your wallet is/was on the _same_ chain as the Safe interface before connecting to it? (Please note that we have supported WalletConnect v2 from its release.)
> > @Claire-serveth @Sherie15, can you also confirm the above with the other reports?
> 
> Hi @iamacook still checking with the user; will definitely update here as soon as the user responds. Thank you 🙏

Hi, yes it is on the same chain!

**Comment by gittyup-ship-it** [comment]
Ta

> > @gittyup-ship-it, can you confirm that your wallet is/was on the _same_ chain as the Safe interface before connecting to it? (Please note that we have supported WalletConnect v2 from its release.)
> > @Claire-serveth @Sherie15, can you also confirm the above with the other reports?
> 
> Hi @iamacook still checking with the user; will definitely update here as soon as the user responds. Thank you 🙏

![image](https://github.com/5afe/safe-support/assets/143585022/2d604722-9f70-4bbf-a841-a79c21bf504d)

**Comment by gittyup-ship-it** [comment]
Hi all, the issue was resolved after multiple attempts. I used the app on safar iOS . Thanks for your help

**Comment by Claire-serveth** [comment]
I haven't heard back from the user anymore, so I'm closing this issue now. Thank you 🙏
