### ISSUE TITLE
Getting "The contract you are sending the transaction to has changed admin/ownership 6 days ago" from Redefine

### ISSUE THREAD

**Issue by jakekvm01** [5afe/safe-support#273]
### Issue Category

Other

### What happened?

User is getting "The contract you are sending the transaction to has changed admin/ownership 6 days ago" from Redefine.

Sender safe address: arb1:0x2f8393a3aC972A6a00453D0384e8495f91a2f6Ed
Receiver safe address: arb1:0x41a9DdB593332A4415082ADAe844aD8973832A67

![image](https://github.com/5afe/safe-support/assets/105864754/a448e00e-4e8d-41b3-bbf4-6ab9c190992f)
![image](https://github.com/5afe/safe-support/assets/105864754/01fc3ad1-a64d-4d3a-9f4a-f87a568f9bf5)

### Date and time this happened or you first noticed this issue

N/A

### Network

Arbitrum

### Safe Address

arb1:0x41a9DdB593332A4415082ADAe844aD8973832A67

### Token Address

N/A

### Token Type

None

**Comment by jakekvm01** [comment]
Is it okay for the user to disregard the error message and just continue with the transaction? Thank you

**Comment by la1234512345** [comment]
> Is it okay for the user to disregard the error message and just continue with the transaction? Thank you

It's referring to the token they are transferring rather than the Safe. Closing this ticket
