### ISSUE TITLE
Etherscan Verified Signature Inquiry

### ISSUE THREAD

**Issue by la1234512345** [5afe/safe-support#274]
### Issue Category

Other

### What happened?

Hi team, 

User is trying to use https://etherscan.io/verifiedSignatures# and he gets verification failed. Will this work with Safe? And what are the correct parameters to be entered? Specifically the address and the signature hash
![image](https://github.com/5afe/safe-support/assets/114544040/ce9acaa3-6aef-4abb-8479-bbbb62356ec8)
![image](https://github.com/5afe/safe-support/assets/114544040/2f3f601a-e312-4506-83db-dcef53e96558)

### Date and time this happened or you first noticed this issue

22/10/2023

### Network

Ethereum Mainnet

### Safe Address

na

### Token Address

na

### Token Type

None

**Comment by mmv08** [comment]
To my knowledge, etherscan doesn't support smart contract wallets, so this isn't possible.

**Comment by la1234512345** [comment]
Thank you @mmv08
