### ISSUE TITLE
Can't load newly created safe wallet on Base network

### ISSUE THREAD

**Issue by jakekvm01** [5afe/safe-support#276]
### Issue Category

Safe loading issue, doesnt load on any interface

### What happened?

Can't load safe wallet on Base network.
Safe wallet was created 14 days ago.
https://basescan.org/address/0x21835332cbdf1b3530fae9f6cd66feb9477dfc02

![image](https://github.com/5afe/safe-support/assets/105864754/298d8da1-b27a-492a-bed3-6639059e3c33)

### Date and time this happened or you first noticed this issue

N/A

### Network

Ethereum Mainnet

### Token Address

base:0x21835332cBDf1b3530fAE9f6Cd66FEB9477dFC02

### Token Type

None

### Transactions

```shell
Safe creation tx: 
https://basescan.org/tx/0x69d83fb46ad450f68a811f93d0c5850495a1654f4bf425b311ff0a809e5fcf6c
```

**Comment by moisses89** [comment]
@jakekvm01 how this safe created, it is not initiated correctly and haven't any owner.

**Comment by jakekvm01** [comment]
User is now unresponsive. Closing ticket for now. Thank you @moisses89
