### ISSUE TITLE
Queued transactions randomly disappeared, Current nonce is off

### ISSUE THREAD

**Issue by joanpan** [5afe/safe-support#28]
### Issue Category

Transaction missing / not visible in app or service

### What happened?

> Queued transactions randomly disappeared, user was able to provide screenshot of previously queued txns:
![image](https://user-images.githubusercontent.com/114049668/194933924-f16c57e2-1d5c-4a07-af8f-0de08bb18e40.png)

> According to user when the last signer signed the 1902 txn, he had to resign it for some reason, then everything disappeared

> Current nonce is **1898** and last executed txn is **1896**
Current nonce:
![image](https://user-images.githubusercontent.com/114049668/194934453-e363504f-0ddd-490c-ae8e-614af3c12e11.png)

Last executed:
![image](https://user-images.githubusercontent.com/114049668/194934435-98fee6f1-c29e-44c7-9db6-99310d58c849.png)

> Created new txn and updated the nonce to 1897 -- nothing happened
> Created new txn used nonce 1898 -- seems to be working fine

### Date and time this happened or you first noticed this issue

11-10-2022

### Network

Ethereum Mainnet

### Safe Address

  0xF930EBBd05eF8b25B1797b9b2109DDC9B0d43063

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Uxio0** [comment]
@joanpan This was a temporary indexing issue and it's fixed now
