### ISSUE TITLE
[ETH] Current nonce in the UI doesn't update

### ISSUE THREAD

**Issue by bingclo** [5afe/safe-support#280]
### Issue Category

Transaction execution issue

### What happened?

User already executed 296 and 297, however the UI still thinks the current nonce is 296. This caused queued transactions to be stuck and cannot be executed. 
![image](https://github.com/5afe/safe-support/assets/54754746/6a5e0ca9-67ca-4802-9cde-3e8ced5e1aab)
![image](https://github.com/5afe/safe-support/assets/54754746/185039ee-2ea6-4803-9194-c49b67f2488f)

296 and 297 were executed in a batch about an hour ago: https://etherscan.io/tx/0x2036ae02fea5b4f92c3c79121d5afaf332b0651984d6fe6f81d37bb1a763a542

When checking in Etherscan current nonce seems correct, which is 298.
![image](https://github.com/5afe/safe-support/assets/54754746/cf3a8d03-19f6-4627-8a02-6cbfc6ab41aa)

### Date and time this happened or you first noticed this issue

06/09/2023 22:14:39

### Network

Ethereum Mainnet

### Safe Address

https://app.safe.global/transactions/queue?safe=eth:0x97112D1126D140832AD889e57f0fa46F695Fe67D

### Token Address

NA

### Token Type

None

### Transactions

```shell
https://etherscan.io/tx/0x2036ae02fea5b4f92c3c79121d5afaf332b0651984d6fe6f81d37bb1a763a542
```

**Comment by mmv08** [comment]
https://app.safe.global/settings/setup?safe=eth:0x97112D1126D140832AD889e57f0fa46F695Fe67D the nonce shows 298 for me

**Comment by bingclo** [comment]
Thanks for pointing it out 😅 It wasn't updated 5mins ago. Will inform the user about it 🙏
