### ISSUE TITLE
[ETH] Unable to process message signatures 

### ISSUE THREAD

**Issue by joanpan** [5afe/safe-support#281]
### Issue Category

Safe loading issue, doesnt load on any interface

### What happened?

The user is attempting to sign a message, but there's a delay, and the messages aren't initially appearing in the queue. Co-signers receive a pop-up for the Snapshot signature, but it doesn't immediately appear in the queue. After some time, it eventually shows up, but now there's an error occurring for all of their signers.
![400](https://github.com/5afe/safe-support/assets/114049668/04eda9a5-6001-4b37-9100-0ae9dbdc9057)

Tried clearing cache, multiple browser, tested different dapp - to no avail

### Date and time this happened or you first noticed this issue

08-09-2023

### Network

Ethereum Mainnet

### Safe Address

0x550F25f78DAF6CCBda6c4F77e239B15b6AD48A8B

### Token Type

None

**Comment by joanpan** [comment]
We've received reports from a few users experiencing a common problem where messages are either not appearing in the queue or are being significantly delayed.

**Comment by la1234512345** [comment]
Hi team, issue is still on-going even for new users
Sharing another affected user eth:0x3E7691154F84FB0991c6A731878880f6eeC24b14

**Comment by madjin** [comment]
I'm also facing this issue, trying to sign message in snapshot safe app which requires signing messages. They are super delayed in appearing in the queue for messages, and signing them will result in errors. This seems to be recent, we were able to sign messages normally last week.

**Comment by fmrsabino** [comment]
We have deployed a fix which fixed some of the issues around the latest state of the messages. We will continue to monitor it.

Thanks for reporting!

**Comment by JagoFigueroa** [comment]
Any more issues or complains regarding this @joanpan @la1234512345? Feel free to close the ticket it if everything looks good on your end too 😄

**Comment by Claire-serveth** [comment]
> Any more issues or complains regarding this @joanpan @la1234512345? Feel free to close the ticket it if everything looks good on your end too 😄

Hi @JagoFigueroa I haven't seen any tickets in snoozed having this issue and we haven't got new cases so far, so I'm closing this ticket. Thank you 🙏
