### ISSUE TITLE
Zksync Era Mainnet Balance and History not updating

### ISSUE THREAD

**Issue by la1234512345** [5afe/safe-support#284]
### Issue Category

Token balance not up-to-date, in the interface or service

### What happened?

Hi team, it has been 23 hours since the Safe received ETH and the web app UI has not updated yet
https://app.safe.global/home?safe=zksync:0x47916FD3Ca3C7282BA766A79091d0EcD661B4b4A

![image](https://github.com/5afe/safe-support/assets/114544040/89db2bba-8e00-4d20-9977-3144b25cbb96)
![image](https://github.com/5afe/safe-support/assets/114544040/1e1bc036-646c-4e59-bb68-d7d681e5112b)

### Date and time this happened or you first noticed this issue

10/09/2023

### Network

Zksync Era Mainnet

### Safe Address

0x47916FD3Ca3C7282BA766A79091d0EcD661B4b4A

### Token Address

na

### Token Type

None

### Transactions

```shell
https://explorer.zksync.io/tx/0x4fe4a58f6737a98e861e19a659978b28616191ead5496488631d69a2ce382394
```

**Comment by JagoFigueroa** [comment]
Issue should be resolved now 🚀

**Comment by Claire-serveth** [comment]
> Issue should be resolved now 🚀

Thank you @JagoFigueroa will inform the users 🙏 closing this issue now.
