### ISSUE TITLE
Zksync Era Mainnet Cannot Load Newly Created Safes

### ISSUE THREAD

**Issue by inahlikenoother** [5afe/safe-support#285]
### Issue Category

Safe loading issue, doesnt load on any interface

### What happened?

Successful safe creation but cannot load newly created Safes

![image](https://github.com/5afe/safe-support/assets/114049495/a24e1fc4-689c-4992-85c4-a80669e59578)

Safe creation tx https://explorer.zksync.io/tx/0x89bb2d45db66609167c019741e647ac5e37c333fb323dbb63877bd3bf5cadb25#eventlog

Other affected Safe addresses 
0x57E539E98A2Dd4d9229c167133b74F3261fB7AE7

### Date and time this happened or you first noticed this issue

09-10-2023

### Network

zkSync Era Mainnet

### Token Address

0x2e35937d64f6c8073aa4a114aa9c770c7245346c

### Token Type

None

### Transactions

```shell
https://explorer.zksync.io/tx/0x89bb2d45db66609167c019741e647ac5e37c333fb323dbb63877bd3bf5cadb25#eventlog
```

**Comment by JagoFigueroa** [comment]
Issue should be resolved now 😄
