### ISSUE TITLE
[Polygon] USDC balance not updated

### ISSUE THREAD

**Issue by joanpan** [5afe/safe-support#286]
### Issue Category

Token balance not up-to-date, in the interface or service

### What happened?

USDC balance not updated, funds were sent 24 hrs ago. Funds showing up on polygonscan:
![image](https://github.com/5afe/safe-support/assets/114049668/27c494a8-7175-4c4e-9bad-9fc9bbdd7ec1)
https://polygonscan.com/address/0x17876AC8cf48f38539F7565999fD8b9398b96BA1#tokentxns

### Date and time this happened or you first noticed this issue

13-09-23

### Network

Polygon

### Safe Address

0x17876AC8cf48f38539F7565999fD8b9398b96BA1

### Token Type

None

**Comment by joanpan** [comment]
Update: token is now showing up, however, fiat value is not showing up correctly
![image](https://github.com/5afe/safe-support/assets/114049668/3885de25-809a-4778-b531-f751b38abed5)

**Comment by JagoFigueroa** [comment]
Good morning! Issue should be resolved now 😄

**Comment by joanpan** [comment]
Thanks!
