### ISSUE TITLE
Getting Internal JSON-RPC error during safe creation on Optimism network

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#288]
### Issue Category

Other

### What happened?

Upon safe creation, user was not getting a pop up confirmation on the connected wallet (metamask) instead, getting Internal JSON-RPC error. Already tried doing a hard refresh, clearing cache/cookies, using another browser and changing metamask RPC but issue still persists.

Wallet address used upon safe creation: 0x65d5962971F3EeE6bbB4bC6DeDc7B61F36Da4dEa

![image](https://github.com/5afe/safe-support/assets/114005210/12d6bb42-f0c3-4d38-ab30-26bd41d14bf4)

User was able to create a safe through OZ defender client while he was no able to do so in the safe UI.

### Date and time this happened or you first noticed this issue

17-09-2023

### Network

Optimism

### Token Type

None

**Comment by Claire-serveth** [comment]
Another user reported the same issue using Metamask wallet. Wallet address: 0x76E059C6FF6bf9FFFD5f33AFdf4AB2FD511C9DF4

**Comment by JagoFigueroa** [comment]
Issue should be resolved now 😄 Looks like there were some dramatic gas price spikes on the last couple of days for the chain and that's why safe creation was failing, internally we were setting a smaller amount for safe creation. 

Everything looks more stable today, could you let the users know and let us know if there are still any issues? 

Thanks!

**Comment by Claire-serveth** [comment]
> Issue should be resolved now 😄 Looks like there were some dramatic gas price spikes on the last couple of days for the chain and that's why safe creation was failing, internally we were setting a smaller amount.
> 
> Everything looks more stable today, could you let the users know and let us know if there are still any issues?
> 
> Thanks!

Thank you @JagoFigueroa will check with the users if it's fixed on their end. 🙏

**Comment by Claire-serveth** [comment]
Users confirmed the issue is fixed. Closing this issue now 🙏
