### ISSUE TITLE
Cannot load newly created Safe on Gnosis chain via Gelato network

### ISSUE THREAD

**Issue by phoebe-serveth** [5afe/safe-support#289]
### Issue Category

Safe loading issue, doesnt load on any interface

### What happened?

Getting an error loading newly created Safe via Gelato. Safes that are created directly from the wallet on the Gnosis chain work fine.

![image](https://github.com/5afe/safe-support/assets/114040259/65ddde72-c70b-4130-b22c-c87fdfd896eb)

![image](https://github.com/5afe/safe-support/assets/114040259/2e9cca8d-68cc-4ef1-a481-c5e966fbeaaa)

Safe creation more than 6hrs now.
![image](https://github.com/5afe/safe-support/assets/114040259/eadbc62f-0fac-494e-8662-2c900b1831b1)

### Date and time this happened or you first noticed this issue

19-09-2023 04:31 PM

### Network

Gnosis Chain

### Token Type

None

**Comment by kunalmodi** [comment]
Another example here in case useful:
- https://gnosisscan.io/tx/0x8d4b55271c2759b21d7d7f20fedb796831babe640e009f53176f9ac890aefdc9
- API Link: https://safe-transaction-gnosis-chain.safe.global/api/v1/safes/0x588A28F81cD227b85650BcdB374961A9518E2AAC/

**Comment by liliya-soroka** [comment]
Thank you for reporting. The team is informed and checking the issue

**Comment by liliya-soroka** [comment]
We are back on the Gnosis chain. Could you check with the user , please?

**Comment by Sherie15** [comment]
Both working properly now. Thank you!
https://app.safe.global/home?safe=gno:0xAAdC9539b198D99Dd7d23b8F2ce9ca3Db5B878b8
https://app.safe.global/home?safe=gno:0xa083388002640a9063767e6a386723A7B995b3ee
