### ISSUE TITLE
[Polygon] Error submitting the transaction

### ISSUE THREAD

**Issue by biafffff** [5afe/safe-support#290]
### Issue Category

Transaction execution issue

### What happened?

I'm having some issues in executing a `removeOwner` transaction on a Polygon Safe multisig. 

After having collected all the signatures, I click on Execute, but the MetaMask signing window does not show up and an error message pops out "Error submitting the transaction. Please try again."

Please also note that there was another message saying, "This transaction will most likely fail. To save gas costs, reject this transaction". Also the Tenderly simulation fails saying "The transaction failed during the simulation throwing error GS205 in the contract at 0x3e5c63644e683549055b9be8653de26e0b4cd36e. Full simulation report is available [on Tenderly](https://dashboard.tenderly.co/public/safe/safe-apps/simulator/a3a3a1f0-fd4b-4560-9f31-8ba5b7a91e7a)".

Being on Polygon, my plan was to try to execute anyway.

The issue was present also yesterday, but after some trials, the MM window popped out. 

<img width="1508" alt="image" src="https://github.com/5afe/safe-support/assets/26275332/a6976574-ca4a-483f-a6f0-7801e67d4985">

### Date and time this happened or you first noticed this issue

19-09-2023

### Network

Polygon

### Safe Address

0x61A944Ca131Ab78B23c8449e0A2eF935981D5cF6

### Token Type

None

**Comment by mmv08** [comment]
There were configuration changes between transactions that changed the owner structure. Since transactions to replace or remove an owner depend on the owner structure encoded in the call data, it must be valid at the time of the execution. Please create a new transaction to remove the owner and replace the current transaction.
