### ISSUE TITLE
NFTs show up as unknown image on iOS app

### ISSUE THREAD

**Issue by joanpan** [5afe/safe-support#292]
### Issue Category

Token missing completely / not visible in the interface or service

### What happened?

User's WNS NFTs show up as unknown image on the iOS app. The images for WNS NFTs initially had images show up but now no image appears. 

iOS:
![image](https://github.com/5afe/safe-support/assets/114049668/db05e7a3-6408-4686-bc8e-226b7795acd6)

Zerion and other apps are correctly displaying the images:
![image](https://github.com/5afe/safe-support/assets/114049668/5ff5a867-c6aa-4afc-a3ab-158132a3a9fe)

### Date and time this happened or you first noticed this issue

27-09-2023

### Network

Ethereum Mainnet

### Safe Address

eth:0x5B3dC2d3d4c3ae1116C286b54d7f99E16815c20c

### Token Address

0xBA9BBEa08241845013b40a061E4A77c9345e4562

### Token Type

ERC721

**Comment by JagoFigueroa** [comment]
Hey team, this is not an issue. We are showing those tokens as unknown because it is not possible for us to fetch any metadata for them. [Example](https://api.wnsdomains.io/metadata/?tokenid=9229)

Cheers!

**Comment by joanpan** [comment]
Thank you!
