### ISSUE TITLE
[Inquiry] Zksync contract not verified

### ISSUE THREAD

**Issue by joanpan** [5afe/safe-support#295]
### Issue Category

Safe loading issue, doesnt load on any interface

### What happened?

Hi team, we have a user asking why the safe contract on zksync is not verified. Any insights on this? Thank you
https://explorer.zksync.io/address/0x85d9F3e6e6487179f4A6658987a1d5Ba61ab8D7D#contract
![image](https://github.com/5afe/safe-support/assets/114049668/5b6ae546-36b4-48f3-ba3e-bd45f8056e26)

Safe contracts are verified on other networks:
<img width="695" alt="image-1" src="https://github.com/5afe/safe-support/assets/114049668/43070d7c-d548-4054-b465-25addd215949">

### Date and time this happened or you first noticed this issue

29-09-2023

### Network

Ethereum Mainnet

### Token Type

None

**Comment by Uxio0** [comment]
Hi @joanpan , during our deployment process there's a script to verify the contracts, but it seems it was not working for this case. Our contracts and deployment scripts are public so everyone can validate the contracts manually if they need so
