### ISSUE TITLE
[zkSync Era Mainnet] QUEUED - TRANSACTION WITH NONCE 0 NEEDS TO BE EXECUTED FIRST error when nonce 0 is already executed

### ISSUE THREAD

**Issue by Sherie15** [5afe/safe-support#296]
### Issue Category

Other

### What happened?

The user cannot execute nonce 1 as it shows that nonce 0 has not been executed

![image](https://github.com/5afe/safe-support/assets/113986185/e2184ea3-b8df-4e63-b114-8bcb21c76a0e)
![image](https://github.com/5afe/safe-support/assets/113986185/bc57e792-0f2c-4041-8b6f-145ec7b6d3d0)
![image](https://github.com/5afe/safe-support/assets/113986185/d17bca3c-1c2b-48ec-ae52-afd0be6950d2)

### Date and time this happened or you first noticed this issue

06-10-2023 06:55am

### Network

Ethereum Mainnet

### Safe Address

0xf909C8984E7a22de6162553fc463eedFB5b4d016

### Token Type

None

**Comment by Louis9x** [comment]
I'll wait for you

**Comment by Sherie15** [comment]
Safe nonce just updated to nonce 1. Waiting for your nonce 1 execution @Louis9x, please.

**Comment by Sherie15** [comment]
Another Safe address experiencing the same issue **0x916859041Aa41577c821624f81D895772147D506**
![image](https://github.com/5afe/safe-support/assets/113986185/cb7396c2-8765-48de-9d04-6cc49bc8aad3)
![image](https://github.com/5afe/safe-support/assets/113986185/d8f38b50-0bad-402b-a829-e28b30fc4e95)
![image](https://github.com/5afe/safe-support/assets/113986185/7b2265cc-1566-474d-8f60-dbafd1ff28f1)

**Comment by Louis9x** [comment]
> Safe nonce just updated to nonce 1. Waiting for your nonce 1 execution @Louis9x, please.

thank you for sup. i'm waitting

**Comment by Sherie15** [comment]
Both Safe addresses have Safe nonce updated. We will be closing this ticket as soon as the pending transactions are executed.

**Comment by Louis9x** [comment]
> Both Safe addresses have Safe nonce updated. We will be closing this ticket as soon as the pending transactions are executed.

okay thank you verymuch

**Comment by Louis9x** [comment]
It hasn't been fixed yet, right sirr?

**Comment by Louis9x** [comment]
I have successfully resolved my debt. everything has become normal. thank you for support
