### ISSUE TITLE
Current nonce is not updated or in sync | Gnosis chain

### ISSUE THREAD

**Issue by phoebe-serveth** [5afe/safe-support#297]
### Issue Category

Transaction execution issue

### What happened?

Cannot execute any of the queued transactions. The interface shows current nonce is 72645 and in transaction service API shows nonce 72646. However, there are multiple executed transactions already. History shows executed nonce up until 72688.
![image](https://github.com/5afe/safe-support/assets/114040259/53ad03f4-bcd1-4480-85ed-30ef0f7e2a7c)
![image](https://github.com/5afe/safe-support/assets/114040259/034fbdd1-8493-4b4a-af7a-495a824aa0dd)
![image](https://github.com/5afe/safe-support/assets/114040259/14293f2f-3915-45f0-ad1c-bb91415d3134)
![image](https://github.com/5afe/safe-support/assets/114040259/7fbd5b7d-106a-419f-9e45-6cb3b2e5b784)

### Date and time this happened or you first noticed this issue

07-10-2023 2:23AM

### Network

Gnosis Chain

### Safe Address

0x296033cb983747b68911244EC1A3f01d7708851b

### Token Type

None

**Comment by phoebe-serveth** [comment]
Thanks @liliya-soroka I just rechecked the safe address and it seems that the current nonce is now in sync. However, executed transactions are still not showing up in History tab. 
![image](https://github.com/5afe/safe-support/assets/114040259/e65c8783-058d-4e6a-8603-60aa1cf8ccdd)
![image](https://github.com/5afe/safe-support/assets/114040259/ef11f744-1687-4a83-bdf2-1f2ade56e1b8)
![image](https://github.com/5afe/safe-support/assets/114040259/61fb880c-5f07-4a60-a224-0b09423debf3)
![image](https://github.com/5afe/safe-support/assets/114040259/7590d82d-eb57-47d5-ba29-90c14917059f)

**Comment by liliya-soroka** [comment]
the team is checking
