### ISSUE TITLE
ETH: Unable to load Safe 

### ISSUE THREAD

**Issue by reyserveth** [5afe/safe-support#30]
### Issue Category

Safe loading issue, doesn't load on any interface

### What happened?

Unable to load Safe in the UI. 

### Date and time this happened, or you first noticed this issue

11-10-2022 8:30 PM

### Network

Ethereum Mainnet

### Safe Address

0x14caA9EA7A15f18ee85a1541766Ea058a6CBDeE1
0x7401d6ae9C98BEf608c981AD151B37124c04738E
0xb85aaF40B57f841208b2D0247aFA5B84373D45b3
0x28Ae028cB2c0e369bCf2f21183aC6678Be1A90c1
0x2c67d860b32F428f15378cB8cD480667F9f3B9Af

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Claire-serveth** [comment]
Another users/addresses that can't load their safes currenntly:

eth:0x2D163ab86C046a24D039ea3f93624de96aB73427
eth:0x7d89900543FB8723C21faeCEfeB6E7Fc96F8A2ad
eth:0xb298cECc6C3eF5284ad4a24c12883F87752654a2
eth:0x5B5173599A2F29973397c34D01a49b3A0Ee8963D
eth:0xc45A789969EB22b7382aE6a580B6c67493A9E200

**Comment by jakekvm01** [comment]
Additional addresses

eth:0xa40FBd692350C9Ed22137F97d64E6Baa4f869E8C
eth:0x4b6c63E6a94ef26E2dF60b89372db2d8e211F1B7
eth:0x07de0318c24D67141e6758370e9D7B6d863635AA
eth:0x4B107Fb97F7Dbe18D7Fe8B588731CfD590aaed2E
eth:0x694a8B77a71CE9500D7448D80345a92082AB8C18
eth:0x42892f6cdB42DAEA233Fb4e5a2728d0bDf14af54
eth:0x66736EAbEFEb5825c96b394497D4c78370CB6624
eth:0xEd2AAdADA6E6BaF17eC4ac3a0602459B87865243
eth:0x5B5173599A2F29973397c34D01a49b3A0Ee8963D
eth:0xc133e7222F5c7C579B0F3a876e06ED2de46C96bA
eth:0x66736EAbEFEb5825c96b394497D4c78370CB6624

**Comment by reyserveth** [comment]
ETH Safe unable to load issue is now fixed. I am able to load multiple safes.
