### ISSUE TITLE
UI delay in updating current nonce and Executed transaction is still stuck on queue [BSC network]

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#302]
### Issue Category

Other

### What happened?

Successfully executed transaction is still stuck on queue and current nonce is delayed in updating.

https://app.safe.global/transactions/queue?safe=bnb:0x2292D9B28EdFD4ef625015A051CbA9D7C11Af00c

![image](https://github.com/5afe/safe-support/assets/114005210/335b8c1b-6516-4539-b79d-b8d1770811ac)
![image](https://github.com/5afe/safe-support/assets/114005210/10d0b7ae-af6d-4803-884f-61a9bbf6fc36)

### Date and time this happened or you first noticed this issue

10-10-2023

### Network

Binance Smart Chain

### Safe Address

bnb:0x2292D9B28EdFD4ef625015A051CbA9D7C11Af00c

### Token Type

None

**Comment by liliya-soroka** [comment]
checking with the team

**Comment by liliya-soroka** [comment]
The issue should be fixed now. Could you check with the user, please?

**Comment by Claire-serveth** [comment]
> The issue should be fixed now. Could you check with the user, please?

Will update the user, thank you @liliya-soroka 🙏

**Comment by Claire-serveth** [comment]
Since UI is updated already (although no response from the user yet) I'll go ahead and close this issue now. 🙏
