### ISSUE TITLE
Tenderly simuation not working

### ISSUE THREAD

**Issue by CindyLo0** [5afe/safe-support#303]
### Issue Category

Other

### What happened?

Hi team. Some users reported the option to simulate transactions in the UI using Tenderly is not working. Checked in Goerli and got the same issue. See error below: 
![image](https://github.com/5afe/safe-support/assets/79137197/bfc4fce2-2873-4b5d-9f37-f5dbf044cd19)

### Date and time this happened or you first noticed this issue

10-10-2023 16:30

### Network

Ethereum Mainnet

### Token Type

None

**Comment by liliya-soroka** [comment]
the team is informed, checking

**Comment by liliya-soroka** [comment]
Tenderly should be back. Please, check

**Comment by bingclo** [comment]
Thank you 🙏
