### ISSUE TITLE
[Arbitrum] Safe webapp crashes when viewing History page due to unauthorized/scam transactions

### ISSUE THREAD

**Issue by phoebe-serveth** [5afe/safe-support#304]
### Issue Category

Safe loading issue, doesnt load on any interface

### What happened?

Safe continuously loads and crashes when accessing the History page, making it difficult for users to use the interface. Despite multiple transactions not being signed and executed by the Safe owners, the UI displays them as successful "Sent" transactions. 
Transaction hash shows it did not interact with the safe contract. https://arbiscan.io/tx/0x065adfeeb2af23a50016efa864f0ffd5954fcdd6ffc300edd16e0a7b976b9cf6
![image](https://github.com/5afe/safe-support/assets/114040259/0180fad0-69ad-4c5b-9abc-a86c32677d5e)
![image](https://github.com/5afe/safe-support/assets/114040259/237e3148-aa97-42a6-bcb6-9dbfbca100a5)

### Date and time this happened or you first noticed this issue

11-10-2023 10:45 am

### Network

Arbitrum

### Safe Address

0x5318f07a3a20a2f8bb0ddf14f1dd58c517a76508

### Token Address

0x5504F71E8a3f4D8aa3DA1A80c34b19D9D75B0b88

### Token Type

None

### Transactions

```shell
https://arbiscan.io/tx/0x065adfeeb2af23a50016efa864f0ffd5954fcdd6ffc300edd16e0a7b976b9cf6
```

**Comment by liliya-soroka** [comment]
reported to the team

**Comment by phoebe-serveth** [comment]
The user confirms that the UI now loads more quickly compared to before. Closing this ticket.
