### ISSUE TITLE
Polygon - Cannot load safe

### ISSUE THREAD

**Issue by inahlikenoother** [5afe/safe-support#305]
### Issue Category

Safe loading issue, doesnt load on any interface

### What happened?

User is unable to load the Safe, behavior is the same when loading user's Safe on my end. Safe is not a newly created Safe
<img width="1190" alt="1697085811706" src="https://github.com/5afe/safe-support/assets/114049495/d155bccf-3784-4a17-afd6-1f9baf1ac052">

![image](https://github.com/5afe/safe-support/assets/114049495/3a940d66-4105-4a39-8624-e460a3e34da6)

A few other Polygon Safe addresses (from the same user) also not loading:

0x26490BbB94bE89FB4dCFFdF907FA9c495aD2Ecb5
0x94fFd831F75f4234A48ed8c1D0bE0DBFfA30F7cC
0x21516A4099C3122ff759BBb61df9F4C23B5c7201
0xc8D6C3f866597a63780fdEC4C4Cb08B5C19CDb60

### Date and time this happened or you first noticed this issue

12-10-2023 

### Network

Polygon

### Safe Address

0x1186c7524da17f5cf573abd064d785ae664144f1

### Token Type

None

### Transactions

```shell
Safe creation tx hash https://polygonscan.com/tx/0x206eb29333c0209ebff0553bdf5d79f2f723200c3b9fd6e08f4d7cfd25573512#eventlog
```

**Comment by liliya-soroka** [comment]
do we know how the safes were created?

**Comment by inahlikenoother** [comment]
> do we know how the safes were created?

I will check and confirm with the user, thank you

**Comment by Sherie15** [comment]
The user said it was created using the official Safe web app https://app.safe.global/welcome.
