### ISSUE TITLE
Various issues (safe not loading, nonce not loading, balance not updating) on ZKsync era network

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#307]
### Issue Category

Other

### What happened?

A number of users are having issues on zksync era network--unable to load their safes, balance is not updated/not showing up on the UI, nonce is not updating hence getting an error "Failed to add to queue":

![image](https://github.com/5afe/safe-support/assets/114005210/fab66e0a-cda0-4ef6-9c50-849670d2abe9)
![image](https://github.com/5afe/safe-support/assets/114005210/45ad0dd1-925f-472b-b8a2-fda2c91d49b4)

### Date and time this happened or you first noticed this issue

15-10-2023

### Network

Ethereum Mainnet

### Token Type

None

**Comment by Claire-serveth** [comment]
> Zksync network should be more stable now. The node was changed from the Ankr node to https://mainnet.era.zksync.io/

Thank you so much @liliya-soroka will check with the users if the issue is fixed on their before closing this ticket 🙏

**Comment by Claire-serveth** [comment]
> Zksync network should be more stable now. The node was changed from the Ankr node to https://mainnet.era.zksync.io/

Hi @liliya-soroka user's balance (including transaction history) is still not updated until now. USDT was transferred yesterday but until now it's not yet visible. Safe address: https://app.safe.global/balances?safe=zksync:0xa5ea15cd188A7Ff75fff03F201f5C41B0E774504

**Comment by Claire-serveth** [comment]
Hello @liliya-soroka user's safe was created yesterday but still unable to load until now. Safe address: https://app.safe.global/home?safe=zksync:0xc4C4AE4B88781608B24B967897F70d16b62A7809

**Comment by liliya-soroka** [comment]
going to check with the team

**Comment by Sherie15** [comment]
Hi team, another issue from a user where the current nonce is already executed but still appears in the pending transaction queue for more than 2days. 
![image](https://github.com/5afe/safe-support/assets/113986185/749c123c-fb68-44bf-a8ce-ca100823e4bc)

**Comment by Claire-serveth** [comment]
Hi @liliya-soroka it looks like the safes are now updated. I'm still waiting for the users' response though to check if the issue is fixed on their end and will close the ticket by then. Thank you so much 🙏
