### ISSUE TITLE
BSC: Unable to load Safe

### ISSUE THREAD

**Issue by reyserveth** [5afe/safe-support#31]
### Issue Category

Safe loading issue, doesnt load on any interface

### What happened?

Unable to load Safe in the UI
Failed transaction. "Failed to create transaction: Server side error

### Date and time this happened or you first noticed this issue

11-10-2022 9:00 PM

### Network

Binance Smart Chain

### Safe Address

0xda1800a8F2A32dc422f1F1b33e5dDE806e99B97c
0xe6E26A17Dc579570686B3158326Fd29752aedC80
0x2a0d28D209751022DE28DfDE2E90e01d661BC2c0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Claire-serveth** [comment]
Hello team, 

Another users/addresses that can't load their safes currenntly:

bnb:0xFAdB6FbA3213C0D300D918a55f7946dF7C1A3b3e

bnb:0x3c02B427c783D6699aF06C29D362a6f3640836B3

bnb:0xBBa59472fC7f26C413944A779C46044412d01E7E

bnb:0x5bea976f5b75A83Ae9375E234C8C99D38981E755

bnb:0xC3e6D13CE05aA0a75634B47B2D791fb5e5670F65

bnb:0x8B8BaA866ba48a156376AeEaA5Cc6DfE17e71b3b

**Comment by cigarbnb** [comment]
Is anybody can help?

**Comment by reyserveth** [comment]
ETH delay is now fixed. Safe are now online
