### ISSUE TITLE
Error 9902 on Safe iOS app when connecting to a dapp

### ISSUE THREAD

**Issue by joanpan** [5afe/safe-support#311]
### Issue Category

Safe loading issue, doesnt load on any interface

### What happened?

Tried restarting the app and trying different dapps (Uniswap and Zerion) - same issue

I was able to replicate on my end too.

App version 3.24.1 (1972)

![IMG_5681](https://github.com/5afe/safe-support/assets/114049668/3ec1bdb6-b70a-4625-815e-ba29121b71d1)

### Date and time this happened or you first noticed this issue

20-10-2023

### Network

Ethereum Mainnet

### Token Type

None

**Comment by olofedlund** [comment]
FYI: As of 11/1 this is still a problem. Encountered on iPadOS 17.1.

**Comment by liliya-soroka** [comment]
Could you provide more information and steps , please?
In the 3.24.2 we have fixed the issue with connection to the dapp opened on the desktop 
Known issue with the WC in the mobile browser - [[iOS] Can't connect to some apps via WalletConnect in the mobile browser: "address is invalid error"#3262](https://github.com/safe-global/safe-ios/issues/3262)

**Comment by Claire-serveth** [comment]
> Could you provide more information and steps , please? In the 3.24.2 we have fixed the issue with connection to the dapp opened on the desktop Known issue with the WC in the mobile browser - [[iOS] Can't connect to some apps via WalletConnect in the mobile browser: "address is invalid error"#3262](https://github.com/safe-global/safe-ios/issues/3262)

Hi @liliya-soroka indeed the issue seemed fixed on version 3.24.2. Will keep track on the other opened issue regarding walletconnect on mobile browser as well. Thank you for the update. Closing this issue now 🙏
