### ISSUE TITLE
[Zksync] USDC token not appearing in the UI

### ISSUE THREAD

**Issue by la1234512345** [5afe/safe-support#313]
### Issue Category

Token missing completely / not visible in the interface or service

### What happened?

More than 2 hours of USDC token not appearing in the UI since it was sent
![image](https://github.com/5afe/safe-support/assets/114544040/c60af856-9bdf-48f7-9105-3550907231ab)
![image](https://github.com/5afe/safe-support/assets/114544040/b2f47ad9-680e-4721-a921-144b89c552c2)

### Date and time this happened or you first noticed this issue

25/10/2023

### Network

Ethereum Mainnet

### Safe Address

zksync:0x4111830af206aae47eabE99E90666bf510E2d08b

### Token Type

None

### Transactions

```shell
https://explorer.zksync.io/tx/0x2fa9d28b0d92f8f0165a116461e5333804be4f5ab828629c64e9831dbb4f1f72
```

**Comment by la1234512345** [comment]
Another user affected: zksync:0x1b6be2e93a8ca7cd1b34ebdb35520e8d6fceea06

**Comment by Claire-serveth** [comment]
Another token missing issue but this time SIS token: zksync:0x0A92eddA23512C32870d8cA3b99115cafED958a9

**Comment by la1234512345** [comment]
Hi team, all tokens here have appeared in the Safe already. Closing this ticket
