### ISSUE TITLE
Nested safe --owner safe can't connect using native integration with walletconnect on Polygon 

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#317]
### Issue Category

Other

### What happened?

User can't connect the owner safe via native integration with walletconnect on Polygon network. After pasting the walletconnect code on the owner safe, nothing happens, it's just stuck and it doesn't connect to the client safe: 
![image](https://github.com/5afe/safe-support/assets/114005210/f4103bd5-901a-44d0-a388-acdce0b260ce)
![image](https://github.com/5afe/safe-support/assets/114005210/c655942e-9bbd-408c-a8c6-2b77f29133a7)

Already tried basic troubleshooting steps and tried different browsers but issue still persists. I am also able to replicate the issue on my end.

Client safe address: https://app.safe.global/home?safe=matic:0x624384d763a57985809D6383c21D708C9C64c572
Owner safe address: https://app.safe.global/home?safe=matic:0x8864E55bAaC34Fd91070B0DB5f9cAdf43360EFd0

### Date and time this happened or you first noticed this issue

31-10-2023

### Network

Polygon

### Safe Address

matic:0x624384d763a57985809D6383c21D708C9C64c572

### Token Type

None

**Comment by katspaugh** [comment]
@liliya-soroka have you tried connecting Safe to Safe?

**Comment by liliya-soroka** [comment]
hm, yes we tired and @francovenica rechecked yesterday.

**Comment by Claire-serveth** [comment]
Another user having the same issue but on ETH network.

Client safe address: https://app.safe.global/settings/setup?safe=eth:0x87AcDD9208f73bFc9207e1f6F0fDE906bcA95cc6
Owner safe address: https://app.safe.global/settings/setup?safe=eth:0xA2A855Ac8D2a92e8A5a437690875261535c8320C

**Comment by liliya-soroka** [comment]
@Claire-serveth , could you ensure that 2 different browsers or 2 different browser sessions are used in the case of native WC +safe-as-an-owner?
@katspaugh , there is a problem only when the app is used in two tab, I will bring it to our board to discuss.
But in general, I recommend using two different browsers for the connection instead of two tabs in the same browser under the same session for the safe-as-an-owner option

**Comment by Claire-serveth** [comment]
Hi @liliya-soroka oh, I haven't thought of using 2 different browsers (only 2 tabs), but let me check on my end first before I relay to users. Thank you 🙏

**Comment by liliya-soroka** [comment]
the issue about using WC+safe-as-an-owner in 2 tabs of the same browser( same session) - https://github.com/safe-global/safe-wallet-web/issues/2719
