### ISSUE TITLE
[iOS] Safe mobile app doesn’t connect to trust wallet 

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#318]
### Issue Category

Other

### What happened?

User is trying to connect safe mobile app to trustwallet via walletconnect to sign transaction but it doesn't open trustwallet rather it redirects to safari browser: 
![image](https://github.com/5afe/safe-support/assets/114005210/78371a80-ad8a-4523-8f43-b95fbbe8e88b)

Details:

Safe mobile app version: 3.24.1
Device OS and version: Iphone 13 mini, iOS 16.5.1
Trustwallet app version: 10.1 (827
Safe address: eth:0x792395E3d5129FfCA8449d47EE7C8c4aE089E7DD

### Date and time this happened or you first noticed this issue

01-11-2023

### Network

Ethereum Mainnet

### Safe Address

eth:0x792395E3d5129FfCA8449d47EE7C8c4aE089E7DD

### Token Type

None

**Comment by 0xJem** [comment]
Facing this too - it's an annoyance

**Comment by Claire-serveth** [comment]
> Facing this too - it's an annoyance

Hi there, we already have the feedback from our devs and this issue should be fixed in the upcoming 3.24.2 release. Let's wait for the updates to be live on the safe mobile app [iOS] in 2 weeks. Closing this issue now. All the best to you and have a nice day! 🙏
