### ISSUE TITLE
Transactions in Queue/History displays as a contract interaction instead of a normal Send

### ISSUE THREAD

**Issue by shebeengs** [5afe/safe-support#32]
### Issue Category

Other

### What happened?

Sending WILD token (ERC-20) and NFTs displays as a contract interaction instead of a normal Send transaction in Queue/History. User is only sending these tokens via **New transaction** > **Send funds** or **Send NFT**

![image](https://user-images.githubusercontent.com/54754746/195154805-38514fe5-2733-4cd3-8744-3107131ae48b.png)
![image](https://user-images.githubusercontent.com/54754746/195155555-5350867e-fd9b-4ad6-8306-347fb0d548a0.png)

### Date and time this happened or you first noticed this issue

10-12-2022 1:03:02 GMT +8

### Network

Ethereum Mainnet

### Safe Address

0x053387FE5c3d990510C0069842c4C77069aDBc55

### Token Address

0x2a3bFF78B79A009976EeA096a51A948a3dC00e34

### Token Type

ERC20

### Transactions

```shell
https://etherscan.io/address/0x2a3bFF78B79A009976EeA096a51A948a3dC00e34
https://etherscan.io/address/0xE7AFFEF46e237991D2f21c1b359EF7fE5DA2f76d
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by liliya-soroka** [comment]
https://safe-client.gnosis.io/v1/chains/1/safes/0x053387FE5c3d990510C0069842c4C77069aDBc55/transactions/history  - custom tx on prod CGW  and outgoing on staging CGW https://safe-client.staging.5afe.dev/v1/chains/1/safes/0x053387FE5c3d990510C0069842c4C77069aDBc55/transactions/history

**Comment by shebeengs** [comment]
Thank you. Should we expect this to be fixed in the next update?

**Comment by mikhailxyz** [comment]
@shebeengs Liliya just left a note for developers who will debug the issue. We're still looking into it :)

**Comment by Uxio0** [comment]
> https://safe-client.gnosis.io/v1/chains/1/safes/0x053387FE5c3d990510C0069842c4C77069aDBc55/transactions/history - custom tx on prod CGW and outgoing on staging CGW https://safe-client.staging.5afe.dev/v1/chains/1/safes/0x053387FE5c3d990510C0069842c4C77069aDBc55/transactions/history nonce: 266,

Tx service correctly shows transfers inside transactions

**Comment by la1234512345** [comment]
@fmrsabino 
Having a similar issue here with USDC in ETH network
https://gnosis-safe.io/app/eth:0x755F60a301E070d09137bc4cFf0cBEabF5722ae6/transactions/history

![image](https://user-images.githubusercontent.com/114544040/198930020-2f1d3e0f-129b-4f60-9ef8-dac2bd47c206.png)

**Comment by Sherie15** [comment]
Another user is experiencing the same issue. USDC transfer shows Contract interaction from the transaction history.

https://gnosis-safe.io/app/eth:0xC231F1865A706b41182D131F5bA40e2372d9fc51/home

![image](https://user-images.githubusercontent.com/113986185/198945684-e41e317f-e20d-45aa-87df-aa4e1c856b8c.png)

**Comment by fmrsabino** [comment]
> Another user is experiencing the same issue. USDC transfer shows Contract interaction from the transaction history.
> 
> https://gnosis-safe.io/app/eth:0xC231F1865A706b41182D131F5bA40e2372d9fc51/home
> 
> ![image](https://user-images.githubusercontent.com/113986185/198945684-e41e317f-e20d-45aa-87df-aa4e1c856b8c.png)

I just checked but this Safe has no transactions. Wrong link?

**Comment by fmrsabino** [comment]
> > > Another user is experiencing the same issue. USDC transfer shows Contract interaction from the transaction history.
> > > https://gnosis-safe.io/app/eth:0xC231F1865A706b41182D131F5bA40e2372d9fc51/home
> > > ![image](https://user-images.githubusercontent.com/113986185/198945684-e41e317f-e20d-45aa-87df-aa4e1c856b8c.png)
> > 
> > 
> > I just checked but this Safe has no transactions. Wrong link?
> 
> Sorry about that. This is the correct safe - https://gnosis-safe.io/app/eth:0xeD1Dcb4e91522b55F905Ac78D23Dea560A95c7B3/transactions/history

No problem! Thank you for the link!

**Comment by katspaugh** [comment]
@CindyLo0 could you close this issue and open a new one, please?
This one is really old (the screenshot is from the old app, not supported anymore), and has lots of comments that might not be relevant anymore.
