### ISSUE TITLE
Users in various networks can't execute transactions (Execute button greyed out)

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#321]
### Issue Category

Transaction execution issue

### What happened?

Users in various networks--so far ETH, Polygon, BNB, Base cannot execute transactions. Execute button is greyed out even after basic troubleshooting steps--clearing cache, cookies and hard refresh.

Safe addresses:
https://app.safe.global/transactions/queue?safe=eth:0x39e4fac1A21AE1D8c76B0ac52aC0417398fE738d
https://app.safe.global/transactions/history?safe=matic:0x2dFEdAB1bCc0670eB4F03EFA305C14E50E41ED4d
https://app.safe.global/transactions/queue?safe=matic:0xfE82fEAD341F3c8293C9e64a5D0682Ce34ca51f7
https://app.safe.global/home?safe=matic:0x7eeedCf927309AA27410Ee3286Ea6F93Bc6BAB62
eth:0xDcA17eeDc1aa3dbB14361678566b2dA5A1Bb4C31
eth:0x39e4fac1A21AE1D8c76B0ac52aC0417398fE738d
eth:0x6B4FD234b827833dA40404de1FCf2a784d4bf033
base:0x518168022F39fED1DCB3CBf0Cec306E9fEBF10D4

### Date and time this happened or you first noticed this issue

13-11-2023

### Network

Ethereum Mainnet

### Token Type

None

**Comment by liliya-soroka** [comment]
thank you for reporting the team is informed and checking

**Comment by Claire-serveth** [comment]
> thank you for reporting the team is informed and checking

Thank you so much @liliya-soroka 🙏

**Comment by katspaugh** [comment]
A fix is live now.

**Comment by Claire-serveth** [comment]
> A fix is live now.

Thank you so much @katspaugh 🙏 will check with the user for now before closing this issue.
