### ISSUE TITLE
[iOS] Cannot connect Argent wallet, Trustwallet, Metamask via WalletConnect

### ISSUE THREAD

**Issue by phoebe-serveth** [5afe/safe-support#322]
### Issue Category

Other

### What happened?

Getting a "Failed to start connection" error when connecting Argent wallet, Metamask and Trustwallet via walletconnect.
User also mentioned that they tried other types of wallets listed on the screenshot as well and getting the same error. Already restarted device but still the same error.

Safe mobile app version: 3.24.1 (1972)
Device: iPhone 13 Pro Max
iOS version: 17.0.3

![IMG_3082](https://github.com/5afe/safe-support/assets/114040259/6933b459-7d04-46d8-bf08-d4e6a7b13da8)

### Date and time this happened or you first noticed this issue

14-11-2023 21:00

### Network

Ethereum Mainnet

### Token Type

None

**Comment by DmitryBespalov** [comment]
@phoebe-serveth this, too, should be fixed in the upcoming 3.24.2 release

**Comment by Claire-serveth** [comment]
> @phoebe-serveth this, too, should be fixed in the upcoming 3.24.2 release

Thank you @DmitryBespalov 🙏

**Comment by Claire-serveth** [comment]
Will wait for the release and closing this issue now.
