### ISSUE TITLE
Cannot propose a new transaction in iOS safe mobile app via walletconnect (Error 422422)

### ISSUE THREAD

**Issue by phoebe-serveth** [5afe/safe-support#323]
### Issue Category

Transaction execution issue

### What happened?

Getting an error when proposing a new transaction (Send transaction) It redirects to metamask app but no option to sign and when going back to the safe mobile app, user get this error (see screenshot)
![IMG_4565](https://github.com/5afe/safe-support/assets/114040259/ee3a44ee-8636-4aa4-b990-303d357bfaf7)

When using the webapp within the same mobile device, same behavior but getting this error below, 
![IMG_4568](https://github.com/5afe/safe-support/assets/114040259/87a67547-0e15-496d-81ad-c6d695560a5a)

User has no access to a desktop upon troubleshooting, unable to test using webapp on a desktop browser.

Safe mobile app version: 3.24.1 (1972)
Device: iPhone 11 Pro Max
iOS version: 16.6.1

### Date and time this happened or you first noticed this issue

15-11-2023 01:20

### Network

Ethereum Mainnet

### Token Type

None

**Comment by DmitryBespalov** [comment]
@phoebe-serveth please let the users know that we're on this issue and it's going through final rounds of testing. I expect the release within two weeks

**Comment by Claire-serveth** [comment]
> @phoebe-serveth please let the users know that we're on this issue and it's going through final rounds of testing. I expect the release within two weeks

Hi @DmitryBespalov phoebe is currently offline but I already informed the user. Thank you so much for the update. 🙏

**Comment by Claire-serveth** [comment]
Will wait for the release and closing this issue now.
