### ISSUE TITLE
User cannot open CSV Airdrop Safe App (Optimism)

### ISSUE THREAD

**Issue by inahlikenoother** [5afe/safe-support#324]
### Issue Category

Other

### What happened?

When user opens the CSV Airdrop Safe app, it gives an error in the console 

Google Chrome:
![image](https://github.com/5afe/safe-support/assets/114049495/ae1a5934-2839-43f9-a6ea-2d88829515be)

Firefox:
![image](https://github.com/5afe/safe-support/assets/114049495/751231db-6eb6-45e9-a4c0-8156bb5c558c)
![image](https://github.com/5afe/safe-support/assets/114049495/e9f316e7-04ba-4b89-a3c3-3b83d07eebb7)

User also tried using a personal hotspot, and behavior is the same. User is not using VPN, and this only happened today. Other Safe apps are working fine on his end.

If I load user's Safe on my browser, and open CSV Airdrop, it works fine.
![image](https://github.com/5afe/safe-support/assets/114049495/06e1d150-9551-44b8-af5b-aede659d4842)

### Date and time this happened or you first noticed this issue

15-11-2023 11:16

### Network

Optimism

### Safe Address

0x70ad50958312814e7370A52BDa2b5DA797ab64Bc

### Token Type

None

**Comment by liliya-soroka** [comment]
There is no problem with the app opening on my side as well. However, I have asked the team if any tips can help the user.
As I understand usual tip with hard refresh did not help , right ?

**Comment by inahlikenoother** [comment]
> There is no problem with the app opening on my side as well. However, I have asked the team if any tip can help the user. As I understand, the usual tip with hard refresh did not help, right ?

Yes, didn't help, also with multiple browsers and using personal Hotspot. :/

**Comment by liliya-soroka** [comment]
could the user open “Sablier V1” ? It’s hosted the same way as CSV airdrop.
If the user is not able to open Sablier v1 app as well, most likely either Cloudflare is blocking the user for some reason (location, used IP, whatever) or the internet provider/country where the user is located is blocking access to Cloudflare IPFS.
Unfortunately, we can not do anything on our side with this issue

**Comment by inahlikenoother** [comment]
> Could the user open “Sablier V1” ? It’s hosted the same way as CSV airdrop. If the user cannot open the Sablier v1 app as well, most likely, either Cloudflare is blocking the user for some reason (location, used IP...), or the internet provider/country where the user is located is blocking access to Cloudflare IPFS. Unfortunately, we can not do anything on our side with this issue.

Thank you! Will let the user know 🙏
