### ISSUE TITLE
Can't sign transaction using Argent wallet.

### ISSUE THREAD

**Issue by jakekvm01** [5afe/safe-support#325]
### Issue Category

Transaction execution issue

### What happened?

![image](https://github.com/5afe/safe-support/assets/105864754/6d4cd663-5b9c-4a7e-84f8-a05d372c28b3)

Can't sign transaction using Argent wallet. User was currently using Android Argent app via Wallet Connect with Safe web app on PC browser.
- Done basic troubleshooting and using other browsers.
- Make sure also that both web and mobile app are in the same network.
- Disconnect and Re-connect the wallet.

![image](https://github.com/5afe/safe-support/assets/105864754/5d5e69d1-da08-4713-91f4-b13bd9b598f0)
![image](https://github.com/5afe/safe-support/assets/105864754/e3b6d667-1fd1-492b-9a17-ed68c677c5c2)

Dev console logs:
![image](https://github.com/5afe/safe-support/assets/105864754/6eef6b4e-fe48-41c3-9d1b-f2bf13f77377)

### Date and time this happened or you first noticed this issue

N/A

### Network

Ethereum Mainnet

### Safe Address

eth:0xE7594d92f7bE2e7e0645F0c43Fd07ebd4Aba2eDd

### Token Address

N/A

### Token Type

None

**Comment by katspaugh** [comment]
The same was happening with the 1inch wallet until it was fixed on their side. Something about how the Swift SDK for WalletConnect orders chains. Instead of mainnet, it picks one of the optional chains.

**Comment by Claire-serveth** [comment]
> The same was happening with the 1inch wallet until it was fixed on their side. Something about how the Swift SDK for WalletConnect orders chains. Instead of mainnet, it picks one of the optional chains.

Hi @katspaugh so it needs to be fixed on the wallet's side. Thank you so much for the update; I'll go ahead and close this issue now. 🙏
