### ISSUE TITLE
iOS Error: Failed to create transaction. Network request failed with an unexpected error. Please try again later. (Error 422422) 

### ISSUE THREAD

**Issue by inahlikenoother** [5afe/safe-support#330]
### Issue Category

Other

### What happened?

When user tries to initiate a send transaction in the iOS Safe mobile app, it gives an error 
![IMG_1551](https://github.com/5afe/safe-support/assets/114049495/17a8e69f-07f1-4e5a-b0a8-663143a419a9)

User's safe mobile app is not in Read only mode and they already imported owner keys. User said this was working previously, and they updated their Safe mobile app 2 days ago, and now they're experiencing this issue. Another owner also tried to initiate the tx using his own device (iOS as well) and also get this error. 

User tried on Web app and it works fine, they were able to initiate the send transaction. Tx was successfully submitted on the web app and it shows in Queue tab, but checking the transaction in the Safe mobile app gives another error "Failed to load transaction" a similar issue reported in https://github.com/5afe/safe-support/issues/327 
![IMG_1554](https://github.com/5afe/safe-support/assets/114049495/a28220bd-8604-4bf9-828e-c76638c4618e)

IOS version 16.6.1
Safe mobile app version 3.24.2

### Date and time this happened or you first noticed this issue

20-11-2023 10:58

### Network

Ethereum Mainnet

### Safe Address

0x001d2D93B3758FBe792E329cca5Cd579a105EE96

### Token Type

None

**Comment by liliya-soroka** [comment]
checking

**Comment by inahlikenoother** [comment]
> checking

Thank you. :pray:  Also, additional context - when user initiated the tx from the Web app, it's successful and it shows in the queue tab, but when checking the Transactions tab in the safe mobile app, it gives error "Failed to load transaction", a similar issue reported here https://github.com/5afe/safe-support/issues/327

**Comment by DmitryBespalov** [comment]
@inahlikenoother we checked and saw that we could open the tx details now. Is this issue still persists?

**Comment by inahlikenoother** [comment]
> @inahlikenoother we checked and saw that we could open the tx details now. Is this issue still persists?

User responded and said that he can open the tx details now on the Safe mobile app, however, he's unable to sign it as it gives the same error " Failed to load tx details " 
Also, initiating a tx from the Safe mobile app still gives the same error as well "Failed to create transaction"

**Comment by liliya-soroka** [comment]
Please, take into account that if the MM mobile app is used for the tx creation, signing , there is an issue with signature from the MM mobile app - https://github.com/MetaMask/metamask-mobile/issues/7792
