### ISSUE TITLE
[iOS] can't connect to Trust wallet (stuck at connecting) 

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#331]
### Issue Category

Safe loading issue, doesnt load on any interface

### What happened?

User is still having issues connecting to trust wallet on the safe mobile app--it never connects and only got stuck at connecting: 

iOS 17.1.1 (iPhone 13 Pro)
Safe App version 3.24.2 (1975)
Trust Wallet ver. 10.2 (838)

![image](https://github.com/5afe/safe-support/assets/114005210/4125011f-6aa6-41de-b19a-162dba5a6541)

### Date and time this happened or you first noticed this issue

21-11-2023

### Network

Polygon

### Token Type

None

**Comment by liliya-soroka** [comment]
It might be related to https://github.com/safe-global/safe-ios/issues/3365 . 
I will include Trust Wallet in the tests when the migration to wc v2 will be done for the keys in the mobile app.
Please, follow the ticket on the mobile board

**Comment by Claire-serveth** [comment]
> It might be related to [safe-global/safe-ios#3365](https://github.com/safe-global/safe-ios/issues/3365) . I will include Trust Wallet in the tests when the migration to wc v2 will be done for the keys in the mobile app. Please, follow the ticket on the mobile board

Thank you @liliya-soroka will relay this to the user and follow the related issue instead. I'll go ahead and close this issue now.
