### ISSUE TITLE
[ETH] Multiple transactions executed in the same nonce 89, 92 and 94

### ISSUE THREAD

**Issue by Sherie15** [5afe/safe-support#342]
### Issue Category

Other

### What happened?

The user is not familiar with this address **_eth:0xc345d32B985f739DF53eA4541bEe6FdE5C973AE9_**

![image](https://github.com/5afe/safe-support/assets/113986185/55bd2db2-87ad-4421-9f6a-bd22145dbc21)
![image](https://github.com/5afe/safe-support/assets/113986185/561cca3e-da86-4a1e-8c01-c912e5fabca4)
![image](https://github.com/5afe/safe-support/assets/113986185/99d27a0c-57de-4e60-9d45-7d0e57f83388)

### Date and time this happened or you first noticed this issue

02-12-2023 05:49am

### Network

Ethereum Mainnet

### Safe Address

eth:0xE38F85D5C174D472282695eEDb45195D98206C3d

### Token Type

None

**Comment by tiechou** [comment]
I am is not familiar with this address  eth:0xc345d32B985f739DF53eA4541bEe6FdE5C973AE9, but I transfer USDT to this address because of my oversight  in Nonce 94
I confuse why appear two address in nonce 89, and they look a little similar.

**Comment by Sherie15** [comment]
Closed GitHub ticket as user was a victim of >>> https://support.metamask.io/hc/en-us/articles/11967455819035-Address-poisoning-scams
