### ISSUE TITLE
[Polygon zkEVM] Receiving error when using Transaction Service "Problem connecting to Ethereum network" "NodeConnectionException"

### ISSUE THREAD

**Issue by phoebe-serveth** [5afe/safe-support#345]
### Issue Category

Safe loading issue, doesnt load on any interface

### What happened?
Receiving error when using transaction service in Polygon zkEVM
exception: "Problem connecting to Ethereum network
trace: "NodeConnectionException"

https://safe-transaction-zkevm.safe.global/api/v1/safes/0xf58a6C2E3AFD2240b2Bc46751114566eA55671B0/
![image](https://github.com/5afe/safe-support/assets/114040259/4689ca55-722e-45b1-bc1b-a9e32049f1de)

Other safes does not load in the interface as well.
![image](https://github.com/5afe/safe-support/assets/114040259/6092f279-2796-4528-9246-d2acc6192990)

### Date and time this happened or you first noticed this issue

05-12-23 16:48:44

### Network

Polygon zkEVM

### Token Type

None

**Comment by DefiDebauchery** [comment]
Any updates on this? Not having access to any of our Safes is pretty limiting.

**Comment by liliya-soroka** [comment]
The underlying RPC is having issues. Until this is resolved, we do expect issues to occur.
Unfortunately, a timeline is undefined for now.
The team is on it

**Comment by DefiDebauchery** [comment]
Could you change the configured RPC? It looks like it's defined for a local cluster, but public RPCs could at least help you catch up to HEAD and allow people to use it.

**Comment by mmv08** [comment]
> Could you change the configured RPC? It looks like it's defined for a local cluster, but public RPCs could at least help you catch up to HEAD and allow people to use it.

We have a specific set of requirements for RPCs in terms of rate limits, batch transaction support, etc. Unfortunately, there are no other nodes available for polygon zkEVM. We contacted the polygon team and are waiting for the resolution.

**Comment by liliya-soroka** [comment]
Incoming txs with "untrusted" tokens are hidden - https://github.com/safe-global/safe-client-gateway/pull/910.
The team is working on more user-friendly solution https://github.com/safe-global/safe-wallet-web/issues/2991

**Comment by DefiDebauchery** [comment]
Service to zkEVM seems to have been restored; can you confirm that it should now be stable?

**Comment by Uxio0** [comment]
Yes, everything should be stable now, I'm closing this. We are also working in finding and evaluating backup RPCs so this doesn't happen again
