### ISSUE TITLE
Cannot load safe on Polygon zkEVM

### ISSUE THREAD

**Issue by inahlikenoother** [5afe/safe-support#348]
### Issue Category

Safe loading issue, doesnt load on any interface

### What happened?

User cannot load Safe on any browsers
![image](https://github.com/5afe/safe-support/assets/114049495/092bf890-6c4f-48ee-a4c5-dbfc712fbf17)

### Date and time this happened or you first noticed this issue

12-0702023

### Network

Polygon zkEVM

### Safe Address

0x02468e288890C04457964BbAa7B1bf966bC75d47

### Token Type

None

**Comment by liliya-soroka** [comment]
same as here - https://github.com/5afe/safe-support/issues/346

**Comment by inahlikenoother** [comment]
> same as here - #346

Thank you! Will close this one as duplicate
