### ISSUE TITLE
Execute buttons unresponsive; cannot execute transaction [Optimism network]

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#350]
### Issue Category

Transaction execution issue

### What happened?

User was not able to execute transaction since execute buttons are greyed out--both current and succeeding nonces. I also tried to impersonate the owner's address and was able to replicate the issue. 

Safe address: https://app.safe.global/transactions/queue?safe=oeth:0x7A352a3E85b7485B22DCb914216e27fCD3ce588F

![image](https://github.com/5afe/safe-support/assets/114005210/6bb4f57d-743a-46f6-b259-b233dbb9b41b)

### Date and time this happened or you first noticed this issue

12-12-2023

### Network

Optimism

### Safe Address

oeth:0x7A352a3E85b7485B22DCb914216e27fCD3ce588F

### Token Type

None

**Comment by usame-algan** [comment]
Thanks for reporting! Looks like some RPC requests return 502. There is a partial outage on infura for optimism: https://status.infura.io/

**Comment by Claire-serveth** [comment]
> Thanks for reporting! Looks like some RPC requests return 502. There is a partial outage on infura for optimism: https://status.infura.io/

Thank you @usame-algan I was able to check infura's status earlier (before creating the issue) but there's no warning yet, so I thought it was beyond that. But thank you so much for the update 🙏 I'll go ahead and close this issue now.
