### ISSUE TITLE
Could not detect network error while confirming transaction [BNB chain]

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#352]
### Issue Category

Transaction execution issue

### What happened?

User was not able to initiate transaction since he gets "could not detect" error while confirming the transaction: 
![image](https://github.com/5afe/safe-support/assets/114005210/4f10c214-c6ce-49a7-81aa-dcd9632ae7b6)

Already did basic troubleshooting steps (and double checked it's the right account connected on metamask) but issue still persists. Safe address: https://app.safe.global/settings/setup?safe=bnb:0x4E2B8e08f725B8FEEAbd9be30dc811e979F30bA4

### Date and time this happened or you first noticed this issue

15-12-2023

### Network

Binance Smart Chain

### Safe Address

bnb:0x4E2B8e08f725B8FEEAbd9be30dc811e979F30bA4

### Token Type

None

**Comment by Sherie15** [comment]
Hi team, another user reported the same error message. 
![image](https://github.com/5afe/safe-support/assets/113986185/3794b6d3-cb3b-45dc-a7b9-98f0b10c1a11)

**Comment by liliya-soroka** [comment]
reported to the team - https://github.com/safe-global/safe-wallet-web/issues/3046

**Comment by Claire-serveth** [comment]
> reported to the team - [safe-global/safe-wallet-web#3046](https://github.com/safe-global/safe-wallet-web/issues/3046)

Thank you @liliya-soroka 🙏

**Comment by mmv08** [comment]
I debugged the same issue someone reported to me privately. For some reason, my browser blocked the request to the RPC (https://bsc-dataseed.binance.org). It could've been an ad blocker or something similar. The RPC was accessible outside the browser from my computer. I could fix this in three ways:
1. Add a different rpc URL in `Settings > Environment variables`
2. Use a different browser with no ad blocker
3. Use an incognito mode

**Comment by Claire-serveth** [comment]
Thank you @mmv08 🙏 already shared this with the user and took note of the workarounds. We'll also follow the github link shared by liliya for the progress. Closing this ticket now.
