### ISSUE TITLE
[iOS] Are signing keys stored in the cloud or locally?

### ISSUE THREAD

**Issue by CindyLo0** [5afe/safe-support#354]
### Issue Category

Other

### What happened?

Hi team. Help center article did not specifically say if signing keys are stored in the cloud or locally and a user wants to confirm. 
https://help.safe.global/en/articles/40829-how-signer-keys-are-stored

### Date and time this happened or you first noticed this issue

17-12-2023

### Network

Ethereum Mainnet

### Token Type

None

**Comment by mmv08** [comment]
This is mentioned in the help center:
> iOS
Signing keys are stored in the native iOS Keychain Services, as recommended by Apple. The keychain ensures that only the Safe app can access your keys. Please refer to the [Keychain Services Developer Documentation](https://developer.apple.com/documentation/security/keychain_services) for all details.

iOS Keychain is a local key storage.

**Comment by bingclo** [comment]
Hi @mmv08 followup question from the user 🙏 
> in iphone backups it still shows an option to backup Safe app data - what is it backing up there? just the safe names and signer names

**Comment by DmitryBespalov** [comment]
@bingclo the keys are stored locally on the phone. If the phone is backed up via computer they'll be backed up, too. However, they will not be restored if user chooses iCloud backup.

**Comment by bingclo** [comment]
I see. Thank you 🙏
