### ISSUE TITLE
"Anonymous login to Intercom Failed" comes up everytime when opening Safe Mobile App (iOS)

### ISSUE THREAD

**Issue by inahlikenoother** [5afe/safe-support#359]
### Issue Category

Other

### What happened?

User gets this error every time when opening the Safe Mobile app (iOS). It goes away after a while, but when opening the app again, it comes up again.
![IMG_4841](https://github.com/5afe/safe-support/assets/114049495/12fbe960-9c7e-4eb8-9f1b-ffad6efc82cb)
User's iOS version:  iOS 17.1.2
User's Safe Mobile app version: 3.24.2

I'm also getting the same behavior
![image](https://github.com/5afe/safe-support/assets/114049495/524a47f8-ac0c-400d-940b-f9c1c7dcb715)
My iOS version: 17.0.2
Safe Mobile app version: 3.24.2

### Date and time this happened or you first noticed this issue

21-12-2023

### Network

Ethereum Mainnet

### Safe Address

0x18eCA2Ef92a15CF155dA9EeFb502d518488b4d1c

### Token Type

None

**Comment by liliya-soroka** [comment]
Please check the message on Discord in the support channel. 
This is expected till the next release. We will release 3.25.0 as soon as possible

**Comment by inahlikenoother** [comment]
> Please check the message on Discord in the support channel. This is expected till the next release. We will release 3.25.0 as soon as possible

Thank you, Liliya!
