### ISSUE TITLE
[BSC] Untrusted transaction alert on executed transaction

### ISSUE THREAD

**Issue by joanpan** [5afe/safe-support#360]
### Issue Category

Safe loading issue, doesnt load on any interface

### What happened?

User is seeing "Untrusted transaction" alert on executed transaction: https://app.safe.global/transactions/tx?safe=bnb:0x7E42186E3a95a673734B8D2eEaB8c6db0298FB24&id=multisig_0x7E42186E3a95a673734B8D2eEaB8c6db0298FB24_0x020e0cf627ce367d9dd05029db6efbe03d4862977602b3e6b88e145ce2bb1618

Do you have any insights into the reason behind this issue? The user also mentioned a delay in transaction proposals being posted in the queue.
![image](https://github.com/5afe/safe-support/assets/114049668/5ca5223c-4977-4d8b-ac1c-07aa46d7fc14)

### Date and time this happened or you first noticed this issue

22-12-2023

### Network

Binance Smart Chain

### Safe Address

0x7E42186E3a95a673734B8D2eEaB8c6db0298FB24

### Token Type

None

**Comment by liliya-soroka** [comment]
thank you for reporting, the team is informed.
The tx status is not updated on the CGW side - https://safe-client.safe.global/v1/chains/56/safes/0x7E42186E3a95a673734B8D2eEaB8c6db0298FB24/transactions/queued
But the ts is successfully executed on-chain

**Comment by liliya-soroka** [comment]
The team is working on the fix for the delay problem for all networks - https://github.com/safe-global/safe-client-gateway/issues/893

**Comment by KriptoQraf** [comment]
I also have the same problem - indexing on the Binance Smart Chain network occurs with a delay of several hours.

**Comment by liliya-soroka** [comment]
The BSC chain's ongoing issues should be solved now. It was chain-specific. Could you check with the users and ping us if it is still an issue on BSC
It was different from the issue the team is working on in the https://github.com/safe-global/safe-client-gateway/issues/893
