### ISSUE TITLE
[BASE] - Transaction Service Down

### ISSUE THREAD

**Issue by DefiDebauchery** [5afe/safe-support#362]
### Issue Category

Safe loading issue, doesnt load on any interface

### What happened?

On Base, any TXS calls that require a blockchain connection are returning an HTTP 500 error (vs a simple connection error)

e.g. https://safe-transaction-base.safe.global/api/v1/safes/0x1A07DceEfeEbBA3D1873e2B92BeF190d2f11C3cB/balances/

### Date and time this happened or you first noticed this issue

12-23-2023 06:00

### Network

Base

### Safe Address

0x1A07DceEfeEbBA3D1873e2B92BeF190d2f11C3cB

### Token Type

None

**Comment by DefiDebauchery** [comment]
Seems to have fixed itself for the moment, but I almost made a similar post a few days ago; it's been unstable compared to other chains.

**Comment by JagoFigueroa** [comment]
Hi there! Any further issues on Base since last time? We have been monitoring the chain and the tx-service has been stable the last few days. Feel free to close the ticket if that's the case 😄

**Comment by DefiDebauchery** [comment]
Haven't directly seen any issues since this was reported. Closing for now.
