### ISSUE TITLE
[Sepolia] Signing message Failed 500: an error occured

### ISSUE THREAD

**Issue by Sherie15** [5afe/safe-support#365]
### Issue Category

Other

### What happened?

The user cannot sign a message for **https://dev.fxhash-dev.xyz/** is on Sepolia but successful for **https://www.fxhash.xyz/** is on mainnet. 

- Metamask
- Chrome and Firefox

![image](https://github.com/5afe/safe-support/assets/113986185/2f60b44e-10c5-461c-98f1-3f4cdcd18b3d)
![image](https://github.com/5afe/safe-support/assets/113986185/5cab86bd-636c-44ff-8ff2-d58b3e85160d)

### Date and time this happened or you first noticed this issue

05-01-2023 12:09 PM

### Network

Goerli

### Safe Address

0x3Ba3A2B6723713A2183c0C05a30AE1f858304506

### Token Type

None

**Comment by liliya-soroka** [comment]
could you re-check, please? I can not reproduce 500 error
