### ISSUE TITLE
[Polygon] Transaction stuck at processing but not visible to other owners

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#366]
### Issue Category

Safe loading issue, doesnt load on any interface

### What happened?

One of the safe owners initiated/confirmed the transaction, which was stuck at processing (safe transaction hash: 0x97f5241c286f13a31177a4032f9ef29c7a4d720187039e21b0396ae383bfdae5) although submitted, it's not visible to the other owners even though 2 days had passed:

![image](https://github.com/5afe/safe-support/assets/114005210/918e9413-ae61-4c7f-bc70-cd1181daf1bb)

Safe address: https://app.safe.global/transactions/queue?safe=matic:0x5D17a47da8F343B1E35D500D1d1feAB42f8f75A8

Are the blocks being behind caused the transaction to be stuck?

![image](https://github.com/5afe/safe-support/assets/114005210/6621ce09-e8ba-448d-89b1-8b102aa1dc92)

### Date and time this happened or you first noticed this issue

08-01-2024

### Network

Polygon

### Token Type

None

**Comment by liliya-soroka** [comment]
The TX is untrusted. This is the reason why it's not displayed on UI
Do we have any details on how the TX was created?
![image](https://github.com/5afe/safe-support/assets/338622/e87e44c4-52ae-4f45-8326-83e1b702bfd3)

**Comment by Claire-serveth** [comment]
Hi @liliya-soroka I believe it's from request finance app but I can double check with the user and get back to you. 🙏

**Comment by Claire-serveth** [comment]
@liliya-soroka already got a response from the user:

"The transaction was created from Request Finance app.
It's available on most networks that are supported by Safe, and listed in the app Safe menu for all of these chains.
Several transaction are created using this app everyday and we never had this problem.

What's is weird is that this transaction was displayed at some point in the Safe UI as "processing"

And it was displayed as "processing" for more than 10 hours." (screenshot was taken few days ago)

![image](https://github.com/5afe/safe-support/assets/114005210/92f55def-9dbc-41bd-875c-9ec58c45e54d)

**Comment by katspaugh** [comment]
That's the correct behavior, in 1/X Safes an immediately executed tx has no signatures and thus can be visible to others only via a direct link.

As for it beign stuck, they could try re-submitting it via their wallet (not via the Safe UI) with higher gas.

**Comment by Claire-serveth** [comment]
Hi @katspaugh thank you, already relayed this to the user. Will wait for his response for now in case he has a follow up question. Will close this when I get the confirmation from the user.

**Comment by Claire-serveth** [comment]
Hello @katspaugh the explanation was already clear to the user; closing this ticket now. Thanks again 🙏
