### ISSUE TITLE
Cannot add Ledger Nano X owner key when creating a new Safe in iOS

### ISSUE THREAD

**Issue by phoebe-serveth** [5afe/safe-support#367]
### Issue Category

Other

### What happened?

User cannot proceed with creating a new safe using Ledger Nano X in iOS safe mobile app. Keep saying "Key not set" even after setting up owner key via Bluetooth. It works when using the safe webapp only.
![image](https://github.com/5afe/safe-support/assets/114040259/2c90d3f9-f266-4bbb-bbd3-792f16a94a99)

Safe mobile app version: 3.25.0
iOS version: 17.0.2

### Date and time this happened or you first noticed this issue

11-01-2024 10:00

### Network

Ethereum Mainnet

### Token Type

None

**Comment by liliya-soroka** [comment]
This is expected behaviour , because execution with Ledger Nano X is not available in the mobile app

**Comment by phoebe-serveth** [comment]
I see, will update the user. Closing this as completed :) Thanks @liliya-soroka
