### ISSUE TITLE
[MATIC] Delay issue / transaction stuck processing

### ISSUE THREAD

**Issue by joanpan** [5afe/safe-support#368]
### Issue Category

Transaction execution issue

### What happened?

The user is experiencing difficulties executing transactions as they seem to be stuck in processing for the past couple of hours.
![image](https://github.com/5afe/safe-support/assets/114049668/715ecc0e-c770-4f8b-8f29-9a2dce71dcdf)

<img width="379" alt="Screenshot 2024-01-11 at 3 47 49 PM" src="https://github.com/5afe/safe-support/assets/114049668/4d618205-241a-4090-9425-b6629e152174">

Tried different browser, change RPC - no lucl

### Date and time this happened or you first noticed this issue

12-01-2024

### Network

Polygon

### Safe Address

0xd4F254006d486688cE7515199C55266C581B949A

### Token Type

None

**Comment by katspaugh** [comment]
We're having gas issues on Polygon atm, the user can speed up the tx in their executing wallet.

**Comment by joanpan** [comment]
User was able to execute the transaction. Thank you
