### ISSUE TITLE
Transaction proposed by a delegate is not displayed in the app

### ISSUE THREAD

**Issue by mikhailxyz** [5afe/safe-support#37]
### Issue Category

Transaction missing / not visible in app or service

### What happened?

I'm testing this on mainnet, safe address is 0x71e1c244eF17516bcD1FA65db74F8F4f397e9097 and delegated address (which is not an owner) is 0x9e44554C0832151B08a37B484d7DfEada7d34Eb7. You may verify the address is delegated here https://safe-transaction-mainnet.safe.global/api/v1/delegates/?safe=0x71e1c244eF17516bcD1FA65db74F8F4f397e9097

I do all the steps suggested on the tutorial, and they all work as expected. I can confirm the used endpoints throw errors when appropriate (ie signatures not formatted correctly, wrong params, tx reverted or other) so I assume there are no errors now in the whole flow. 

The issue is that once I POST to https://safe-transaction-mainnet.safe.global/api/v1/safes/{address}/multisig-transactions/ I get a 201, but there is no tx queued on the safe.

You can see the relevant logic here:
- https://github.com/slice-so/merge-to-earn-app/blob/master/pages/api/test.ts
- https://github.com/slice-so/merge-to-earn-app/blob/master/utils/initContracts.ts
And a temp endpoint to trigger the whole flow at https://mte.slice.so/api/test (which you may see returns 201)

### Date and time this happened or you first noticed this issue

october 16 5:20PM

### Network

Ethereum Mainnet

### Safe Address

0x71e1c244eF17516bcD1FA65db74F8F4f397e9097

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mikhailxyz** [comment]
this came from discord's #api channel
https://discord.com/channels/907968493134155807/960898410037272616/1031225098801266749

**Comment by Uxio0** [comment]
As mainnet is still not migrated you should still be using https://safe-transaction.mainnet.gnosis.io/

**Comment by Uxio0** [comment]
> Used `safe-transaction-mainnet.safe.global` as `safe-transaction.mainnet.gnosis.io` was not working during these days. Now that it works I can confirm transactions are submitted correctly. Thanks!

We are not aware of any downtime on safe-transaction.mainnet.gnosis.io , but glad that it worked for you!

**Comment by DefiDebauchery** [comment]
Actually, I can also confirm an issue. POST requests to Safe Transaction Services on gnosis.io are not working, as the infra is redirecting all requests to safe.global. Since POST requests cannot be forwarded, any API calls using gnosis.io get treated like a GET request, which simply returns all transactions.

The answer is obviously for external clients to change all service URLs to the safe.global endpoints, but it would have been great to have an extended transition period where both hostnames were usable.

**Comment by Uxio0** [comment]
Hi @DefiDebauchery, during our migration we cannot do more than redirecting from the old domain to the new one. I encourage you to stay tunned to our migration and change the urls you are using as soon as we migrate: https://forum.gnosis-safe.io/t/transaction-service-migration-october-2022/1550

**Comment by Uxio0** [comment]
@DefiDebauchery Sorry, we checked and we were not using a `308` status code for redirect. Everything should be working now even if you `POST` to the old url, let us know and thanks for reporting.
