### ISSUE TITLE
ERC 721 NFT image not loading 

### ISSUE THREAD

**Issue by bingclo** [5afe/safe-support#371]
### Issue Category

Other

### What happened?

User sent CLOAKS NFT to his safe but the NFT image doesn't load. See below
![image](https://github.com/5afe/safe-support/assets/54754746/9be4894d-2ba2-4ee1-953b-01db692305e0)

On the webapp it gets stuck in loading as well: 
![image](https://github.com/5afe/safe-support/assets/54754746/ff337abd-0c33-486f-8d84-b1c146fff9ef)

The NFT image loads fine in these marketplaces
https://opensea.io/assets/ethereum/0x0c56f29b8d90eea71d57cadeb3216b4ef7494abc/11842
https://looksrare.org/collections/0x0c56f29B8D90eea71D57CAdEB3216b4Ef7494abC/11842?ref=9075509
https://rarible.com/token/0x0c56f29B8D90eea71D57CAdEB3216b4Ef7494abC:11842

### Date and time this happened or you first noticed this issue

15/01/2024 08:52:19

### Network

Ethereum Mainnet

### Safe Address

0xB099aef778f91DD93D77D7785088aD9eaDB2EDef

### Token Address

0x0c56f29b8d90eea71d57cadeb3216b4ef7494abc

### Token Type

ERC721

### Transactions

```shell
https://etherscan.io/tx/0x7235c77ae8d26c1d1557acd800e8be9f9426c93b330ef6b46cfa820e24db1dd7
```

**Comment by liliya-soroka** [comment]
This token uses a IPFS url for the image: https://ipfs.io/ipfs/QmSzn68idqk4ATRVjoToXSc6wLcxmkGMDWCyvcHvz1Ue8U/11842. We currently don't support IPFS-hosted images, and we don't plan to do that in the near future.
