### ISSUE TITLE
[Polygon] Safe webapp crashes when confirming a transaction

### ISSUE THREAD

**Issue by phoebe-serveth** [5afe/safe-support#374]
### Issue Category

Transaction execution issue

### What happened?

User is unable to confirm transaction with nonce 14 from 4 days ago. The safe webapp crashes after clicking the "confirm" button. Although new queued transactions with nonce 15 and 16 are signed/confirmed.

https://app.safe.global/transactions/queue?safe=matic:0x0E4e8EC7bd334AF73Ed8d87457007664812737Fe
![image](https://github.com/5afe/safe-support/assets/114040259/193bc21b-3b1d-4a52-9e75-dee3b23c5461)

### Date and time this happened or you first noticed this issue

23-01-2024 6:24 PM

### Network

Polygon

### Safe Address

0x0E4e8EC7bd334AF73Ed8d87457007664812737Fe

### Token Type

None

**Comment by liliya-soroka** [comment]
checking with the team ...

**Comment by phoebe-serveth** [comment]
Hi @liliya-soroka , thanks for checking on it. We're still waiting for the user's response. However, I can see that they have rejected nonce 14 and were able to execute new transactions now. Just waiting for the user to respond before closing it.
