### ISSUE TITLE
[Sepolia] Safe creation via relayer unsuccessful

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#377]
### Issue Category

Transaction execution issue

### What happened?

User was trying to create safe via relayer but getting "transaction unsuccessful" error:

![image](https://github.com/5afe/safe-support/assets/114005210/3912ef77-7c38-4e69-8be4-6dae450798b8)

### Date and time this happened or you first noticed this issue

29-01-2024

### Network

Goerli

### Token Type

None

**Comment by usame-algan** [comment]
Thanks for reporting! We just deployed a fix and it should work now

**Comment by Claire-serveth** [comment]
> Thanks for reporting! We just deployed a fix and it should work now

Thank you @usame-algan checking with the user before closing this ticket. Thank you 🙏

**Comment by Claire-serveth** [comment]
The issue is indeed fixed on user's end. Thank you so much @usame-algan 🙏 Closing this ticket now.
