### ISSUE TITLE
[ETH mainnet delay] Newly proposed transactions not showing up in queue 

### ISSUE THREAD

**Issue by phoebe-serveth** [5afe/safe-support#378]
### Issue Category

Transaction missing / not visible in app or service

### What happened?

It takes more than 10 minutes for newly proposed transactions to appear in queue. There is also a delay when signing transactions, it does not immediately appear as signed or confirmed in the UI right after signing the transaction.

### Date and time this happened or you first noticed this issue

29-01-2024 6:00 pm

### Network

Ethereum Mainnet

### Token Type

None

**Comment by la1234512345** [comment]
Hi team, multiple users have also had this same exact issue on other networks (BSC, Arbitrum)

**Comment by liliya-soroka** [comment]
thank you for reporting ,checking with the back-end team

**Comment by Sherie15** [comment]
Hi team, we have a user reporting delays on Gnosis chain. They cannot execute transactions since it is not appearing in the queue.

**Comment by JagoFigueroa** [comment]
Issue should be fixed now for all chains. Please let us know 🙏
