### ISSUE TITLE
[Ethereum] Reject transaction is shown as "Contract Interaction"

### ISSUE THREAD

**Issue by bingclo** [5afe/safe-support#379]
### Issue Category

Other

### What happened?

User clicked on Replace > Reject on a transaction but instead of "On-chain Rejection" it's shown as "Contract Interaction" (nonce 5)

![image](https://github.com/5afe/safe-support/assets/54754746/6b5d8191-dcc5-4147-a48d-39874c3719ae)

### Date and time this happened or you first noticed this issue

29-01-2024 22:39:15

### Network

Ethereum Mainnet

### Safe Address

https://app.safe.global/transactions/history?safe=eth:0x4d71Bc00b22464b62C096e1caeAb3171e6148e9a

### Token Address

NA

### Token Type

None

**Comment by liliya-soroka** [comment]
thank you for reporting. please follow https://github.com/safe-global/safe-wallet-web/issues/3171 to see the progress.

**Comment by bingclo** [comment]
Thank you @liliya-soroka 🙏
