### ISSUE TITLE
Safe desktop app installation failed on Windows 7

### ISSUE THREAD

**Issue by joanpan** [5afe/safe-support#38]
### Issue Category

Other

### What happened?

User tried installing the Safe desktop app, v3.22.1 on an old Windows 7 laptop but the installation failed. 

Is Windows 7 not supported?

### Date and time this happened or you first noticed this issue

18-10-2022

### Network

Ethereum Mainnet

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dasanra** [comment]
We are not providing support to Windows 7 as it's life cycle already ended. As last check make sure that you are using a 64 bits system, as we never provided a 32 bit compatible build but if it's not working it won't be fixed.
