### ISSUE TITLE
Getting GS026 error messages when executing transactions in Eth mainnet

### ISSUE THREAD

**Issue by bingclo** [5afe/safe-support#382]
### Issue Category

Transaction execution issue

### What happened?

User is getting GS026 errors executing transactions from the safe

![image](https://github.com/5afe/safe-support/assets/54754746/aa625dd4-1259-4c6f-8fad-03b793b926bb)

Using the last signer to execute the transaction works intermittently however expected behavior is any address should be able to execute the transaction once signatures are complete. 

### Date and time this happened or you first noticed this issue

14/02/2024 19:12:07

### Network

Ethereum Mainnet

### Safe Address

https://etherscan.io/address/0xfB889B8A33b1A5e0C46c279b6848ffEfe2BA75C7

### Token Address

NA

### Token Type

None

### Transactions

```shell
https://etherscan.io/tx/0xede4f307681fa256f5b05b2c9641ac6acb53d554281b05420be1872c7b195b73
https://etherscan.io/tx/0x8090238e83bbc75bcf423dbf9a7d8841eb499515f62e3a5923067d776d8cf0fc
https://etherscan.io/tx/0x34af0ee3ace1201db3642834e9feb785cd9b26143a7d686eabbf809c4804bd30
https://etherscan.io/tx/0x45867a3cceede82442a9f7ed2a1f26b1e5a93c7d7f65912f3a0b3cacd4402aee
https://etherscan.io/tx/0x4d3305e5ca9bab195acdc28a3d677ee5b934f8573b4c09e71a7e79c4f89928a8
https://etherscan.io/tx/0x873bf0716eda134a368c13684c2b269fc1f272a8d31d8a785a47210a2551d03a
```

**Comment by JagoFigueroa** [comment]
Hi! Thank you for the report 😄 I can see some errors in our logs around the time you reported the issue but our services look stable again. Could you recheck? It should be resolved now but if not I will share it with the team first thing tomorrow 🙏

**Comment by bingclo** [comment]
Thanks @JagoFigueroa ! I'll check with the user 🙏

**Comment by bingclo** [comment]
The user doesn't have any pending transactions at the moment so we'll close this for now. We'll reopen if the issues reoccurs 🙏
