### ISSUE TITLE
USDT tokens are not showing in the UI 

### ISSUE THREAD

**Issue by jakekvm01** [5afe/safe-support#383]
### Issue Category

Token missing completely / not visible in the interface or service

### What happened?

USDT tokens are not showing in the UI but present on etherscan.

![image](https://github.com/5afe/safe-support/assets/105864754/abf520bb-6333-46e7-ad26-a2fd0e6442f6)
![image](https://github.com/5afe/safe-support/assets/105864754/4bacd05e-2f70-4f2a-a57f-5d58d7ce9c03)

### Date and time this happened or you first noticed this issue

N/A

### Network

Ethereum Mainnet

### Safe Address

eth:0x0E9CE573e2f55A5bfcA6e5EeA32198E65a57bA93

### Token Address

0xdAC17F958D2ee523a2206206994597C13D831ec7

### Token Type

ERC20

### Transactions

```shell
https://app.safe.global/balances?safe=eth:0x0E9CE573e2f55A5bfcA6e5EeA32198E65a57bA93
```

**Comment by liliya-soroka** [comment]
checking

**Comment by johannesmoormann** [comment]
The USDT was transferred before the Safe contract was deployed (around 900 days before) and therefore the balance was not indexed properly. We should check with the team whether this is default behaviour or if it was missed when indexing the Safe.

**Comment by Claire-serveth** [comment]
> The USDT was transferred before the Safe contract was deployed (around 900 days before). We should check with the team whether this is default behaviour or if it was missed when indexing the Safe.

Hello @johannesmoormann as I checked the safe of the user, the tokens may have shown after all since he was able to transfer the USDT tokens successfully: 
![image](https://github.com/5afe/safe-support/assets/114005210/3e6c4b9b-07a7-40d7-aa7e-6d425c1ce504)

**Comment by Claire-serveth** [comment]
Closing this issue now. Thank you @liliya-soroka @johannesmoormann! 🙏
