### ISSUE TITLE
[Ethereum] Transaction Builder does not load ABI for any contract

### ISSUE THREAD

**Issue by la1234512345** [5afe/safe-support#385]
### Issue Category

Other

### What happened?

When address is entered, UI doesn't give an option to populate ABI. Tried different contracts including USDC. USDT and none of them worked

Tried using the link https://apps-portal.safe.global/tx-builder in custom apps, still the UI does not work 

### Date and time this happened or you first noticed this issue

18-02-2024

### Network

Ethereum Mainnet

### Safe Address

NA

### Token Address

0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48

### Token Type

None

**Comment by Claire-serveth** [comment]
Another user reported the same issue. Here's a screenshot of the console logs: 
![image](https://github.com/5afe/safe-support/assets/114005210/82b9a986-391c-4429-a720-caf38c33c54b)

**Comment by JagoFigueroa** [comment]
Good morning! Thank you for reporting, the issue should be resoled now 😄

**Comment by Claire-serveth** [comment]
> Good morning! Thank you for reporting, the issue should be resoled now 😄

Thank you again @JagoFigueroa! Already informed the affected users and still waiting for their response, but I'll go ahead and close this issue now and will reopen should there be a need. 🙏
