### ISSUE TITLE
[ETH network] Getting error code 32005 when connecting to various safe apps

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#386]
### Issue Category

Safe loading issue, doesnt load on any interface

### What happened?

Users are having issues connecting/interacting dapps via the safe app list: (able to access using walletconnect) 
![image](https://github.com/5afe/safe-support/assets/114005210/6cdb8381-f72d-4c85-8df2-9837704108bd)
![image](https://github.com/5afe/safe-support/assets/114005210/7f281b62-6a08-4598-b238-1b672a20e495)

### Date and time this happened or you first noticed this issue

18-02-2024

### Network

Ethereum Mainnet

### Token Type

None

**Comment by JagoFigueroa** [comment]
Good morning! Thank you for reporting, the issue should be resoled now 😃

**Comment by Claire-serveth** [comment]
> Good morning! Thank you for reporting, the issue should be resoled now 😃

Thank you so much @JagoFigueroa 🙏 Will check with the users before closing this issue.

**Comment by Claire-serveth** [comment]
Still waiting for the users' responses but I'll go ahead and close this for now. Thanks again team! 🙏
