### ISSUE TITLE
Nonce not updated in Queue tab

### ISSUE THREAD

**Issue by inahlikenoother** [5afe/safe-support#387]
### Issue Category

Transaction execution issue

### What happened?

User is trying to execute Nonce 2121 but Nonce 2093 still shows pending in the queue tab. 
![image](https://github.com/5afe/safe-support/assets/114049495/29e68a5b-6f80-454a-acea-71653ee1599c)
Nonce 2093 also shows as the current nonce via Safe transaction API
![image](https://github.com/5afe/safe-support/assets/114049495/cb1c6452-e12b-447f-97b2-7fffcac71cf0)

However, user said that Nonce 2093 was already executed last February 16
<img width="1902" alt="Screenshot 2024-02-19 at 12 30 31 AM" src="https://github.com/5afe/safe-support/assets/114049495/858fe025-a27e-4306-944a-6822b928fb12">
Transaction hash 0xafd620f10876c11e3b461f335bb233a815211f47f35efc1483c98855d52749f7
Safe transaction hash 0xc7b667109e50efa16193cfe2b7eb843b0962fb8376552cec1b3a087c95e7964d

Ethereum mainnet status
![image](https://github.com/5afe/safe-support/assets/114049495/828c33d0-8a71-4328-8f7d-7d1b72b780da)

### Date and time this happened or you first noticed this issue

19-02-2024

### Network

Ethereum Mainnet

### Safe Address

0xfF7B5E167c9877f2b9f65D19d9c8c9aa651Fe19F

### Token Type

None

### Transactions

```shell
nonce 2093 https://etherscan.io/tx/0xafd620f10876c11e3b461f335bb233a815211f47f35efc1483c98855d52749f7
Safe tx hash 0xc7b667109e50efa16193cfe2b7eb843b0962fb8376552cec1b3a087c95e7964d
```

**Comment by liliya-soroka** [comment]
checking with the team...

**Comment by inahlikenoother** [comment]
> checking with the team...

Thank you, Liliya.

I got an update from user and he said he was able to execute a transaction on Nonce 2093 through direct interactions using the following libs:
```
"@safe-global/protocol-kit": "^1.2.0",
"@safe-global/safe-core-sdk-types": "^2.2.0",
```
Not sure how user was able to do this if Nonce 2093 was already executed and showing in his History tab based on the screenshot I provided above? Or is this possible via contract interaction? 

Current nonce for his Safe now is Nonce 2094. User's History tab earlier was messed up (nonces skipped) but right now it's already in order, but I still don't see Nonce 2093 that was previously executed based on user's screenshot above

**Comment by inahlikenoother** [comment]
Nonces in user's history tab earlier(skipped, as well as in the top part of the page)
![image](https://github.com/5afe/safe-support/assets/114049495/ac4c4ba2-9ac4-4130-a9f6-4c81fa8d9df0)
Nonces in user's history tab now(already in order but still missing nonce 2092 and 2093)
![image](https://github.com/5afe/safe-support/assets/114049495/61829370-4593-41d2-a8bd-1507744547ec)

**Comment by Claire-serveth** [comment]
Update from the user, he executed several more TXs by going directly to the safe contract--nonces 2094 and 2095, but these are also not appearing on the UI.

**Comment by Claire-serveth** [comment]
> checking with the team...

Hi @liliya-soroka it looks like the user's transaction history is now updated: 
![image](https://github.com/5afe/safe-support/assets/114005210/657906e7-49bf-442b-a277-ff2799fb10cd)

I'm still waiting for the user's response, then I'll close this issue. Thank you 🙏
