### ISSUE TITLE
Token is visible in blockexplorer but not in the Safe UI

### ISSUE THREAD

**Issue by la1234512345** [5afe/safe-support#39]
### Issue Category

Token missing completely / not visible in the interface or service

### What happened?

User bridged assets (USDT) to Optimism Safe and while it has arrived as confirmed in the blockexplorer, it is not reflecting in the UI

https://optimistic.etherscan.io/address/0x726F4D7511586f6A562d6AAee1F63a6a7eFc72dA
https://optimistic.etherscan.io/tx/0x97546ab7a5553cc79ad0a9e6bb27c66bb44cab9e5357cffc473c8bece5483eaa

![image](https://user-images.githubusercontent.com/114544040/196334041-b6202070-f98d-47ba-87de-f64a6a8abd29.png)

### Date and time this happened or you first noticed this issue

18-10-2022 06:00

### Network

Optimism

### Safe Address

0x726F4D7511586f6A562d6AAee1F63a6a7eFc72dA

### Token Address

0x94b008aA00579c1307B0EF2c499aD98a8ce58e58

### Token Type

ERC20

### Transactions

```shell
https://optimistic.etherscan.io/tx/0x97546ab7a5553cc79ad0a9e6bb27c66bb44cab9e5357cffc473c8bece5483eaa
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JagoFigueroa** [comment]
Morning! Thanks for reporting this. We are currently experiencing some indexing issues on Optimism and the infra team is working on it. I will let you know as soon as it's fixed 😄

**Comment by JagoFigueroa** [comment]
Hi! The issue should be resolved for the user now. I can see the token on his safe and after performing a few transactions on my test safe I can see that asset balances are updating as expected now 😄 

Cheers!

**Comment by la1234512345** [comment]
Thank you! I'll let the user know. Cheers!
