### ISSUE TITLE
[ETH Mainnet] Error GS026 upon execution, cannot replace a transaction with the same nonce

### ISSUE THREAD

**Issue by phoebe-serveth** [5afe/safe-support#390]
### Issue Category

Transaction execution issue

### What happened?

Getting GS026 error when executing "Send" transaction: https://etherscan.io/tx/0x806f0a755e43ac89858a630803a12eed100eb8d157eaaa74895e272c8788c9e1
User also tried to replace the transaction by sending USDC with the same nonce (5) but it does not appear in the UI after going through the Replace process. Only reject transactions appear under the same nonce in the UI (nonce 4).
![image](https://github.com/5afe/safe-support/assets/114040259/246d64f5-87c4-4d71-b00e-3d75d16f7224)

### Date and time this happened or you first noticed this issue

22-02-2024 5:00pm

### Network

Ethereum Mainnet

### Safe Address

0x7Aa2e06e5Eca10716b0179C2F5e9B7230fd4f649

### Token Type

None

**Comment by JagoFigueroa** [comment]
Good morning! Checking with the team, let you know as soon as I have any new info 😄

**Comment by phoebe-serveth** [comment]
Hi @mmv08 @liliya-soroka , thanks for looking into this. 

@mmv08 The transaction you linked above is an on-chain rejection for the previous transaction (nonce 4) which is a different transaction (different amount and recipient)
Simulation in tenderly for nonce 5 was also successful but it still reverted with GS026 error, which is the tx hash provided 
User did try to execute nonce 5 again today with another owner wallet but it reverted with GS013 error: https://etherscan.io/tx/0x10ae684c478269c9b1063c0ea85c9df40807279c942b71585d50a42c683f6ed3

@liliya-soroka 
1. Yes, the replace transaction is identical. I'll check with the user if the same happens with a different amount. 
2. User is using metamask. They just tried executing nonce 5 today with a different owner.
3. Fully signed transaction.

**Comment by phoebe-serveth** [comment]
Hi team. The user has managed to clear all queued transactions. It seems they replaced each transaction with an integer value. Is it normal for transactions to be executed with whole numbers only?
![image](https://github.com/5afe/safe-support/assets/114040259/131a0230-3aa6-4bc1-975e-1d033fa30794)

**Comment by mmv08** [comment]
> User did try to execute nonce 5 again today with another owner wallet but it reverted with GS013 error: https://etherscan.io/tx/0x10ae684c478269c9b1063c0ea85c9df40807279c942b71585d50a42c683f6ed3

This transaction failed because the supplied gas limit was too low. It needed 90000 gas, but the supplied amount was 88000.

**Comment by liliya-soroka** [comment]
@phoebe-serveth , the additional research was done, and  the issue might be related to the https://github.com/safe-global/safe-wallet-web/issues/3332
