### ISSUE TITLE
[Polygon] Layer3 campaign

### ISSUE THREAD

**Issue by la1234512345** [5afe/safe-support#392]
### Issue Category

Other

### What happened?

Hi team, need guidance on where we should redirect layer3 quests concerns.

For the meantime, posting it here: 
https://twitter.com/safe/status/1760985300938220001
https://layer3.xyz/quests/safe-mastery-on-polygon-pos

User already added 2 new signers individually but quest fails to acknowledge/find the transaction
![image](https://github.com/5afe/safe-support/assets/114544040/7d2a5871-5087-4196-9f46-4ff7350d6000)

### Date and time this happened or you first noticed this issue

24-02-2024

### Network

Polygon

### Safe Address

matic:0xA01EbE50Ca0F4C4aa19835B142FF318145102F36

### Token Address

NA

### Token Type

None

### Transactions

```shell
https://polygonscan.com/tx/0xce9aac8f688f960fa7feab2c0f8cc74c45e96eac74147051bc30c5e2b3bf7036
https://polygonscan.com/tx/0x2bd15fdbbdd1245b54641a79ac147bb291a8eae1df6f913ff99cc0b60e4cfb25
```

**Comment by Claire-serveth** [comment]
I also have another user reporting the same issue. 🙏

**Comment by liliya-soroka** [comment]
When users reach this screen in the account creation process, they should select the "Pay Now" option for the quest to be verified on Layer3. The reason for this is that if they choose "Pay Later" there is no on-chain event taking place, and Layer3 relies on on-chain events to verify the steps in the quest.
<img width="1140" alt="image" src="https://github.com/5afe/safe-support/assets/338622/c80d0805-ed8e-4f9c-b1b5-8d1c7d2c9243">

**Comment by liliya-soroka** [comment]
Closing the issue - For any questions related to Layer3 quests, please refer users to the Layer3 Discord server
