### ISSUE TITLE
Pending transactions on Etherscan not showing in Queue tab

### ISSUE THREAD

**Issue by inahlikenoother** [5afe/safe-support#393]
### Issue Category

Transaction execution issue

### What happened?

User is unable to execute transactions, gives the following error
<img width="1710" alt="__________ 2024-02-27 ____ 2 34 37" src="https://github.com/5afe/safe-support/assets/114049495/cd194f5c-e6a1-428d-9dea-b43fefc2b265">
But it shows as pending in Etherscan, but does not show in Queue tab
![image](https://github.com/5afe/safe-support/assets/114049495/91a9b122-2d5e-43b6-89ec-5273c63d8eb2)
There are a lot of other transactions that are pending in Etherscan for user's Safe, but is not showing in Queue tab
![image](https://github.com/5afe/safe-support/assets/114049495/4ebde083-ba3f-4040-867b-841168bcb787)
![image](https://github.com/5afe/safe-support/assets/114049495/d9e00bb9-0bde-4cb5-8ca3-4c7e44662b07)

User's last successful transaction in History tab is Nonce 144, and API shows current nonce should be Nonce 145
![image](https://github.com/5afe/safe-support/assets/114049495/e2cea429-14bd-45fe-a4ba-a7c8f16457bd)
![image-1](https://github.com/5afe/safe-support/assets/114049495/08e0a526-7265-43fa-ba4e-2fcdd9726b9e)

### Date and time this happened or you first noticed this issue

02-27-2024

### Network

Ethereum Mainnet

### Safe Address

0xC370b9ddc0d4D50993c1c8f6c1C9f41A56aa04b6

### Token Type

None

### Transactions

```shell
Pending transactions in Etherscan that is not showing in Queue tab:
https://etherscan.io/tx/0xeb9531c927355c4d61d9b4b6b06e0c2dd9617c8fd4f3b8805e7388de7abcc0b9
https://etherscan.io/tx/0x9117706a0835cf2d1e0c1a75b1c1657f81f374c3504d6a30c74c3dbb95dc0a7c
https://etherscan.io/tx/0x09e40b5635ccb339eba091b793c41f3404f3764b6a4239a0fe95b09adb3717d1
```

**Comment by liliya-soroka** [comment]
checking

**Comment by inahlikenoother** [comment]
> Did the user perform create+execute together? If yes, such tx will not be displayed on UI in queue list. They will appear in the history after on-chain execution. Timeout error is shown if the tx was not executed on-chain withing the 60 sec. The gaslimit might be too low for the quick tx execution on-chain. The txs can be speed or cancelled up in the user's wallet

Hi Liliya, as you said here the tx can be speed up or cancelled in the user's wallet, do you mean the EOA wallet/signer wallet? User does not see these transactions in their wallet

**Comment by liliya-soroka** [comment]
Yes, I mean EOA wallet( owner wallet) that was used for tx execution.
What wallet was used? Was it Metamask ?

**Comment by inahlikenoother** [comment]
> Yes, I mean EOA wallet( owner wallet) that was used for tx execution. What wallet was used? Was it Metamask ?

User used this address, `0xacB43333dC6f3ec471b8a8135C142C7249d7e680` not sure with what wallet app was used, but I asked user and still waiting response

**Comment by inahlikenoother** [comment]
> Yes, I mean EOA wallet( owner wallet) that was used for tx execution. What wallet was used? Was it Metamask ?

Hi Liliya, this issue is resolved, thank you so much for your help, appreciate it :pray: 

Will close this Github issue now.
