### ISSUE TITLE
[Polygon] WMATIC is not showing up on the Assets page

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#394]
### Issue Category

Token missing completely / not visible in the interface or service

### What happened?

User executed a successful Matic Wrapping transaction via the Safe app (Quickswap) on the safe mobile app iOS, but it's not showing up on both Assets page on the UI and polygon scan: 

![image](https://github.com/5afe/safe-support/assets/114005210/dde839b3-eabe-493a-91fe-6f155bce55db)
![image](https://github.com/5afe/safe-support/assets/114005210/333bfae1-39c6-4d88-ad2c-889836844010)
![image](https://github.com/5afe/safe-support/assets/114005210/8140a45b-39da-4ffc-a3f6-28788f8b20dc)

It only showed up on the UI and polygonscan after user transferred WMATIC to his safe wallet. Is this normal behavior for those Wrapped Matic executed via internal transactions? Is there something a user must do in order for the WMATIC to show up on the UI, aside from transferring WMATIC to his safe wallet?

### Date and time this happened or you first noticed this issue

27-02-2024

### Network

Polygon

### Safe Address

matic:0x51b70Fed8F1D970179E3A5d05999dE678737D774

### Token Address

0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270

### Token Type

None

**Comment by liliya-soroka** [comment]
checking....

**Comment by liliya-soroka** [comment]
We were not able to reproduce the issue.
I suggest to close the issue for now.
If you have other complains with the same problem ,please, reopen the issue and ping we to check it right away

**Comment by Claire-serveth** [comment]
Alright. Thank you so much @liliya-soroka 🙏 closing this issue now.
