### ISSUE TITLE
Redeploy safe created through relayer on BSC

### ISSUE THREAD

**Issue by joanpan** [5afe/safe-support#395]
### Issue Category

Other

### What happened?

User mistakenly transferred funds to the wrong network (BSC) instead of the Gnosis chain. Although the proxy addresses for GNO and BSC safes match, which usually allows for recreation, the user's safe was created through a relayer (Gelato network), using the Gnosis pay card. Is it possible to redeploy the safe in this case?

TX: https://bscscan.com/tx/0xee452080c1b6ca170047ca98756309af27825960105c461529aef4463b2ff98f

Safe address: gno:0x04D9D9D31c91d811d43b1E3ef70b72c3E63feAa4
Safe creation tx: https://gnosisscan.io/tx/0x9e36e2ddac26bdedb92e46e14c81b10565012a06ec2d54f46e69608aa1c52549

![image](https://github.com/5afe/safe-support/assets/114049668/cd09fd29-d7e4-41b2-afca-dedd9dbcfba5)

### Date and time this happened or you first noticed this issue

29/02/2024

### Network

Gnosis Chain

### Safe Address

0x04D9D9D31c91d811d43b1E3ef70b72c3E63feAa4

### Token Type

None

**Comment by mmv08** [comment]
They should be able to redeploy by sending a transaction to:
```
0xa6b71e26c5e0845f74c812102ca7114b6a896ab2
```
with the calldata:
```
0x1688f0b9000000000000000000000000d9db270c1b5e3bd161e8c8503c55ceabee70955200000000000000000000000000000000000000000000000000000000000000600b4ec9b9344ab024bb523a6df71116f65f24eb0ec59f6e3b79bd2685af030d640000000000000000000000000000000000000000000000000000000000000164b63e800d0000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000140000000000000000000000000f48f2b2d2a534e402487b3ee7c18c33aec0fe5e4000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000099b2c7057b4828d1ee1706e05c04d1603b733656000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
```

**Comment by joanpan** [comment]
Thank you @mmv08! Will let the user know

**Comment by joanpan** [comment]
It worked, thank you

**Comment by joanpan** [comment]
Hi @mmv08, got a similar case but this time it's from Gnosis chain to Polygon. Safe address: gno:0x4271680aE172f4ab1e3bD69dFdeF1e5666946Ca8

I've noticed that the calldata you provided for the previous case differs from the calldata used in the Safe transaction creation. Could you please explain what changes were made?

Additionally, if we encounter any new cases, how should we handle the calldata?

**Comment by mmv08** [comment]
> Hi @mmv08, got a similar case but this time it's from Gnosis chain to Polygon. Safe address: gno:0x4271680aE172f4ab1e3bD69dFdeF1e5666946Ca8
> 
> I've noticed that the calldata you provided for the previous case differs from the calldata used in the Safe transaction creation. Could you please explain what changes were made?
> 
> Additionally, if we encounter any new cases, how should we handle the calldata?

Hey, different calldata is expected because the calldata contains safe configuration parameters such as owner addresses, the singleton contract to be used, the threshold, the modules to enable, and so forth. I don't think we can handle such cases efficiently now, so please feel free to ping us if the new case occurs.

So for this safe, the calldata should be:
Recipient:
```
0xa6b71e26c5e0845f74c812102ca7114b6a896ab2
```

Data:
```
0x1688f0b90000000000000000000000003e5c63644e683549055b9be8653de26e0b4cd36e00000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000018b8fe52b350000000000000000000000000000000000000000000000000000000000000164b63e800d0000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000140000000000000000000000000f48f2b2d2a534e402487b3ee7c18c33aec0fe5e40000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000c0d874d8888ab8bb18ab0145eb70910b8c07e63d000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
```
