### ISSUE TITLE
[ETH] User is getting Failed. Timeout. error for pending transaction 

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#397]
### Issue Category

Transaction execution issue

### What happened?

User is getting failed transaction on the Safe UI although it's only pending on etherscan:
![image](https://github.com/5afe/safe-support/assets/114005210/10380407-6b40-4786-b1ce-84f6eb43daec)

Because of this error, user sent 4 transactions instead of 1, hence wanted to refund the gas incurred for the unnecessary transactions:
![image](https://github.com/5afe/safe-support/assets/114005210/ad9dcf98-0219-4736-9f5c-4e8f9e2523bf)

### Date and time this happened or you first noticed this issue

03-03-2024

### Network

Ethereum Mainnet

### Safe Address

eth:0x8aaF729dfaD4c79c112Ed257a9A56Ad5858240BC

### Token Type

None

**Comment by kirkkonen** [comment]
Hi there! Wallet team here. As far as I can see on Etherscan, all the transactions were executed in the end. And these are not duplicates, the USDC amounts were different each time. Not sure if that's a valid case for a refund.

<img width="1403" alt="image" src="https://github.com/5afe/safe-support/assets/5926677/5100ce0b-6159-456b-8a9e-34ceb30b788f">

**Comment by kirkkonen** [comment]
Hi there! Wallet team here. As far as I can see on Etherscan, all the transactions were executed in the end. And these are not duplicates, the USDC amounts were different each time. Not sure if that's a valid case for a refund.

<img width="1403" alt="image" src="https://github.com/5afe/safe-support/assets/5926677/5100ce0b-6159-456b-8a9e-34ceb30b788f">

**Comment by Claire-serveth** [comment]
Hello @kirkkonen User was referring to these transactions: https://app.safe.global/transactions/history?safe=eth:0x8aaF729dfaD4c79c112Ed257a9A56Ad5858240BC
![image](https://github.com/5afe/safe-support/assets/114005210/dc8ca1c4-4694-4ee5-a12d-c453b43e7953)

**Comment by kirkkonen** [comment]
Hm when I look them up in Etherscan, all of them are shown as successfully executed. https://etherscan.io/address/0x8aaf729dfad4c79c112ed257a9a56ad5858240bc#tokentxns

**Comment by Claire-serveth** [comment]
> Hm when I look them up in Etherscan, all of them are shown as successfully executed. https://etherscan.io/address/0x8aaf729dfad4c79c112ed257a9a56ad5858240bc#tokentxns

Yeah, indeed, they were successfully executed but user was bothered by the Failed. Time out. error on the UI and thought that the transaction did fail (without double checking on etherscan if the transaction did fail or succeeded), and so he executed another (same) transaction. 

Hence, he was asking if the team can refund the gas spent due to UI bug.

**Comment by Claire-serveth** [comment]
Hello @kirkkonen just following up if this error can't be considered as bug? 🙏

**Comment by kirkkonen** [comment]
Hi, sorry for the delayed response. We unfortunately can't refund these transactions. But we changed the logic for execution that takes longer than usual - added "speed up" button which suggests doing so in the connected wallet.

**Comment by Claire-serveth** [comment]
Thank you so much @kirkkonen we'll relay this to the user and close this issue now. 🙏
