### ISSUE TITLE
[Polygon] Token not showing up on Assets page

### ISSUE THREAD

**Issue by joanpan** [5afe/safe-support#40]
### Issue Category

Token missing completely / not visible in the interface or service

### What happened?

User reported LDO token not showing up on Assets page but is showing up on block explorer, not showing up on my end either

Assets page: ![image](https://user-images.githubusercontent.com/114049668/196495651-4b843602-d2bc-4478-9ff1-c37b753457e2.png)

Blockexplorer: 
![image](https://user-images.githubusercontent.com/114049668/196495676-3225d090-b5bd-447c-8018-a615326c70a4.png)

### Date and time this happened or you first noticed this issue

19-10-2022

### Network

Polygon

### Safe Address

0xd2B5b0a3B1FF7574a7feCa4C3b9098e991191fe3

### Token Address

0xC3C7d422809852031b44ab29EEC9F1EfF2A58756

### Token Type

ERC20

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joanpan** [comment]
Reporting a similar issue for the following safes:
matic:0x08Ff1d235959963180683E463d368546e902F556
matic:0x27911AA37Ab20F14B14977E7E8a3faA9c821d87a

**Comment by JagoFigueroa** [comment]
Good morning! Looks like we are experiencing some indexing issues on the chain. I will let the infra team know 😄

**Comment by Uxio0** [comment]
Hi everyone,

At first we thought it could be an indexing problem but after further analysis we realised that it was an issue with the token. As we see it's a proxy, and at the time we indexed it it had no decimals, so we were excluding it from the balances list.

It's showing now
