### ISSUE TITLE
zkSync Era - USDC not showing in Assets page, but showing in Blockexplorer

### ISSUE THREAD

**Issue by inahlikenoother** [5afe/safe-support#406]
### Issue Category

Token missing completely / not visible in the interface or service

### What happened?

User transferred USDC to his Safe, but it's not showing in the Assets page
![image](https://github.com/5afe/safe-support/assets/114049495/db44ab5a-a12c-4d13-bedc-519dee897bf7)
![image](https://github.com/5afe/safe-support/assets/114049495/135a262b-a2da-4eac-80ca-0e542ff43903)

### Date and time this happened or you first noticed this issue

18-03-2024

### Network

zkSync Era

### Safe Address

0xbA9d7FD4b65fBc90fC49ca34Bd9f8d1bb1958589

### Token Type

None

### Transactions

```shell
https://era.zksync.network/address/0xbA9d7FD4b65fBc90fC49ca34Bd9f8d1bb1958589#tokentxns
https://era.zksync.network/tx/0xee83e6498096d9a1589ad530c6aaf113dc3910520ff9326967e5e1dc8d54fe3f
```

**Comment by inahlikenoother** [comment]
zkSync status is green 
![image](https://github.com/5afe/safe-support/assets/114049495/f644fba7-9b55-44b1-82a0-688320557833)

**Comment by JagoFigueroa** [comment]
Hi! Issue should be resolve now 😄

**Comment by Claire-serveth** [comment]
Thank you so much @JagoFigueroa will inform the user and closing this issue now. 🙏
