### ISSUE TITLE
[ARB] 2 Official ARB tokens showing up on the UI  

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#407]
### Issue Category

Other

### What happened?

There are 2 ARB tokens showing up on the UI but the one with the balance is the one without the official logo: 

![image](https://github.com/5afe/safe-support/assets/114005210/1bfb42b0-d53b-40f9-a6db-2575ca90cf1e)

When I check the token contract, it is also the official one:

![image](https://github.com/5afe/safe-support/assets/114005210/eaa26f26-a0cb-4d5c-8dc6-eca4bf5a8fb2)

Safe address: https://app.safe.global/balances?safe=arb1:0x9002C60685df7dd5CB25638547e9FD26c7e955ce

### Date and time this happened or you first noticed this issue

18-03-2024

### Network

Arbitrum

### Safe Address

arb1:0x9002C60685df7dd5CB25638547e9FD26c7e955ce

### Token Address

0x912CE59144191C1204E64559FE8253a0e49E6548

### Token Type

ERC20

### Transactions

```shell
Intercom ticket: https://app.eu.intercom.com/a/inbox/pynbtguw/inbox/shared/all/conversation/212174700006663?view=List
```

**Comment by katspaugh** [comment]
They seem to be mixing up the Arbitrum governnce token (ARB) which they do hold, and the native network currency (Arbitrum Ether / AETH) which we always display in all Safes even if the balance is 0.

**Comment by katspaugh** [comment]
I'll see if we can update AETH's icon to make it clearer, though.

**Comment by Claire-serveth** [comment]
> I'll see if we can update AETH's icon to make it clearer, though.

So sorry @katspaugh yeah. I realized it after posting the issue hence I immediately closed it. But I truly appreciate your response 🙏

**Comment by katspaugh** [comment]
I've changed the AETH icon to the generic Ether icon to avoid confusion with the ARB token. Also I noticed that the ARB token isn't visible with the default token list turned on, we're looking into it. Cheers!
