### ISSUE TITLE
No confirmation pops up on metamask through walletconnect on iOS mobile app

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#41]
### Issue Category

Transaction execution issue

### What happened?

User was trying to process transactions, which then proceeds to the owner key page but when user click MetaMask wallet, nothing pops up on MetaMask. 

https://user-images.githubusercontent.com/114005210/196780389-6a3299f8-0592-4e00-a41f-5ce112a52bec.mp4

### Date and time this happened or you first noticed this issue

20-10-2022 19:21

### Network

Avalanche

### Safe Address

https://gnosis-safe.io/app/avax:0xe605bb8ADCf2eFe93D27f6807A041d95399a2029/home

### Token Address

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JagoFigueroa** [comment]
Good morning! Thank you for reporting this. I was able to reproduce it as well, will let the mobile team know 😄

**Comment by DmitryBespalov** [comment]
Good day, we are in the migration process of the infrastructure, and unfortunately the wallet connect messaging is down. We'll issue a new release to fix it within a week.

If you wish to use your key on the mobile device, for the meantime, please either use Ledger or import the key to the mobile app directly.

Thank you for understanding.

**Comment by DmitryBespalov** [comment]
@shyos Please try this out: https://testflight.apple.com/join/c6k0CIUk
