### ISSUE TITLE
[ETH] Safe account is taking too long to load

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#410]
### Issue Category

Safe loading issue, doesnt load on any interface

### What happened?

This safe account is taking too long to load on the UI (around 3 minutes): https://app.safe.global/balances?safe=eth:0xF326e4dE8F66A0BDC0970b79E0924e33c79f1915

I tried loading other safe wallet addresses but they're loading just fine. It seems this is the only affected account so far.

### Date and time this happened or you first noticed this issue

20-03-2024

### Network

Ethereum Mainnet

### Safe Address

eth:0xF326e4dE8F66A0BDC0970b79E0924e33c79f1915

### Token Type

None

**Comment by JagoFigueroa** [comment]
Hi! Although it is true that it takes some time for this safe to load, I would say it is more or less expected given the amount of 
incoming transactions it has every minute. Of course 3 minutes for it to load wouldn't be acceptable but during my testing with different browsers it is not taking nowhere near 3 minutes but around 30 seconds 🥲

**Comment by Claire-serveth** [comment]
Thank you @JagoFigueroa will inform the user 🙏
