### ISSUE TITLE
[Polygon] Safe account couldn't be loaded

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#411]
### Issue Category

Safe loading issue, doesnt load on any interface

### What happened?

This safe account is taking time to load and ended up not loading at all: https://app.safe.global/balances?safe=matic:0x930DEDdDB92Fef1B4Ab2665D250877339f064eac

![image](https://github.com/5afe/safe-support/assets/114005210/bdcf49c7-736f-4c1d-a58e-262f98ffd44c)

### Date and time this happened or you first noticed this issue

20-03-2024

### Network

Polygon

### Safe Address

matic:0x930DEDdDB92Fef1B4Ab2665D250877339f064eac

### Token Type

None

**Comment by JagoFigueroa** [comment]
Sharing with the team, thank you @Claire-serveth 😄

**Comment by Claire-serveth** [comment]
Thank you so much @JagoFigueroa 🙏

**Comment by JagoFigueroa** [comment]
[Here](https://github.com/safe-global/safe-transaction-service/issues/1930) is the opened ticket. This should also help with the mainnet safe that was loading a bit slow 😃 

Thanks again!
