### ISSUE TITLE
[BASE] Getting "could not coalesce error..." while executing transaction

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#412]
### Issue Category

Transaction execution issue

### What happened?

Two users are getting this error upon executing transaction on Base network:
![image](https://github.com/5afe/safe-support/assets/114005210/2652e2b7-1f0f-4fbb-adfe-9c9e2129089c)

The transactions were successfully executed after changing the gas parameters (100x priority fee)
Wallet used: Metamask, Rabby
Tried on different browsers

Safe address: https://app.safe.global/home?safe=base%3A0x6a476CFcA942Af7f00beEaE4eFC240482947Ce19

### Date and time this happened or you first noticed this issue

21-03-2024

### Network

Ethereum Mainnet

### Safe Address

base:0x6a476CFcA942Af7f00beEaE4eFC240482947Ce19

### Token Type

None

**Comment by liliya-soroka** [comment]
Thank you for reporting. This is a known issue with the gas fee. The ticket to follow: https://github.com/safe-global/safe-wallet-web/issues/3442.

**Comment by Claire-serveth** [comment]
Thank you so much @liliya-soroka 🙏
