### ISSUE TITLE
[BASE] Safe created from UI getting "Unsupported base contract error"

### ISSUE THREAD

**Issue by joanpan** [5afe/safe-support#413]
### Issue Category

Other

### What happened?

Safe created from the UI is getting "Unsupported base contract error". 
It doesn't look like the safe was redeployed from a different network.

Checked the safe creation tx, contract used is 0xa6b71e26c5e0845f74c812102ca7114b6a896ab2 instead of 0xC22834581EbC8527d974F8a1c97E1bEA4EF910BC:
![image](https://github.com/5afe/safe-support/assets/114049668/73e96862-2111-4df2-8917-81580d065308)
https://basescan.org/tx/0xa52e52ab4bfe802165459d0338dd2efecc11ebef864b963c19b57d11dda01a89

https://app.safe.global/home?safe=base:0xE321C47e0b0c3F07b1721bfdce1eCE7Aa9612b05

### Date and time this happened or you first noticed this issue

21-03-2024

### Network

Ethereum Mainnet

### Safe Address

base:0xE321C47e0b0c3F07b1721bfdce1eCE7Aa9612b05

### Token Type

None

**Comment by JagoFigueroa** [comment]
Hi there! Are we sure that the safe was created from the UI and not from other tools like the safe-CLI? I can see that it has an invalid masterCopy:

```
{
    "address": "0xE321C47e0b0c3F07b1721bfdce1eCE7Aa9612b05",
    "nonce": 0,
    "threshold": 2,
    "owners": [
        "0x939B8FBBD07954B61b0Ab98df589Dac2160e1c51",
        "0xe280Cb35D8B478BE54a284e2060FA284FfdFB847",
        "0x0111F4A1811b7841aE9dAF65B4d2C8e389d71490"
    ],
    "masterCopy": "0xd9Db270c1B5E3Bd161E8c8503c55cEABeE709552", <----
    "modules": [],
    "fallbackHandler": "0x017062a1dE2FE6b99BE3d9d37841FeD19F573804",
    "guard": "0x0000000000000000000000000000000000000000",
    "version": "1.3.0"
}
```

When it should have the address found [here](https://github.com/safe-global/safe-deployments/blob/main/src/assets/v1.3.0/gnosis_safe.json) for chainId `8453`. Maybe the user was playing around with safe creation and used an invalid one by mistake 🤔  Also if created from the UI should be the latest version, `1.3.0+L2`

**Comment by joanpan** [comment]
Hi @JagoFigueroa thank you, I'll inform the user

**Comment by Sherie15** [comment]
Hi team, this is the response of the user. 

_Thanks for the update. I don't have the safe-CLI installed. I am 100% certain I did it from the UI.
It would be rather concerning if the UI had been hijacked and a different address had been inserted instead of the correct one._

**Comment by liliya-soroka** [comment]
checking

**Comment by liliya-soroka** [comment]
Could you point me to the discussion on Intercom, please?

**Comment by liliya-soroka** [comment]
Thank you. Could you check with the user if it was CF safe initially and if the user tried to create safes on other networks on the same day? 
Searching for the steps.
I have tried the creation flow on Base a few times and the safe is deployed with the correct master copy on UI when it's straightforward safe creation( deployed safe and CF safe)

**Comment by Sherie15** [comment]
I will confirm this with the user. Thank you @liliya-soroka

**Comment by Sherie15** [comment]
Hi @liliya-soroka this is the response from the user

_Hi Sherie,

I have not created the Safe account of the same address previously on another network.

I'd like to know if the contract I have created is just an old version of the official contract, or if the contract is a completely foreign one. Is it as "safe" to use as any other safe? Or should I avoid interacting with it in case it is malicious?_

**Comment by joanpan** [comment]
Hi @liliya-soroka got another similar case on Polygon. They created the safe on the safe website but getting the unsupported base contract error. They did not recreate this safe from another network. 

Contract used in the safe creation tx is 0xaacFeEa03eb1561C4e67d661e40682Bd20E3541b

https://app.safe.global/home?safe=matic:0x505d045ffF6AA4c6CD655940831a6d5feAEfeDb7

**Comment by mmv08** [comment]
The official safe factory contract on polygon is `0xa6B71E26C5e0845f74c812102Ca7114b6a896AB2`
