### ISSUE TITLE
[Sepolia] Indexing issue: Transaction not showing up on UI

### ISSUE THREAD

**Issue by joanpan** [5afe/safe-support#414]
### Issue Category

Safe loading issue, doesnt load on any interface

### What happened?

User executed a transaction but does not display in the Safe UI. 
https://app.safe.global/transactions/history?safe=sep:0x7680690C85F7FCE55B013c3bA17eB47e36FeD5b7
![image](https://github.com/5afe/safe-support/assets/114049668/4729d3a6-f358-4e1c-824d-933489c7cd3e)

TX hash: https://sepolia.etherscan.io/tx/0xf2576eb0bc35fd95ff07af0fb849ce9d4bc6587bb27f433d0f236f71078d51ce

Safe Tx Service Status is red:
![image](https://github.com/5afe/safe-support/assets/114049668/46dc7a71-5a06-4bb6-83de-3c018965f5a9)

### Date and time this happened or you first noticed this issue

26-03-2023

### Network

Ethereum Mainnet

### Safe Address

sep:0x7680690C85F7FCE55B013c3bA17eB47e36FeD5b7

### Token Type

None

**Comment by liliya-soroka** [comment]
Thank you for reporting. The team is on it - https://github.com/safe-global/safe-transaction-service/issues/1948

**Comment by JagoFigueroa** [comment]
Hi there! I can see that the fix was merged in main last week so it should be resolved know 😄 let us know if there are still any issues

**Comment by Claire-serveth** [comment]
Thank you @liliya-soroka @JagoFigueroa closing this issue now 🙏
