### ISSUE TITLE
[Polygon] Safe not loading issue

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#417]
### Issue Category

Safe loading issue, doesnt load on any interface

### What happened?

User is not able to load his safe on Polygon network: https://app.safe.global/home?safe=matic:0x0b8e0aAF940cc99EDA5DA5Ab0a8d6Ed798eDc08A
![image](https://github.com/5afe/safe-support/assets/114005210/2490cf2a-8874-4ca8-b578-51bb7a3962e2)

Also, another user is unable to load transactions on the safe mobile app:
![image](https://github.com/5afe/safe-support/assets/114005210/23ab2558-09e3-41fd-af21-fb93a4a086e3)

Is it due to the status:
![image](https://github.com/5afe/safe-support/assets/114005210/23ab9950-6ac4-4e18-806d-09497b19e4c2)

### Date and time this happened or you first noticed this issue

23-03-2024

### Network

Polygon

### Safe Address

matic:0x0b8e0aAF940cc99EDA5DA5Ab0a8d6Ed798eDc08A

### Token Type

None

**Comment by JagoFigueroa** [comment]
Same as this [ticket](https://github.com/5afe/safe-support/issues/416) Feel free to close it as well if all is good 😎

**Comment by Claire-serveth** [comment]
Thanks again @JagoFigueroa closing this now. 🙏
