### ISSUE TITLE
[Sepolia] Untrusted transaction

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#418]
### Issue Category

Other

### What happened?

Contract interaction transactions (via openzeppelin) tagged as "Untrusted transaction" is it safe to execute? 
![image](https://github.com/5afe/safe-support/assets/114005210/2b7065b2-46ef-4379-8859-92347b0ae531)

### Date and time this happened or you first noticed this issue

26-03-2024

### Network

Goerli

### Safe Address

sep:0xc56fA6505d10bF322e01327e22479DE78C3Bf1cE

### Token Type

None

**Comment by JagoFigueroa** [comment]
Hi there! I cannot see a tx with that nonce marked as untrusted anymore and all the executed ones interacting with that **create2** method of that contract do not have that flag anymore 😞 

I would strongly recommend for the user to reach our to the openzeppelin team if they are curious about the contract that is being interacted with but on our end I see no issues.

Cheers!

**Comment by Claire-serveth** [comment]
I see. Thank you so much @JagoFigueroa 🙏 will inform the user and close this after his confirmation.
