### ISSUE TITLE
[Polygon] Already activated Safe does not display ERC20

### ISSUE THREAD

**Issue by CindyLo0** [5afe/safe-support#419]
### Issue Category

Token missing completely / not visible in the interface or service

### What happened?

User created a Polygon Safe via Pay Later option. 

Safe has already been activated but it only displayed native MATIC tokens under Assets, no ERC20 tokens.

https://app.safe.global/balances?safe=matic:0x688A06dBECB39e2328E01BEAde60Af9029A7286d
![image](https://github.com/5afe/safe-support/assets/79137197/f3337b5e-1445-47eb-8fe8-58ea2c45ea8a)

https://polygonscan.com/address/0x688A06dBECB39e2328E01BEAde60Af9029A7286d
![image](https://github.com/5afe/safe-support/assets/79137197/8730eecb-9237-41a4-a919-c4d80aabf788)

### Date and time this happened or you first noticed this issue

28-03-2023 18:00

### Network

Polygon

### Safe Address

matic:0x688A06dBECB39e2328E01BEAde60Af9029A7286d

### Token Type

None

**Comment by JagoFigueroa** [comment]
Hi again! I have asked the team to reindex the safe and can see the missing tokens now 😄 This probably happened due to the tokens being received before the safe creation.

Cheers!

**Comment by Claire-serveth** [comment]
Thank you so much @JagoFigueroa closing this issue now. 🙏
