### ISSUE TITLE
[ETH] The Safe SDK could not be initialized... error 

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#421]
### Issue Category

Transaction execution issue

### What happened?

User is getting this error while initiating a token transfer transaction:
![image](https://github.com/5afe/safe-support/assets/114005210/47331c63-75ab-402d-860c-a9a3d70059f2)
![image](https://github.com/5afe/safe-support/assets/114005210/96d7d5f8-727f-4102-a93e-4eccdc329016)
![image](https://github.com/5afe/safe-support/assets/114005210/12b979e0-8d43-4d13-b0bc-672b9d929692)

Already tried basic TS, using different browsers, changing Metamask RPC. but user get the same error.
Safe address: https://app.safe.global/balances?safe=eth:0xb779EFEEdA6cF887b80bc386E7EB9fdCEd6753f6

### Date and time this happened or you first noticed this issue

01-04-2024

### Network

Ethereum Mainnet

### Safe Address

eth:0xb779EFEEdA6cF887b80bc386E7EB9fdCEd6753f6

### Token Type

None

**Comment by liliya-soroka** [comment]
checking with the team ...

**Comment by liliya-soroka** [comment]
Could you check with the user if there is still a problem?
Seems that the user was able to sign and execute txs

**Comment by Claire-serveth** [comment]
Hi @liliya-soroka still checking with the user. Will close this issue as soon as I get the response from him. Thank you 🙏

**Comment by Claire-serveth** [comment]
Issue resolved. Closing this ticket now.
