### ISSUE TITLE
Transferred token 2 days ago does not show up

### ISSUE THREAD

**Issue by bingclo** [5afe/safe-support#422]
### Issue Category

Token missing completely / not visible in the interface or service

### What happened?

User transferred Gitcoin (GTC) tokens to an inactivated safe 2 days ago, then activated the Safe today. Token still doesn't show up.
Seeing the same issue on my end, already selected All tokens in the Asset page:
![image](https://github.com/5afe/safe-support/assets/54754746/45b0a5c1-fa49-4174-99ad-3aefb5b695d3)

Tx Service Status only shows synchronized or 1-2 blocks behind only 
![image](https://github.com/5afe/safe-support/assets/54754746/5f19e80b-658d-4284-8fe0-9e511b3bcd28)

Are tokens sent before safe activation not detected? Is there any action required from the users' end for the tokens to show up?

### Date and time this happened or you first noticed this issue

02/04/2024 04:44:04

### Network

Ethereum Mainnet

### Safe Address

0xb89daDfFeEE790A7A8207D30e72D4E4A441f5Ec7

### Token Address

0xDe30da39c46104798bB5aA3fe8B9e0e1F348163F

### Token Type

ERC20

### Transactions

```shell
Token transfer: https://etherscan.io/tx/0xabeb1bf09353692a40a6a5531bc3297ea1d219245166923d8d789dceaa3680f0
Create Safe: https://etherscan.io/tx/0x2bf86446902c9e36d9a150cc5c4fd746df6adb61e90a0749fb96ec9b9d2c63ca
```

**Comment by JagoFigueroa** [comment]
Hi there! Unfortunately this is expected for now, yes. We are working to improve this in the near future but for now every token send to an address that later is used to create a safe won't be indexed by our service as indexing starts as soon as the safe has been created. 

I will ask the team to perform a reindex so that the tokens show up, let you know 😄

**Comment by JagoFigueroa** [comment]
You should see the token now.

Cheers!

**Comment by bingclo** [comment]
I see. Thanks! I can see the tokens now too. :)
