### ISSUE TITLE
[ETH] Incorrect Safe owner associated after a Safe creation is completed

### ISSUE THREAD

**Issue by Sherie15** [5afe/safe-support#424]
### Issue Category

Other

### What happened?

The user created a Safe with wallet creator address: 0x9F3151C14BBfB0E10bEB3A30970C825C5F5c270E but when the Safe creation was completed it has a different wallet address: 0x36219686a2c9a2cEFCc866FB3038583e5568Ca25 which is another user's wallet. I informed the user to replace the existing Safe owner with the expected one.

The user said:  
_your system seems to be bugged and potentially verifies another wallet than the one that is actually being used to make and pay for the account_
_Your system is absolutely flawed_

Chrome/Dekstop/Edge

These are the steps 
1. _https://safe.global/_ I opened up the website here
2. I Launched wallet
3. I Pressed Create Account (Ensuring I was signed into **0x9F3151C14BBfB0E10bEB3A30970C825C5F5c270E**
4. when I reviewed any prompts and addresses whilst executing the purchase of the safe wallet, I ensured the field corresponded to 0x9F3151C14BBfB0E10bEB3A30970C825C5F5c270E only
5. Upon creation I was unable to link and verify this on Gitcoin Passport
6. I was not even aware that **0x36219686a2c9a2cEFCc866FB3038583e5568Ca25** was wallet signed until you informed me here on the chat, every other Address I reviewed upon the Account creation referred to wallet address: **0x9F3151C14BBfB0E10bEB3A30970C825C5F5c270E**

### Date and time this happened or you first noticed this issue

03-04-2024 10:54  

### Network

Ethereum Mainnet

### Safe Address

eth:0xa78bf31cC15CF3CEC78A42B12dF23117Ad867b46

### Token Type

None

**Comment by liliya-soroka** [comment]
thank you for reporting. The next issue related to the safe creation and signer wallet switching was fixed and released- https://github.com/safe-global/safe-wallet-web/issues/3571

**Comment by Sherie15** [comment]
@liliya-soroka, Thank you so much. Closing this ticket.
