### ISSUE TITLE
[BASE] Safe SDK error on recreated safe

### ISSUE THREAD

**Issue by joanpan** [5afe/safe-support#426]
### Issue Category

Safe loading issue, doesnt load on any interface

### What happened?

User is having issues on Base, getting a Safe Core SDK error and unable to execute a transaction. 

Safe is replayed from mainnet. Address: base:0x25C13c0F5c957a7c50966De8141b4Cd86627dD39

This is a previous transaction on Base, where the "replayed" Safe transaction worked: https://basescan.org/tx/0x9d0e89ccb40734737272c489c0db607094dd746782552fe3a2e44f1d16d732a9. 

User wanted to know if there were any changes in the Safe base integration because they were previously able to move assets, but now it doesn't seem to work.

### Date and time this happened or you first noticed this issue

06-04-2024

### Network

Ethereum Mainnet

### Safe Address

0x25C13c0F5c957a7c50966De8141b4Cd86627dD39

### Token Type

None

**Comment by liliya-soroka** [comment]
did the user use CLI for the assets transfer?

**Comment by liliya-soroka** [comment]
Sorry, but we can not guarantee the UI work for the recreated safes.
 We recommend using the CLI interface instead.

**Comment by joanpan** [comment]
Hi @liliya-soroka the user had previously succeeded in transferring via the UI for this particular txn: https://basesc0db607094d2552fe3a2e44f1d16d732a9. They're encountering an error now and are curious about any changes. 

I'll inform them that success isn't guaranteed.
