### ISSUE TITLE
[Optimism] Safe accounts cannot be loaded

### ISSUE THREAD

**Issue by CindyLo0** [5afe/safe-support#427]
### Issue Category

Safe loading issue, doesnt load on any interface

### What happened?

Cannot load Safes in Optimism: 
0xF510a2Ff7e9DD7e18629137adA4eb56B9c13E885

Another user reported in Discord. 
![image](https://github.com/5afe/safe-support/assets/79137197/81ee6949-c92a-487d-900e-50e3cee396ca)

### Date and time this happened or you first noticed this issue

06-04-2024

### Network

Optimism

### Safe Address

0xF510a2Ff7e9DD7e18629137adA4eb56B9c13E885

### Token Type

None

**Comment by Sherie15** [comment]
Another user is also affected [0x23f351363bD25eca392EBdd3E30f90dda347475C](https://app.safe.global/home?safe=oeth:0x801DEcb63a0ca6FD0F57660aB81f068718451E36)
![image](https://github.com/5afe/safe-support/assets/113986185/4a4b4878-58b8-4c48-916b-775acc77d5ca)

**Comment by Sherie15** [comment]
0x84E9feeEae1FDE348b1adf0575026a104e830C8e 
<img width="655" alt="Capture" src="https://github.com/5afe/safe-support/assets/113986185/170e2385-a6e3-4177-8105-440ffe6a9e8e">

**Comment by liliya-soroka** [comment]
could you check? The Optimism is stable again

**Comment by Claire-serveth** [comment]
Thank you @liliya-soroka it seems users were able to access their safes already. Closing this issue now 🙏
