### ISSUE TITLE
Can't sign a login Message from Eigenlayer using OKS keyless web3 wallet

### ISSUE THREAD

**Issue by bingclo** [5afe/safe-support#428]
### Issue Category

Transaction execution issue

### What happened?

User is trying to login to https://app.eigenlayer.xyz/ but keep on getting these errors: 
<img width="456" alt="image" src="https://github.com/5afe/safe-support/assets/54754746/4bd635b1-79b9-48a3-8daf-d546d2fe6fef">

The user already tried clearing cache and cookies, reconnected his wallet (terminated the session completely in OKX wallet app) using other browsers and computers.

The user also had other safes that is owned by the same wallet (using OKS keyless web3 wallet) and was able to login to Eigenlayer with it but not this one. 
https://app.safe.global/home?safe=eth:0x2CCfdB4b04Ab3f32644647FCc0FD8cbAAC5Faab1

Below are the errors in the dev console:
<img width="1717" alt="image" src="https://github.com/5afe/safe-support/assets/54754746/19e11f1a-8b59-4ac3-bd6a-6653d6a18959">
<img width="1718" alt="image-1" src="https://github.com/5afe/safe-support/assets/54754746/20ab8ec0-c2cb-4f4d-a893-ee1277258789">

What could be the reason this is isolated on this particular safe? 

### Date and time this happened or you first noticed this issue

08/04/2024 03:53:34

### Network

Ethereum Mainnet

### Safe Address

https://app.safe.global/home?safe=eth:0x2CCfdB4b04Ab3f32644647FCc0FD8cbAAC5Faab1

### Token Address

N/A

### Token Type

None

### Transactions

```shell
N/A
```

**Comment by liliya-soroka** [comment]
The message already exists in the Messages list ( check the first message at the bottom in the safe) , so no need to sign it again

**Comment by Claire-serveth** [comment]
Thank you @liliya-soroka will inform the user. 🙏

**Comment by Claire-serveth** [comment]
Thank you @liliya-soroka closing this issue now 🙏
