### ISSUE TITLE
[ZKsync] USDC.e token not showing up on the UI

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#429]
### Issue Category

Token missing completely / not visible in the interface or service

### What happened?

Successfully transferred USDC.e token still not showing up on the UI since yesterday. Safe address: https://app.safe.global/balances?safe=zksync:0x619B35a3ec0Bc08B0bbe7D0479038Ead41A1C68B

![image](https://github.com/5afe/safe-support/assets/114005210/756518a6-624f-4a41-a5da-b83c27dd9f5f)
![image](https://github.com/5afe/safe-support/assets/114005210/b4e1980f-72e6-4a64-917c-7fcd252850b8)

NOTE: Chose non-existing network (Volta) since ZKsync network is not included in the list

### Date and time this happened or you first noticed this issue

08-04-2024

### Network

Volta

### Safe Address

zksync:0x619B35a3ec0Bc08B0bbe7D0479038Ead41A1C68B

### Token Address

0x3355df6D4c9C3035724Fd0e3914dE96A5a83aaf4

### Token Type

ERC20

### Transactions

```shell
https://explorer.zksync.io/tx/0x19a3c2c58120d06a3778e198c3c7cb01fce7d1da3396cc813be61e28fd490f1a
```

**Comment by JagoFigueroa** [comment]
Hi! Issue should be resolved now 😄

**Comment by Claire-serveth** [comment]
Thank you so much @JagoFigueroa closing this issue now. 🙏
