### ISSUE TITLE
NFT image not displayed in the UI

### ISSUE THREAD

**Issue by CindyLo0** [5afe/safe-support#43]
### Issue Category

Other

### What happened?

Some NFTs from the same collection are not being displayed in the safe UI (see screenshot) 

![image](https://user-images.githubusercontent.com/79137197/197218310-852d4cbc-15d3-45f5-a4d7-774d58f29eb9.png)

All NFT image from the same collection are displayed when viewed from Zerion app. 

### Date and time this happened or you first noticed this issue

21-10-2022 13:00

### Network

Ethereum Mainnet

### Safe Address

0xff82057a4559af98C4594088334E428f6b0F61cB

### Token Address

0xe22ef3BbC4869CA7367a23fd80D397B9BA4e8cfD

### Token Type

ERC721

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JagoFigueroa** [comment]
Hi! Talking with the web team and seeing that we will be migrating to the new web interface soon we won't tackle this at this moment. NFT experience is smoother there and the images for the shared safe are loading fine for me there 😄 

Cheers!

**Comment by tempe-techie** [comment]
Just to add some additional information. The NFT in question (.basin) has onchain metadata, which means that metadata is written in the smart contract and then base64 encoded.

I believe this is the reason why metadata is not showing on the frontend. So basically you just need to implement the support for NFTs with onchain data on the frontend (decoding the base64 encoded response that you get from tokenURI, and then parsing the data).

Also, please note that the image in most NFTs with onchain metadata is usually an SVG.

Hope this helps.

**Comment by med3000** [comment]
hi, the underlining issue was resolved. We will display image previews on NFTs page now,  y ou can follow this task here https://github.com/safe-global/web-core/issues/1633
