### ISSUE TITLE
[ETH] ETH fiat value is OFF

### ISSUE THREAD

**Issue by Sherie15** [5afe/safe-support#431]
### Issue Category

Token balance not up-to-date, in the interface or service

### What happened?
The ETH USD value in the Safe UI is way lower than what is fetched from Etherscan. Uniswap and Kraken have the same range as the Etherscan.

![image](https://github.com/5afe/safe-support/assets/113986185/1ba1b550-f5f3-4a5c-9dc9-f30e25bfc866)
![image](https://github.com/5afe/safe-support/assets/113986185/cb45953e-054a-41f1-9717-b0a9d38659e7)
![image](https://github.com/5afe/safe-support/assets/113986185/d9125487-f1c9-4802-ad66-c8f61f36cf88)
![image](https://github.com/5afe/safe-support/assets/113986185/58de0811-2bc9-407e-b726-ff918651322c)

![image](https://github.com/5afe/safe-support/assets/113986185/d62475f3-9318-419a-9335-bd178dd29a1f)
https://safe-react-status.netlify.app/

### Date and time this happened or you first noticed this issue

13-04-2024 07:03 am 

### Network

Ethereum Mainnet

### Token Type

None

**Comment by liliya-soroka** [comment]
CoinGecko is used as a fiat value provider, and there is a 2-hour caching on our side. We are going to reduce the caching to 30 minutes. But even after it is important to know that :
- there is no real-time value update 
- CoinGecko is our 3rd party provider

**Comment by Sherie15** [comment]
Thank you so much @liliya-soroka I will inform the user about your findings and action.
