### ISSUE TITLE
[Polygon] Cannot upload a JSON file in Transaction builder

### ISSUE THREAD

**Issue by phoebe-serveth** [5afe/safe-support#433]
### Issue Category

Other

### What happened?

Nothing happens when uploading JSON file. Can't move forward when choosing to upload via "drag and drop" or choose a file. It's only showing this screen. 
![Screenshot 2024-04-22 at 16 07 37](https://github.com/5afe/safe-support/assets/114040259/2a647292-5e3d-4c47-b8cd-ac2c8d8c15e7)
Console logs: 
![Screenshot 2024-04-22 at 16 29 33](https://github.com/5afe/safe-support/assets/114040259/e3a45186-e180-4729-a4d5-cd8a8792e21b)

The user is on MacOS and has already attempted to resolve the issue by trying different browsers. Also tried using a Windows computer, but encountered the same error in the logs. I did a test and I was able to upload a JSON file. Advised user to ask in stackexchange though but was redirected back to support. Not really sure how to proceed. 
User uploaded a video to show the behavior in stackexchange: https://ethereum.stackexchange.com/questions/162822/transaction-builder-json-upload-issue

### Date and time this happened or you first noticed this issue

23-04-2024 3:00am

### Network

Polygon

### Safe Address

0x8221638702df12C4A1cBb65A9A90690E517AeC0d

### Token Type

None

**Comment by JagoFigueroa** [comment]
Good morning! For me dragging and dropping is working as expected in the app and looks to be working as usual with valid JSON files. 

Are we sure that there are no issues with the JSON file the user is trying to upload and use for batching? Or maybe it is valid and there is an edge case but either way it will be quite tricky for us to debug 😞 

Attaching an example of one empty batch that as it is invalid and will throw the same error (for reference of the error he is getting)
[empty batch.json](https://github.com/5afe/safe-support/files/15090241/empty.batch.json)

Cheers!

**Comment by Claire-serveth** [comment]
Thank you @JagoFigueroa relayed this to the user and still waiting for the response. 🙏

**Comment by liliya-soroka** [comment]
Simple example of Json from Transaction builder
[Transactions Batch (4).json](https://github.com/5afe/safe-support/files/15096424/Transactions.Batch.4.json)

**Comment by Claire-serveth** [comment]
Thank you so much @liliya-soroka 🙏 Shared this with the user and still waiting for his response.

**Comment by Claire-serveth** [comment]
Haven't received any feedback from the user, so I'm closing this issue now. Thanks again @liliya-soroka @JagoFigueroa 🙏
