### ISSUE TITLE
[Android] Cannot view and sign queued transactions, Queue and history page not loading

### ISSUE THREAD

**Issue by phoebe-serveth** [5afe/safe-support#437]
### Issue Category

Transaction missing / not visible in app or service

### What happened?

There are two users reporting loading issues with the Safe Android app. The queue and history page is not loading transactions. I was able to replicate the issue on my end as well. 
![image](https://github.com/5afe/safe-support/assets/114040259/476eadd6-8c64-4727-ad69-196463bfcc87)
![image](https://github.com/5afe/safe-support/assets/114040259/c5a852d8-eff7-44bd-ade3-33e987d9d8ae)

Works fine on the safe webapp.
![image](https://github.com/5afe/safe-support/assets/114040259/8a5c6fc3-0960-43d6-8a65-0661a7c15f6f)

### Date and time this happened or you first noticed this issue

29-04-2024 12:00

### Network

Ethereum Mainnet

### Safe Address

0xd848e07374EAbF9ed80C770ecCdFe0eD8AF7672b

### Token Type

None

**Comment by liliya-soroka** [comment]
Hello, yes, this is a known issue. We are working on the fix and a new release will be soon available for the users

**Comment by inahlikenoother** [comment]
> [safe-global/safe-android#2023](https://github.com/safe-global/safe-android/issues/2023)

Hi team , I have another user experiencing the same issue just now.

![Screenshot_2024-05-01-09-56-06-955_io gnosis safe](https://github.com/5afe/safe-support/assets/114049495/cad152af-5018-4a54-844d-8fa91ef57cae)
![Screenshot_2024-05-01-09-55-45-468_io gnosis safe](https://github.com/5afe/safe-support/assets/114049495/3c4eea47-b7c4-4e2d-980f-8bf1fd5d0601)

**Comment by phoebe-serveth** [comment]
Closing this ticket now that a new update for the Android safe app has been released.
