### ISSUE TITLE
Cannot execute queued attempts for Account Recovery

### ISSUE THREAD

**Issue by bingclo** [5afe/safe-support#442]
### Issue Category

Transaction execution issue

### What happened?

User already setup account recovery for his safe and was able to start a recovery from it. 

This was right after he proposed the Recovery: 
![Screenshot 2024-05-11 142150](https://github.com/5afe/safe-support/assets/54754746/3588c1a7-52bd-4971-97a7-d85fd3ae7b0b)

User set his cooldown to 2 days but when checking after 35 hours the queue is empty and no transaction can be executed. There are no rejections on chain as well. 
<img width="1919" alt="image" src="https://github.com/5afe/safe-support/assets/54754746/6dcbd8bc-4358-461d-b347-845612571d6d">

### Date and time this happened or you first noticed this issue

12/05/2024 20:15:32

### Network

Gnosis Chain

### Safe Address

https://app.safe.global/transactions/queue?safe=gno:0xf45E6e13Ce8EaF623DAC30193A28419293e7FABf

### Token Address

NA

### Token Type

None

### Transactions

```shell
https://gnosisscan.io/tx/0x0bb6314500390566ba6578d5a7baf74eab3061d360ce58b06b7a7c0438574f9c/
```

**Comment by schmanu** [comment]
gm @bingclo,

it was an issue / limitation with our used RPC on gnosis chain.
We switched it to a different RPC which resolves the issue.

**Comment by bingclo** [comment]
Thanks! Will check with the user. 🙏

**Comment by bingclo** [comment]
User has been unresponsive. Will close this 🙏 Thank you!
