### ISSUE TITLE
Polygon - Cannot initiate transaction / Transaction History also not loading

### ISSUE THREAD

**Issue by inahlikenoother** [5afe/safe-support#444]
### Issue Category

Transaction execution issue

### What happened?

User gets the following error when trying to initiate a transaction
![Capturesafe](https://github.com/5afe/safe-support/assets/114049495/76ac3d2a-1cf3-4bd8-8d5a-27b698da9ce7)

Transaction History tab doesn't load 
![image](https://github.com/5afe/safe-support/assets/114049495/3e07a5e8-e92f-4ff1-b3fc-94927e9c7e13)

And when user tried to use a different browser to isolate issue, connected correct owner wallet to Safe, user could not see the Polygon Safe
![Capturewtf](https://github.com/5afe/safe-support/assets/114049495/7f87981e-f692-45d0-b9ca-f11ced480f6d)

### Date and time this happened or you first noticed this issue

13-05-2024

### Network

Polygon

### Safe Address

0x9232657Ede8d5b99cbf74Fc1073a53b9709f29FD

### Token Type

None

**Comment by JagoFigueroa** [comment]
Thank you for reporting! We are on it, we will show a banner shortly to let the users know that we are experiencing some issues on the chain 😄 Let you know as soon as it is fixed.

Cheers!

**Comment by inahlikenoother** [comment]
> Thank you for reporting! We are on it, we will show a banner shortly to let the users know that we are experiencing some issues on the chain 😄 Let you know as soon as it is fixed.
> 
> Cheers!

Thank you for the update 🙏🏼

**Comment by JagoFigueroa** [comment]
We deployed a fix 😄 I've done a quick check and the chain looks stable again, was able to transact 🎉  let us know if all is good on your end too.

Cheers!

**Comment by inahlikenoother** [comment]
> We deployed a fix 😄 I've done a quick check and the chain looks stable again, was able to transact 🎉 let us know if all is good on your end too.
> 
> Cheers!

Thank you! Will let the user know
