### ISSUE TITLE
[Optimism] Unable to submit transaction, no Nonce

### ISSUE THREAD

**Issue by la1234512345** [5afe/safe-support#445]
### Issue Category

Transaction execution issue

### What happened?

- When creating any new transaction (sending erc20 token in this case) , Nonce appears as blank and cannot be edited
![image](https://github.com/5afe/safe-support/assets/114544040/c6b4a07c-7b4b-4016-a925-4b27a6a28898)
- Simulation shows as successful but when signed or executed, an error is returned
![image](https://github.com/5afe/safe-support/assets/114544040/86e59b7d-7d8b-4358-b7f1-e49010a7a268)

### Date and time this happened or you first noticed this issue

14-05-2024

### Network

Optimism

### Safe Address

0x71aC73a95f5b623ee70361BfA559F054Ddc06B6a

### Token Address

0x395Ae52bB17aef68C2888d941736A71dC6d4e125

### Token Type

ERC20

**Comment by JagoFigueroa** [comment]
Good morning! Could you re-check? to see if it was just a temporary indexing issue? Chain looks stable on my end, was able to transact without issues. 

If the user is still experiencing issues I will talk with the team, I see a big amount of transactions every day so that might be causing some issues with the nonces. 

Cheers!

**Comment by phoebe-serveth** [comment]
Hi @JagoFigueroa , received a response from the user today, and they are still experiencing the same issue when submitting a new transaction using the safe interface. According to the user, nothing has changed, and the same error continues to appear in the console logs. Additionally, the user is currently using a different interface to execute transactions, but there is still no nonce assigned in the transaction history. They made a basic interface to make transactions with calldata.

_These are the steps user did and still having the same issue:
Changing the RPC URL does not fix the issue. There are many APIs failing here.
For further context, in case this helps with debugging: I am using the Brave browser, but I have confirmed that turning off Brave shields does not prevent the errors. I am using Rainbow Wallet, but I have confirmed that using MetaMask or switching RPC URLs does not prevent the errors._

**Comment by JagoFigueroa** [comment]
Sorry for the delay! I have shared this with the team and we are checking 😄

**Comment by JagoFigueroa** [comment]
Good morning! Issue should be resolved now 😄

**Comment by Claire-serveth** [comment]
Thank you so much @JagoFigueroa closing this issue now. 🙏
