### ISSUE TITLE
[BNB] Cannot confirm transaction--getting NetworkError when attempting to fetch resource

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#446]
### Issue Category

Transaction execution issue

### What happened?

User was trying to sign/confirm transaction using Metamask wallet but getting this error instead:
![image](https://github.com/5afe/safe-support/assets/114005210/69ba68cc-eb90-415c-8422-4c45826a9e96)

Already tried basic troubleshooting steps--clear cache, hard refresh, use another browsers, changing RPCs, but issue still persists. User is not using VPN as well. Confirm button is also greyed out:
![image](https://github.com/5afe/safe-support/assets/114005210/33c67b94-3397-4ca5-b094-73a286102818)
![image](https://github.com/5afe/safe-support/assets/114005210/5e0b94af-9cbe-458c-9029-55ead39f0713)

Safe address: https://app.safe.global/transactions/queue?safe=bnb:0x24d953748be7D983f039248496Be283A28040f58

### Date and time this happened or you first noticed this issue

15-05-2024

### Network

Binance Smart Chain

### Safe Address

bnb:0x24d953748be7D983f039248496Be283A28040f58

### Token Type

None

### Transactions

```shell
Intercom: https://app.eu.intercom.com/a/inbox/pynbtguw/inbox/shared/all/conversation/212174700008136?view=List
```

**Comment by JagoFigueroa** [comment]
Hi there! I have been checking and our services look stable at the moment, was just able to transact on this chain. I can see some spikes in our response times during the time the user was trying to transact. Could they try again? just in case, do we know if the default RPC is being used? 

Cheers! 😄

**Comment by Claire-serveth** [comment]
Hi @JagoFigueroa thank you for the response. I'll check with the user if he's able to sign now. When you say default RPC, this is on the safe UI (Environment variables tab), right? I believe it's the default: 
![image](https://github.com/5afe/safe-support/assets/114005210/38af7585-a980-4ae6-83f5-af6f51dfca5c)

**Comment by Claire-serveth** [comment]
@JagoFigueroa the user tried again after a hard refresh, unfortunately, the issue still persists: 
![image](https://github.com/5afe/safe-support/assets/114005210/21e4264e-e278-428d-b5a8-a1654c21d4ac)

**Comment by JagoFigueroa** [comment]
Sorry for the delay! I can see that the user did manage to send the stuck transactions. All good? Do we know how he resolved it?

**Comment by Claire-serveth** [comment]
Hello @JagoFigueroa sorry for the delay, just got back from my RD. It was not solved yet for the specific owner having issues. Other owner did confirm and execute transactions. Also, the owner wallet having issues was already removed:
![image](https://github.com/5afe/safe-support/assets/114005210/52bfbdde-02f6-4763-b342-811b477f854e)

**Comment by JagoFigueroa** [comment]
Hi and sorry for the delay, most of the team was off last week (myself included) so catching up with support tickets again 😄 With the owner with issues gone it makes it a little bit tricky for me to further debug 😞  I can't see any new transactions since last time either. Could we know if any of the current owners has this issues? if they could queue a tx like last time that they cannot confirm that would be super helpful.

Thank you and sorry for the delay again 🙏

**Comment by Claire-serveth** [comment]
Hi @JagoFigueroa for sure, no problem at all. Unfortunately, the user was unresponsive and the ticket was already closed as well. But if ever the user responds or if I'll encounter the same issue in the future, I will respond here (and reopen the ticket). Closing this issue for now. Thank you so much again 🙏
