### ISSUE TITLE
Redeploy safe created through Gnosis chain relayer to ETH network

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#447]
### Issue Category

Other

### What happened?

User mistakenly transferred funds to Ethereum network instead of the Gnosis chain. As I checked, the proxy factory addresses for GNO and ETH safes match, which would be easier for the recreation, however the user's safe was created through a relayer. How to get the calldata for the safe creation transaction while the function is not createProxyWithNonce: 
![image](https://github.com/5afe/safe-support/assets/114005210/2fb2cfb7-d94f-4a7f-a7da-2b7836082309)

Safe address: gno:0x37a5E35D269fcD6bE19A5cadf1eC07c7314f8357
Safe creation tx: https://gnosisscan.io/tx/0x29fa9bee134daeb613e040bea21622203d07f22cf73b95022946f49b0638a439

By the way, should we continue to ask this type of query here or should we forward users to stackexchange directly?

### Date and time this happened or you first noticed this issue

15-05-2024

### Network

Ethereum Mainnet, Gnosis Chain

### Safe Address

0x37a5E35D269fcD6bE19A5cadf1eC07c7314f8357

### Token Type

None

### Transactions

Intercom: https://app.eu.intercom.com/a/inbox/pynbtguw/inbox/shared/all/conversation/212174700008142?view=List

**Comment by schmanu** [comment]
The data can be found in the transaction details.
The Relayer (Gelato) does a createProxyWithNonce call, from which the nonce and initializer data can be taken.

Here is the tenderly debugger for this transaction: https://dashboard.tenderly.co/tx/gnosis-chain/0x29fa9bee134daeb613e040bea21622203d07f22cf73b95022946f49b0638a439/debugger?trace=0.0.0.0

Looking into the createProxyWithNonce call it reveals these params:
```json
{
  "_singleton": "0x3e5c63644e683549055b9be8653de26e0b4cd36e",
  "initializer": "0xb63e800d0000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000140000000000000000000000000f48f2b2d2a534e402487b3ee7c18c33aec0fe5e400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000e20bab33d0ef71a71cd906dc64323833c1d8a2a0000000000000000000000000000000000000000000000000000000000000000",
  "saltNonce": "0"
}
```

That should result in the same address on mainnet.

**Comment by Claire-serveth** [comment]
Thank you @schmanu how to convert these params/view input to original?

**Comment by Claire-serveth** [comment]
@schmanu I tried simulating it on tenderly and just wanted to double check if this is the right raw input data: https://dashboard.tenderly.co/undoubted/project/simulator/88515dc3-bef8-44b0-87d5-74db93b5de53

`0x1688f0b90000000000000000000000003e5c63644e683549055b9be8653de26e0b4cd36e000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000164b63e800d0000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000140000000000000000000000000f48f2b2d2a534e402487b3ee7c18c33aec0fe5e400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000e20bab33d0ef71a71cd906dc64323833c1d8a2a000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000`

**Comment by mmv08** [comment]
> @schmanu I tried simulating it on tenderly and just wanted to double check if this is the right raw input data: https://dashboard.tenderly.co/undoubted/project/simulator/88515dc3-bef8-44b0-87d5-74db93b5de53
> 
> `0x1688f0b90000000000000000000000003e5c63644e683549055b9be8653de26e0b4cd36e000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000164b63e800d0000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000140000000000000000000000000f48f2b2d2a534e402487b3ee7c18c33aec0fe5e400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000e20bab33d0ef71a71cd906dc64323833c1d8a2a000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000`

Wow, you're a legend 💪 It is correct. You can verify it by checking the address in the `ProxyCreation` event on the events tab on the Tenderly simulation page.

![Screenshot 2024-05-15 at 22 25 37](https://github.com/5afe/safe-support/assets/16622558/cb5ab897-c1ab-482c-89b8-bb02e4fe58bd)

**Comment by Claire-serveth** [comment]
Hello @mmv08 apologies for the delayed response, I just got back from my RD. Thank you so much. Indeed, the user was able to recreate the same safe address successfully. Closing this issue now. 🙏
