### ISSUE TITLE
USDT token is not showing up on assets page ( Optimism)

### ISSUE THREAD

**Issue by jakekvm01** [5afe/safe-support#448]
### Issue Category

Token missing completely / not visible in the interface or service

### What happened?

USDT token is not showing up on assets page ( Optimism)

![image](https://github.com/5afe/safe-support/assets/105864754/fe23789a-fded-409e-bb64-925d938352b7)
![image](https://github.com/5afe/safe-support/assets/105864754/1979cbf4-74f5-475b-aca2-b78988950c00)

### Date and time this happened or you first noticed this issue

N/A

### Network

Optimism

### Safe Address

oeth:0x612e7Fa865E03F79531F530B650008467398E110

### Token Address

USDT 0x94b008aA00579c1307B0EF2c499aD98a8ce58e58

### Token Type

ERC20

**Comment by jakekvm01** [comment]
Following up on this. Thank you

**Comment by jakekvm01** [comment]
Closing this ticket now. Thank you

**Comment by FearlessThompson** [comment]
This wasn't resolved, could this be clarified on?

**Comment by liliya-soroka** [comment]
checking

**Comment by FearlessThompson** [comment]
Thank you

**Comment by liliya-soroka** [comment]
@FearlessThompson , please, re-check. We have re-indexed the safe and the balance is correct for me now

**Comment by FearlessThompson** [comment]
Thank you, the re-indexing worked
