### ISSUE TITLE
Can't load newly created safe on Arbitrum network

### ISSUE THREAD

**Issue by jakekvm01** [5afe/safe-support#449]
### Issue Category

Safe loading issue, doesnt load on any interface

### What happened?

Can't load newly created safe on Arbitrum network.

![image](https://github.com/5afe/safe-support/assets/105864754/e6f32297-1dff-48e3-b2b2-f2bdccfc179a)

### Date and time this happened or you first noticed this issue

N/A

### Network

Arbitrum

### Safe Address

arb1:0x0a29D934B5D133dA2BE8D13956F1ED834EDdAa32

### Token Address

N/A

### Token Type

None

**Comment by inahlikenoother** [comment]
Safe can already be loaded
