### ISSUE TITLE
NFTs not showing up in safe assets list

### ISSUE THREAD

**Issue by phoebe-serveth** [5afe/safe-support#45]
### Issue Category

Token missing completely / not visible in the interface or service

### What happened?

ERC721 NFTs are not showing up in asssets list but is visible in polygon scan.

$KMC Land Mystery Box
https://polygonscan.com/token/0x99501338585ac426c3afbe853ad64ea3c662a0b2?a=0x88c4bBC0394Bfa723803b68DEe3212098fFb6137
![image](https://user-images.githubusercontent.com/114040259/197685126-e3250c34-c81b-4842-8bed-6577241ef492.png)

### Date and time this happened or you first noticed this issue

25-10-2022 12:40 pm

### Network

Polygon

### Safe Address

0x88c4bBC0394Bfa723803b68DEe3212098fFb6137

### Token Address

0x99501338585Ac426C3aFBE853Ad64Ea3C662a0B2

### Token Type

ERC721

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by phoebe-serveth** [comment]
Thanks for the update @Uxio0 will let the user know.

**Comment by yagopv** [comment]
Hey @Uxio0 is this issue still relevant or can be closed?

**Comment by Uxio0** [comment]
It can be closed, as new website is using the new URL
