### ISSUE TITLE
[ZKsync] Unexpected delegate call warning when signing a message

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#451]
### Issue Category

Other

### What happened?

User interacted with one of the apps on the Safe apps list "Gelato" but getting an "Unexpected delegate call" warning. User already executed the transaction and wanted to know what the warning is about and if he should be worried knowing that it's been executed already.

Safe address: https://app.safe.global/transactions/history?safe=zksync:0x68930CDdfF1C0b2B19062f0a95149724990B9a1A 

![image](https://github.com/5afe/safe-support/assets/114005210/8d2f8474-e1e0-4beb-b65e-2daf9b4ffd9b)

### Date and time this happened or you first noticed this issue

20-05-2024

### Network

Ethereum Mainnet

### Token Address

zksync:0x68930CDdfF1C0b2B19062f0a95149724990B9a1A

### Token Type

None

**Comment by liliya-soroka** [comment]
the team is pinged to mark signMessageLib contact as trusted on zksync

**Comment by liliya-soroka** [comment]
done

**Comment by Claire-serveth** [comment]
Thank you @liliya-soroka closing this issue now 🙏
