### ISSUE TITLE
zksync - Can't send ETH out to another address

### ISSUE THREAD

**Issue by bingclo** [5afe/safe-support#454]
### Issue Category

Transaction execution issue

### What happened?

User is trying to send out all his ETH to his EOA wallet using the **Send** button in the interface but doesn't get sent. The transaction shows as sent however when checking in zksync etherscan it shows ETH as a token and gets sent back to the safe upon execution.

![image](https://github.com/5afe/safe-support/assets/54754746/0dc09143-88f7-4ddf-8ef4-6d03120eaacb)
![image](https://github.com/5afe/safe-support/assets/54754746/c85a876c-319a-4e40-a258-70cdd8456ff9)

User tried sending it to another address recently but still had the same behavior.

### Date and time this happened or you first noticed this issue

25/05/2024 20:57:29

### Network

Ethereum Mainnet

### Safe Address

https://app.safe.global/transactions/history?safe=zksync:0x259a0ef37dF2bAc3713FE8BB46AE1d9B76940f19

### Token Address

N/A (ETH)

### Token Type

None

### Transactions

```shell
https://era.zksync.network/tx/0x95ec0930ad30c4f3473aed52f04a0a6d18ec31180b91f5c884369991d3dd5e2b
```

**Comment by liliya-soroka** [comment]
checking ...

**Comment by liliya-soroka** [comment]
could we check if it's still an issue for the user?

**Comment by Claire-serveth** [comment]
Hi @liliya-soroka yes, the user is still unable to transfer the assets out from his safe account.

**Comment by Claire-serveth** [comment]
Hi @liliya-soroka we're still waiting for user's confirmation as he was not able to execute transaction since the issue was reported (May 26th). We'll definitely update you here as soon as we get the response from the user.

**Comment by Claire-serveth** [comment]
User is unresponsive; closing this issue for now and reopen should there be a need. 🙏
