### ISSUE TITLE
Getting "something went wrong, please try again later" error while accessing Transactions tab/history, Safe Apps tab on various networks

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#457]
### Issue Category

Safe loading issue, doesnt load on any interface

### What happened?

User can't access the transactions tab as it prompts with this error message:
![image](https://github.com/5afe/safe-support/assets/114005210/03de5920-313c-4296-8e6c-3453508e8774)

Safe: https://app.safe.global/transactions/history?safe=celo%3A0x0D9E269ECc319BAE886Dd8c8B98F7B89269C2B1B

### Date and time this happened or you first noticed this issue

29-05-2024

### Network

Volta

### Safe Address

celo:0x0D9E269ECc319BAE886Dd8c8B98F7B89269C2B1B

### Token Type

None

**Comment by jakekvm01** [comment]
User from Sepolia network can't access safe apps also. Getting same error. 
https://app.safe.global/apps?safe=sep:0x88f2178139Ed9F6D870b3afc293eb735F54d655e
![image](https://github.com/5afe/safe-support/assets/105864754/97558c19-3086-40a4-aa6f-92945f5826df)

**Comment by iamacook** [comment]
There was a configuration error on our end. This should now be solved.

**Comment by Claire-serveth** [comment]
Thank you so much @iamacook 🙏

**Comment by ribeirojose** [comment]
can confirm this has been solved on my end as well 👍

**Comment by Claire-serveth** [comment]
Issue resolved on users end as well. Closing this ticket now.
