### ISSUE TITLE
Scroll Network - Safe SDK could not be initialized

### ISSUE THREAD

**Issue by la1234512345** [5afe/safe-support#458]
### Issue Category

Other

### What happened?

When the user tries to create a transaction even for simple send of ETH, he gets this error: 
![image](https://github.com/5afe/safe-support/assets/114544040/0300e390-645d-4410-82fc-f8bd9dba8af5)
On the dev console
![image](https://github.com/5afe/safe-support/assets/114544040/324f3c74-e25f-45cf-9e7d-e1e4237507fe)

- Tried to have him change to atleast have RPCs, and tried using mobile browser as well, same error
- User is using Rabby but had him try Metamask as the signer as well, no hardware wallets, same error
- User is not using VPN nor does have access to one
- User is located in Lima,Peru

### Date and time this happened or you first noticed this issue

02/06/2024

### Network

Scroll

### Safe Address

0xA0A1EF804DA2927C2F1Ff55EE498afbe819C9190

### Token Type

None

**Comment by inahlikenoother** [comment]
I have another user experiencing the issue when trying to send out ETH
Safe: https://app.safe.global/home?safe=scr:0x3A17f10b4A5d64b3583960430521bC1E530D5d03
![Captura de pantalla 2024-06-03 032936](https://github.com/5afe/safe-support/assets/114049495/bdde58e5-0ad2-4c27-bb44-cd9d4a59f476)
![image](https://github.com/5afe/safe-support/assets/114049495/ca82481d-5ad7-4788-8658-db6b69767303)

**Comment by liliya-soroka** [comment]
checking...

**Comment by inahlikenoother** [comment]
> Could you get more details from the user:
> 
>     1. signer wallet
> 
>     2. rpc in the signer wallet
> 
> 
> I can not reproduce the issue and don't see any additional information from the user about the connected wallet

Hi @liliya-soroka , first user responded:
signer wallet: 0xe147d670f92887F507dCCd2c7777255370795F3e (Rabby)
RPCs used: https://scroll.blockpi.network/v1/rpc/public , https://scroll-mainnet.chainstacklabs.com/ , https://scroll.drpc.org/

**Comment by inahlikenoother** [comment]
> Could you get more details from the user:
> 
>     1. signer wallet
> 
>     2. rpc in the signer wallet
> 
> 
> I can not reproduce the issue and don't see any additional information from the user about the connected wallet

For second user:
signer wallet: 0x127aD227fB8a9F3B12984175260Dfc165CCDa8C8 (Rabby, also tried in MetaMask)
RPC used: https://rpc.scroll.io/

**Comment by liliya-soroka** [comment]
Dear support team, could you help us get more details for debuging? I will lead you how to do it for this issue, as we can not reproduce it on our side.
On the first screenshot, there is an error in the console related to the PRC https://rpc.scroll.io/. As the site can not get access to the RPC, our SDK can not be initialized. To get more details about CORS error for the https://rpc.scroll.io/ RPC, could you ask the user,when there is an CORS error for the RPC in console:
1. open Networks tab in the dev tool 
<img width="479" alt="image" src="https://github.com/5afe/safe-support/assets/338622/15ff4796-19c7-4bcb-840f-20878a0c737a">
2. find the request to RPC https://rpc.scroll.io/ nd click on it
3. check header to see the response status/ payload and response 
<img width="1436" alt="image" src="https://github.com/5afe/safe-support/assets/338622/db342f4c-8126-4a2b-ba0f-342a955ea82d">

**Comment by inahlikenoother** [comment]
> 1. in

Thank you Liliya, will ask both users who are experiencing the issue and will update here.

**Comment by liliya-soroka** [comment]
thank you , good to know. 
the user had 429 error - rate limit error. The information about the response to the RPC request was provided to the Scroll team for their official RPC https://rpc.scroll.io/

**Comment by inahlikenoother** [comment]
> thank you , good to know. the user had 429 error - rate limit error. The information about the response to the RPC request was provided to the Scroll team for their official RPC https://rpc.scroll.io/

Thank you Liliya. Here is a screenshot of the first user who had this issue with Safe scr:0xA0A1EF804DA2927C2F1Ff55EE498afbe819C9190 they just provided it today
![image](https://github.com/5afe/safe-support/assets/114049495/47e7ca36-5933-4857-9d5e-3b8e84154150)
![image-1](https://github.com/5afe/safe-support/assets/114049495/08b10ddd-e3cb-486c-a5a7-e84ced492f48)

**Comment by liliya-soroka** [comment]
thank you . I see that this is the same 429 too many requests. We have sent the information to the scroll team

**Comment by anitapatel20241** [comment]
> k you . I see that this is the same 429 too many requests. We have sent the information to the scroll t

I'm the wallet owner. Where can I follow the issue with the scroll team?   I'm surprised only me is complaining as I tried several wallets and all of them get the same error, now even when connecting to safe using scroll.

**Comment by anitapatel20241** [comment]
@liliya-soroka It just worked today. Seems the scroll team finally solved their issue. Thank you very much for your kind assistance with this.

**Comment by phoebe-serveth** [comment]
User confirmed it's working now, closing this ticket.
