### ISSUE TITLE
Optimism - Cannot load Safe

### ISSUE THREAD

**Issue by inahlikenoother** [5afe/safe-support#459]
### Issue Category

Safe loading issue, doesnt load on any interface

### What happened?

Newly created Safe cannot be loaded, and Safe address does not show in Safe transaction API 
![Safe-Wallet-99](https://github.com/5afe/safe-support/assets/114049495/f2a04a5c-8d2c-416e-b2fb-c7e8dd056370)
![image](https://github.com/5afe/safe-support/assets/114049495/d6aeac67-647e-4c10-a81a-2eab75610b6b)

Optimism status in https://safe-react-status.netlify.app/
![image](https://github.com/5afe/safe-support/assets/114049495/13010a8d-b964-47d6-ab25-9fa95b9fa916)

### Date and time this happened or you first noticed this issue

02-06-2024

### Network

Optimism

### Safe Address

0xF0E1c35f481E03CfFFbDc283121EfE393917b4Bd

### Token Type

None

### Transactions

```shell
Safe creation transaction hash: 
https://optimistic.etherscan.io/tx/0x77011b0a603c001dbee042efe197d5fccf1cb291e059f387816d74c691190793
```

**Comment by Claire-serveth** [comment]
I have another user having the same issue as well:
![image](https://github.com/5afe/safe-support/assets/114005210/2f5bc7f7-28d4-4ade-9311-ef4fe4261075)

**Comment by inahlikenoother** [comment]
I have 2 other users reporting the same behavior on OP network
1 another newly created Safe
1 Safe that is not new

**Comment by liliya-soroka** [comment]
Thank you for reporting.
There is ongoing indexing issue. The team is informed and checking 
<img width="1184" alt="image" src="https://github.com/5afe/safe-support/assets/338622/df20fced-4893-4bba-b337-b920f5ec7ce3">

**Comment by inahlikenoother** [comment]
I can already load 4 of my affected users' Safes :pray: 

Just waiting for their confirmation now before closing

**Comment by liliya-soroka** [comment]
The issue should be fixed now.
