### ISSUE TITLE
Unauthorized token approval

### ISSUE THREAD

**Issue by CindyLo0** [5afe/safe-support#46]
### Issue Category

Other

### What happened?

Hi team, 

A user reported a token transfer( 0 AWO token) was executed without any confirmation from the Safe. Please check screenshot: 

![image](https://user-images.githubusercontent.com/79137197/197737529-a3f0571e-daf1-4039-af48-e1b4d83deb4d.png)

The Safe address seems to have approved the Spender address but how was it able to approve without the confirmation and execution from the safe? I don't see any approval transaction on the Safe history.

![image](https://user-images.githubusercontent.com/79137197/197738004-cb97fb41-b312-49b4-94f5-ab01f3e1bb53.png)

### Date and time this happened or you first noticed this issue

25-10-2022 11:35

### Network

Ethereum Mainnet

### Safe Address

0xBffD0508679C19f12d1fCCc50b2A6f654892196d

### Token Address

0x68C85B9f78F30A0df5aC5723e4e700037f185415

### Token Type

ERC20

### Transactions

```shell
https://etherscan.io/tx/0x87f89b3a41376c34d3b958c5b47fba3fab7cb1c34b6142ec9e9abb7cb4591b0b
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mikhailxyz** [comment]
The token contract has a security flaw, and the `transferFrom/allowance` functions are public and not protected. For more information, the user should talk to the maintainers of the token contract.
