### ISSUE TITLE
USDC display seems broken

### ISSUE THREAD

**Issue by DanBigM** [5afe/safe-support#461]
### Issue Category

Transaction execution issue

### What happened?

strange display of USDC amount
![Screenshot 2024-06-10 160726](https://github.com/5afe/safe-support/assets/33380797/8d2a2d1c-53fe-40e2-91bc-5d7ff435d5e3)

### Date and time this happened or you first noticed this issue

10-06-2024

### Network

Ethereum Mainnet

### Safe Address

0x70608b1809c93Ec57160C266a38322144E9A9d28

### Token Address

usdc

### Token Type

ERC20

### Transactions

```shell
https://app.safe.global/transactions/queue?safe=eth:0x70608b1809c93Ec57160C266a38322144E9A9d28
```

**Comment by DanBigM** [comment]
in chrome, Version 125.0.6422.142 (Official Build) (64-bit)

**Comment by katspaugh** [comment]
It's displayed correctly in my Chrome (Mac).

**Comment by katspaugh** [comment]
This has been fixed by Redefine.
