### ISSUE TITLE
[ETH] Newly deployed token contract marked with warning sign on the UI

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#463]
### Issue Category

Other

### What happened?

User has a new project and their team wanted to use the safe to manage their treasury. But as they transferred their token into the safe, it shows the warning: _This token is unfamiliar and may pose risks when interacting with it or involved addresses_:
![image](https://github.com/5afe/safe-support/assets/114005210/d9b4a018-9caf-47f1-8829-d15918836f07)

Their IDO will happen on June 24th, thus need help to fix the problem.
Safe address: https://app.safe.global/transactions/history?safe=eth:0x210E9773f9de4CeE91079aCf8059CF79F5E6843C

### Date and time this happened or you first noticed this issue

17-06-2024

### Network

Ethereum Mainnet

### Safe Address

eth:0x210E9773f9de4CeE91079aCf8059CF79F5E6843C

### Token Address

0x55747be9F9f5BeB232aD59FE7aF013b81d95fD5e

### Token Type

ERC20

### Transactions

```shell
https://etherscan.io/tx/0x86c41c60b7173977b2ae853a6a2e1795feb9bca2ca5798b58305fb295f122ae4
```

**Comment by Uxio0** [comment]
We trust tokens in this list, so you need to contact coingecko: https://tokens.coingecko.com/uniswap/all.json

The list is automatically checked by the service once a day
