### ISSUE TITLE
Update token name in Assets

### ISSUE THREAD

**Issue by CindyLo0** [5afe/safe-support#465]
### Issue Category

Other

### What happened?

Hi team, is this something you can assist with? 
Destablecoin HAY was rebranded and is now known as ListaUSD.
![image](https://github.com/5afe/safe-support/assets/79137197/8660ead0-e781-448a-af4d-944a61bef417)
But still shows up as HAY in Safe Assets tab 
![image](https://github.com/5afe/safe-support/assets/79137197/11a32612-71e5-4a10-9ebf-c12e5649a84a)

### Date and time this happened or you first noticed this issue

06-19-2024

### Network

Binance Smart Chain

### Safe Address

bnb:0x34A6F643d25fea9E6b7FCEAA33CAF18e35a6e07f

### Token Address

0x0782b6d8c4551B9760e74c0545a9bCD90bdc41E5

### Token Type

None

**Comment by Uxio0** [comment]
Done!
