### ISSUE TITLE
Wrong USDC transferred?

### ISSUE THREAD

**Issue by DanBigM** [5afe/safe-support#466]
### Issue Category

Transaction execution issue

### What happened?

![Screenshot 2024-06-19 150534](https://github.com/5afe/safe-support/assets/33380797/976a4ef3-8a3f-4247-9254-d10ff0c096e4)

We did some USDC transactions and apparently a wrong token was sent instead of the USDC that we selected in the safe app: 

https://etherscan.io/tx/0xff6545cf09c49ead9a5c0bcbb2ddc4cf7613c2e5b175bb8b100ebc444b9f5265
https://etherscan.io/tx/0xb685a7f12a0317d1a1d30d76fce1fa8b4a4ad4bd9c66f752939a4bcaf13e175d

### Date and time this happened or you first noticed this issue

18-06-2024 18:00

### Network

Ethereum Mainnet

### Safe Address

0x70608b1809c93Ec57160C266a38322144E9A9d28

### Token Address

https://etherscan.io/token/0xfc2a0392c4b407fdc3a0bfea043be7520f73a901?a=0x70608b1809c93Ec57160C266a38322144E9A9d28

### Token Type

ERC20

### Transactions

```shell
link to the transactions on etherscan:
https://etherscan.io/token/0xfc2a0392c4b407fdc3a0bfea043be7520f73a901?a=0x70608b1809c93Ec57160C266a38322144E9A9d28


trx hashes shown in the safe wallet:
https://etherscan.io/tx/0xff6545cf09c49ead9a5c0bcbb2ddc4cf7613c2e5b175bb8b100ebc444b9f5265
https://etherscan.io/tx/0xb685a7f12a0317d1a1d30d76fce1fa8b4a4ad4bd9c66f752939a4bcaf13e175d
```

**Comment by JagoFigueroa** [comment]
Hello friend, this looks like an address poisoning attempt.

I can see that these transactions do not have a safeTxHash and they are just batching multiple txs from different addresses under the same transaction hash with the hopes that next time you guys try to send your USDC will copy / paste the recipient addresses under the attackers control of these malicious txs. See that the recipient addresses are extremely similar to the ones of the actual transactions from your safe with nonces 177, 178 & 179.

Scary stuff to say the least but the team is working on a solution to make these attacks harder on our UI. For now I would strongly recommend to click on this 'hide unknown' and should get rid of these: 
<img width="1359" alt="Screenshot 2024-06-19 at 16 06 44" src="https://github.com/5afe/safe-support/assets/92332710/7861b19e-4586-484f-807a-552c103ce199">

We have [this](https://safe.mirror.xyz/3Tv05rMXhD9-8QBt7-8BjS5k23SqycruAQvXfFNTgdg) help article too 🙏
