### ISSUE TITLE
Transaction executed without confirmation

### ISSUE THREAD

**Issue by phoebe-serveth** [5afe/safe-support#47]
### Issue Category

Transaction execution issue

### What happened?

User not really sure if he was able to confirm the transaction but it was successfully executed. Safe interface also shows 0 confirmation but it shows success in transaction history. 
![image](https://user-images.githubusercontent.com/114040259/198418512-5b610f8c-a58e-4d52-84f3-94827fce3ccb.png)

Arbiscan also shows that the next nonce is 32 and transaction hash is visible. 
https://arbiscan.io/tx/0xcef090f0faac47644fd589faeb7ee4c3ee45527223b8300bfa3efd7d9c7fab12
![image](https://user-images.githubusercontent.com/114040259/198418740-6c4833d2-9ae9-42a9-892b-c6818d17cae5.png)

### Date and time this happened or you first noticed this issue

28-10-2022 07:03

### Network

Arbitrum

### Safe Address

0x0B06DB2EdF040EEDeb956D81d388A6c5bCf5955B

### Transactions

```shell
https://arbiscan.io/tx/0xcef090f0faac47644fd589faeb7ee4c3ee45527223b8300bfa3efd7d9c7fab12
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mikhailxyz** [comment]
There was a lag on the backend. There's a confirmation displayed now.

![image](https://user-images.githubusercontent.com/16622558/198551165-90230715-e4e7-4da2-9c2d-0ebc0101dda3.png)
