### ISSUE TITLE
[ETH] Fiat value for Token RLC not updated

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#472]
### Issue Category

Other

### What happened?

The price for an asset (RLC token) on the UI is not updated/incorrect in a week (minimum). How long is the price fetched from coingecko or is there any problem fetching the token price?

This is the price on the UI:
![image](https://github.com/5afe/safe-support/assets/114005210/6f152327-0b32-4f2b-85b4-1b08762a6249)

The price on Zerion:
![image](https://github.com/5afe/safe-support/assets/114005210/7e723f27-60c4-4ac5-afb4-23bbbb46655f)

Safe address: https://app.safe.global/balances?safe=eth:0xD29adE8753570dae1740d7C58f75eFa60dB5e446

### Date and time this happened or you first noticed this issue

25-06-2024

### Network

Ethereum Mainnet

### Safe Address

eth:0xD29adE8753570dae1740d7C58f75eFa60dB5e446

### Token Address

0x607F4C5BB672230e8672085532f7e901544a7375

### Token Type

ERC20

**Comment by liliya-soroka** [comment]
checking with the team

**Comment by liliya-soroka** [comment]
The price was updated.
Thank you for reporting

**Comment by Claire-serveth** [comment]
Thank you so much @liliya-soroka 🙏 will let the user know.
