### ISSUE TITLE
[Arbitrum] No option to reject transaction

### ISSUE THREAD

**Issue by la1234512345** [5afe/safe-support#476]
### Issue Category

Other

### What happened?

1. User created transaction via API
2. User has been creating transactions via API and reject option has always been available 
3. Tried impersonating user's wallet and got the same result (no reject/delete button)
![image](https://github.com/5afe/safe-support/assets/114544040/3a351e6b-a001-4378-9af3-ebcad8fa36d2)

### Date and time this happened or you first noticed this issue

30-06-2024

### Network

Arbitrum

### Safe Address

0xf7EC8986c660Fa8269f6440A631B22337f398Ccd

### Token Type

None

**Comment by DefiDebauchery** [comment]
Turns out that transactions need at least one confirmation in order to show the Reject prompt.

I feel like this is changed behavior, but unsure how long that's been the case.

**Comment by liliya-soroka** [comment]
closed as expected result for unsigned txs
