### ISSUE TITLE
Queue Tab not updating

### ISSUE THREAD

**Issue by la1234512345** [5afe/safe-support#477]
### Issue Category

Other

### What happened?

User cannot execute Nonce 82. Despite Nonce 81 being executed already, Queue tab and Safe current nonce is still stuck on Nonce 81
![image](https://github.com/5afe/safe-support/assets/114544040/271682bb-2ea9-4232-a25e-4276ec9e35a5)
![image](https://github.com/5afe/safe-support/assets/114544040/066ce4bf-5533-4766-a461-a25c15f135f9)
![image](https://github.com/5afe/safe-support/assets/114544040/9a828645-bc22-4ec3-bccd-90eb71376ec5)

### Date and time this happened or you first noticed this issue

30-06-2024

### Network

Ethereum Mainnet

### Safe Address

0xbf9945BcAC6b8e4FfDB41337579306Fa33E79cfb

### Token Type

None

**Comment by inahlikenoother** [comment]
Hi team, also have another user that may have a related issue wherein he cannot execute transactions on ETH mainnet 
tx hashes 0xd9d68cf7bddc1f5ffbf58f2f57c6698550a2efe2aa400bdb6226927c64e1e348, 0x50df76ff3812a8cd1da5983e6b815f5b29f4004dec46ace4bd524379832645a0
Safe eth:0x129f35cDa830eA48B343a48728c2e384Ca956776, eth:0x20b80e9D37255Bc2B8Be20224A9c5636C368C8F3

**Comment by la1234512345** [comment]
Users are still reporting as of this moment but usually gets resolved within 15-30 minutes

**Comment by liliya-soroka** [comment]
Please, use delay tag for the complaints related to the issue 
We are on it and checking with the team

**Comment by Claire-serveth** [comment]
Hi @liliya-soroka we have another user having a delay issue on ETH network. User is trying to execute a uniswap multicall transaction (Nonce 16). But it seems the UI updated after 10 minutes. Safe transaction hashes: 
Original: 0x4a52c5581416cb8cca36adb98331d7cafe1cbbf642c93203aa44c4d7d15ad5f4
Replaced: 0xa1ac8656204f6981a23d620b789fb7952a4dd539be4e7ac82f698d5ea7bdf2a2

![image](https://github.com/5afe/safe-support/assets/114005210/d22bdb60-cab9-40ee-bd16-3e9c3ec5fd1a)

Safe address: https://app.safe.global/transactions/history?safe=eth:0x11116B04C19aC7266c856CdC623B2903e102218d

**Comment by inahlikenoother** [comment]
Hi team, another Safe where queue tab is not updating 
![image](https://github.com/user-attachments/assets/dc959990-d998-4bde-957a-d9db0b3ea7ab)
![image](https://github.com/user-attachments/assets/f3eaa16b-dcdd-4f91-814b-8d05e5ca8ca3)

Safe: https://app.safe.global/transactions/queue?safe=eth:0xe705b1D26B85c9F9f91A3690079D336295F14F08****

**Comment by liliya-soroka** [comment]
Hey, dear support team, do we still have reports about delays on Ethereum? If so, could you ping me immediately with a link to the intercom conversation or safe data? We will have only 10 minutes before cache invalidation to debug.

**Comment by Claire-serveth** [comment]
Hi @liliya-soroka yes, there is from time to time but when they reach out to us and after few minutes, the UI updates already before we can report here. But we'll definitely do this, will ping you on the intercom ticket directly as well. 🙏

**Comment by la1234512345** [comment]
Hi @liliya-soroka we have another user experiencing the issue eth:0x1D6b52532Fb4432198e30b29945aa2890F59C246

**Comment by Claire-serveth** [comment]
Escalations for delay issues is now via intercom ticket with Rudy. Closing this issue now.
