### ISSUE TITLE
[Matic] Sign button greyed out; getting Safe SDK could not be initialized and unsupported base contract errors

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#478]
### Issue Category

Transaction execution issue

### What happened?

User is trying to transfer USDC from his safe but unable to do so since the sign button is greyed out and getting the following errors shown on the SS: 
![image](https://github.com/5afe/safe-support/assets/114005210/98385094-15a1-49fc-94d3-392402d2bd78)

Already tried basic TS, importing wallet to metamask but still getting the same error. I also tried impersonating the user's account but also having the same issue on my end.

User was able to successfully execute transactions from the previous days (but not now):
![image](https://github.com/5afe/safe-support/assets/114005210/9b4519c4-98be-41af-9499-767a8418af56)

Safe address: https://app.safe.global/home?safe=matic:0x5A3e1E40CE6EFaBA3a4180f3d58b6d86cC90d76f
User is not technical, so he's only relying on the UI.

### Date and time this happened or you first noticed this issue

01-07-2024

### Network

Polygon

### Safe Address

matic:0x5A3e1E40CE6EFaBA3a4180f3d58b6d86cC90d76f

### Token Type

None

### Transactions

```shell
https://app.eu.intercom.com/a/inbox/pynbtguw/inbox/shared/all/conversation/212174700009077?view=List
```

**Comment by liliya-soroka** [comment]
As the message says, the safe is unsupported by our UI  base version. Please, use Safe_CLI to interact with the safe 
<img width="352" alt="image" src="https://github.com/5afe/safe-support/assets/338622/3bcb9aed-b968-452a-838e-7335b802e63c">

**Comment by liliya-soroka** [comment]
checking with the team. 
Thank you for reporting

**Comment by Claire-serveth** [comment]
Thank you @liliya-soroka 🙏

**Comment by liliya-soroka** [comment]
The issue was fixed - https://github.com/safe-global/safe-wallet-web/pull/3868 and will be included into next release

**Comment by Claire-serveth** [comment]
Thanks again @liliya-soroka will let the user know 🙏

**Comment by liliya-soroka** [comment]
@Claire-serveth , sorry, the comment above was related to the Nan for Matic in csv file

**Comment by Claire-serveth** [comment]
Yeah, that what I thought so too 😅 thank you for the confirmation @liliya-soroka 🙏

**Comment by Claire-serveth** [comment]
Hi @liliya-soroka / team, user is following up on this issue, do we have an update on this one?

**Comment by liliya-soroka** [comment]
do we have an update from the user? If yes, could you link me to the conversation in the intercom to get more details about the issue.
The fix I wrote above was released 2 weeks ago on Friday

**Comment by Claire-serveth** [comment]
@liliya-soroka here's the intercom link: https://app.eu.intercom.com/a/inbox/pynbtguw/inbox/admin/50011286/conversation/212174700009077?view=List

I don't see any new transaction from the user's account but I can check with the user as well. 🙏

**Comment by Claire-serveth** [comment]
User is unresponsive and was able to execute transactions already. Closing this issue now.
