### ISSUE TITLE
Clicking on Ellipal wallet when adding an Owner key redirects to Ellipal website instead of the wallet

### ISSUE THREAD

**Issue by inahlikenoother** [5afe/safe-support#479]
### Issue Category

Other

### What happened?

User said when adding an owner key and when selecting Ellipal wallet, it redirects to the Ellipal website instead of the wallet app. When selecting other wallets it redirects to the wallet app just fine
![IMG_6511-1](https://github.com/5afe/safe-support/assets/114049495/e6401fbf-31a4-49d5-b5d1-992e0b259c18)
![image](https://github.com/5afe/safe-support/assets/114049495/7f460eb3-ef72-4320-b797-127c2fce74e0)
![IMG_6512-1](https://github.com/5afe/safe-support/assets/114049495/db5650d4-2eb1-4912-bb15-9735b970380b)
User also said app is up to date and no pending updates from app store

### Date and time this happened or you first noticed this issue

01-07-2024

### Network

Ethereum Mainnet

### Token Type

None

**Comment by DmitryBespalov** [comment]
I have checked and this is an issue on the ellipal's wallet website or an app. The app should support universal linking, but it doesn't. 
Did the user check that the Ellipal wallet works with wallet connect with other dapps?

**Comment by inahlikenoother** [comment]
> the Ellipal wallet works with wallet connect with other dapps?

Will ask the user and update here :pray:

**Comment by inahlikenoother** [comment]
> I have checked and this is an issue on the ellipal's wallet website or an app. The app should support universal linking, but it doesn't. Did the user check that the Ellipal wallet works with wallet connect with other dapps?

Hi team, just got an update from user today and user said Ellipal wallet works with walletconnect with other dApps. I also advised to try to connect via WalletConnect for now and it does work, however when selecting Ellipal wallet from the list redirects to their website instead of the wallet app 
![IMG_6578](https://github.com/5afe/safe-support/assets/114049495/801607a8-2ade-4ecb-8567-6d8eb6154924)

**Comment by DmitryBespalov** [comment]
sorry, I couldn't make the ellipal wallet work with the app. Please advise to contact the ellipal support or use another wallet.

**Comment by inahlikenoother** [comment]
> sorry, I couldn't make the ellipal wallet work with the app. Please advise to contact the ellipal support or use another wallet.

Thank you, will do!
