### ISSUE TITLE
[iOS] Cannot enable Push notifications, WalletConnect + Trust wallet and Argent wallet

### ISSUE THREAD

**Issue by phoebe-serveth** [5afe/safe-support#480]
### Issue Category

Other

### What happened?

When enabling Push notifications, it opens trust wallet app but nothing happens. Owner key connected via Walletconnect + Trustwallet.
With argent wallet, the approve button is not clickable when enabling Push notifications. 
![image](https://github.com/5afe/safe-support/assets/114040259/54cd207f-457e-49f1-8aef-f31a8398ff8c)

Safe mobile app version: 3.26.0 (2015)
Device: iPhone 15, iOS version 17.5.1 
I was able to replicate issue with Trust wallet with iOS version 17.4 as well.

### Date and time this happened or you first noticed this issue

04-07-2024 8:00 pm

### Network

Ethereum Mainnet

### Token Type

None

**Comment by schmanu** [comment]
Sadly the notifications backend currently does not support 1271 at the moment. So it won't be possible to subscribe with Smart Accounts.

**Comment by schmanu** [comment]
In order to sign up for notifications the wallet has to sign a message. But currently we only support signatures which are made by private key based accounts. Not smart accounts. In order to validate signatures of smart accounts the EIP 1271 Standard has to be supported.

**Comment by phoebe-serveth** [comment]
Hi @schmanu, Thanks for the update. I did try to enable push notifications with trust wallet created via secret phrase that is imported via WalletConnect but nothing happens. It opens the trust wallet app but there is no prompt to sign or approve a message. Also tried to click on "Confirm to receive push notifications" upon importing keys but it's still not enabled.

**Comment by liliya-soroka** [comment]
1. Make sure that the network in the safe mobile app is the same as the networks in the Trust wallet
2. as for push notifications enabling old "eth_sign" is used, you will need to allow it in the trust settings ->security to be able to use push notifications

**Comment by liliya-soroka** [comment]
Any update from the user?

**Comment by Claire-serveth** [comment]
Hi @liliya-soroka I can't seem to find the user's ticket. I'll go ahead and close this ticket for now and reopen should the issue still persists. Thank you 🙏
