### ISSUE TITLE
[Base] Enemyo token (ERC20) does not appear in Assets page

### ISSUE THREAD

**Issue by phoebe-serveth** [5afe/safe-support#483]
### Issue Category

Token missing completely / not visible in the interface or service
### What happened?

User sent Enemyo tokens to their Safe in base network but it doesn't appear in the Assets page. Transaction history does not show the token name as well. 
![image](https://github.com/user-attachments/assets/3d1dafc6-8ab1-4117-9060-2cb50612332b)

### Date and time this happened or you first noticed this issue

13-07-2024 2:00

### Network

Base

### Safe Address

base:0xcb963A3E3146a4C41B7C1123db0cc0acd3DDfeC3

### Token Address

0x910Ca0e53280b48413C642432449E187e9bB7464

### Token Type

ERC20

**Comment by JagoFigueroa** [comment]
Hi! Token is listed now. 

Similar to this [ticket](https://github.com/5afe/safe-support/issues/484) we are experiencing some issues with token listings that were fixed and deployed later today 😄 

Cheers!

**Comment by phoebe-serveth** [comment]
@JagoFigueroa Thank you. The token is now showing up in the Assets page. Closing this now.
