### ISSUE TITLE
[AVAX] Token does not show up in UI

### ISSUE THREAD

**Issue by joanpan** [5afe/safe-support#484]
### Issue Category

Token missing completely / not visible in the interface or service

### What happened?

The Ultravioleta Token (ERC20 standard) is not appearing in the UI. Token address: 0x281027C6a46142D6FC57f12665147221CE69Af33

Initially, there was an original Ultravioleta Token (showed up in the UI), but it got hacked, so they had to create a new one. The new token was minted before the compromised one was burned. Now, the new token doesn't show up.

### Date and time this happened or you first noticed this issue

13-07-2024

### Network

Avalanche

### Safe Address

avax:0x52110a2Cc8B6bBf846101265edAAe34E753f3389

### Token Address

0x281027C6a46142D6FC57f12665147221CE69Af33

### Token Type

None

**Comment by JagoFigueroa** [comment]
Hello! I can see the token displaying as expected now 😄

**Comment by 0xultravioleta** [comment]
i can confirm its all good now guys, thanks for the quick help!
![image](https://github.com/user-attachments/assets/3657b244-bced-4c48-b248-86cd25ec9ccf)
