### ISSUE TITLE
[ETH] Token missing/not showing up on the UI

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#486]
### Issue Category

Token missing completely / not visible in the interface or service

### What happened?

SPACE-iZ Token (SPIZ) is not showing up on the UI after they were successfully received about an hour now. Other asset like USDT, was updated immediately:
![image](https://github.com/user-attachments/assets/a1852a67-6c49-4b8e-a5c2-08527b27a21a)

Also, token shows a warning sign on transactions history:
![image](https://github.com/user-attachments/assets/673e0cd5-09df-4208-b699-6bc2822d5787)

Safe address: https://app.safe.global/balances?safe=eth:0xE505af95F117d4A6Bfd8e6582b9368E153F26De0

### Date and time this happened or you first noticed this issue

15-07-2024

### Network

Ethereum Mainnet

### Safe Address

eth:0xE505af95F117d4A6Bfd8e6582b9368E153F26De0

### Token Address

0xa7A5c1058194Af8F00c187adB7FcC0c95f1C6c2d

### Token Type

None

**Comment by JagoFigueroa** [comment]
Issues with missing tokens should be resolved now, let us know 😄

**Comment by Claire-serveth** [comment]
Thank you so much @JagoFigueroa tokens are indeed showing up now. Closing this issue 🙏
