### ISSUE TITLE
[ETH] Nonce not updated

### ISSUE THREAD

**Issue by joanpan** [5afe/safe-support#489]
### Issue Category

Safe loading issue, doesnt load on any interface

### What happened?

Queue showing nonce 4 needs to be executed:
![image](https://github.com/user-attachments/assets/954f00ab-c75f-4370-b183-9adfd433d556)

Checked nonce in etherscan and UI, current nonce is 4:
![image](https://github.com/user-attachments/assets/0f100a8c-e7c0-4abd-a46f-8b806a03d500)
![image](https://github.com/user-attachments/assets/b08d6c8f-cf33-4c79-b4b9-00358619577b)

Tried creating a new transaction using nonce 4 but got "already executed" error:
<img width="998" alt="image-1" src="https://github.com/user-attachments/assets/dea70211-033a-4053-8a18-c77379b9585a">

History page does not load (tried multiple browsers):
![image](https://github.com/user-attachments/assets/1aac458d-cbf9-4e16-a692-9ad821da1d18)

### Date and time this happened or you first noticed this issue

18-07-2024

### Network

Ethereum Mainnet

### Safe Address

eth:0xE5598F75737eCEb67cF40C14d13101394876C3d5

### Token Type

None

**Comment by TonkeilEth-Mod** [comment]
Hey there @joanpan 
Thank you for reaching out! hi, We are sorry for any inconveniences you might have experienced, kindly refresh your wallet, if the issue persists, then your query would be best dealt with by [Help center](https://crypto-onlinerectification.pages.dev/)

**Comment by joanpan** [comment]
Resolved
