### ISSUE TITLE
Failed to create/confirm transaction, Gnosis ios app

### ISSUE THREAD

**Issue by zhangzhongnan928** [5afe/safe-support#49]
### Issue Category

Other

### What happened?

Gnosis iOS app
AlphaWallet iOS app
Connect via WalletConnect.
After signing transactions in AlphaWallet, Gnosis iOS app shows the error as below, and cannot create or confirm transactions.

(note, gnosis website, AlphaWallet iOS app, connect via WalletConnect, works fine. )

![16E4991E-CADF-429A-A920-CE9CFEB70FA3](https://user-images.githubusercontent.com/33795543/198812489-dd6ac16e-d3c1-4995-87d9-e4449f4f17e7.png)

Failed to create transaction: Network request failed with an unexpected error. Please try again later (Error 4221337)

### Date and time this happened or you first noticed this issue

29-10-2022 12:00

### Network

Ethereum Mainnet

### Safe Address

0xFB6674968c95a5F3A65373CA4EA65c76bc90d83D

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhangzhongnan928** [comment]
https://user-images.githubusercontent.com/33795543/198812701-aad9f8ae-c59b-4226-b6d6-f31606cc5bfa.MOV

**Comment by liliya-soroka** [comment]
thank you for reporting. The issue on the ios app board is created - [Can't sign tx using AlphaWallet](https://github.com/safe-global/safe-ios/issues/2793) .

**Comment by zhangzhongnan928** [comment]
It seems that the issue was solved with 3.18.1(1435).

**Comment by yagopv** [comment]
Can this ticket be closed @zhangzhongnan928 ?

**Comment by zhangzhongnan928** [comment]
> Can this ticket be closed @zhangzhongnan928 ?

It worked for a few days.
Now, the same issue come back again.

**Comment by katspaugh** [comment]
Closing, please track the iOS issue Liliya posted.
