### ISSUE TITLE
[Ethereum] Cannot create a new transaction, unable to edit nonce, History not loading

### ISSUE THREAD

**Issue by phoebe-serveth** [5afe/safe-support#494]
### Issue Category

Transaction execution issue

### What happened?

User cannot create a new transaction, receiving an error stating that nonce 8 has already been executed in tx hash https://etherscan.io/tx/0x61f2fcd0aacfc74878499493e2bd9230e05241f94ceb9056ec5bac3626887cfc However, both Etherscan and Safe UI show that the current nonce is 8. Edit nonce option is also greyed out, preventing the user from editing the nonce when creating the transaction
![image](https://github.com/user-attachments/assets/6817e7dc-5aa3-4ef2-9ecb-4b9b23b2d40e)
![image](https://github.com/user-attachments/assets/cf7a2ed8-229a-482b-b067-4d6e2f099e55)
![image](https://github.com/user-attachments/assets/622fe436-2c2d-4c1e-a48b-5f079a75de94)
Transaction service shows nonce 8 is already executed 
![image](https://github.com/user-attachments/assets/efd088c6-83c7-43e8-b75f-033c7667510b)
Transaction history is not showing up as well. 
![image](https://github.com/user-attachments/assets/bd6b8422-ab3a-4de9-9345-421d9d20c6a9)
User has other safes on ETH mainnet that work fine; only this particular safe is experiencing issues eth:0xAD463DE7B7a071BC4C1AAC9bbd6eDeA09CB69aab 
Errors in console logs:
![image](https://github.com/user-attachments/assets/20b548c1-4e3a-4ca4-866e-8ec10112b614)

### Date and time this happened or you first noticed this issue

07-30-2024 10:00pm

### Network

Ethereum Mainnet

### Safe Address

0xAD463DE7B7a071BC4C1AAC9bbd6eDeA09CB69aab

### Token Type

None

**Comment by liliya-soroka** [comment]
reported to the team

**Comment by liliya-soroka** [comment]
Please, re-check with the user. The history is loaded now

**Comment by Claire-serveth** [comment]
Thank you @liliya-soroka 🙏 closing this issue now.
