### ISSUE TITLE
CSV airdrop app cannot be loaded 

### ISSUE THREAD

**Issue by CindyLo0** [5afe/safe-support#495]
### Issue Category

Other

### What happened?

CSV airdrop app cannot be loaded. Seems to be an issue on all chains. 
Getting error below: 
![image](https://github.com/user-attachments/assets/06ff526e-dd02-40d4-a6e5-891f493b6782)

### Date and time this happened or you first noticed this issue

01-08-2024 15:30

### Network

Ethereum Mainnet

### Token Type

None

**Comment by katspaugh** [comment]
Looks like IPFS issues again, cc @schmanu

**Comment by schmanu** [comment]
Hmm it loads for me without issues. The app is still being served from the dedicated Infura gateway. This should at least happen way less frequent.

**Comment by liliya-soroka** [comment]
please, check with the user and ping us if it's still an issue

**Comment by Claire-serveth** [comment]
I can't seem to find the ticket. I'll close this issue for now and reopen should the issue still persists. Thank you @liliya-soroka 🙏
