### ISSUE TITLE
Issues to connect Ledger to Safe app

### ISSUE THREAD

**Issue by DanBigM** [5afe/safe-support#496]
### Issue Category

Safe loading issue, doesnt load on any interface

### What happened?

Not sure whether I chose the right category. 
I use ledger Nano S, recently upgraded to OS 1.1.2 - when the troubles started. 
First I couldn't connect the ledger "Ledger device is locked, please unlock to continue" was always the feedback. I tried many times, different browsers, restarted, made sure it was nowhere else connected - and suddenly it worked when I was connecting from the "settings" page of the safe wallet. 
Now i have another error for another transaction - I can connect to the wallet but when I try to execute, it tells me that "You are currently not a signer of this Safe Account and won't be able to submit this transaction."
2 other people have confirmed that I'm actually a signer in that wallet. Every time I try to execute, it automatically disconnects the ledger from the wallet. 

### Date and time this happened or you first noticed this issue

31-07-2024

### Network

Ethereum Mainnet

### Safe Address

0x07e5069f8f8E6a80432B13F20E9D4906de097E1A

### Token Type

ERC20

### Transactions

```shell
https://app.safe.global/transactions/queue?safe=arb1:0xcede5f45a568C31a9F0997434cD8782BeC6fac4a
```

**Comment by liliya-soroka** [comment]
Thank you for reporting . The issue was reported to the team.
This is the ticket to follow the progress - https://github.com/safe-global/safe-wallet-web/issues/4041

**Comment by liliya-soroka** [comment]
Please, follow the conversation in the ticket above
