### ISSUE TITLE
Can't update safe contract version 0.1.0 to the latest version

### ISSUE THREAD

**Issue by jakekvm01** [5afe/safe-support#497]
### Issue Category

Other

### What happened?

Can't update safe contract version 0.1.0 to the latest version.

Can't sign the update transaction via webapp.

![image](https://github.com/user-attachments/assets/0ae82457-ac4c-4ccc-9af7-7fb16e2e5ecc)

Via mobile
![image](https://github.com/user-attachments/assets/d204bff3-8071-40d1-96df-43a00e9074aa)

![image](https://github.com/user-attachments/assets/71b6072a-526a-4e51-bdd8-8f7a50df25df)

### Date and time this happened or you first noticed this issue

N/A

### Network

Ethereum Mainnet

### Safe Address

https://app.safe.global/home?safe=eth:0x055AbeCBC7bB298721Fd0a52510D5ef04d4E0411

### Token Address

N/A

### Token Type

None

**Comment by liliya-soroka** [comment]
what the mobile app is used for the update ? we don't have such screen in our official ios and android appsand mobile apps don't support 0.1.0 mastercopy contract  
<img width="451" alt="image" src="https://github.com/user-attachments/assets/a993112d-fc9f-4be1-9fac-f59e64babd23">

**Comment by felixww1** [comment]
![IMG_3502 PNG](https://github.com/user-attachments/assets/276fe6b6-a171-4af8-a18b-7f00783d425d)
It's old ios version safe wallet .

**Comment by liliya-soroka** [comment]
we can suggest the same as was in the previous ticket related to the 0.1.0 update - https://github.com/5afe/safe-support/issues/106#issuecomment-1365744796

**Comment by liliya-soroka** [comment]
the ticket is closed; please, use the safe-cli tool to update the safe
