### ISSUE TITLE
[Scroll] server response 500 when trying to execute a transaction in Scroll

### ISSUE THREAD

**Issue by bingclo** [5afe/safe-support#498]
### Issue Category

Transaction execution issue

### What happened?

User gets this error when trying to execute a swap: 
<img width="642" alt="Screenshot 2024-08-03 at 12 06 12 PM" src="https://github.com/user-attachments/assets/1b0f760b-6a3d-41fc-a96c-fb7a3dea6368">

Swap already expired but user mentioned he did not let it expire and still got the error. Impersonated user's wallets and got the same error. Changing RPC in Settings > Environment variables works

Choosing to execute later also gives the error: 
![image](https://github.com/user-attachments/assets/0619cec8-0a37-470f-9b57-99b47dfd3758)

Changing RPC in Settings > Environment variables works

### Date and time this happened or you first noticed this issue

03/08/2024 21:21:59

### Network

Ethereum Mainnet

### Safe Address

0x4F99453412F1246a141fb0d80424eef493D454c5

### Token Type

ERC20

### Transactions

```shell
N/A
```

**Comment by la1234512345** [comment]
Another user in Scroll Network having the issue 0xa09b87d045AD746ac48652478a8105B14172718A

**Comment by la1234512345** [comment]
Adding another wallet affected 0x09c304334F075D5E56B1AF5b699F3FD162770155

**Comment by liliya-soroka** [comment]
checking the RPC with the team ... we will update it soon

**Comment by liliya-soroka** [comment]
The RPC was updated. Let us know if there are any issues

**Comment by Claire-serveth** [comment]
Thank you @liliya-soroka already informed the user and still waiting for his response. 🙏

**Comment by Claire-serveth** [comment]
User was unresponsive; closing this issue now.
