### ISSUE TITLE
Base - Assets/Balance not updating

### ISSUE THREAD

**Issue by inahlikenoother** [5afe/safe-support#499]
### Issue Category

Token missing completely / not visible in the interface or service

### What happened?

User deposited 0.99 USDC to his Safe 2 hours ago, and until now it's not showing in the Safe interface. The USDC is showing in the block explorer, but not in the Safe interface
![image](https://github.com/user-attachments/assets/f2aa1ff1-cac4-4282-b6f4-aa21302dd40e)
![image](https://github.com/user-attachments/assets/84eb3c3a-ab4b-40ec-8bbf-f4ae2934a0f0)

https://app.safe.global/balances?safe=base:0x6AAfFe5364E67aD00BE7732C4ba4D902E9e64168

### Date and time this happened or you first noticed this issue

04-08-2024

### Network

Base

### Safe Address

0x6AAfFe5364E67aD00BE7732C4ba4D902E9e64168

### Token Type

None

### Transactions

```shell
https://basescan.org/tx/0x2404d14b556d00ee8a1a6760306c105328fe963acb69ac4d625a2005ed637f4a
```

**Comment by liliya-soroka** [comment]
The balance is updated

**Comment by inahlikenoother** [comment]
> The balance is updated

Thank you Liliya, just saw it now too. It took almost 24 hours for it to reflect on the web app. Will let the user know
