### ISSUE TITLE
Cannot connect Metamask through Wallet connect on Safe desktop app

### ISSUE THREAD

**Issue by la1234512345** [5afe/safe-support#50]
### Issue Category

Other

### What happened?

-User is unable to connect Metamask through Walletconnect in safe desktop app, doesn't return any error
-Restarted computer, disabled VPN, still not able to connect
-User upgraded to Safe desktop app v3.22.1, still not able to connect
-Tried isolating using web app and connected still through Walletconnect, no issues when using web app and have connected successfully
-User to use web app temporarily, issue with desktop app still persist
-Device used: Mac OS v12.6

### Date and time this happened or you first noticed this issue

18-10-2022 06:00

### Network

Ethereum Mainnet

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oceanemil** [comment]
Same issue MacOS  v13.0.1
Cannot connect Trust via Wallet connect on Safe desktop app (v3.22.1) on MacOS

**Comment by jakekvm01** [comment]
I'm having the same issue with this user https://app.intercom.com/a/inbox/km54f6ih/inbox/shared/all/conversation/36000020700?view=List using Windows 10. Can't connect metamask wallet via walletconnect in Goerli network.

gor:0xE30A8B7F6bc8688FA7539f175d5255c071d7C4EC

**Comment by ennisjo** [comment]
@dasanra @JagoFigueroa  - could the safe apps team test this? Or should we communicate something to the users here surrounding the desktop app and MM<>WC? i.e. will this fix be in the next version or there is no plan for a new version anytime soon.

**Comment by JagoFigueroa** [comment]
Hola team! We have just finished preparing and testing a new release for the desktop app that should arrive this week and fix these WC connection issues. Will post another comment in here as soon as it is live 😄

**Comment by JagoFigueroa** [comment]
New release of the desktop app was deployed solving this issue 😎
