### ISSUE TITLE
tx no longer appears in the web UI (but shows up in safe-cli)

### ISSUE THREAD

**Issue by ratio91** [5afe/safe-support#500]
### Issue Category

Transaction missing / not visible in app or service

### What happened?

We have set up a Safe on Polygon as a "replay transaction" from our Safe on Ethereum and are experiencing issues with executing a single transaction to transfer ownership away from a contract. We are already using the Safe CLI, but unfortunately, we cannot import private keys due to "social reasons" (2 ex employees would never give us their private keys). Unfortunately, the transactions no longer appear in the web UI.

Safe TX Hash: `0x8ce355eacf6a479ca51ed1287100a78859d7738aleed2fe1640882da5a915ec4`

### Date and time this happened or you first noticed this issue

2024-08-09

### Network

Polygon

### Safe Address

0x088a012BF6d510aa923c814eA83807f75F7061A0

### Token Type

None

**Comment by ratio91** [comment]
since we replayed the L1 tx on L2 - the indexer has not picked up the safe-tx 0x8ce355eacf6a479ca51ed1287100a78859d7738aleed2fe1640882da5a915ec4

Can it be added manually?

again, we would love to use safe-cli, but while the ex-employees are willingto SIGN tx via the safe-UI, they are NOT willing to hand us their private keys directly - which would be needed in order to sign a tx via the safe-cli, correct?

**Comment by moisses89** [comment]
Got it 
They can use the cli to add locally their keys and sign the transaction from the safe-cli, following the next steps:
- change to transaction service mode by `tx-service` command
- load the owners with `load_cli_owners <account-private-key> `
- sign the transaction with `sign-tx <safe-tx-hash>` 
After collect the signatures you can execute the transaction with `execute-tx <safe-tx-hash>`
![image](https://github.com/user-attachments/assets/a5d14fce-0278-45bc-89c1-43451ea782d7)

**Comment by liliya-soroka** [comment]
@ratio91 , did the comment above help?

**Comment by ratio91** [comment]
thank you, we can consider this ticket as solved.
