### ISSUE TITLE
[CELO] CELO tokens shown twice on the assets page 

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#501]
### Issue Category

Other

### What happened?

User reported that there are two (2) CELO tokens shown on the UI but when checking on the blockchain there's only one CELO token:
![image](https://github.com/user-attachments/assets/93c6ecbb-6073-43b4-a462-eb849db5a516)
![image](https://github.com/user-attachments/assets/39c3be54-67c7-472c-aaa6-3224c27238b6)

Issue has been present for over 3 weeks now.
Safe address: https://app.safe.global/balances?safe=celo:0x40713Ca5223eFb79E861E282495092D2563c1eCE

### Date and time this happened or you first noticed this issue

12-08-2024

### Network

Energy Web Chain Mainent

### Safe Address

celo:0x40713Ca5223eFb79E861E282495092D2563c1eCE

### Token Address

0x471EcE3750Da237f93B8E339c536989b8978a438

### Token Type

None

### Transactions

```shell
https://app.eu.intercom.com/a/inbox/pynbtguw/inbox/shared/all/conversation/212174700009684?view=List
```

**Comment by JagoFigueroa** [comment]
Good morning! It looks a bit odd but you can tell the user that this is expected for the chain.

We had some internal discussions in the past when adding the chain and decided not to change this token duplicity as it would require some backend work on our end (the Celo team is aware of this duplicity too).

Cheers!

**Comment by Claire-serveth** [comment]
Oh, thank you so much @JagoFigueroa will inform the user. 🙏
