### ISSUE TITLE
[ARB] Incorrect token decimal

### ISSUE THREAD

**Issue by joanpan** [5afe/safe-support#503]
### Issue Category

Token balance not up-to-date, in the interface or service

### What happened?

When user swaps test tokens USDT to  USDE on https://arbapp.worldes.io/trade
![image-1](https://github.com/user-attachments/assets/12945c62-9b5e-4785-ad7e-4201eee85395)

Token decimal for both tokens are incorrectly showing up in the confirm page:
![image](https://github.com/user-attachments/assets/783ad661-7d16-4dd0-82a5-63e67539ded5)

### Date and time this happened or you first noticed this issue

14/08/2024

### Network

Arbitrum

### Safe Address

arb1:0xf585d09834661aa8e5c03bf38C5E5C9327aDF1dD

### Token Type

None

**Comment by JagoFigueroa** [comment]
Good morning! Do we know if this also happens outside of this test app and with tokens that are not test tokens created by the user? I have been checking on other apps like uniswap, 1inch and such but can not reproduce it, amounts look ok on the confirmation screen. 

I think this issue might not be on our end.

Cheers!

**Comment by JagoFigueroa** [comment]
I will go ahead and close this if that is okay.

Cheers!
