### ISSUE TITLE
Error connecting to the blockchain

### ISSUE THREAD

**Issue by DanBigM** [5afe/safe-support#505]
### Issue Category

Safe loading issue, doesnt load on any interface

### What happened?

![Screenshot 2024-08-20 175340](https://github.com/user-attachments/assets/8982f7b3-c476-4ce8-a9cd-0f050dc9dabe)

With different ledgers we cannot connect to the Safe anymore, restarting computers doesn't bring any value neither. 
Using latest chrome on PC. Connection to LedgerLive and other platform works, hence it shouldn't be an issue on Ledger side. 

### Date and time this happened or you first noticed this issue

20-08-2024 17:30

### Network

Ethereum Mainnet

### Token Type

ERC20

**Comment by JagoFigueroa** [comment]
Good morning! Just tried connecting my ledger wallet on chrome and had no issues. Is the issue still present on your side? Hopefully it was just a temporary rpc connection issue

Cheers!

**Comment by DanBigM** [comment]
Thanks JagoFigueroa, especially for the Ninja hint! 
All good again, next time I now know where to check first :)

**Comment by JagoFigueroa** [comment]
Anytime friend 😄 

Closing the issue if that is okay
