### ISSUE TITLE
[Android] Cannot access Assets tab when opening the app from a notification

### ISSUE THREAD

**Issue by phoebe-serveth** [5afe/safe-support#506]
### Issue Category

Other

### What happened?

When opening the safe mobile app from a notification (successful transactions and incoming token), the Assets tab is inaccessible. Only the Transactions and Settings tabs are available. The issue persists even when switching Safe accounts and can only be resolved by closing and reopening the app
User said it happens on Arbitrum and ETH mainnet and I was able to reproduce the issue on Sepolia network.

https://github.com/user-attachments/assets/17a7d3f3-42b2-49f2-b96c-96f858b7975d

### Date and time this happened or you first noticed this issue

20-08-2024 10:00pm

### Network

Ethereum Mainnet, Arbitrum

### Token Type

None

**Comment by liliya-soroka** [comment]
Thank you for reporting. This is a known issue. Please follow the  https://github.com/safe-global/safe-android/issues/1948 . There is no eta

**Comment by phoebe-serveth** [comment]
@liliya-soroka Thank you. I'll inform the user and close this ticket.
