### ISSUE TITLE
[Base] Getting "Error connecting to the blockchain" when connected to the default RPC

### ISSUE THREAD

**Issue by phoebe-serveth** [5afe/safe-support#507]
### Issue Category

Transaction execution issue

### What happened?

Multiple users have reported an issue on the Base network when making transactions. Getting the error below when connected to the default RPC. Changing the RPC in Environment variables resolves the issue.
```
Error connecting to the blockchain. Please try reloading the page.
Details
missing response for request (value=[ { "id": "3", "jsonrpc": "2.0", "result": "0x2105" }, { "id": 4, "jsonrpc": "2.0", "result": "0x608060405273ffffffffffffffffffffffffffffffffffffffff600054167fa619486e0000000000000000000000000000000000000000000000000000000060003514156050578060005260206000f35b3660008037600080366000845af43d6000803e60008114156070573d6000fd5b3d6000f3fea2646970667358221220d1429297349653a4918076d650332de1a1068c5f3e07c5c82360c277770b955264736f6c63430007060033" } ], info={ "payload": { "id": 3, "jsonrpc": "2.0", "method": "eth_chainId", "params": [ ] } }, code=BAD_DATA, version=6.11.1)
```
Current Default RPC on base network:
![image](https://github.com/user-attachments/assets/09add492-42de-4b86-bdba-5434bb3a8300)

### Date and time this happened or you first noticed this issue

23-08-2024 1:40

### Network

Base

### Token Type

None

**Comment by liliya-soroka** [comment]
Could you check with the user if it's still an issue?

**Comment by Claire-serveth** [comment]
Hi @liliya-soroka users were already unresponsive as they were able to change the RPC on environment variables while the default RPC returns an error. But is it okay to restore to the default RPC now?

**Comment by JagoFigueroa** [comment]
Hello @Claire-serveth! Sorry for the delay, the default rpc and the chain look to be stable at the moment so should be good to switch. Please let us know if the user is still experiencing issues.

Cheers!

**Comment by Claire-serveth** [comment]
Alright, thank you so much for the update @JagoFigueroa we haven't receive new complaints so far, so I'm closing this issue now. 🙏
