### ISSUE TITLE
Polygon - Cannot submit/Execute transaction

### ISSUE THREAD

**Issue by inahlikenoother** [5afe/safe-support#509]
### Issue Category

Transaction execution issue

### What happened?

User gets the following error in the Safe mobile app when executing Safe nonce 57
![WhatsApp Image 2024-08-27 at 01 26 44_ecea516e](https://github.com/user-attachments/assets/cf8b1367-ab50-45af-87eb-6d4750cf3a8e)
And when using a web app on the desktop browser, it only keeps on loading 
![image](https://github.com/user-attachments/assets/4b0c4537-943f-43fb-9ce2-720dc8f03ad8)

Already tried:
Different browsers (Chrome and Firefox)
Executing using either of the 3 owner wallets on the Safe (same issue)
Changed RPC in wallet application (same issue)
Used different internet connection with no VPN (same issue)

Console logs from Firefox browser when submitting the transaction
![image-1](https://github.com/user-attachments/assets/4638b8f6-c0a2-434c-b531-93835ecf3379)

Console logs from Chrome browser when submitting the transaction
![image](https://github.com/user-attachments/assets/502c4fdd-77df-43c1-9ea0-f4af0b230988)

### Date and time this happened or you first noticed this issue

27-08-2024

### Network

Polygon

### Safe Address

0xB9064746F0a28D43C63AFc0Fee26F92C72290cBc

### Token Type

None

**Comment by Claire-serveth** [comment]
Issue was resolved on user's end and intercom ticket was already closed; closing this issue now.
