### ISSUE TITLE
CSV airdrop having skipped status on chain with 500 transfers

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#511]
### Issue Category

Other

### What happened?

User on Scroll network was having a "skipped" status on the block explorer when he executed the CSV airdrop transaction with 500 transfers:
![image](https://github.com/user-attachments/assets/0f1d1edd-9bd6-4631-bf28-da2908b98582)
![image](https://github.com/user-attachments/assets/882c1fb8-7860-40fc-984a-8e0956ee1d10)

Clarification:
- What is the maximum number of token transfers/actions in a single transaction on CSV airdrop? 
- Does the limit depend per network (or the same for all supported network)?

### Date and time this happened or you first noticed this issue

01-09-2024

### Network

Aurora

### Token Type

None

**Comment by schmanu** [comment]
The maximum number of transfers depends a lot on the kind of transfers:
If it contains ERC20 / ERC712 / ERC1155 transfers it depends how those token contracts are implemented. 

I once tried to find good average numbers and found that the gas usage can differ a lot between contracts - even for the same standard such as ERC20.

And then the networks also have different block gas limits and therefore different restrictions for the gas usage of transactions.

Could the user try to cut the transfers into two 250 entry transfers?

**Comment by Claire-serveth** [comment]
Hi @schmanu yes, that's what the user tried and it did go through. Transaction was successful with 200+ but not 500. So, it would be best then to limit the transfers to 200 (although depending on the of the type) in order for the transaction to go through successfully. Thank you so much for the response, closing this issue now. 🙏
