### ISSUE TITLE
[Sepolia] Safe created in webapp cannot be loaded in iOS app

### ISSUE THREAD

**Issue by bingclo** [5afe/safe-support#514]
### Issue Category

Safe loading issue, doesnt load on any interface

### What happened?

User created 2 safes, one in iOS and one in webapp. The safe created in iOS loads find in the mobile app but the one created in webapp results in this error when being added:

![image](https://github.com/user-attachments/assets/0329e4c6-b2e1-4ac9-8106-fd15b1a3afa3)

When checking the ones created in the iOS has the old contract version (1.3.0+L2):
https://sepolia.etherscan.io/tx/0x65a39d1c61da6db249b4b9e10dffb3779a25ed50b10c1635dd2d0501f6240ee3

![image](https://github.com/user-attachments/assets/546b48c8-e956-40b9-b74d-ef5fd2c4361b)

While the one created in the webapp has the new contracts (1.4.1+L2):
https://sepolia.etherscan.io/tx/0x7fe413da48d37df628fd46617946f43d35a811ff803fbc40b1ee2b41b8c1ae84

![image](https://github.com/user-attachments/assets/6fbee3b3-d3f4-4282-bdcc-7978d7255a91)

### Date and time this happened or you first noticed this issue

03/09/2024 09:24:06

### Network

Ethereum Mainnet

### Safe Address

https://app.safe.global/settings/setup?safe=sep:0xc5bc620c508b0B63f2B5E9162CF467d3C6428E1c

### Token Address

N/A

### Token Type

None

### Transactions

```shell
Created in iOS app:
https://sepolia.etherscan.io/tx/0x65a39d1c61da6db249b4b9e10dffb3779a25ed50b10c1635dd2d0501f6240ee3

Created in webapp
https://sepolia.etherscan.io/tx/0x7fe413da48d37df628fd46617946f43d35a811ff803fbc40b1ee2b41b8c1ae84
```

**Comment by liliya-soroka** [comment]
thank you for reporting. This is a known issue that 1.4.1 is not supported on mobile for now.

**Comment by bingclo** [comment]
Thank you!
