### ISSUE TITLE
[Base] WETH token not showing up on the Asset's page 

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#516]
### Issue Category

Token missing completely / not visible in the interface or service

### What happened?

User tried wrapping his ETH but after the successful transaction, WETH is not showing up on the UI, but it is shown that the token is already in his account:
Safe: https://app.safe.global/balances?safe=Base:0xCEa56c6f0c06288d585B605DA4474B3542BDeA26
![image](https://github.com/user-attachments/assets/136acc2f-e5ac-4da9-ac5b-b55838d13519)

Was this because it was not swapped rather only deposited to the WETH contract, hence user still needs to withdraw?

### Date and time this happened or you first noticed this issue

09-09-2024

### Network

Ethereum Mainnet

### Safe Address

base:0xCEa56c6f0c06288d585B605DA4474B3542BDeA26

### Token Address

0x4200000000000000000000000000000000000006

### Token Type

ERC20

**Comment by laalauren1** [comment]
> ### Issue Category
> Token missing completely / not visible in the interface or service
> 
> ### What happened?
> User tried wrapping his ETH but after the successful transaction, WETH is not showing up on the UI, but it is shown that the token is already in his account: Safe: https://app.safe.global/balances?safe=Base:0xCEa56c6f0c06288d585B605DA4474B3542BDeA26 ![image](https://private-user-images.githubusercontent.com/114005210/365670494-136acc2f-e5ac-4da9-ac5b-b55838d13519.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5MjU0OTksIm5iZiI6MTcyNTkyNTE5OSwicGF0aCI6Ii8xMTQwMDUyMTAvMzY1NjcwNDk0LTEzNmFjYzJmLWU1YWMtNGRhOS1hYzViLWI1NTgzOGQxMzUxOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQyMzM5NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wODE1MGM5NWUxYmNhZWM3ODNmZTg1NmUyZmQ2MzMxM2U4MmJhNzNhMzEwYjYxZTUzYzgyMDhiYzVkZmJkNmI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5yKrwdQ9_zsk5xih2LVsEixq-KBGdMFZZWjdoRUgP0E)
> 
> Was this because it was not swapped rather only deposited to the WETH contract, hence user still needs to withdraw?
> 
> ### Date and time this happened or you first noticed this issue
> 09-09-2024
> 
> ### Network
> Ethereum Mainnet
> 
> ### Safe Address
> base:0xCEa56c6f0c06288d585B605DA4474B3542BDeA26
> 
> ### Token Address
> 0x4200000000000000000000000000000000000006
> 
> ### Token Type
> ERC20
> 
> ### Transactions
> _No response_

@Claire-serveth Has your issue already been escalated?

**Comment by ru513** [comment]
@Claire-serveth @laalauren1  this has been escalated to the API team , we will try to get an update for you asap.

**Comment by Uxio0** [comment]
Token was minted, not transferred (even etherscan couldn't index it https://basescan.org/address/0xCEa56c6f0c06288d585B605DA4474B3542BDeA26#tokentxns). But you can check now, it shows in balances
