### ISSUE TITLE
USDC PoS showing zero (0) USD value

### ISSUE THREAD

**Issue by inahlikenoother** [5afe/safe-support#53]
### Issue Category

Token balance not up-to-date, in the interface or service

### What happened?

User's USDC PoS tokens are showing 0 dollar value in the safe web u.i
![image](https://user-images.githubusercontent.com/114049495/199383053-db2ebd62-06f3-4eaa-b4c1-90cde3f83621.png)

### Date and time this happened or you first noticed this issue

01/11/2022 11:00 AM PH time

### Network

Polygon

### Token Address

0xe62999Ae2A44Faece55E82f7Ae0e9C6C49787B45

### Token Type

ERC20

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Claire-serveth** [comment]
> USDC balance should be showing now. Works for me. Can you ask the user to re-check?

Hi John, thank you so much! It's updated on my end as well; will inform the user.

**Comment by ennisjo** [comment]
Good to close the issue?

**Comment by Claire-serveth** [comment]
> Good to close the issue?

Hi John, yes, I just checked the ticket on Intercom was closed already. I don't have the option to close this issue on my end though. Thank you again!
