### ISSUE TITLE
pax.world (PAXW) token not showing up on the UI on Polygon network

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#54]
### Issue Category

Token missing completely / not visible in the interface or service

### What happened?

Token was successfully transferred to the safe as shown on polygonscan, but still not showing up on the UI for more than 4 hours now.
![image](https://user-images.githubusercontent.com/114005210/199536658-ef51c3d6-3f10-4e2a-88c5-8141239ea53e.png)
![image](https://user-images.githubusercontent.com/114005210/199536764-8c8fff9a-8ea2-46a7-a68b-78e1905dd672.png)

### Date and time this happened or you first noticed this issue

02-11-2022

### Network

Polygon

### Safe Address

0x4466f0242e93e1c32DED38Bf47d8E37A24e81c3B

### Token Address

0xC79Ae93D9C215EAa8c8DA5C77E465baC7dE28891

### Token Type

ERC20

### Transactions

```shell
https://polygonscan.com/tx/0x1783c728b9ab5e570f440f84fe3737419b864c6b4df6114dda46d22e210898dc
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ennisjo** [comment]
Checking with the team. Could be that the token contract doesn't 100% comply with ERC20. Can you let the user know that?

**Comment by Uxio0** [comment]
Fixed: https://gnosis-safe.io/app/matic:0x4466f0242e93e1c32DED38Bf47d8E37A24e81c3B/balances
