### ISSUE TITLE
This Safe couldn't be loaded error on Aurora network

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#55]
### Issue Category

Safe loading issue, doesnt load on any interface

### What happened?

User can't load their safe for more than an hour now.
![image](https://user-images.githubusercontent.com/114005210/199775739-62ed95cd-0573-4118-bc1d-ec63d7bfadc8.png)

### Date and time this happened or you first noticed this issue

03-11-2022

### Network

Aurora

### Safe Address

0x4f44d184908AE367CAD0cb1b332A11545d76Bc87

### Token Address

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Claire-serveth** [comment]
> Hey there! Checking with the infra team the issue looks to be on Aurora's side (nodes are returning lots of errors). I reached out to the team so that they are aware but I think we can close this ticket as no action is needed from our side 😄

Hi Jago, oh I see. Will let the user know. Thank you so much for the updates!

**Comment by Claire-serveth** [comment]
> Hey there! Checking with the infra team the issue looks to be on Aurora's side (nodes are returning lots of errors). I reached out to the team so that they are aware but I think we can close this ticket as no action is needed from our side 😄

Hi Jiago, I just wonder, the reported safe address can now be loaded but the other safe address of the user, which is in Aurora network as well, can't still be loaded. Safe address: https://gnosis-safe.io/app/aurora:0x58ac3103c54FF3757e3b9132c8598fc5C1e69475/home

Is this an issue with Aurora network still?

**Comment by JagoFigueroa** [comment]
Hi again! The Aurora team is still checking, yes 😄 

For reference none of the 2 safes are loading for me still. They might end up loading when leaving them for some good time but the issue has not been resolved yet. 

Cheers!

**Comment by JagoFigueroa** [comment]
Issues should be resolved now 🥳
