### ISSUE TITLE
Unauthorized transfer/transaction (BSC)

### ISSUE THREAD

**Issue by jakekvm01** [5afe/safe-support#56]
### Issue Category

Other

### What happened?

Hi - our safe has been wiped out.
Someone unstaked our liquidity from PCS, and then transfered out the tokens. Our entire treasury has gone.
This transaction is on BSCScan but not show in the Gnosis app. None of us approeved it. How is this possible?
https://bscscan.com/tx/0x085beaf22438287312d56620973b9c00a82b99a44a6cf1f00ef6c88ab3656464
Can you see how this was authorised?
Thanks
![image](https://user-images.githubusercontent.com/105864754/200022880-38715992-07db-4569-8b1f-bfd1c178ae60.png)

### Date and time this happened or you first noticed this issue

 7 hrs 21 mins ago (Nov-04-2022 08:30:55 AM +UTC) 

### Network

Binance Smart Chain

### Safe Address

https://gnosis-safe.io/app/bnb:0x4B64F382aa063C07F1C55Cf53c66ccE3b6fD0bb0/home

### Token Address

0x91191A15E778d46255FC9AcD37D028228D97e786

### Token Type

ERC20

### Transactions

```shell
Unauthorized transaction - https://bscscan.com/tx/0x085beaf22438287312d56620973b9c00a82b99a44a6cf1f00ef6c88ab3656464

Please see attached image above.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mikhailxyz** [comment]
The transaction never interacted with the Safe contract, it called the token contract directly. All token balances are held in the token contract, and transfers are performed with the token contract as well. It seems like the contract was missing authorization checks. Please tell the user to talk to the token's developers

**Comment by jakekvm01** [comment]
Thank you @mikhailxyz

**Comment by Pedrojok01** [comment]
Hi there, and thank you for your help.
Any idea how could that have happened? Missing authorization checks on the transfer function?
This contract is a basic ERC20. The only addition is ERC20Permit. All contracts are from open-zeppelin. Could it be an issue with the permit function?

**Comment by Pedrojok01** [comment]
@mikhailxyz that's right, the attacker contract (`0xCd62dDE0e5aCbc1D596b1C1699c8b2A5f1327693`) managed to drain all fund via a `transferFrom` directly. That means it somehow had to be approved by the safe earlier. But that never happened, and there is no Approval event that matches. Afaik, there is no way to trigger `transferFrom` without previous approval, and any approval emits an event (at least with the openzeppelin contract used in this case). Could you be more specific about the missing authorizations you are referring to?
