### ISSUE TITLE
[missing transaction] The interface doesn't show latest transactions on optimism

### ISSUE THREAD

**Issue by mikhailxyz** [5afe/safe-support#57]
### Issue Category

Transaction missing / not visible in app or service

### What happened?

Transaction with nonces 13 and 14 are missing in the interface

Eth transaction executing safe transaction with nonce 14: https://optimistic.etherscan.io/tx/0x69a9b5d0f0901c634e4e268cb6c9ad914db2b3b732fe5dabd03136e554fe45dd

Safe link: https://app.safe.global/oeth:0x0a6dDC58356926838cA6e86217034B9D8FE29E1a/settings/setup

### Date and time this happened or you first noticed this issue

08-11-2022 9:50

### Network

Optimism

### Safe Address

0x0a6dDC58356926838cA6e86217034B9D8FE29E1a

### Transactions

```shell
https://optimistic.etherscan.io/tx/0x69a9b5d0f0901c634e4e268cb6c9ad914db2b3b732fe5dabd03136e554fe45dd
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by schmanu** [comment]
Hey @mikhailxyz if I check the safe now I see the txs with nonces 13 and 14.

Probably the indexer was just lagging a bit behind.
