### ISSUE TITLE
Mobile app crashes when signing with a Ledger Nano X on an iPad

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#63]
### Issue Category

Transaction execution issue

### What happened?

The mobile app crashes when user tried to sign the transaction using Ledger Nano X. All are updated, also tried force close and restarting device. (the last part of the video goes back to the home screen)

Safe version: 3.18.0, 
Ledger Nano X version: 2.0.2 
Device: M1 iPad Pro
iPadOS: 16.1.1.

https://user-images.githubusercontent.com/114005210/201132879-1f865235-d8bf-451f-86e4-dfe6da3c5a90.mp4

### Date and time this happened or you first noticed this issue

10-11-2022 

### Network

Goerli

### Token Address

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by liliya-soroka** [comment]
known issue - https://github.com/safe-global/safe-ios/issues/2464 .
I will bring it back to the team

**Comment by Claire-serveth** [comment]
> known issue - [safe-global/safe-ios#2464](https://github.com/safe-global/safe-ios/issues/2464) . I will bring it back to the team

Oh, thank you so much liliya! Should I close this issue or keep this open until the issue is fixed?

**Comment by med3000** [comment]
hi @Claire-serveth i will close this off and the known issue can be tracked here https://github.com/safe-global/safe-ios/issues/2464 thanks.
