### ISSUE TITLE
Send transaction keeps failing

### ISSUE THREAD

**Issue by joanpan** [5afe/safe-support#65]
### Issue Category

Transaction execution issue

### What happened?

User is trying to send LDO tokens (add: 0x5A98FcBEA516Cf06857215779Fd812CA3beF1B32) but the transaction keeps failing
> Safe has enough balance
> Executing wallet has enough funds to cover for gas
> Manually set gas

Txn hash:
https://etherscan.io/tx/0x02dd3c0a164e0c3302e8d6b0b04669f461fe8787fc9d45988f1302fce00a485f

Is this a token issue?

### Date and time this happened or you first noticed this issue

12-11-2022

### Network

Ethereum Mainnet

### Safe Address

0x91e4f4bC6aE705Eb4e939C147133558c0f906Eeb

### Token Address

0x5A98FcBEA516Cf06857215779Fd812CA3beF1B32

### Token Type

ERC20

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by moisses89** [comment]
Yes, I can see that the ERC20 contract is reverting, https://dashboard.tenderly.co/tx/mainnet/0x02dd3c0a164e0c3302e8d6b0b04669f461fe8787fc9d45988f1302fce00a485f?trace=0.0.2.0.0.0.2.0
```
onTransfer in MiniMeToken:227
   onTransfer in AppProxyUpgradeable:278 
```

**Comment by joanpan** [comment]
Thanks, will let the user know
