### ISSUE TITLE
[Feedback on new UI] Pressing Enter will replace the entered amount with the MAX amount of tokens in Send Tokens prompt

### ISSUE THREAD

**Issue by shebeengs** [5afe/safe-support#66]
### Issue Category

Other

### What happened?

**Feedback from user**
> If I enter an amount in the 'amount' field for a send tokens transaction, then press enter, it replaces the amount with the max - it appears 'max' is the default button in that field.
> 
> This could obviously lead to someone accidentally sending way more than they intended.

**Replicated steps in a Goerli Safe but user's safe was in Ethereum mainnet:**
1. `New Transaction` > `Send Tokens`
2. Fill out details - recipient, asset and amount
3. Press `Enter `on keyboard.
4. Amount in the `Amount` field is replaced with the `MAX` amount. 
5. Same thing happens when I try via `Assets` > hover on token > `Send`

Tried in the old UI, pressing Enter will proceed to Step 2, same as pressing Next.
![image](https://user-images.githubusercontent.com/54754746/202057234-181400b6-4d2a-4a7e-bc12-5bc1a4a3f6a0.png)

### Date and time this happened or you first noticed this issue

16-11-2022 08:35 

### Network

Ethereum Mainnet

### Safe Address

N/A

### Token Address

N/A

### Token Type

ERC20

### Transactions

```shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by johannesmoormann** [comment]
thanks for the report! we will change the outlined behavior.

**Comment by shebeengs** [comment]
Thank you 🙏
