### ISSUE TITLE
Can't connect metamask + trezor with the safe using the new UI (ethereum and polygon)

### ISSUE THREAD

**Issue by jakekvm01** [5afe/safe-support#67]
### Issue Category

Other

### What happened?

Hey Guys since the update the app has been really unreliable
I can no longer connect with my hardware wallet.

https://app.safe.global/matic:0x6279ff3716Dc541eC639026D29f0cC528C0C43be/home
https://app.safe.global/eth:0x87Eb1da61e5A45beE2F7Cb21586E68359C4FD370/home
https://app.intercom.com/a/inbox/km54f6ih/inbox/shared/all/conversation/36000020247?view=List

Done basic troubleshooting.
Please check video :
https://user-images.githubusercontent.com/105864754/202274064-9fcf0091-9e28-4b33-b230-e85e0ebf3242.mov

### Date and time this happened or you first noticed this issue

n/a

### Network

Ethereum Mainnet

### Safe Address

https://app.safe.global/eth:0x87Eb1da61e5A45beE2F7Cb21586E68359C4FD370/home
https://app.safe.global/matic:0x6279ff3716Dc541eC639026D29f0cC528C0C43be/home

### Token Address

n/a

### Token Type

n/a

### Transactions

```shell
Can't connect metamask + trezor with the safe using the new UI (ethereum)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by moisses89** [comment]
@jakekvm01 the issue mentions the web update but the video shows the old one, where are you experiencing the issue? in the old one or in the new interface?

**Comment by jakekvm01** [comment]
User said he can't connect after the update but seems the video still did use the old UI. He was able to resolved the issue though. Thank you @moisses89
