### ISSUE TITLE
Unknown safe address displayed in the Safe UI

### ISSUE THREAD

**Issue by joanpan** [5afe/safe-support#69]
### Issue Category

Other

### What happened?

User reported seeing a different address displayed in the Safe interface. Their safe address is 0x1ec078551A5ac8F0f51fAc57Ffc48Ea7d9A86E9d but 0x2C5dAF7D5a766a73E907fB7470Eb7C6E71AAF15b is displayed. User does not own the latter. Tried different browsers, same issue. I get the same behavior on my end too.

![image](https://user-images.githubusercontent.com/114049668/202825954-3a4c3d07-497a-44b8-a6b1-94e9b861a125.png)

### Date and time this happened or you first noticed this issue

19-11-2022

### Network

Ethereum Mainnet

### Safe Address

0x1ec078551A5ac8F0f51fAc57Ffc48Ea7d9A86E9d 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by liliya-soroka** [comment]
Could you provide more information, please?
How did you reproduce it?
<img width="785" alt="image" src="https://user-images.githubusercontent.com/338622/202900132-dd968d42-6f56-4426-83f9-f9a1712dbef4.png">

**Comment by yagopv** [comment]
Hey @joanpan can we close this issue?
