### ISSUE TITLE
Token-missing in Optimism: Received USDT does not appear/update balance in the interface (both old and new)

### ISSUE THREAD

**Issue by shebeengs** [5afe/safe-support#70]
### Issue Category

Token missing completely / not visible in the interface or service

### What happened?

User sent USDT to his safe in this transaction in Optimism: https://optimistic.etherscan.io/tx/0x95b2a56d2e8f0181b0558d3c5f12541467fd464eee551de1e1186406ec5f41ab

USDT balance can be seen in the block explorer but not in the interface:

![image](https://user-images.githubusercontent.com/54754746/202915888-4acb419b-575c-4ae2-8b23-f4086acb8c2b.png)
![image](https://user-images.githubusercontent.com/54754746/202915891-d4de97ef-61cc-430d-8ea4-f09b9632d167.png)
![image](https://user-images.githubusercontent.com/54754746/202915894-4e43e893-2f92-4af2-8c2a-fe6492af3832.png)

### Date and time this happened or you first noticed this issue

20/11/2022 07:11:10

### Network

Optimism

### Safe Address

0xa0399d412e7F022c011E1f64F3b6af3242A249AB

### Token Address

0x94b008aa00579c1307b0ef2c499ad98a8ce58e58

### Token Type

ERC20

### Transactions

```shell
https://optimistic.etherscan.io/tx/0x95b2a56d2e8f0181b0558d3c5f12541467fd464eee551de1e1186406ec5f41ab
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by moisses89** [comment]
Reindexing should appear in a while.

**Comment by hectorgomezv** [comment]
Hi @shebeengs, I think the missing token it's shown in the UI now, could you double check?

![Screenshot 2022-11-21 at 12 11 24](https://user-images.githubusercontent.com/21182069/203036530-293638d8-3bc8-405f-8e38-af2e75adf453.png)

**Comment by shebeengs** [comment]
Yes, it does now. I see the user was able to transfer as well :) Thank you 🙏
