### ISSUE TITLE
[Polygon] NFT not showing in Assets page

### ISSUE THREAD

**Issue by joanpan** [5afe/safe-support#72]
### Issue Category

Transaction missing / not visible in app or service

### What happened?

ERC721 NFT not showing up on Assets page. User is the developer and mentioned that they are not able to verify the contract -- is this what's causing the issue?

https://polygonscan.com/address/0xABDce09D5989D7E2e9Fc53132718A7F5129f2625#tokentxnsErc721

![image](https://user-images.githubusercontent.com/114049668/203185600-38240e25-a7f0-4c5e-bba2-71a8f57ed8d1.png)
![image](https://user-images.githubusercontent.com/114049668/203185620-615a4d62-52cc-49e8-b322-c3b359cae8a7.png)

### Date and time this happened or you first noticed this issue

22-11-2022

### Network

Polygon

### Safe Address

0xABDce09D5989D7E2e9Fc53132718A7F5129f2625

### Token Address

0x099883b83AE4189fE8B8c98aEC900a675CC88cE1

### Token Type

ERC721

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by usame-algan** [comment]
Checked both in the old and new app and can see all NFTs. The screenshot is from the old app and might have to do with a request timeout because we don’t use the paginated endpoint there. For an improved UX we recommend to use the new app under app.safe.global

**Comment by joanpan** [comment]
Thank you!
