### ISSUE TITLE
Signing long message (>1024) in MM +Trezor wallet is not supported

### ISSUE THREAD

**Issue by CindyLo0** [5afe/safe-support#73]
### Issue Category

Other

### What happened?

A user posted this feature request in Intercom but has not replied to follow ups. Not sure if this is worth looking into. Please let me know or if we can close. 

![image](https://user-images.githubusercontent.com/79137197/203536824-3272763c-e32f-45e7-bf22-5614cbbe4e58.png)

### Date and time this happened or you first noticed this issue

23-11-2022 13:00

### Network

Ethereum Mainnet

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jakekvm01** [comment]
I'm having same issue with this user https://app.intercom.com/a/inbox/km54f6ih/inbox/shared/unassigned/conversation/36000021362?view=List

Safe address : 0xC8e27EdF3b65B4D8d6B5627D0cd9d5dd4E95DE94

**Comment by med3000** [comment]
+1 https://github.com/5afe/safe-support/issues/114

**Comment by iamacook** [comment]
We have just merged a [fix for this issue](https://github.com/safe-global/web-core/pull/1589) into our main codebase. It will included in the [forthcoming release](https://github.com/safe-global/web-core/milestone/2).
