### ISSUE TITLE
[Polygon] Tokens not showing up in Assets page / balance not updating

### ISSUE THREAD

**Issue by joanpan** [5afe/safe-support#74]
### Issue Category

Token balance not up-to-date, in the interface or service

### What happened?

Two users have reported token balance not updating

Safe address: 0x0556887acf3dcbdd4d4370df5a57a1bda536137b
Txn hash: https://polygonscan.com/tx/0x22e238820df5d42c9e95d135ab47cac22b5389495f5c11059b641a1414715a0f
![image](https://user-images.githubusercontent.com/114049668/203652327-304ca418-c270-4494-91dc-ca029797ac20.png)
![image](https://user-images.githubusercontent.com/114049668/203652474-e386ac38-ba16-4851-825a-927e87d809c6.png)

Safe address: 0xce31ab3b71cc5b7bf5e649844ced0329e3099db0
Txn hash: https://polygonscan.com/tx/0x5d0662b153af21f45c9b08604f5477987f9e438bfe05304dd9558a40953fd60e
![image](https://user-images.githubusercontent.com/114049668/203652271-1ff3efa8-7fa8-45f7-98d6-50640d262e94.png)
![image](https://user-images.githubusercontent.com/114049668/203652594-5507138a-48c1-4b6e-b841-9004f8b7dab2.png)

### Date and time this happened or you first noticed this issue

24-11-2022

### Network

Polygon

### Safe Address

0x0556887acf3dcbdd4d4370df5a57a1bda536137b

### Token Type

ERC20

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joanpan** [comment]
Another user reported similar issue

safe address: 0xb24Bf9DE7819d88d657b24cc2f56e1682c21DEE5 

![image](https://user-images.githubusercontent.com/114049668/203664228-67487c2c-0aae-4c5e-9fae-12681b43b57c.png)
![image](https://user-images.githubusercontent.com/114049668/203664343-bddd5c33-8504-4e70-b9e6-4cc8da1332c5.png)

https://polygonscan.com/tx/0x7eef7f66348b6bfaaad6897a8839604a0f4680fae8fc7d9f9364941670d7dc28

**Comment by ZeroV0LT** [comment]
Please reopen as also today is not working.

Here is real balance:

https://polygonscan.com/token/0x4e6ace2f99d94aabf8ffbbbf487adb40b1f875a5?a=0xce31ab3b71cc5b7bf5e649844ced0329e3099db0

But in web app is still showing 6 YLM as balance:

![image](https://user-images.githubusercontent.com/16348495/203754136-8468562c-8ad8-4b35-8fc2-f082e5bfb147.png)

**Comment by dancog1972** [comment]
Hi team, 
we keep on having the same issue over and over, with transactions not showing or taking long time to show in the UI. 
https://app.safe.global/matic:0xCE31AB3B71Cc5b7bF5e649844CEd0329e3099db0/balances

**Comment by JagoFigueroa** [comment]
Hi! (and sorry for the delayed reply) Checked the shared safes and I can see that all the tokens are being displayed as expected on the interface. 

The issue was more than likely related to the indexing related issues we were experiencing at the end of last month so I will go ahead and close this ticket if that is okay 😃

**Comment by ZeroV0LT** [comment]
Confirm, I played lately and it seems all ok. ---- On Tue, 27 Dec 2022 13:46:40 +0100  ***@***.***  wrote ----
Closed #74 as completed.
