### ISSUE TITLE
ACC Web3.0 Fund (AWF) shows incorrect fiat value of assets in the Safe UI

### ISSUE THREAD

**Issue by Sherie15** [5afe/safe-support#75]
### Issue Category

Other

### What happened?

The user claimed that the price of the asset is wrong - ACC Web3.0 Fund (AWF). May we know which price oracle the token is pulling out from the Safe and it is possible to remove the price for the token?

1inch shows _**price is unknown**_ for the token
https://app.1inch.io/#/1/unified/swap/AWF/DAI
![image](https://user-images.githubusercontent.com/113986185/203682458-cd155975-6aa3-4a76-b546-5abe08a5c1e5.png)

Matcha shows insufficient liquity
https://www.matcha.xyz/markets/1/0xd618b03c7a1c0f3248ae049954d69e8d96a142c0
![image](https://user-images.githubusercontent.com/113986185/203682610-557e9a68-0e46-45ca-8e80-f2e064704f3b.png)

Safe UI shows 
![image](https://user-images.githubusercontent.com/113986185/203682780-de06419a-f424-4263-b981-3bf8610ac8d3.png)
https://gnosis-safe.io/app/eth:0xC8055063e8937F33ec4741c422a27B8d9B1eB31b/balances

### Date and time this happened or you first noticed this issue

24-11-2022 

### Network

Ethereum Mainnet

### Safe Address

0xC8055063e8937F33ec4741c422a27B8d9B1eB31b

### Token Address

0xd618b03C7A1c0F3248Ae049954D69e8d96a142C0

### Token Type

ERC20

### Transactions

```shell
https://etherscan.io/tx/0x1aeacee1ae9143bf28d05d5bd7ad8b35194a7bfb55a5d0cc39e16931988581cd
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Uxio0** [comment]
Maybe there was temporary liquidity in any of our oracles, price is `0` now
