### ISSUE TITLE
 A "send" transaction shown as "contract interaction" in the pending queue for sending a Bevvies NFT

### ISSUE THREAD

**Issue by Sherie15** [5afe/safe-support#76]
### Issue Category

Other

### What happened?

![image](https://user-images.githubusercontent.com/113986185/203699671-6fa6855d-439e-4e59-a994-4cb5b020a25a.png)
![image](https://user-images.githubusercontent.com/113986185/203699686-0bf13ab2-88c5-4980-900b-a685f21a1fea.png)

https://etherscan.io/token/0x3a07a0e07ee928df401e1cec8d001a3bfdd5dbd2?a=0xF4A3aeEbA5Ab408e65c9a97b56923FDa8142B41B

### Date and time this happened or you first noticed this issue

24-11-2022 7:20:04 PM

### Network

Ethereum Mainnet

### Safe Address

0xF4A3aeEbA5Ab408e65c9a97b56923FDa8142B41B

### Token Address

0x3a07A0E07eE928dF401e1cEC8D001A3bfdD5DbD2

### Token Type

ERC721

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fmrsabino** [comment]
Hi @Sherie15 

The specified token (address `0x3a07A0E07eE928dF401e1cEC8D001A3bfdD5DbD2`) does not have a symbol associated with it so it's not indexed by our service.

We only index tokens which contain a `name` and `symbol`.

**Comment by JagoFigueroa** [comment]
Hi! Seeing the reply from the infra team I will go ahead and close this ticket 😄 

Cheers!
