### ISSUE TITLE
[Polygon] Tokens not showing up in Assets page / balance not updating

### ISSUE THREAD

**Issue by ZeroV0LT** [5afe/safe-support#77]
Please reopen as also today is not working.

Here is real balance:

https://polygonscan.com/token/0x4e6ace2f99d94aabf8ffbbbf487adb40b1f875a5?a=0xce31ab3b71cc5b7bf5e649844ced0329e3099db0

But in web app is still showing 6 YLM as balance:

![image](https://user-images.githubusercontent.com/16348495/203754136-8468562c-8ad8-4b35-8fc2-f082e5bfb147.png)

_Originally posted by @ZeroV0LT in https://github.com/5afe/safe-support/issues/74#issuecomment-1326214573_

**Comment by Uxio0** [comment]
We are having recurring issues of ERC20 indexing on Polygon and we are doing our best to fix them

**Comment by JagoFigueroa** [comment]
I will go ahead and close this one as with this other [ticket](https://github.com/5afe/safe-support/issues/74) 😄
