### ISSUE TITLE
Incorrect safe nonce generated

### ISSUE THREAD

**Issue by CindyLo0** [5afe/safe-support#78]
### Issue Category

Other

### What happened?

Issue: 

1. User has 2 Safes on different chains, Avalanche and Ethereum with the same signer wallet. 
2. Both safes are set up in the same browser with MetaMask extension
3. Avalanche current nonce was 583 when user submitted transaction. 
4. User then switched Safe to Ethereum but did not switch MetaMask wallet to Ethereum yet. Ethereum safe current nonce was only at 140.
5. User then tried to submit a transaction in Ethereum but nonce was automatically set to 584 (following the next nonce from Avalanche) instead of Ethereum nonce 141. 
6. User then switches wallet to Ethereum but nonce 584 was retained. 
7. Safe should pick up the nonce based on the currently selected network in safe (not the one selected in the connected wallet)
8. Safe nonce can still be edited in Advanced Parameters page but if the user is not careful, it will submit a transaction with incorrect nonce so it will only be stuck in pending. 

https://user-images.githubusercontent.com/79137197/203984934-d6ffb172-63c3-4273-bece-cf5d30d352c6.mp4

https://user-images.githubusercontent.com/79137197/203984946-2d330eb5-23d9-42ad-9d17-770a3d11f6e9.mp4

avax:0x42eb8E224981445F64Cd12E32CD9e5dd1fAC734c
eth:0xecAe704097dF715a1fCC8dCB9793F29E068Cf171

### Date and time this happened or you first noticed this issue

25-11-2022 14:22

### Network

Ethereum Mainnet

### Safe Address

avax:0x42eb8E224981445F64Cd12E32CD9e5dd1fAC734c eth:0xecAe704097dF715a1fCC8dCB9793F29E068Cf171

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TanyaEfremova** [comment]
Thank you for reporting @CindyLo0 ! We created a bug issue and will be working on fixing it.

**Comment by JagoFigueroa** [comment]
Hi! As with this [ticket](https://github.com/5afe/safe-support/issues/90) Closing this one as the fix was merged into production via [this](https://github.com/safe-global/web-core/issues/1253) other one (🤯 😆).

Cheers!
