### ISSUE TITLE
[Connect to Mobile functionality doesn't work] 

### ISSUE THREAD

**Issue by Sherie15** [5afe/safe-support#80]
### Issue Category

Other

### What happened?

The user issue
_Connect to Mobile functionality doesn't work.. I installed Safe on MacOS, v3.22.1, clicked Connect Wallet, then I scanned QR (Connect to Mobile) using my Safe on mobile (Settings>Connect to Web)_

_Results, it is stuck on "Connection requested window" and only Reject is active on the bottom, Confirm inactive. Then error showed: "Failed to connect. Connection timeout. Please reload web app"_

Also, the user is experiencing an issue with __"Connect a Wallet" via WalletConnect then scan from Trust Wallet, doesn't work. Tested on two different pairs of Macbook Pro + iPhone_
![image](https://user-images.githubusercontent.com/113986185/204211266-30cb899a-e860-4c95-9b51-9122ff1fb729.png)
![image](https://user-images.githubusercontent.com/113986185/204211351-7ebaeca1-b8a6-44be-9121-76e04289740f.png)
![image](https://user-images.githubusercontent.com/113986185/204211427-cee9ebc7-d2ec-4eb3-96d4-6cfef032365c.png)

PC and OS: Macbook Pro - MacOS Ventura the latest update
Safe Desktop app version: 3.22.1
Mobile iOS version: iOS 16.1.1
Safe Mobile app version: 3.18.1

https://gnosis-safe.io/app/matic:0xaad8DAFcF6F5fd15d2c7097Ea38dcA1995D88d90/home

The users also asked
_Can you please clarify whether such issues considered as a bugs and can be applied via Bug Bounty?
https://docs.gnosis-safe.io/introduction/security/bug-bounty-program
Or Safe UI issues are not subject to Bug Bounty?_

### Date and time this happened or you first noticed this issue

28/11/2022  7:20:04 PM

### Network

Polygon

### Safe Address

0xaad8DAFcF6F5fd15d2c7097Ea38dcA1995D88d90

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TanyaEfremova** [comment]
Hi @Sherie15, could you try to reload the **Web App page** please and tell whether it solves the issue?

**Comment by oceanemil** [comment]
> Hi @Sherie15, could you try to reload the **Web App page** please and tell whether it solves the issue?

Hi Tanya, it is not a web app, it is a Desktop app for Mac OS v3.22.1 (the last one)

**Comment by usame-algan** [comment]
Hi @oceanemil, I can confirm that it doesn't work on the desktop app for Mac OS v3.22.1. We might release another version for the desktop app that includes a fix but not timeline given yet. We stopped active development for safe-react (which the desktop app is based on) with the release of web-core. In the meantime I suggest to use either of the web apps for full functionality.

**Comment by JagoFigueroa** [comment]
Hi again! This was fixed on v3.33.2 of the desktop app released last week 😄
