### ISSUE TITLE
Transaction showing 0/0 confirmation -- none of the owners can do anything to approve

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#83]
### Issue Category

Transaction execution issue

### What happened?

Previous nonces are showing 0/0 confirmation and the owners can't do anything to approve it. Already done basic troubleshooting steps including clear data for the safe app site.

![image](https://user-images.githubusercontent.com/114005210/205128818-7198c39b-3f5e-40ed-ba06-0d862bc6fdff.png)

This error pops up when trying to confirm:

![image](https://user-images.githubusercontent.com/114005210/205129239-6a75a72c-7509-4452-bed7-4c681d80b7e1.png)

### Date and time this happened or you first noticed this issue

02-12-2022

### Network

Ethereum Mainnet

### Safe Address

0x50BcFeAfee486183c7b6fB09877Fb1b33474Fe7C

### Token Address

n/a

### Token Type

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by usame-algan** [comment]
@Claire-serveth Looks like the confirmations are correctly displayed now. Might have been a short indexing issue.

**Comment by Claire-serveth** [comment]
> Might have been a short indexing issue

Thank you so much for the quick response @usame-algan, already relayed this to the user since he really needed an urgent help for this issue. Thank you so much again :)
