### ISSUE TITLE
WalletConnect safe app not working

### ISSUE THREAD

**Issue by joanpan** [5afe/safe-support#84]
### Issue Category

Other

### What happened?

Multiple users are unable to connect via WalletConnect safe app. Same issue on my end too.

When I paste the QR code link from the dapp it just refreshes to the past link field and nothing happens.

![image](https://user-images.githubusercontent.com/114049668/205414843-8664f157-1850-4295-8d84-0104735db3b3.png)

### Date and time this happened or you first noticed this issue

01-12-2022

### Network

Ethereum Mainnet, Goerli

### Token Type

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by usame-algan** [comment]
@joanpan could you provide more info on to which app you are trying to connect and which environment (gnosis-safe.io/app or app.safe.global). Thanks!

**Comment by NFT-timmy** [comment]
I am having the same issue on polygon. 
1. It shows connected on gnosis safe and the polygonscan page. However, when I call a function on polygonscan, wallet connect don't open the prompt on gnosis safe to execute the transaction. It was working fine before December. Last WalletConnect transaction I did was October. 

2. For another dapp, the WalletConnect does't work even after pasting the QR code.

**Comment by shebeengs** [comment]
> @joanpan could you provide more info on to which app you are trying to connect and which environment (gnosis-safe.io/app or app.safe.global). Thanks!

Hi @usame-algan another also reported the same issue and is on the new interface (app.safe.global). Still checking with the other user. :)

**Comment by JagoFigueroa** [comment]
Hi! 😄  Any updates on the issues the users were having with WC safe app? It is working as usual for me but would love to replicate more specific scenarios to see if there are any issues. 

Cheers!
