### ISSUE TITLE
Can't connect trezor directly on the web app using brave browser

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#85]
### Issue Category

Other

### What happened?

User can't connect his Trezor directly with the safe. There's no error popping up, just not able to connect. Already tried basic troubleshooting steps (but not using other browsers because he's too cautious on using them). But he can connect with metamask + trezor successfully.

### Date and time this happened or you first noticed this issue

04-12-2022

### Network

Ethereum Mainnet

### Safe Address

0xAde69F54F41AEc41130fa633Be703040889f04c9

### Token Address

n/a

### Token Type

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by usame-algan** [comment]
@Claire-serveth this is most likely an issue with Brave shield causing issues with the Trezor bridge. It doesn't seem that Brave is supported by Trezor. To solve this, there are different steps suggested here: https://forum.trezor.io/t/brave-browser-issues-cannot-sign-transaction/8006/3
