### ISSUE TITLE
[Ethereum] Some transactions shows complete signatures gathered but still cannot execute the transaction.

### ISSUE THREAD

**Issue by shebeengs** [5afe/safe-support#87]
### Issue Category

Transaction execution issue

### What happened?

User is having issues with some transactions that is showing complete signatures gathered (2 out of 2) but still cannot execute the transaction. 

It shows complete signatures at the top but incomplete in the list of confirmations (see image). Tried to execute on my end as well but also getting the same error. 

Same behavior in new domain app.safe.global

Error: 
![image](https://user-images.githubusercontent.com/54754746/205694398-df9c22f5-1f3e-4b98-a6ab-77143a7f5f9e.png)

![Screenshot 2022-12-06 004047](https://user-images.githubusercontent.com/54754746/205695581-4ec686a1-fc3f-4c5c-af0d-e9b7f235a684.png)

Workaround: Some transactions looked fine (see nonce 342) so the user had to reject those transactions with the mentioned behavior above to proceed with the others. 

### Date and time this happened or you first noticed this issue

06/12/2022 18:50:44

### Network

Ethereum Mainnet

### Safe Address

0xaf3f8aC788e0c440f03c4922fAED66655AdbDE10

### Token Type

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by usame-algan** [comment]
Hi @shebeengs, I saw that in the meantime the transactions were executed. Judging from the screenshots this is most likely an indexing issue.

**Comment by shebeengs** [comment]
Yes, the user had to reject those transactions with issues. We'll keep on monitoring but all good now! 🙏
