### ISSUE TITLE
ETH balance not updated after 2 transactions created; wrapped ETH still not showing on the UI

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#88]
### Issue Category

Token balance not up-to-date, in the interface or service

### What happened?

User made 2 wrapped ETH transactions in Uniswap successfully, but the WETH is still not showing on the UI. Also, the current balance of the safe is not the same with the balance showing on the blockexplorer.

### Date and time this happened or you first noticed this issue

06-12-2022

### Network

Optimism

### Safe Address

0xE32e44029C7644a2915810BB39c2AD2B38d9E6CC

### Token Address

0x4200000000000000000000000000000000000006

### Token Type

ERC20

### Transactions

```shell
https://optimistic.etherscan.io/tx/0x295660a90f64bd6055e979a9e608cd73873073c155dbd84f5a7376be1ff715ce
https://optimistic.etherscan.io/tx/0x94a7f5a1b9381c26c51de2787b15eb2f88e5990e8bbb179073d0fd796843429b
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by usame-algan** [comment]
The transactions only called `deposit` on the WETH contract and didn't do a full swap so the balance is in there and not in their safe contract. They should be able to `withdraw` their balance e.g. by doing a custom contract interaction.

**Comment by usame-algan** [comment]
You are right, `deposit` is enough on goerli. Will investigate this further.

**Comment by usame-algan** [comment]
Looks like the WETH contract doesn't emit transfer events (only on deposit) so the indexer is not picking it up unless a workaround is being used which should be in place now. The balance is visible in the safe now :)

**Comment by Claire-serveth** [comment]
> Looks like the WETH contract doesn't emit transfer events on minting (only on deposit) so the indexer is not picking it up unless a workaround is being used which should be in place now. The balance is visible in the safe now :)

Yeah, it's already showing up on the UI. Thank you so much again @usame-algan :)
