### ISSUE TITLE
Can't unwrap WETH using Uniswap safe app

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#89]
### Issue Category

Other

### What happened?

User can't unwrap WETH using the Uniswap safe app; no response or no confirmation popping up after clicking unwrap button. This is on ETH network and same behavior on goerli network.

This is the dev console:

![image](https://user-images.githubusercontent.com/114005210/206222305-f1b52a8d-c474-4fe6-9a4b-89e6ea838136.png)

### Date and time this happened or you first noticed this issue

07-12-2022

### Network

Ethereum Mainnet

### Safe Address

0x42E51a81881f3114A82ABc327F84fda11E3AA90d

### Token Address

0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2

### Token Type

ERC20

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yagopv** [comment]
Hey @Claire-serveth I think this is a problem on the UniSwap side as is described in [this issue](https://github.com/safe-global/safe-react-apps/issues/199)

If the user uses Wallet Connect is probably going to have the same issue/error

Perhaps the Transaction Builder could be an option (Can test in Goerli)

**Comment by Claire-serveth** [comment]
> Hey @Claire-serveth I think this is a problem on the UniSwap side as is described in [this issue](https://github.com/safe-global/safe-react-apps/issues/199)
> 
> If the user uses Wallet Connect is probably going to have the same issue/error
> 
> Perhaps the Transaction Builder could be an option (Can test in Goerli)

Hi @yagopv, I've also tried on my end in goerli network and got the same issue. I'm using walletconnect safe app to interact with Uniswap. But if I use an EOA wallet, specifically metamask, the Uniswap UI is working. While using the safe, no confirmation popping up on the walletconnect safe app interface.

Is the transaction builder the only option to unwrap WETH?

**Comment by yagopv** [comment]
Hey @Claire-serveth. As the Transaction Builder is a more advanced option i can recommend better using [Cow Swap](https://app.safe.global/share/safe-app?appUrl=https%3A%2F%2Fswap.cow.fi%2F&chain=eth) that work just fine as they seems to do different estimations than Uniswap or Sushiswap (failing as well)

(Thanks to @mikhailxyz for the tip)

**Comment by Claire-serveth** [comment]
> Hey @Claire-serveth. As the Transaction Builder is a more advanced option i can recommend better using [Cow Swap](https://app.safe.global/share/safe-app?appUrl=https%3A%2F%2Fswap.cow.fi%2F&chain=eth) that work just fine as they seems to do different estimations than Uniswap or Sushiswap (failing as well)
> 
> (Thanks to @mikhailxyz for the tip)

Hello @yagopv I see, already relayed this to the user. Thank you so much and to Mikhail as well! :)
