### ISSUE TITLE
[BSC] Safe nonce is proposing 197 for a new transaction instead of the current Safe nonce of 56

### ISSUE THREAD

**Issue by Sherie15** [5afe/safe-support#90]
### Issue Category

Other

### What happened?

When the user tries to create a new transaction it proposes nonce 197 instead of the current Safe nonce of 56. The user manually edited the Safe nonce for his latest transaction just to replicate if the Safe is incorrectly proposing the nonce.

Environment:
Chrome version: 108.0.5359.98
MAC OS

![image](https://user-images.githubusercontent.com/113986185/206405878-7f08f5b9-76f4-4474-ab4b-9f01c34e02de.png)
![image](https://user-images.githubusercontent.com/113986185/206406253-8670b7bd-7db6-4a1e-9da5-96648a0e8d03.png)

![image](https://user-images.githubusercontent.com/113986185/206406399-529cd987-1f1b-4417-9d9e-2ea2cb6b4c86.png)

https://gnosis-safe.io/app/bnb:0xf4Ad3ba2be7089092AbB55766E07953a50952139/settings/advanced

### Date and time this happened or you first noticed this issue

8/12/2022   7:20:04 PM

### Network

Binance Smart Chain

### Safe Address

0xf4Ad3ba2be7089092AbB55766E07953a50952139

### Token Type

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by usame-algan** [comment]
Thanks for reporting. This is a known issue and will be fixed in the next release: https://github.com/safe-global/web-core/issues/1253

**Comment by JagoFigueroa** [comment]
Hi! Closing this ticket as the one mentioned by usame was merged into production fixing this issue. Cheers!
