### ISSUE TITLE
Signers are getting "Invalid owner provided" error

### ISSUE THREAD

**Issue by joanpan** [5afe/safe-support#91]
### Issue Category

Transaction execution issue

### What happened?

Multiple signers are getting "Invalid owner provided" error. First signer who initiated the transaction did not get the error.
https://dashboard.tenderly.co/public/safe/safe-apps/simulator/30a2ad33-9362-4c3b-94d4-ed224f53a928?trace=0.0.1.2

Transaction was created in the new UI. Tested in the old UI and it seems to working fine. Issue is only in the new UI.

Safe address:
eth:0xb270FE91e8E4b80452fBF1b4704208792A350f53

### Date and time this happened or you first noticed this issue

09-12-2022

### Network

Ethereum Mainnet

### Safe Address

0xb270FE91e8E4b80452fBF1b4704208792A350f53

### Token Type

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yagopv** [comment]
The transactions with one missing signer i guess they tried to sign and execute right? For scoping the error to the execution

**Comment by yagopv** [comment]
Opened a [ticket](https://github.com/safe-global/web-core/issues/1343) in the web-core repo (new UI)

**Comment by JagoFigueroa** [comment]
Hi! The fix for this ticket was included on our last release of the web interface so I will go ahead and close it. 

Cheers! (and sorry for the spam today, going through every ticket on the repo)
