### ISSUE TITLE
[iOS] Cannot sign with Argent wallet

### ISSUE THREAD

**Issue by CindyLo0** [5afe/safe-support#92]
### Issue Category

Transaction execution issue

### What happened?
Hi team. Is Argent wallet app supported? 
User is not getting any option to sign in their Argent wallet app when using Safe iOS mobile app. Works fine when done using the Safe web app on a browser + WalletConnect (Argent mobile app)

Current set up: 
 1. Using iOS Safe mobile app with Argent wallet app already installed on the same phone. 
 2. Argent is one of the signers/owners, already imported in iOS Safe mobile app. 
    iOS Version: 16.0 (20A362)
   Safe App Version: 3.18.1(1435)
   Argent App Version: 4.11.4
   Argent wallet address: 0x376ff6497ce127cbcfBA68B69049C8075c4f7102

Steps taken: 
 1. Sign transaction using Argent wallet but is unable to, see video recording: 
https://user-images.githubusercontent.com/79137197/206849384-d5650543-7dfe-41b6-93f5-6ef7e408d83a.mp4
 2. Enable receive push notifications, same issue, see video recording: 
https://user-images.githubusercontent.com/79137197/206849419-e1d87c4f-f742-4ed2-8eda-2f9cf825d41e.mp4

### Date and time this happened or you first noticed this issue

10-12-2022 12:10 

### Network

Ethereum Mainnet

### Safe Address

eth:0xEc37033Ca79D2a2af3a7AD11a48e00eDF27E4910

### Token Type

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by biafra23** [comment]
I can reproduce the problem with enabling push notifications on my iPhone.

**Comment by biafra23** [comment]
Will open a ticket in the ios repo. Please follow that for updates on the fixing progress.
