### ISSUE TITLE
[ETH mainnet] Signatures show up as 3 out of 2 - safe only needed 2 confirmations to reach threshold

### ISSUE THREAD

**Issue by shebeengs** [5afe/safe-support#96]
### Issue Category

Transaction execution issue

### What happened?

Hi team, a user reported this issue with the interface: 
At first the signatures showed up as 2 out of 2 but can't execute it due an error and list of addresses who confirmed only showed 1 out of 2.
![image](https://user-images.githubusercontent.com/54754746/207133942-7092ff79-567a-4fdd-9903-718452dc0915.png)

Signatures then showed up as 3 out of 2 - safe only needed 2 confirmations to reach threshold. 
![image](https://user-images.githubusercontent.com/54754746/207133758-2a3a4974-2860-4cbf-8a89-948fd06ccaf1.png)

The user was able to execute the transaction even with the incorrect display of signatures though.
![image](https://user-images.githubusercontent.com/54754746/207135193-3f4c4feb-4d5e-46d2-bf38-a6911a41b608.png)

User has also mentioned this happens multiple times now. 
Linking this issue [#87](https://github.com/5afe/safe-support/issues/87) here as well, as it's somehow related to the user's first issue.

### Date and time this happened or you first noticed this issue

13/12/2022 20:19:52

### Network

Ethereum Mainnet

### Safe Address

0x0036aA4Cb362be6a39B484582306703af44Fee8e

### Token Type

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JagoFigueroa** [comment]
Hi! Might this issue been fixed for the user as a result of #87? If so I think we can close this ticket 😎 

I have checked the shared safe but unfortunately there is no transaction in the queue for me to play around with.

Cheers!
