### ISSUE TITLE
Can't connect Trezor on various browsers (Edge, Chrome, Firefox)

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#97]
### Issue Category

Other

### What happened?

User was trying to create a new safe but was not able to connect his trezor with the safe. Already tried basic troubleshooting steps using different browsers including private browsing (using both new and old URL).

![image](https://user-images.githubusercontent.com/114005210/207400912-7c090dc8-251d-4ae9-a334-8e03e45f0a94.png)

### Date and time this happened or you first noticed this issue

13-12-2022

### Network

Ethereum Mainnet

### Safe Address

n/a

### Token Address

n/a

### Token Type

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JagoFigueroa** [comment]
Good morning! Could you ask the user to try again on the new web interface with the safety checks set to 'Prompt' on the Trezor Suite app? I think that should do the trick.

To do so the setting would be under device -> security -> safety checks

<img width="735" alt="Screenshot 2022-12-14 at 09 50 50" src="https://user-images.githubusercontent.com/92332710/207551946-a2ea1f6b-ca68-4b5c-b3a0-7d996ccc6054.png">

**Comment by Claire-serveth** [comment]
> Good morning! Could you ask the user to try again on the new web interface with the safety checks set to 'Prompt' on the Trezor Suite app? I think that should do the trick.
> 
> To do so the setting would be under device -> security -> safety checks

Thank you so much @JagoFigueroa :) This has been relayed to the user already and still waiting for the response.

**Comment by Claire-serveth** [comment]
Hello @JagoFigueroa, I haven't heard from the user since, so I just closed the chat on intercom. I will close this issue for now and re-open in case the user will give feedback. Thank you again :)
