### ISSUE TITLE
[iOS] No notification received when a transaction is queued 

### ISSUE THREAD

**Issue by shebeengs** [5afe/safe-support#98]
### Issue Category

Other

### What happened?

iOS version: 16.1.2
Safe app: 3.18.1

No notifications is received when initiating a transaction in other devices in iOS. Replicated on Goerli and had the same behavior. Notification is only received when the transaction has already been submitted/executed. 

### Date and time this happened or you first noticed this issue

14/12/2022 12:07:41

### Network

Ethereum Mainnet

### Token Type

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by liliiaorlenko** [comment]
Most likely this happens because we moving the app to the new account, once we done with it, the issue will be solved.

**Comment by biafra23** [comment]
@shebeengs I tried to reproduce this issue and I do get notified on prod / Görli about new transactions that need my confirmation. 

Was this temporary problem?
Can you still reproduce it?
If so please provide steps to reproduce, environment (staging/production) and version of the iOS app.

**Comment by shebeengs** [comment]
Hi, I was using same specs as the user. 
iOS version: 16.1.2
Safe app: 3.18.1

Tried it again and looks like it's fixed. I'll confirm with the user as well. Thank you

**Comment by ennisjo** [comment]
@shebeengs -  can we close this issue now?

**Comment by shebeengs** [comment]
We can. The user has been unresponsive but I can receive notifications on my end. Thank you!
