### ISSUE TITLE
"Airdrop is not available for you at the moment" error when trying to claim Safe airdrop

### ISSUE THREAD

**Issue by inahlikenoother** [5afe/safe-support#99]
### Issue Category

Other

### What happened?

When user tries to claim Safe airdrop, it prompts with "Sorry, the Airdrop is not available for you at the moment"
![image](https://user-images.githubusercontent.com/114049495/207772934-e758fdb6-3c5a-4afb-bff4-0e9f76a11c06.png)

Behavior is the same on different browsers, as well as when other owners tries to claim the Airdrop.

### Date and time this happened or you first noticed this issue

15-12-2022 11:46

### Network

Ethereum Mainnet

### Safe Address

0xb238b3263c68d588e9856346C2436DDCd206990d

### Token Type

None

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Sherie15** [comment]
Another impacted user encountered the same error using the OLD/NEW URL.

[0x9D2966F07C90D7799f916C96D6ac03b4fc24ce95](https://gnosis-safe.io/app/eth:0x9D2966F07C90D7799f916C96D6ac03b4fc24ce95/home)

![image](https://user-images.githubusercontent.com/113986185/207789672-f0e18a6f-3c63-4e1e-a5c3-a98b0983da52.png)

**Comment by liliiaorlenko** [comment]
We already working on this issue and a release with fixes coming in next few days.

**Comment by dasanra** [comment]
It should be solved now. Thank you for your report and sorry for the inconveniences
